### ISSUE TITLE
Add oliver to QGEP project

### ISSUE THREAD

**Issue by sjib** [QGEP/QGEP#104]
Could you check with Marco to add Oliver to project?

**Comment by m-kuhn** [comment]
Could you convince Marco to request github to turn the QGEP user to a QGEP organization so we don't rely on a particular user account for things like this but can have several admins on this organization.

**Comment by andreasneumann** [comment]
fine with me - how can we do that? As to oliver - what is his github name?

**Comment by oliver-ch** [comment]
oliver-ch

**Comment by 3nids** [comment]
The point is @mhugent is the only one with admin right on qgep because qgep is a user and not a group.

1. Transfer the QGEP repo to a group: QGEP1
2. Delete qgep user
3. Create qgep group (can't do until qgep user is deleted)
4. Transfer QGEP repo to qgep group

@mhugent can you proceed?

**Comment by 3nids** [comment]
I sent a mail yesterdai morning (07.05.2015) to Marco to ask for this change, I have no answer yet.

**Comment by qgep** [comment]
@3nids : I don't have admin rights on QGEP1, so github does not let me do the transfer. Can you add that?

**Comment by 3nids** [comment]
@qgep done!

**Comment by 3nids** [comment]
@qgep let me know if you can delete the qgep account afterwards.

**Comment by qgep** [comment]
I still get the same error message ('You don't have admin rights to QGEP1').

**Comment by 3nids** [comment]
sorry I sent the invitation to @mhugent , I did now for @qgep

**Comment by 3nids** [comment]
thanks MArco!
QGEP is now a repo of QGEP group!

does someone has Koni username on github?

**Comment by oliver-ch** [comment]
it is @kfischerar

**Comment by 3nids** [comment]
thanks a lot!
