### ISSUE TITLE
Custom data model extensions

### ISSUE THREAD

**Issue by m-kuhn** [QGEP/QGEP#105]
How do we deal with custom extensions.
@3nids / SIGE already reported a couple of additional fields they want to maintain and probably others will follow.

We could integrate them all into QGEP or create per-user extensions.

Number one has the advantage that a future upgrade will be painless for Uster.
Number two has the advantage that we don't have to further bloat the database with extensions that are only used by few organizations and the majority does not care. I assume we'll have other requests from every single organization that joins.

It could be interesting to add an extension field on every od_xxx table where organizations can save their private extensions.
http://clarkdave.net/2013/06/what-can-you-do-with-postgresql-and-json/
But we would need to implement support for this in QGIS upstream.

**Comment by sjib** [comment]
Documentation here: https://qgep.github.io/docs/admin-guide/db-customization/index.html

Please reopen if still an issue
