### ISSUE TITLE
od_backflow_prevention.fk_throttle_shut_off_unit and od_backflow_prevention.fk_pomp

### ISSUE THREAD

**Issue by m-kuhn** [QGEP/QGEP#108]
We don't have the fields fk_throttle_shut_off_unit and fk_pomp fk_aquifer present on od_backflow_prevention but it is present in the print/hardcopy of an ER that I have here.

Are these fields no longer or not yet in our database?

**Comment by sjib** [comment]
I am not sure how old this table is https://github.com/QGEP/QGEP-Datamodel/blob/master/diagram/dom_Class-dom_Attribut.xlsx . Who supported this one? It looks like a model 2008 version. If needed I can create an updated version of the 2014 model

**Comment by m-kuhn** [comment]
See #112
