### ISSUE TITLE
pipes used for venting

### ISSUE THREAD

**Issue by 3nids** [QGEP/QGEP#109]
in TB2, I have some pipes which are used for venting.

How would you define this in VSA?

In special_structure, there is the venting function but the geometry is polygon.
There is no such function for the channel if I'm correct. I would have liked to have a venting in vl_chanel_usage_current.

What do you think?

**Comment by sjib** [comment]
see https://github.com/QGEP/QGEP/issues/85 (I reopened that issues and added the feedback).

special_structure.function = venting is the whole special structure as venting, e.g. for large channels. But this is not the pipes you think of.
