### ISSUE TITLE
manhole material (more generally extension of value lists)

### ISSUE THREAD

**Issue by 3nids** [QGEP/QGEP#110]
In the case of manhole material, we have (the SIGE) a precise list.
Much more detailed than the VSA one (concrete/plastic/other/unknown).

For instance, we have 3 types of concrete (armed/unarmed/prebuilt).

It's quite easy for me to extend this list, in my DB.

Although, I think that customized values should have a correspondence in the VSA list. I.e. all my concretes should have the VSA-code 4541.

What do you think of adding a column in the value lists name vsa_code or something similar?

**Comment by urskaufmann** [comment]
Manhole - material is always prebuilt (and not built on place - that would be a special structure). Prebuilt may also be armed or unarmed concrete. So this value list is not so helpful.

**Comment by 3nids** [comment]
Apparently, in the old times they used to build the manhole directly on place. Would consider this as special structure? Strictly speaking they're standard manholes.
Also, I understand that prebuilt can be armed or unarmed, but where do you save that info?

More globally, I don't believe every user can stick to the existing value lists. If it's for a GEP, then ok, but for the company or service it's not ok to loose such details.

**Comment by 3nids** [comment]
if I should use special structure, can I have the material somewhere?

**Comment by urskaufmann** [comment]
ok, we have in Thun also very old manholes, that are build on place. No - they are not special structures.
I have no info, if they are armed or not. Normally, they have special dimensions (like 1050 / 700).
In vsa-dss, special structures have no material-attribute. Normally it's armed concrete...

also in reach - material, you can not distinguish between armed and unarmed concrete.
i agree with you (If it's for a GEP, then ok, but for the company or service it's not ok to loose such details.)

**Comment by 3nids** [comment]
@urskaufmann thanks a lot for the feedback!

@ all: what do you think of the proposition to extend value list with a VSA-code column?

**Comment by sjib** [comment]
In INTERLIS I would just write an extend for the values you want more detailed – this then gives the new subvalues e.g. concrete_armed, concrete_unarmed, concrete_prebuilt. That is the easiest and best way to extend values and to already have built in the mechanism to bring back the extensions to the main value. We do the same with status for example in the SIA405 Leitungskataster and the media models.

**Comment by 3nids** [comment]
Thanks for the reply.

I'm not sure it's the safest way. One will add many rows but they won't have any correspondence in VSA codes. With the proposed approach it does not need any extra magic, you already have the correct code in the table.

**Comment by sjib** [comment]
We have a meeting next Tuesday with the model commission of VSA-DSS. Send me your extended value list then I can propose those. Best allready as extensions to the existing values like this:
concrete
    armed
    unarmed
    prebuilt
plastic
other
    xxx
unknown

@urskaufmann - please comment then which ones you would also find helpful for a new VSA-DSS release

**Comment by 3nids** [comment]
Hi Stefan,
I think I have a list which might be a bit specific. There will be always one material that would not fit in the list. And if it's not for me it will be for someone else.
We have to find a proper solution to extend value list without breaking the export to the strict VSA-DSS. Hence the proposition of having the vsa-code column.

**Comment by sjib** [comment]
Hoi Dennis

But you will have to have a mechanism that fits them to the DSS list if you want to exchange the values. That is also a must. With concrete, plastic and other you can match everything.

**Comment by 3nids** [comment]
After a short discussion with Matthias, the idea is to add a column vsa_code to the existing value lists, which will be the same as code at the origin. If one wants to add custom entries, it will require to have a code > 10000 so it can be handled in model updates.
This code will be created automatically with a dedicated sequence, unique over all vl_* tables.

As said, we think it's a requirement to add custom value lists.
This approach has been chosen for its simplicity and it's the safest in terms of data coherence.

@sjib do you think 10'000 is enough? or shall we take 100'000?

**Comment by m-kuhn** [comment]
Stefan will add a new column vsa_code to the value lists, with defaults from the code column.

Link to feedback form in the comment.

Minimum value 100000

**Comment by sjib** [comment]
Added in Metadatenbank - ready in next release

**Comment by sjib** [comment]
I extended the is_dictionary with now 3 tables:
qgep.is_dictionary_od_table (overview)
qep.is_dictionary_od_fields (all details of attributes)
qgep.is_dictionary_od_values (all details of values)

CREATE VIEW qgep.is_dictionary_value_list AS
  SELECT p.relname AS vl_name, vl.*
  FROM qgep.is_value_list_base vl, pg_class p
  WHERE vl.tableoid = p.oid;


CREATE TABLE qgep.is_dictionary_od_table
(
  id integer NOT NULL,
  tablename text,
  name_en text,
  shortcut_en character(2),
  name_de text,
  shortcut_de character(2),
  name_fr text,
  shortcut_fr character(2),
  CONSTRAINT pkey_qgep_is_dictonary_id PRIMARY KEY (id),
  CONSTRAINT unq_qgep_is_dictonary_tablename UNIQUE (tablename)
)
WITH (
  OIDS = False
);

CREATE TYPE plantype AS ENUM ('Leitungskataster','Werkinformation', 'GEP_Verband', 'GEP_Traegerschaft', 'PAA', 'SAA', 'kein_Plantyp_definiert');
CREATE TABLE qgep.is_dictionary_od_field (
    id serial NOT NULL,
    class_id integer,
    attribute_id integer,
    table_name character varying(80),
    field_name character varying(80),
    field_name_en character varying(80),
    field_name_de character varying(100),
    field_name_fr character varying(100),
    field_name_it character varying(100),
    field_description_en text,
    field_description_de text,
    field_description_fr text,
    field_description_it text,
    field_mandatory plantype[],
    field_visible boolean,
    field_datatype character varying(40),
    field_unit_de character varying(60),
    field_unit_en character varying(50),
    field_unit_fr character varying(50),
    field_unit_it character varying(50),
    field_min numeric,
    field_max numeric,
    CONSTRAINT is_dictionary_od_field_pkey PRIMARY KEY (id)
);

CREATE TABLE qgep.is_dictionary_od_values (
  id serial NOT NULL,
  class_id integer,
  attribute_id integer,
  value_id integer,
  table_name character varying(80),
  field_name character varying(80),
  value_name character varying(100),
  value_name_en character varying(80),
  shortcut_en character(2),
  value_name_de character varying(100),
  shortcut_de character(2),
  value_name_fr character varying(100),
  shortcut_fr character(2),
  value_name_it character varying(100),
  shortcut_it character(2),
  value_description_en text,
  value_description_de text,
  value_description_fr text,
  value_description_it text,
CONSTRAINT is_dictionary_od_values_pkey PRIMARY KEY (id)
);

**Comment by sjib** [comment]
The latest release should be debugged completely (finally (-: ). You'll get it by email.

**Comment by sjib** [comment]
Next steps are to add Italien (partly missing) and Romanian also.

**Comment by sjib** [comment]
Is done with the new version of today by email. Please check whether you are happy with it.

**Comment by sjib** [comment]
Here the new structures of the 3 Tables:
CREATE TABLE qgep.is_dictionary_od_table
(
  id integer NOT NULL,
  tablename text,
  name_en text,
  shortcut_en character(2),
  name_de text,
  shortcut_de character(2),
  name_fr text,
  shortcut_fr character(2),
  name_it text,
  shortcut_it character(2),
  name_ro text,
  shortcut_ro character(2),
  CONSTRAINT pkey_qgep_is_dictonary_id PRIMARY KEY (id),
  CONSTRAINT unq_qgep_is_dictonary_tablename UNIQUE (tablename)
)
WITH (
  OIDS = False
);

2) for the attributes - unit new as short and long version:
field_unit_de character varying(20),
    field_unit_description_de character varying(90),

------------
CREATE TABLE qgep.is_dictionary_od_field (
    id serial NOT NULL,
    class_id integer,
    attribute_id integer,
    table_name character varying(80),
    field_name character varying(80),
    field_name_en character varying(80),
    field_name_de character varying(100),
    field_name_fr character varying(100),
    field_name_it character varying(100),
    field_name_ro character varying(100),
    field_description_en text,
    field_description_de text,
    field_description_fr text,
    field_description_it text,
    field_description_ro text,
    field_mandatory plantype[],
    field_visible boolean,
    field_datatype character varying(40),
    field_unit_de character varying(20),
    field_unit_description_de character varying(90),
    field_unit_en character varying(20),
    field_unit_description_en character varying(90),
    field_unit_fr character varying(20),
    field_unit_description_fr character varying(90),
    field_unit_it character varying(20),
    field_unit_description_it character varying(90),
    field_unit_ro character varying(20),
    field_unit_description_ro character varying(90),
    field_min numeric,
    field_max numeric,
    CONSTRAINT is_dictionary_od_field_pkey PRIMARY KEY (id)
);

and for the values:
CREATE TABLE qgep.is_dictionary_od_values (
  id serial NOT NULL,
  class_id integer,
  attribute_id integer,
  value_id integer,
  table_name character varying(80),
  field_name character varying(80),
  value_name character varying(100),
  value_name_en character varying(80),
  shortcut_en character(3),
  value_name_de character varying(100),
  shortcut_de character(3),
  value_name_fr character varying(100),
  shortcut_fr character(3),
  value_name_it character varying(100),
  shortcut_it character(3),
  value_name_ro character varying(100),
  shortcut_ro character(3),
  value_description_en text,
  value_description_de text,
  value_description_fr text,
  value_description_it text,
  value_description_ro text,
CONSTRAINT is_dictionary_od_values_pkey PRIMARY KEY (id)
);

**Comment by 3nids** [comment]
Sorry what's the use for is_dictionary_od_values?

**Comment by sjib** [comment]
You have the information to what table and attribute a value is belonging without having to look it up thru a query.

**Comment by m-kuhn** [comment]
So it is a merge of all the vl_-tables?

**Comment by sjib** [comment]
yes but it includes also the corresponding class and attribute name and id of each value:
class_id integer,
attribute_id integer,
value_id integer,
table_name character varying(80),
field_name character varying(80),

**Comment by m-kuhn** [comment]
That's not yet implemented

**Comment by sjib** [comment]
Updates ready to take into master https://github.com/QGEP/datamodel/pull/5

**Comment by tudorbarascu** [comment]
@sjib  @m-kuhn Is there a reason not make the **is_dictionary_od_values** be a view uniting all the vl_* tables instead of a table aggregate that's saved on disk?
