### ISSUE TITLE
Add fields to is_dictionary_od_field

### ISSUE THREAD

**Issue by m-kuhn** [QGEP/QGEP#112]
Add fields to is_dictionary_od_field

add column 
 * mandatory
 * visible
 * min
 * max
 * unit (de, en, it, fr) (see DOM Attributes from DABASE) (SB)

rules for
min / max width messages for database (CHECK CONSTRAINT ...) (SB)

**Comment by m-kuhn** [comment]
Quote:

> I am not sure how old this table is https://github.com/QGEP/QGEP-Datamodel/blob/master/diagram/dom_Class-dom_Attribut.xlsx . Who supported this one? It looks like a model 2008 version. If needed I can create an updated version of the 2014 model

It was a table I once received from Urs. Nothing depends on it and it's only there fore reference. I think once this issue here is solved we can remove it.

It would be good to have any information from the metadatabase available.

**Comment by m-kuhn** [comment]
@sjib what are your thoughts on this? Is this a big work?

**Comment by sjib** [comment]
I am working on this – it is almost finished – I hope tomorrow.

**Comment by sjib** [comment]
Ich habe jetzt zwei neue Felder eingefügt in is_dictionary_od_field mit field_mandatory und field_visible. 
@urskaufmann und @kfischerar: Die Frage stellt sich dann, wie diese abgefüllt werden sollen: Mandatory für welchen Fall (Umfang sia405abwasser Wekinformation, Leitungskataster, Minimalumfang GEP Gemeinde oder Verband) 

"CREATE TABLE qgep.is_dictionary_od_field ("
Print #13, "    id serial NOT NULL,"
Print #13, "    class_id integer,"
Print #13, "    attribute_id integer,"
Print #13, "    table_name character varying(80),"
Print #13, "    field_name character varying(80),"
Print #13, "    field_name_en character varying(80),"
Print #13, "    field_name_de character varying(100),"
Print #13, "    field_name_fr character varying(100),"
Print #13, "    field_name_it character varying(100),"
Print #13, "    field_description_en text,"
Print #13, "    field_description_de text,"
Print #13, "    field_description_fr text,"
Print #13, "    field_description_it text,"
Print #13, "    **field_mandatory boolean**,"
Print #13, "    **field_visible boolean**,"
Print #13, "    CONSTRAINT is_dictionary_od_field_pkey PRIMARY KEY (id)"

**Comment by sjib** [comment]
Dann habe ich eine weitere Tabelle is_dictionary_od_values vorgesehen, wo nun auch die Einheiten value_unit_* und value_min und value_max erscheinen würden (falls der Datentyp eine Zahl ist). Ist das in dieser Form hilfreich? Müsste man auch noch den PostGis Datentyp einfügen? ***value_datatype***

Print #13, "CREATE TABLE qgep.is_dictionary_od_values ("
    Print #13, "  id serial NOT NULL,"
    Print #13, "  class_id integer,"
    Print #13, "  attribute_id integer,"
    Print #13, "  value_id integer,"
    Print #13, "  table_name character varying(80),"
    Print #13, "  field_name character varying(80),"
    Print #13, "  value_name character varying(100)"
    Print #13, "  value_name_en character varying(80),"
    Print #13, "  shortcut_en character(2),"
    Print #13, "  value_name_de character varying(100),"
    Print #13, "  shortcut_de character(2),"
    Print #13, "  value_name_fr character varying(100),"
    Print #13, "  shortcut_fr character(2),"
    Print #13, "  value_name_it character varying(100),"
    Print #13, "  shortcut_it character(2),"
    Print #13, "  value_description_en text,"
    Print #13, "  value_description_de text,"
    Print #13, "  value_description_fr text,"
    Print #13, "  value_description_it text,"
    Print #13, "  **value_unit_en** text,"
    Print #13, "  **value_unit_de** text,"
    Print #13, "  **value_unit_fr** text,"
    Print #13, "  **value_unit_it** text,"
    Print #13, "  **value_min** text,"
    Print #13, "  **value_max** text,"
    Print #13, "CONSTRAINT is_dictionary_od_field_pkey PRIMARY KEY (id)"
Print #13, ");"

**Comment by sjib** [comment]
Should value_min / max be text or a number type (can be anything like 0, 0.00, 10.000, 9999.9999, etc.)

**Comment by andreasneumann** [comment]
I'd say better not use "text" but data type "numeric" for "value_min" and "value_max".

**Comment by m-kuhn** [comment]
@sjib Thank you

Mandatory / Visible
-----------------

Do you have the "mandatory flag" for all these cases ready?
If yes, are they hierarchic : in this case an enum defining the "minimal case" would be good instead of a boolean.  (e.g. "is mandatory for Leitungskataster and more detailed)
If they are not hierarchic : adding an array of "mandatory for these cases" would be good.

Other fields
-----------

Postgres field types are available from the table metadata already, no need to insert it.

value_min and value_max should probably be numbers instead of text

**Comment by m-kuhn** [comment]
@sjib I just realized that there was also a field "decimal places" in the domattributes document. Can you add that as well?
Is there more information from the metadatabase available?

**Comment by sjib** [comment]
What do you mean with that? postgis datatyps show e.g. decimal(9,2)

**Comment by andreasneumann** [comment]
numeric is a datatype on its own that leaves it up to the user how many digits he wants to use - just like text is kind of unlimited. Numeric ranges from up to 131072 digits before the decimal point; up to 16383 digits after the decimal point. See also http://www.postgresql.org/docs/9.3/static/datatype-numeric.html

**Comment by m-kuhn** [comment]
@sjib 
ah, if that's already defined there then there's no need to add it again.
the other question remains: is there more data from the metadatabase which we do not have available yet?

**Comment by sjib** [comment]
***Mandatory***
I am not sure, whether they are always hierarchic - we would need to look into that:
  Leitungskataster 1
  Wekinformation 2
Leitungskataster + Werkinformation 3
These two are hierarchic

These next two include Leitungskataster but not all of Werkinformation
GEP Abwasserverband is a subpart (Teilmenge) of GEP Organisation 

So do you know of a system to sum this up in a certain way?

**Comment by sjib** [comment]
Definiton for Min / Max
Print #13, " value_min numeric,"
Print #13, " value_max numeric,"

Is this ok?

**Comment by m-kuhn** [comment]
You could add an array of enums.

|CREATE TYPE plan_type AS ENUM ('||Leitungskataster','||Wekinformation',...);

CREATE TABLE ...(
||plans_mandatory plan_type[]|

)

INSERT INTO ... VALUES(

|ARRAY['|||||Leitungskataster|','|||||Wekinformation|']::plan_type[]
)
|

**Comment by sjib** [comment]
***field_visible boolean***
Könnte man einsetzen um ein Projekt zu konfigurieren an dem ein anderes Ingenieurbüro z.B. nur gewisse Daten ergänzt im Rahmen der GEP-Bearbeitung und alle diejenigen Attribute ausblenden, wo sie gar nichts ändern sollen oder dürfen. Dies kommt hoffentlich vermehrt zum Einsatz im Rahmen der GEP-Bearbeitung mit QGEP indem man das Projekt für eine Zeit "sperrt" und einem anderen Büro den "beschränkten" Zugang gibt um Daten zu ergänzen (Teilprojekt XY). Das wäre eine einfache Möglichkeit ohne gross zu exportieren und wieder zu importieren. Vielleicht könnte man das sogar im selben Projekt benutzerabhängig nutzen (visble Konfiguration je nach Benutzer(rechten)

**Comment by sjib** [comment]
Ich setze im Moment mal alles auf true

**Comment by m-kuhn** [comment]
@sjib @urskaufmann @andreasneumann 

Would it make sense to have a read-only flag as well?

**Comment by sjib** [comment]
Finde ich auch eine gute Idee. Schaut euch mal meinen ersten Wurf an, dann kann ich das immer noch einbauen.

**Comment by urskaufmann** [comment]
Visible: Die Liste der Attribute in den Tabellen und damit in den Eingabemasken ist lang. Man könnte die Eingabemasken damit benutzerfreundlicher auf das wesentliche konzentrieren (wenn die Eingabemasken automatisch erstellt werden)...

Read only: das hat ja irgendwie mit Zugriffsrechten eines Benutzers zu tun. Da ist von mir aus ein Flag bei den Atributten der falsche Ort.

**Comment by m-kuhn** [comment]
Visible:
If the list of attributes is too long we spread it on different tabs at the moment so would it maybe be better define the tab under which the field is listed?

Read only: If there are access rights defined on column level (I don't think we do this) we could also take this as input hint. I was thinking about e.g. obj_id but if it's just for this column we can also do this on another level.

**Comment by m-kuhn** [comment]
@sjib What is the status of this?

**Comment by sjib** [comment]
I implemented so fare everything in the latest release - please check there whether it fits or not. We can discuss further improvements on Monday

**Comment by m-kuhn** [comment]
Is the latest release the one you sent me per mail or is there a newer one available?
As far as I remember the latest script I received exited with errors.

**Comment by sjib** [comment]
Yes, it is the one by email. I need your feedback about the errors of the SQL create to continue. The is_dictionary should be ok. Thanks.

**Comment by m-kuhn** [comment]
I just checked again. Running the (to my knowledge latest) scripts (qgep_meta_dss_14.07.201580206.18_en.sql.txt, tst3_14.07.201583367.51_en_dss.sql.txt) I am getting the following error:

    psql: 03_qgep_db_dss.sql:8: ERROR:  relation "qgep.is_value_list_base" does not exist

Running the `09_qgep_dictionaries.sql` script without replacing the 03 script fails as well.

Feedback for the views was sent July, 20 by mail.
Thank you.

**Comment by m-kuhn** [comment]
Make sure `CREATE TABLE qgep.is_value_list_base` is on top of 03_qgep.....

**Comment by m-kuhn** [comment]
Fixed with the latest model release
