### ISSUE TITLE
Pivot table for od_maintenance_event <-> od_wastewater_structure

### ISSUE THREAD

**Issue by m-kuhn** [QGEP/QGEP#113]
Create pivot table for n:m relation between maintenance and wastewater_structure.

Further tables?

**Comment by 3nids** [comment]
is that part of the new release?

**Comment by sjib** [comment]
It is now online https://github.com/QGEP/QGEP/blob/master/datamodel/re_maintenance_event_wastewater_structure.sql
Please check and confirm whether ok or not

**Comment by m-kuhn** [comment]
Thank you Stefan,

As mentioned earlier, I would propose to remove the surrogate primary key and replace it with a compound one (I added a pull request #125 with an example).

If there are reasons not to do this I would at least add a unique constraint over the two foreign keys.

**Comment by sjib** [comment]
I am fine with this suggestion. @3nids Can you continue to work with the corrected version of @m-kuhn (https://github.com/QGEP/QGEP/pull/125/files) ?

**Comment by m-kuhn** [comment]
Merged

**Comment by m-kuhn** [comment]
Add indexes

**Comment by sjib** [comment]
Like this?
CREATE UNIQUE INDEX in_re_maintenance_event_wastewater_structure ON qgep.re_maintenance_event_wastewater_structure USING btree (fk_wastewater_structure ASC NULLS LAST, fk_maintenance_event ASC NULLS LAST);
