### ISSUE TITLE
Multi edit

### ISSUE THREAD

**Issue by m-kuhn** [QGEP/QGEP#116]
Possibility to edit multiple entries with a single form.

**Comment by sjib** [comment]
Add additional specifications

**Comment by m-kuhn** [comment]
Is in progress

**Comment by andreasneumann** [comment]
see https://github.com/qgis/QGIS/pull/2995

**Comment by m-kuhn** [comment]
Fixed in master https://github.com/qgis/QGIS/commit/66b51d4a8146bf75e85fe5135ec21af9f3b9c46f

**Comment by m-kuhn** [comment]
For the curious, there is a demonstration video of multiedit available:
https://www.youtube.com/watch?v=czmr1SOvIVQ
