### ISSUE TITLE
View generator for subclass / superclass

### ISSUE THREAD

**Issue by m-kuhn** [QGEP/QGEP#117]
Automatic generation of `vw_{classname}` views for object relations.

 * sub- and superclass combination
 * reach point attributes to reach
 * including insert, update and delete rules/triggers
 * generate reach point geometry from reach geometry

May be used for interlis export as well

**Comment by m-kuhn** [comment]
Sample for reach:
https://github.com/QGEP/QGEP/blob/master/datamodel/view/vw_reach.sql

Sample for object oriented table
https://github.com/QGEP/QGEP/blob/master/datamodel/view/vw_access_aid.sql

**Comment by m-kuhn** [comment]
@sjib can you give a time estimate for when this is ready?
vw_reach can also be added at a later point if it's harder to implement.

**Comment by sjib** [comment]
Give me another 2 weeks for this, I will need half a day to do this

**Comment by sjib** [comment]
@m-kuhn I am sending you the corrected versions of sql create and qgep meta:
a) VSA-DSS in two version, with Text and Symbol Tables at the end (do you need that in the sql create?
b) sia405 (if you don't want to start with all classes)

**Comment by m-kuhn** [comment]
I think having the full VSA-DSS ready will be best. I can start with the SIA405 as well but we'll have everything ready once we need it.

**Comment by m-kuhn** [comment]
Hoi Stefan,

Habs noch etwas mehr Tests gemacht:
 * Ein index für fk_owner wird viele Male erstellt, bevor eine
entsprechende Spalte existiert
 * Ein index für situation anstatt situation_geometry wird erstellt
 * Ein index für perimeter anstatt perimeter_geometry wird erstellt

Da das auch noch nicht alles gelöst hat, habe ich aufgehört zu testen.
Kannst du das Skript auf deiner eigenen Datenbank testen?

Vielen Dank,
Matthias

**Comment by sjib** [comment]
You will get a corrected release on Monday. sia405 is anyway a subset of VSA-DSS - so if you work with VSA-DSS you will allready have sia405 abwasser

**Comment by sjib** [comment]
I tested my first release, there are still some minor errors with the comma settings - next version tomorrow

**Comment by m-kuhn** [comment]
@sjib What is the status of this?
