### ISSUE TITLE
french translation for leapingweir

### ISSUE THREAD

**Issue by 3nids** [QGEP/QGEP#118]
The french translation for table od_leapingweir is missing.
Is is deversoir_refoulement?

**Comment by sjib** [comment]
The translation is LEAPING_WEIR (that is the official VSA-SDEE term)

**Comment by 3nids** [comment]
I meant what is the french translation? leaping weir is english...

**Comment by sjib** [comment]
I checked with our french translator of the VSA-SDEE model - he thinks that is correct and used also in France

**Comment by 3nids** [comment]
This is quite strange.....
The VSA website gives déversoir d'orage as a definition.
https://www.vsa.ch/fr/glossar/fr/terms/main/129/

Can you send me the contact info of the translator?

**Comment by sjib** [comment]
Ich habe nachgeschaut und in der franz. Literatur (ENGEES, Strasbourg) wird der Begriff ebenfalls als "Déversoir leaping weir" bezeichnet. Dementsprechend würde ich auf franz. auch leaping weir weiterhin benutzen.

**Comment by 3nids** [comment]
Thanks for following up! Sorry for the noise.
