### ISSUE TITLE
Interaction with hydraulic modeling software SWMM

### ISSUE THREAD

**Issue by vpicavet** [QGEP/QGEP#121]
This is mentioned here : 
http://www.qgis.ch/en/projects/qgep-waste-water-module/current-development

Interaction with SWMM or other Hydraulic simulation tools would be interesting. 

Oslandia implemented qgis-swmm to be able to use SWMM from QGIS Processing.

PostgreSQL views on QGEP model could be a way to present SWMM a model it can understand, and run simulations onto : 
https://github.com/Oslandia/qgis-swmm

**Comment by sjib** [comment]
Thank you for this hint. That is great.

 

If you are interested we can discuss to set up a model transformation from the VSA-DSS model in QGEP to create an export to SWMM. Do you know where the documentation about the SWMM model is available?

**Comment by vpicavet** [comment]
@vmora would probably know better than me on this

**Comment by vmora** [comment]
The structure of the input tables/layers follows generally the structure described in the SWMM doc. 

But apart from the readme and the example, there is not much else as for as documentation is concerned.

**Comment by tudorbarascu** [comment]
Hi, a good SWMM presentation can be found at http://www.engr.colostate.edu/CIVE572/Lectures/Session%2013%20-%20Introduction%20to%20USEPA%20SWMM/Session%2013_Introduction%20to%20USEPA%20SWMM.ppt

**Comment by sjib** [comment]
see also [#126] (https://github.com/QGEP/QGEP/issues/126) for youtube video on SWMM

**Comment by sjib** [comment]
(New link to SWMM Homepage) [http://www2.epa.gov/water-research/storm-water-management-model-swmm]

**Comment by vmora** [comment]
I started up a [qgis water management cookbook](https://github.com/vmora/qgis-water-management-cookbook) to try and group info about using qgis for water management. For the moment it's mainly about epanet exemples, but any other water-management related examples/link/tips&tricks are welcome.

I've also developed a 2d triangles/quad plugin layer for qgis (not public yet, but will soon be) to visualize 2D simulation results (open GL rendering to allow animation). A presentation is available [here](https://www.meci.co.kr/societyevent/FOSS4G2015/download/presentation/Room%2011/S8-4/PT8-15_On%20simulation%20and%20GIS,%20coupling%20and%20hydrology.zip).

Concerning model transformation, there is a draft version of setting up views on qwat model suitable for the epanet plugin [here](https://github.com/Oslandia/qgis-epanet/blob/master/qwat_to_epanet_views.sql). Not complete, and maybe not even up to date with the current qwat model, but related.

**Comment by sjib** [comment]
Thanks, that is very nice. 

 

I in the meantime  analyzed how we can you use the SWMM plugin and database to directly feed it with data from QGEP. I will present the results later here. It seems not too difficult to create some views for junctions, conduits, etc. directly from the data of QGEP. 

 

Do you know why they use different attribute names in the test database than mentioned in the currents SWMM manual? http://nepis.epa.gov/Adobe/PDF/P100ERK4.pdf

**Comment by tudorbarascu** [comment]
U.S. EPA has started work on re-engineering the SWMM/EPANET GUI and they're doing it with QT/Python.. and QGIS libraries.
More at https://github.com/qwat/QWAT/issues/124

**Comment by sjib** [comment]
We started to check on the current SWMM Plugin. I made a small [fix](https://github.com/Oslandia/qgis-swmm/pull/19) to make it running again on QGIS 2. We will continue to look in how to use it with QGEP.

**Comment by sjib** [comment]
First efforts to create Views in QGEP for export to SWMM: https://github.com/QGEP/datamodel/pull/94

**Comment by bogdanvaduva** [comment]
I've done something similar a while ago. If you think it helps your effort, you can have a look at the following link https://github.com/bogdanvaduva/epanet.js-and-swmm.js/blob/master/sql/qgep_od/fn_swmm.sql.

Regards

**Comment by sjib** [comment]
The QGEP group (@tproduit and @sjib)  worked on this. Views for each SWMM class on qgep schema are prepared. TP defined [requirements for updating SWMM plugin to QGIS 3](https://drive.google.com/drive/folders/1c5A4jHwiz5q6QxqQhJqCTDi2uCWkLn37?usp=sharing) and made specific offer to implement this on QGIS3: Total costs 15k. 

QGEP members agreed to implement steps 1 and 2 (export of data from QGEP into SWMM schema and generating *.imp file) on this years development budget. 

For the rest of the budget we challenge other interested people and organisation to join in for sharing of the cost. TP will make schedule for implementation of first part. As soon as additional finances are available the rest can be implemented also. Please contact QGEP coordinator (@sjib) if you can and want to join in with finances or time.
![swmm qgep plugin planning](https://user-images.githubusercontent.com/1265865/59092242-5c72fd80-8911-11e9-9616-5790fd98a8aa.jpg)

**Comment by sjib** [comment]
With [Release 1.2.0 of the QGEP Plugin](https://github.com/QGEP/qgepplugin/releases) SWMM Export is part of the plugin.

For detailed documentation see: https://qgep.github.io/docs/qgep_swmm/index.html
