### ISSUE TITLE
Joining the project with RO translation

### ISSUE THREAD

**Issue by tudorbarascu** [QGEP/QGEP#123]
Hi guys, your project looks really nice and I've been wanting to join it for a while.
I'm slowly but steady getting to know it and hopefully will find ways of contributing to it.
I thought that I would begin to contribute with the Romanian translation and I began adding ro language to the ``09_qgep_dictionaries.sql`` file.

Any advice is welcomed.
All the best,
Tudor

PS. Hope it's ok to put an issue for RO language. I hope that I will close it soon.

**Comment by andreasneumann** [comment]
Thank you for your interest in QGEP and wanting to contribute the RO translation.

The translations are handled by a master database which is not part of this github project, but this application generates the SQL code for the different languages. As such, you will have to coordinate with Stefan Burckhardt (who is maintaing this part of the code) if you want to add the romanian localization. I will tell him to get in touch with you about coordinating the romanian translation. The project is rather complex and there are quite a few places where we need to take localizations into account. Let's keep in contact.

**Comment by tudorbarascu** [comment]
Hello Andreas, nice to be here, I'll be waiting for Stefan to make contact.

**Comment by m-kuhn** [comment]
Hi @tudorbarascu 

Nice to see you join!

If you want to translate to a new language, you will have to take the following things into account:

 * is_* tables for field and table names (will later be synced with transifex)
 * vl_* tables for value lists (comboboxes for attribute selection)
 * other strings (for forms and plugin) on transifex

**Comment by sjib** [comment]
Buna ziua Tudor. 

Bun venit in QGEP. Vorbest putin Romaneste. Mai mult informatii peste in termen de 2 zile

Stefan

**Comment by tudorbarascu** [comment]
Buna dimineata Stefan.

Multumesc frumos de primire. Astept informatiile.

Salutari!

**Comment by tudorbarascu** [comment]
ping @sjib

**Comment by sjib** [comment]
There are different parts of the data model: https://www.vsa.ch/fachbereiche-cc/siedlungsentwaesserung/datenstruktur-siedlungsentwaesserung/datenmodell/

The sewer network model (Kanalnetz) consists of 18 tables with 130 attributes. Maybe you can start with that.
Then we could include catchements (plus 1)

The full data model VSA-DSS is around 120 tables with 560 attributes. There we are still working on the English translations. 

Do you speak also French, Italien, German - and would this be helpful to have the information in these languages also for translation?

Let me know where I can email you the first two excel lists with tables and attributes
They will have columns for Romanian - RomanianName (lower case, no special characters), RomanianNameDescription (sam as RomanianName but with special characters and spaces), RomanianDescription (descriptive text of what RomanianName is) - you will find these both for classes and attributes.

A list with the values I am in the work of preparing.

**Comment by tudorbarascu** [comment]
I will start with the sewer model then.
I can also speak French and understand Italian, but I found out the german translation would also help me when everything else fails.

You can e-mail the tables at  "tudor (dot) barascu (at) qtibia (dot) ro"

Thanks for the info

**Comment by tudorbarascu** [comment]
@sjib   I got your e-mail and send back the translated file. As I haven't gotten a reply from you and there's a chance my e-mails got caught in your spam filters I'm writing here. Sorry for the noise.
All the best

**Comment by tudorbarascu** [comment]
Hi again,

I have translated all that stefan gave me last week.
Are there any other steps that I should do in order to generate the sql files?

Thanks, all the best,

Tudor

**Comment by sjib** [comment]
Dear Tudor

sorry for keeping you waiting – there are different things going on at the same time

We will need the values also and the datatypes  – I will send you the list of values and datatypes until tomorrow.

Then I can start create the SQL code. Afterwards we can start to translate the forms with Transifex.

Thanks

Stefan

**Comment by sjib** [comment]
I am trying to import your class and attribute translations. The excel for classe has 2 tabs - which one is the correct one? 
![image](https://cloud.githubusercontent.com/assets/1265865/8574430/dbf10062-2596-11e5-87ce-fc758a66ab3e.png) or 
![image](https://cloud.githubusercontent.com/assets/1265865/8574443/ed27b2f4-2596-11e5-8af3-76dc6045f115.png)

**Comment by tudorbarascu** [comment]
deversor is the correct one. as in the other languages the translations slightly differed I thought they could be different depending on the context.
No worries, I can wait but I didn't know in advance so I pinged..
Thanks a lot,
Tudor

**Comment by sjib** [comment]
I just sent you the new files by email. Please confirm when you got them

**Comment by tudorbarascu** [comment]
Hi,
Regarding the reach materials, I have't figured the following material correspondance:
- Beton_Pressrohrbeton (Ge), beton_pousse_tube (Fr), concrete_presspipe (En)

I couldn't find a reference in German English or French of this material existance.

Is it reffering to the Spannbeton (Ge), beton_precontraint (Fr), prestressed_concrete (En) material, which is not in the list?

Thank you for your time,
Tudor

**Comment by sjib** [comment]
This material is more specifing that the pipe has been pushed with a presstube (and that the used concrete has to withhold the standards to do so without being explicitly specified). So I think you just translate “presstube” to Romanian and add it to the concrete_

**Comment by m-kuhn** [comment]
@tudorbarascu Is there anything left on this issue or can we close it?

**Comment by tudorbarascu** [comment]
We can close it, I wanted Stefan to come back so that we generate the SQL's.

**Comment by tudorbarascu** [comment]
@sjib Any updates regarding the Ro values in the SQL? Am I supposed to do something now other than wait?

**Comment by sjib** [comment]
Thanks for the follow up - I will try to include your input into the metadatabase. Thanks for your patience.

**Comment by sjib** [comment]
Romanian is included and will come with the next release (in about 2 weeks)

**Comment by sjib** [comment]
@tudorbarascu Any other needs to include Romanian translation or are you happy with this latest model release?

**Comment by tudorbarascu** [comment]
@sjib It's good enough for now. Thanks a lot!
