### ISSUE TITLE
Movement of manholes

### ISSUE THREAD

**Issue by m-kuhn** [QGEP/QGEP#132]
When a cover which belongs to a manhole is moved:
- The wastewater node shall follow
  - If it is just one, else [.........]
- All attached reaches follow
- If control is clicked
  - [We need requirements]

--- Database triggers

**Comment by sjib** [comment]
Specifications:
1) Moving of whole manhole / special structure - with moving the (main) cover in the "structure" layer, all related coordinates (further covers, waste water nodes, reach points) are moved by the same vector (delta)
2) Analog procedure if a reach is moved
3) If someone just wants to move the cover object, this has to be done in the cover layer (where only covers are editable). The same thing also if a single wastewater node or reach points has to be moved. -> document how to do this
4) Implement this as simple as possible with no user dialogue.

**Comment by m-kuhn** [comment]
Status Quo (pure database solution, no user interaction)
https://vimeo.com/162978741
