### ISSUE TITLE
Profile tool widget reopening

### ISSUE THREAD

**Issue by tudorbarascu** [QGEP/QGEP#137]
When clicking the profile tool the widget where the profile is rendered pops out docked to the bottom.
If one is to close down the widget to better view the map, selects two nodes do do the profile on, everything works good (the path between the nodes is highlighted) but as the profile widget area is closed the user cannot see the profile.

As solutions:
- each time a path is found, the plugin should recheck if the widget dock status and reopen it if it's closed
- deactivate the profile tool on dock closing

**Comment by 3nids** [comment]
closing for a single issue for profile related issues
