### ISSUE TITLE
vw_wastewater_node view no longer propagates nodes from new manholes

### ISSUE THREAD

**Issue by tudorbarascu** [QGEP/QGEP#138]
In the latest datamodel, there no new features appear in the vw_wastewater_node view even though a new manhole has been created.

**Comment by m-kuhn** [comment]
Does it not appear in the view or just without geometry? 
I assume it's a duplicate of #134

**Comment by tudorbarascu** [comment]
It doesn't appear in the view, count(*) gives the same result.

**Comment by m-kuhn** [comment]
Are you using vw_cover or vw_qgep_cover?
The first one does not create the node, the second one does.

**Comment by tudorbarascu** [comment]
I've used vw_qgep_cover manually, and through the plugin. Same result.

**Comment by m-kuhn** [comment]
Strange, it works here.

    insert into qgep.vw_qgep_cover(identifier, ws_type) values ('test',
'manhole')

Also inserts a new record into qgep.od_wastewater_node

Can you download the latest dump and check (although there has nothing
been changed in the last 3 days in this area...)

**Comment by m-kuhn** [comment]
https://github.com/QGEP/datamodel/commit/d5a646df912c0ee2fdcd231aed4eaa4a58311f27 introduces tests that ensure that the wastewater_node is created.

**Comment by tudorbarascu** [comment]
Hmm,
It works if I create a new model.
It doesn't work for the latest demo data at https://github.com/QGEP/data/raw/demodata/qgep_demodata.backup which I'm testing before putting it to the VM.

**Comment by tudorbarascu** [comment]
In the latest demo data (from last night), I cannot create a manhole using the wizard as saving outputs:

```
Could not commit changes to layer vw_qgep_cover

Errors: ERROR: 1 feature(s) not added.
  
  Provider errors:
      PostGIS error while adding features: ERROR:  query string argument of EXECUTE is null
    CONTEXT:  PL/pgSQL function qgep.ws_label_update_by_structure_part_networkelement() line 17 at EXECUTE statement
    SQL statement "INSERT INTO qgep.od_wastewater_networkelement (
                 obj_id
               , identifier
               , remark
               , dataowner
               , provider
               , last_modification
               , fk_wastewater_structure
               )
         VALUES ( qgep.generate_oid('od_wastewater_node') -- obj_id
               , NEW.identifier
               , NEW.remark
               , NEW.dataowner
               , NEW.provider
               , NEW.last_modification
               , NEW.fk_wastewater_structure
               )
               RETURNING obj_id"
    PL/pgSQL function qgep.vw_wastewater_node_insert() line 3 at SQL statement
    SQL statement "INSERT INTO qgep.vw_wastewater_node(
          backflow_level
        , bottom_level
        , situation_geometry
        , identifier
        , remark
        , last_modification
        , dataowner
        , provider
        , fk_wastewater_structure
      )
      VALUES
      (
          NEW.backflow_level
        , NEW.bottom_level
        , NEW.situation_geometry
        , COALESCE(NULLIF(NEW.wn_identifier,''), NEW.identifier)
        , COALESCE(NULLIF(NEW.wn_remark,''), NEW.remark)
        , NOW()
        , COALESCE(NULLIF(NEW.wn_provider,''), NEW.provider) -- TODO will need to be switched to fk
        , COALESCE(NULLIF(NEW.wn_dataowner,''), NEW.dataowner) -- TODO will need to be switched to fk
        , NEW.ws_obj_id
      )"
    PL/pgSQL function qgep.vw_qgep_cover_insert() line 225 at SQL statement
```

**Comment by m-kuhn** [comment]
Verified: The same query only fails with pre-existing data in the DB.

**Comment by tudorbarascu** [comment]
It works now thanks to https://github.com/QGEP/datamodel/commit/6ee40b286be5991c57318e3762416fdfc9e0134a
