### ISSUE TITLE
SVG Symbols in the demo project

### ISSUE THREAD

**Issue by m-kuhn** [QGEP/QGEP#139]
When I open the demo project there are a lot of question marks.

Is that a configuration problem or do I need to install the SVG symbols locally? Can they be shipped in a path relative to the project?

**Comment by m-kuhn** [comment]
Just realized it's in the AV03 dataset... Does anyone know about it?

**Comment by andreasneumann** [comment]
You can add an additional SVG symbol repository for QGEP and add it under "Settings -> Options -> System -> SVG paths".

That's a one time thing  - not hard to do.

**Comment by m-kuhn** [comment]
The SVG symbols for pumps etc. show... It's only the AV03 symbols which are missing.

**Comment by andreasneumann** [comment]
Actually the waste-water project does not require SVG symbols so far - they are multilayer simple markers.
The SVG symbols for AV are at https://github.com/QGEP/QGEP/tree/master/project/svg/av
