### ISSUE TITLE
qgep and qgis server/qwc

### ISSUE THREAD

**Issue by tudorbarascu** [QGEP/QGEP#141]
Hi,

While setting up a Qgis Web Client demo in the VM that holds a working QGEP demo, I got a hold of two issues.

A) For some reason, QGIS Server doesn't output the labels as it should. See bellow image, left-right:desktop-server

![qgep_qwc_problems](https://cloud.githubusercontent.com/assets/3179646/9352926/7ecee3f2-466d-11e5-993b-2f4fbcafcae8.png)

B) While adding the WMS on qgep_en to QGIS Desktop, I encountered what's described here, https://hub.qgis.org/issues/13161

Thus, for the following request:
```
http://qgisplatform.demo/wms/qgep_en?SERVICE=WMS&VERSION=1.3.0&SLD_VERSION=1.1.0&REQUEST=GetLegendGraphic&FORMAT=image/png&LAYER=vw_qgep_cover&STYLE=
```

The outputted error is:
```
/usr/lib/cgi-bin/qgis_mapserv.fcgi(4561) exit(communication error), get unexpected signal 6
```

Is anyone using the qgep along with qgis server? Maybe @andreasneumann ?

**Comment by m-kuhn** [comment]
The expression used for the reach labelling uses some fancy expression function which is defined by the QGEP plugin (`locale()`).

We should

 * add a join of vl_reach_material to vl_qgep_rech
 * use the joined column `abbr_en` as default for the labelling
 * translate the expression itself to localized projects

Any idea why the symbology is messed up on the desktop (manhole symbols)?

When changing the reach labels the labels on vw_qgep_cover should also be changed, it references `mh_label` (or similar) and should instead join `_label`

**Comment by tudorbarascu** [comment]
It's clear now.
Regarding the Desktop symbology being messed up in the image, it's not actual a problem. I took the screenshot in a test project outside the VM as it was handier.
