### ISSUE TITLE
Metadatabase

### ISSUE THREAD

**Issue by m-kuhn** [QGEP/QGEP#148]
Our datamodel is being generated from a metadatabase. Currently we only have the generated datamodel but not the metadatabase and not the conversion scripts. It would be great if we could have access to the metadatabase (publicly or privately) for the reasons outlined below.

In the past we have realized several times that valuable information is present in the datamodel after already having spent a considerable amount of time to enter the same data again manually (e.g. generating forms and widget configurations, generating writable views).

At the moment we are working with generated SQL scripts but whenever changes are required, they are manually updated. Meanwhile, there is already a considerable delta between the two. This will work fine as long as the metadatabase does not change but once it does, the generator will create new SQL scripts and the manual patches will need to be performed again and we risk forgetting something.

**Comment by sjib** [comment]
This are good points and we can look at it in detail at our next meeting. I can also share more what data is already stored.

 

The goal from my side is to gap the changes in code in the export – if I am too far behind we have to think about how I can create more resources to do so.

 

The metadatabase is used to create many other things than the QGEP SQL code, so it is not independent. But having a metadatabase also helps insure the consistency with the official models of sia (waste water) and VSA (GEP) – a major plus point that we should not loose.

**Comment by 3nids** [comment]
@sjib would it be possible to get a dump of the meta DB before next meeting?
I suppose it could bring more ideas when we meet.

**Comment by m-kuhn** [comment]
@sjib we definitely should keep the official model as a source and not diverge too far, staying close to the official model is a base-idea and a unique selling point of QGEP!

What I imagine to be a good process is to have the metadatabase as canonical source and be able to add custom extensions to it (like further field configuration values, custom fields for caching...) so that we can generate a basemodel with QGEP extensions directly from it.

The nice thing about it is, that the extensions could also be moved from QGEP to the base model if they turn out to be good enhancements, practically making it a two-way process.

**Comment by sjib** [comment]
I would prefer to demonstrate you what I have inside at the meeting. So much more information than you already know is not in there (-:
