### ISSUE TITLE
Update trigger qgep.vw_qgep_cover_update has an issue with od_cover.material 

### ISSUE THREAD

**Issue by bogdanvaduva** [QGEP/QGEP#149]
In vw_qgep_cover_update I think there is an issue:

  UPDATE qgep.od_cover
      SET
        brand = NEW.brand,
        cover_shape = new.cover_shape,
        depth = new.depth,
        diameter = new.diameter,
        fastening = new.fastening,
        level = new.level,
        material = new.material, <---------------------------------------- Shouldn't be cover_material ?
        positional_accuracy = new.positional_accuracy,
        situation_geometry = new.situation_geometry,
        sludge_bucket = new.sludge_bucket,
        venting = new.venting
.....

Thanks.

**Comment by m-kuhn** [comment]
Sounds right.

Can you fix it and update the test case for vw_qgep_cover?
It should be trivial I think.

**Comment by bogdanvaduva** [comment]
I will do it.

**Comment by m-kuhn** [comment]
Thank you very much
