### ISSUE TITLE
Cannot remove or unlink Maintenances (or other relations based features) from vw_qgep_reach

### ISSUE THREAD

**Issue by tudorbarascu** [QGEP/QGEP#152]
Basically, the Unlink and Delete buttons don't work.

![relations1](https://cloud.githubusercontent.com/assets/3179646/10018034/f6882cc6-613b-11e5-9b2b-085267f680b9.png)

I discovered this while trying to make final adjustments to a documents plugin that I've been working on that permits adding, storing, linking and viewing documents (videos, pdf's, images etc.) stored in a ftp server to any table.

**Comment by m-kuhn** [comment]
Upstream issue:
https://github.com/QGEP/QGEP/issues/152

Does it work in the table view?

**Comment by tudorbarascu** [comment]
Yes, it does work in table view.
I didn't know about the issue, I somehow thought that it was QGEP related as I when I tested on another project (probably tested in table view) it worked.
Thanks for letting me know!

**Comment by m-kuhn** [comment]
Not making it a P1 since a workaround exists which can be trained.

**Comment by urskaufmann** [comment]
i think can be closed
