### ISSUE TITLE
vw_qgep_cover_update tigger issue with wn_identifier,wn_remark

### ISSUE THREAD

**Issue by bogdanvaduva** [QGEP/QGEP#154]
Here it's the case that I had.
I've entered a cover without cover identifier and I said I will update the identifier later on. I came back and entered a new identifier to that cover. When I navigated to Wastewater Node tab I've saw that identifier it's still empty even though I've entered something to identifier.
I've changed vw_qgep_cover_update tigger by adding the following code:

    UPDATE qgep.vw_wastewater_node
      SET
        identifier = COALESCE(NULLIF(NEW.wn_identifier,''), NEW.identifier),
	remark = COALESCE(NULLIF(NEW.wn_remark,''), NEW.remark),
	provider = COALESCE(NULLIF(NEW.wn_provider,''), NEW.provider), -- TODO will need to be switched to fk
	dataowner = COALESCE(NULLIF(NEW.wn_dataowner,''), NEW.dataowner),
	last_modification = NOW()
    FROM qgep.od_structure_part  
    WHERE qgep.od_structure_part.fk_wastewater_structure=vw_wastewater_node.fk_wastewater_structure 
    AND qgep.od_structure_part.obj_id::text = old.obj_id::text;

Does it seems ok to you?
Best regards,
Bogdan

**Comment by m-kuhn** [comment]
I think we should offer one identifier field per involved object

 * wn_identifier
 * ws_identifier
 * sp_identifier

same for the other fields

What is the idea of our data model experts?
**Are the identifier always, often, sometimes or never equal for these objects**?
@sjib @kfischerar @urskaufmann

**Comment by m-kuhn** [comment]
@bogdanvaduva I think that will fail as soon as there is more than one wastewater node involved. On the identifier column is a unique constraint so you cannot update several wastewater nodes with the same identifier.

Proposal:

Instead the insert statement could be updated to assign an identifier automatically. If the identifier is left empty, the cover obj_id should be used on all involved objects. With this in place the update logic can even be fine tuned to work despite the problem outlined above.

I think that the same logic should NOT be applied on remarks (i.e.  a remark should not be copied but explicitly set on the object of desire by the user).

provider and dataowner are subject to removal and will be replaced by foreign keys in the near future, so I wouldn't touch them, that will just make the future transition harder to perform.

If you agree on the proposal, can you create a pull request with a unit test on  https://github.com/QGEP/datamodel ?

**Comment by bogdanvaduva** [comment]
Your proposal sounds good, it make sense (I didn't knew the details about some of the fields being deleted in the future when I added provider and dataowner). 
I will do these days a pull request.
Thanks.

**Comment by m-kuhn** [comment]
All the tables already have `fk_dataowner` and `fk_provider` [example](https://github.com/QGEP/datamodel/blob/master/03_qgep_db_dss.sql#L189) the other fields are just there for legacy

**Comment by bogdanvaduva** [comment]
Now that you mention, I see the columns (:D)
When I looked at the database/model I've tried to understand only small parts of it, that's why those columns eluded me. For example in my screens I didn't added fk_dataowner,fk_provider
![screenshot from 2015-10-08 18 19 26](https://cloud.githubusercontent.com/assets/11473648/10370818/4cd7fda4-6de9-11e5-8cdc-f77eab997b64.png)

Regards

**Comment by sjib** [comment]
@bogdanvaduva is this still an open issue?

**Comment by bogdanvaduva** [comment]
No

**Comment by m-kuhn** [comment]
Yes, waiting for https://github.com/QGEP/datamodel/pull/3
