### ISSUE TITLE
Definition of ON DELETE actions

### ISSUE THREAD

**Issue by sjib** [QGEP/QGEP#155]
Single object delete (e.g. only cover) and cascades object delete (e,g, full wastewater_structure element with all connected structure_parts). 
Definitions for each foreign key on delete constraints: e.g. 
structure_part.fk_wastewater_structure on delete set null / cascade / restrict (delete is forbidden) / set default (we cannot us this)
SB send UK list of foreignkeys - adding colum with 3 on delete options

in model: extend create foreignkey with ON DELETE actions

ALTER TABLE qgep.od_structure_part ADD CONSTRAINT rel_structure_part_wastewater_structure FOREIGN KEY (fk_wastewater_structure) REFERENCES qgep.od_wastewater_structure(obj_id);
new:
ALTER TABLE qgep.od_structure_part ADD CONSTRAINT rel_structure_part_wastewater_structure FOREIGN KEY (fk_wastewater_structure) REFERENCES qgep.od_wastewater_structure(obj_id) ON DELETE cascade;

**Comment by sjib** [comment]
relate to #143

**Comment by sjib** [comment]
Detaildescription of ON DELETE see https://en.wikibooks.org/wiki/Structured_Query_Language/Foreign_Key#ON_DELETE_.2F_ON_UPDATE

**Comment by sjib** [comment]
[RelationshipAttribut_Overview.xlsx](https://github.com/QGEP/QGEP/files/19687/RelationshipAttribut_Overview.xlsx)

**Comment by sjib** [comment]
Feedback urskaufmann: 
habe die Zeilen mal durchgegangen. Ist nicht überall einfach. Vor allem kenne ich einiges nicht oder habe es noch nie angewendet (KEK, ALR, Mini, Stammkarten).

Auf der anderen Seite fehlen mir doch einige wichtige Fälle. Bauwerksteil zB fehlt als gAttribute.
Das Ding ist doch: wenn ich im GIS arbeite, dann brauche ich eine Geometrie (Punkt, Linie, Fläche), um auf die Daten zuzugreifen. Ich lösche zu 95% Bauwerke (Deckel=Bauwerkteil), Kanäle (Haltung=Abwassernetzelement) und Einzugsgebiete oder Anschlussobjekte. Die beiden Fälle Deckel und Haltung gehen in dieser Tabelle unter. Da braucht es vermutlich das UI im GIS, das nachfragt, was der Benutzer wirklich will (nur ein Deckel, Abwasserknoten oder Haltung löschen oder das ganze Abwasserbauwerk).
Irgendwie gibt es grundsätzlich vermutlich einen Unterschied, ob ein verknüpfter Datensatz eine eigene Geometrie hat oder nicht. Die Badstelle macht ohne Oberflächengewässer keinen Sinn, aber sie hat eine eigene, grundsätzlich unabhängig Geometrie und da wäre ich vorsichtiger mit Cascade, in solchen Fällen ist eine Rückfrage sinnvoll. Finde ich.
KEK: Wenn ich das Abwasserbauwerk lösche, es aber eine Verknüpfung mit einer  Untersuchung hat, dann macht die Untersuchung für sich alleine natürlich keinen Sinn. Aber sie hat stattgefunden, also kann ich sie nicht einfach ignorieren. Wenn ich das Bauwerk lösche, weil es rückgebaut wurde, dann ist cascade richtig. Wenn ich das Bauwerk lösche, weil ein Fehler in den Daten vorhanden war (z.B. Kanal doppelt erfasst), dann muss die Untersuchung bleiben...

bin mir nicht so sicher, ob man das Löschen einfach in der Datenbank aufgrund der Beziehungen zwischen den Klassen automatisieren kann.

**Comment by sjib** [comment]
@urskaufmann 
[RelationshipAttribut_Overview.xlsx](https://github.com/QGEP/QGEP/files/25960/RelationshipAttribut_Overview.xlsx)

OK, dann machen wir eine eigene Spalte in der Metadatenbank
[Uploading RelationshipAttribut_Overview.xlsx…]()

**Comment by m-kuhn** [comment]
Hi,

But there are some which are simple cases, no? Like when deleting a wastewater structure, the structure parts should be deleted as well. Can we mark these on the list and ignore the more complicated cases for the moment. Or are there no simple cases at all (and in this case, what should happen to structure parts when the parent structure is deleted, should they be orphaned `SET NULL`)?

Concerning Bauwerk <-> Untersuchung, isn't that an N:M relation? If it's not, does it make sense to keep the Untersuchung when the related wastewater structure is deleted? Or if this is a requirement would it rather make sense to flag the wastewater structure as deleted, to preserve a certain context?

**Comment by sjib** [comment]
@m-kuhn 
Auch für Subklassen ergänzt: ALTER TABLE qgep.od_planning_zone ADD CONSTRAINT oorel_od_planning_zone_zone FOREIGN KEY (obj_id) REFERENCES qgep.od_zone(obj_id) ON DELETE cascade;
Ist das ok?

**Comment by sjib** [comment]
@m-kuhn Oder ist das schon mit dem Trigger gelöst?

**Comment by sjib** [comment]
[RelationshipAttribut_Overview20151103.xlsx](https://github.com/QGEP/QGEP/files/26085/RelationshipAttribut_Overview20151103.xlsx)
Habe es jetzt mal so implementiert. Wichtig im Moment nur die schwarz eingefärbten Zeilen und ohne VSA-DSS Mini.
Bauwerk <-> Untersuchung is a n:m relation

**Comment by sjib** [comment]
Check scheint ok zu sein https://github.com/QGEP/datamodel/pull/6
