### ISSUE TITLE
Reuse values when digitizing reaches

### ISSUE THREAD

**Issue by m-kuhn** [QGEP/QGEP#163]

**Comment by urskaufmann** [comment]
the same as #294

**Comment by urskaufmann** [comment]
its not the same as #294 

m-kuhn:  with the wizard, the digitizing of vw_qgep_reach is implemented without the standard tools. Therefore the reuse values is not working when using the wizard with this view.

The automatic topology  AND the reuse value are very important features for me.

In my opinion, it would be the best, if the reuse values does not work on every field in the view - only on the fields that are in the general-tab.  In my configuration there are 13 fields (yellow marked on the pics) that should have the reuse value-feature.
![reach-remember2](https://user-images.githubusercontent.com/1257403/59127302-98d14880-8967-11e9-8ca7-615cdf85c455.PNG)

![reach-remember](https://user-images.githubusercontent.com/1257403/59127312-9ec72980-8967-11e9-9171-c6833619adef.PNG)
