### ISSUE TITLE
Value missing in qgep.vl_wastewater_structure_status

### ISSUE THREAD

**Issue by bogdanvaduva** [QGEP/QGEP#167]
In the last model I've downloaded from you there was a value 6528 which does not appear to be in the latest model.
```
6528;6528;"operational.operational";"in_Betrieb.in_Betrieb";"en_service.en_service";"''";"I";"E";TRUE
```

**Comment by sjib** [comment]
I will check on that. There was a change with the new version 2015.

**Comment by bogdanvaduva** [comment]
Thanks.

**Comment by sjib** [comment]
You have to use this model version: https://github.com/QGEP/datamodel/blob/master/03_qgep_db_dss.sql
