### ISSUE TITLE
Improve length-profile along reaches/channels [waiting for printing version]

### ISSUE THREAD

**Issue by andreasneumann** [QGEP/QGEP#17]
Currently we only display simple nodes and lines and elevations. No manhole dimensions and no special_structures and dimensions of reaches. Koni and Urs provided sample drawings as a reference.

Draw key dimensions and attributes below diagram for manholes, special_structures and channels.

Take into account scale thresholds for levels of detail.

Potentially allow expression builder for labels.

See examples at
https://github.com/qgep/QGEP/blob/master/gepview/beispiel_laengenprofile.pdf
https://github.com/qgep/QGEP/blob/master/gepview/length-profile_example_arbon_situation.pdf
https://github.com/qgep/QGEP/blob/master/gepview/length-profile_example_arbon_profile.pdf

**Comment by 3nids** [comment]
closing for a single issue for profile related issues
