### ISSUE TITLE
vw_qgep_cover -> identifier target

### ISSUE THREAD

**Issue by oliver-ch** [QGEP/QGEP#170]
vw_qgep_cover.identifier is selected from od_cover, however od_cover does not have an identifier field. it should be od_wastewater_structure.

**Comment by bogdanvaduva** [comment]
is selected from vw_cover

**Comment by oliver-ch** [comment]
yeah i just realised that aswell. however if i create a new manhole it doesn't fill in the identifier field, but i havent figured out why.

**Comment by sjib** [comment]
It coud be also od_structure_part.identifier – when you have several covers this is not the same.

**Comment by oliver-ch** [comment]
my bad. the tables are all filled in fine but the lable isn't generated correctly. in the function update_wastewater_structure_label it gets the identifier from od_wastewater_structure however the identifier of manholes is stored in od_wastewater_structure_part.

**Comment by sjib** [comment]
Seems to be solved - else reopen
