### ISSUE TITLE
Digitize Drainage Channel

### ISSUE THREAD

**Issue by oliver-ch** [QGEP/QGEP#171]
The tool is broken:
Python error
> An error occurred during execution of following code:
> feature = QgsMapLayerRegistry.instance().mapLayer('od_wastewater_structure').getFeatures( QgsFeatureRequest().setFilterExpression( 'obj_id = \'{}\''.format( '' ) ) ).next()
> qgepplugin.ui.forms.digitizeDrainageChannel(feature.id(), 'od_wastewater_structure')
> 
> Traceback (most recent call last):
>   File "", line 1, in 
> StopIteration

**Comment by oliver-ch** [comment]
The normal digitize tool for the wastewater structures is broken as well.

**Comment by oliver-ch** [comment]
it still produces an error (plugin v0.5.8, qgis 2.15)

> An error occurred during execution of following code:
> import qgepplugin

> feature = QgsMapLayerRegistry.instance().mapLayer('od_wastewater_structure').getFeatures( QgsFeatureRequest().setFilterExpression( 'obj_id = \'{}\''.format( '' ) ) ).next()
qgepplugin.ui.forms.digitizeDrainageChannel(feature.id(), 'od_wastewater_structure')


> Traceback (most recent call last):
>   File "", line 3, in 
> StopIteration

**Comment by m-kuhn** [comment]
The problem is in the project, not in the plugin.

The following code works for me.

```
import qgepplugin

feature = QgsMapLayerRegistry.instance().mapLayer('od_wastewater_structure').getFeatures( QgsFeatureRequest().setFilterExpression( 'obj_id = \'{}\''.format( '[% "ws_obj_id" %]' ) ) ).next()
qgepplugin.ui.forms.digitizeDrainageChannel(feature.id(), 'od_wastewater_structure')
```
