### ISSUE TITLE
comments on columns only availabe in german

### ISSUE THREAD

**Issue by 3nids** [QGEP/QGEP#173]
The columns comments are truncated, at least in the kek extension.
Why so?

for instance:
https://github.com/QGEP/datamodel/blob/master/04_vsa_kek_extension.sql#L172

**Comment by sjib** [comment]
I cut it off in the metadata export. I will correct this with a next release.

**Comment by sjib** [comment]
Should be solved with https://github.com/QGEP/datamodel/pull/17
