### ISSUE TITLE
Restoring demo database reports a lot of ingored errors

### ISSUE THREAD

**Issue by NMItools** [QGEP/QGEP#174]
Is it normal when you restore a [demo](https://github.com/QGEP/data/raw/demodata/qgep_demodata.backup) database you get a lot of errors (although they are ignored) ? Everything is done precisely by manual [instructions](http://qgep.github.io/docs/installation-guide/database-initialization.html)

`WARNING: errors ignored on restore: 1313`

and most of the errors are like

`pg_restore: [archiver (db)] Error while PROCESSING TOC:
pg_restore: [archiver (db)] Error from TOC entry 6235; 2606 20930 FK CONSTRAINT rel_wwtp_energy_use_waste_water_treatment_plant postgres
pg_restore: [archiver (db)] could not execute query: ERROR:  relation "qgep.od_wwtp_energy_use" does not exist
    Command was: ALTER TABLE ONLY qgep.od_wwtp_energy_use DROP CONSTRAINT rel_wwtp_energy_use_waste_water_treatment_plant;
`

After restore I got 259 tables, 35 triggers, 21 views, 10 functions and 106 sequences in a database.
It appears to be working fine when I later load QGIS demo project _qgep_en.qgs_ .It seems nothing is missing but I just wonder is it normal.

I tried to restore it without -clean parameter and then only 6 errors occured 

PostgreSQL 9.3.9
PostGIS 2.1.7
Windows 10 Pro

Thanks,
Nesh

**Comment by m-kuhn** [comment]
Tried to reproduce:

With pgadmin:

* Created a new database "test"
* In an SQL window `CREATE EXTENSION postgis`
* In an SQL window `CREATE EXTENSION hstore` (not sure if that's still required)
* Right clicked the database and restored the dump (default settings)
* Six errors and warnings, originating from `is_dictionary_od_field` (not mission critical at the moment but something to look into in the mid-term future)
* Same amount of db objects like you, `is_dictionary_od_field` is missing

If these step give worse results for you, maybe it's related to the fact that the dump is created with pg 9.4?

**Comment by NMItools** [comment]
Installed 9.4 and tried again, default restore (without -clean). I think we got the same now:

```
	Line 52: pg_restore: [archiver (db)] Error while PROCESSING TOC:
	Line 53: pg_restore: [archiver (db)] Error from TOC entry 829; 1259 23595 TABLE is_dictionary_od_field postgres
	Line 54: pg_restore: [archiver (db)] could not execute query: ERROR:  type "public.plantype[]" does not exist
	Line 62: pg_restore: [archiver (db)] could not execute query: ERROR:  relation "qgep.is_dictionary_od_field" does not exist
	Line 68: pg_restore: [archiver (db)] Error from TOC entry 7245; 0 0 SEQUENCE OWNED BY is_dictionary_od_field_id_seq postgres
	Line 69: pg_restore: [archiver (db)] could not execute query: ERROR:  relation "is_dictionary_od_field" does not exist
	Line 1196: pg_restore: [archiver (db)] Error from TOC entry 5601; 2604 23598 DEFAULT id postgres
	Line 1197: pg_restore: [archiver (db)] could not execute query: ERROR:  relation "is_dictionary_od_field" does not exist
	Line 1206: pg_restore: [archiver (db)] Error from TOC entry 7236; 0 23595 TABLE DATA is_dictionary_od_field postgres
	Line 1207: pg_restore: [archiver (db)] could not execute query: ERROR:  relation "is_dictionary_od_field" does not exist
	Line 1575: pg_restore: [archiver (db)] Error from TOC entry 6213; 2606 23603 CONSTRAINT is_dictionary_od_field_pkey postgres
	Line 1576: pg_restore: [archiver (db)] could not execute query: ERROR:  relation "is_dictionary_od_field" does not exist
	Line 4868: WARNING: errors ignored on restore: 6
```

should I create this table with this [SQL script](https://github.com/QGEP/datamodel/blob/master/10_dict_extension.sql) ?

**Comment by m-kuhn** [comment]
Can you wait for https://travis-ci.org/QGEP/QGEP/builds/110729536 to finish and check if this has really fixed the error?

(Should be there in ~3minutes)
