### ISSUE TITLE
demo database schema privileges

### ISSUE THREAD

**Issue by NMItools** [QGEP/QGEP#176]
Instructions from [user manual](http://qgep.github.io/docs/installation-guide/database-initialization.html)
says :

> Update privileges for the database
> 	- Right click the qgep schema
> 	- Click Grant Wizard …
> 		Selection, click Check All
> 		Privileges
> 		Group qgep
> 		Choose ALL
> 

After this when I tried to open QGIS project layers are still not accessible (57 layers in Handle Bad Layers window). 

I tried to log in as **qgepuser** with pgAdmin and when I try to select _wv_qgep_reach_ or any table I get `PERMISSION DENIED FOR SCHEMA QGEP`

Before "Grant Wizard..." step I think it is needed to grant privileges to qgep schema 

`GRANT USAGE ON SCHEMA qgep TO GROUP qgep;`
or
`GRANT ALL ON SCHEMA qgep TO GROUP qgep;`

**Comment by m-kuhn** [comment]
Would you mind making a pull request here? https://github.com/QGEP/docs/blob/master/en/installation-guide/database-initialization.rst

**Comment by NMItools** [comment]
Sorry Matthias, I am total NOOB about GitHub so I need assistance for using it :(

**Comment by NMItools** [comment]
I try it now. Is this OK ?

**Comment by m-kuhn** [comment]
Seems @tudorbarascu already fixed it

But if you find other things:

 * Find it (close to the link above)
 * Click the edit button on top (pencil)
 * Edit the file...
 * Click "propose change" at the bottom
