### ISSUE TITLE
update selected of vw_qgep tables causes qgis crash

### ISSUE THREAD

**Issue by oliver-ch** [QGEP/QGEP#177]
selecting multiple objectes (from vw_qgep_reach and vw__qgep_cover) and updating those via the field calculator causes a qgis crash. probably more qgis related then qgep

**Comment by m-kuhn** [comment]
Is it correct that it does not crash but freeze?

I have spent some time digging into this today, I think https://github.com/qgis/QGIS/pull/3001 should fix this.

**Comment by oliver-ch** [comment]
Yes it does freeze and it is fixed now. thanks
