### ISSUE TITLE
all names and shortcuts should be unique

### ISSUE THREAD

**Issue by 3nids** [QGEP/QGEP#180]
in the dictionary table `is_dictionary_od_table`, all names and shortcuts should be unique (across all languages)

**Comment by sjib** [comment]
Across all languages is not possible. It is unique in each language. Why would you need across all langueages?

**Comment by 3nids** [comment]
Yes that's what I meant. Each column should have unique constraint which is not the case now. That would avoid having same table shortnames.

**Comment by sjib** [comment]
Should be solved with latest model update https://raw.githubusercontent.com/QGEP/datamodel/master/09_qgep_dictionaries.sql - @3nids close if ok or else let me know if you see something is still wrong

**Comment by 3nids** [comment]
not it is not, in the link, only `tablename` is unique while we should have `name_en`, `shortcut_en`, etc.

**Comment by sjib** [comment]
Then give me the examples where shortcut_en is not unique. Then I can fix it. I can only make names in one language unique.

**Comment by 3nids** [comment]
I didn't check if there is one, but unique constraint are used to be future proof.
There is no limitation for the number of unique indexes.
That would mean to add

```
ALTER TABLE qgep.is_dictionary_od_table ADD CONSTRAINT unq_qgep_is_dictonary_name_en UNIQUE (name_en);
ALTER TABLE qgep.is_dictionary_od_table ADD CONSTRAINT unq_qgep_is_dictonary_shortcut_en UNIQUE (shortcut_en);
ALTER TABLE qgep.is_dictionary_od_table ADD CONSTRAINT unq_qgep_is_dictonary_name_de UNIQUE (name_de);
ALTER TABLE qgep.is_dictionary_od_table ADD CONSTRAINT unq_qgep_is_dictonary_shortcut_fr UNIQUE (shortcut_fr);
....
```

**Comment by sjib** [comment]
I added the following for en, de, fr, it and ro - you can use this to add to the existing model, in future it will be included.

ALTER TABLE qgep.is_dictionary_od_table ADD CONSTRAINT unq_qgep_is_dictonary_name_en UNIQUE (name_en);
ALTER TABLE qgep.is_dictionary_od_table ADD CONSTRAINT unq_qgep_is_dictonary_shortcut_en UNIQUE (shortcut_en);
ALTER TABLE qgep.is_dictionary_od_table ADD CONSTRAINT unq_qgep_is_dictonary_name_de UNIQUE (name_de);
ALTER TABLE qgep.is_dictionary_od_table ADD CONSTRAINT unq_qgep_is_dictonary_shortcut_de UNIQUE (shortcut_de);
ALTER TABLE qgep.is_dictionary_od_table ADD CONSTRAINT unq_qgep_is_dictonary_name_fr UNIQUE (name_fr);
ALTER TABLE qgep.is_dictionary_od_table ADD CONSTRAINT unq_qgep_is_dictonary_shortcut_fr UNIQUE (shortcut_fr);
ALTER TABLE qgep.is_dictionary_od_table ADD CONSTRAINT unq_qgep_is_dictonary_name_it UNIQUE (name_it);
ALTER TABLE qgep.is_dictionary_od_table ADD CONSTRAINT unq_qgep_is_dictonary_shortcut_it UNIQUE (shortcut_it);
ALTER TABLE qgep.is_dictionary_od_table ADD CONSTRAINT unq_qgep_is_dictonary_name_ro UNIQUE (name_ro);
ALTER TABLE qgep.is_dictionary_od_table ADD CONSTRAINT unq_qgep_is_dictonary_shortcut_ro UNIQUE (shortcut_ro);

**Comment by m-kuhn** [comment]
> For it and ro I cannot run it yet on pgAdmin because there are several empty values because not all of the model is translated

If they are `NULL` values that should work I think

**Comment by 3nids** [comment]
indeed
https://www.postgresql.org/docs/9.0/static/indexes-unique.html

**Comment by sjib** [comment]
follow up it / ro here https://github.com/QGEP/QGEP/issues/340
