### ISSUE TITLE
Reverse direction of a line

### ISSUE THREAD

**Issue by andreasneumann** [QGEP/QGEP#181]
It should be possible to interactively reverse the direction of a line - in case it had been accidentally created in the wrong direction.

See API: https://qgis.org/api/classQgsLineStringV2.html#a4bb426703bf9dba0782e935650e1eb52

**Comment by m-kuhn** [comment]
Does somebody have ideas regarding the user interface? Andreas, can you create an upstream issue?

**Comment by andreasneumann** [comment]
My assumption would be that users first select one or more linestrings or polygons and then press the button for "reverse direction".

I think it makes sense to enable it also for polygons, since they may have a directed symbology, e.g. marker lines, where the direction also matters for polygons.

I would assume that there is already an upstream issue opened - probably by myself several years ago ;-) let me dig it up.

**Comment by m-kuhn** [comment]
That sounds good, where would you put the button?

> I would assume that there is already an upstream issue opened - probably by myself several years ago ;-) let me dig it up.

Oh, there are unresolved issues?

**Comment by andreasneumann** [comment]
Apparently there is already a processing algorithm and a QGIS expression to reverse lines, but no interactive tool. See also http://hub.qgis.org/issues/2701 

This issue was opened 6 years ago (as a feature request for an interactive tool), but was later renamed to "Add a "reverse lines" processing algorithm" after 5.5 years being dormant.

But to me it is way less intuitive having to use Processing to reverse lines compared to an interactive tool.

I would put it in the "Advanced digitizing" toolbar - although this toolbar is getting quite crowded. Maybe it would make sense to move all the part and ring tools into a toolbar of its own. But that is not a big issue for me.

**Comment by m-kuhn** [comment]
After discussion with Urs, the proposed approach is:

 * Implement a QGIS upstream tool to reverse line direction
 * Introduce a database side trigger

```
if OLD.rp_from.geometry == NEW.rp_to.geometry and OLD.rp_to.geometry == NEW.rp_from.geometry:
    switch_fk_wastewater_networkelement(NEW.rp_from, NEW.rp_to)
    switch_geometry(NEW.rp_from, NEW.rp_to)
```

* This is most in line with the approach of staying close to QGIS tools
* Performance impact should be minimal (negligible)
* It is unlikely to trigger by mistake

**Comment by bogdanvaduva** [comment]
I've created a while ago a function to change direction of a reach

> CREATE OR REPLACE FUNCTION qgep.vw_qgep_reach_change_direction(id character varying)
  RETURNS boolean AS
$BODY$DECLARE rp_from character varying (500);
DECLARE rp_to character varying (500);
DECLARE rp_from_geom geometry;
DECLARE rp_to_geom geometry;
DECLARE wn_from character varying (500);
DECLARE wn_to character varying (500);
BEGIN
SELECT fk_reach_point_from INTO rp_from FROM qgep.od_reach WHERE obj_id=id;
SELECT fk_reach_point_to INTO rp_to FROM qgep.od_reach WHERE obj_id=id;
SELECT situation_geometry INTO rp_from_geom FROM qgep.od_reach_point WHERE obj_id=rp_from;
SELECT situation_geometry INTO rp_to_geom FROM qgep.od_reach_point WHERE obj_id=rp_to;
SELECT fk_wastewater_networkelement INTO wn_from FROM qgep.od_reach_point WHERE obj_id=rp_from;
SELECT fk_wastewater_networkelement INTO wn_to FROM qgep.od_reach_point WHERE obj_id=rp_to;
UPDATE qgep.od_reach SET progression_geometry=ST_Reverse(progression_geometry) WHERE obj_id=id;
UPDATE qgep.od_reach_point SET situation_geometry=rp_to_geom,fk_wastewater_networkelement=wn_to WHERE obj_id=rp_from;
UPDATE qgep.od_reach_point SET situation_geometry=rp_from_geom,fk_wastewater_networkelement=wn_from WHERE obj_id=rp_to;
refresh materialized view qgep.vw_network_node;
refresh materialized view qgep.vw_network_segment;
RETURN true;
END;$BODY$
> 

I know it's a little bit off the topic but may be it will help someone else.

Regards,

**Comment by andreasneumann** [comment]
Hi Matthias,

Your proposal with the upstream QGIS tool combined with the DB trigger makes sense to me.

Thanks!

**Comment by m-kuhn** [comment]
Thanks @bogdanvaduva 

For the user interface we will "need" a trigger (or a python solution). Once that is implemented, you can probably make your script a lot easier (i.e. just do an `update reach set geometry = reverse(geometry)` and the trigger will do the rest)

**Comment by m-kuhn** [comment]
@max-trolliet can you send me a dataset with reversed lines and obj_id or identifier of the affected reach?

**Comment by varrieta** [comment]
This is relating to #380
