### ISSUE TITLE
Changing from LV03 to LV95 - ST_Fineltra for Postgis

### ISSUE THREAD

**Issue by sjib** [QGEP/QGEP#193]
[Bezugsrahmenwechsel ST_Fineltra](http://kleinerpreisonline.de/blog/2015/10/04/bezugsrahmenwechsel-st-fineltra-in-action.html) in Action - a step by step instruction from Stefan Ziegler (in German) and the idea and [motivation behind it](http://kleinerpreisonline.de/blog/2015/09/17/bezugsrahmenwechsel-postgis-to-the-rescue.html)
Github Repository: https://github.com/strk/fineltra

**Comment by 3nids** [comment]
closing since it's not an issue.
it might an idea to have something in the docs, if needed, opening an issue in docs repo would be the way to go :)
