### ISSUE TITLE
performance problem

### ISSUE THREAD

**Issue by kfischerar** [QGEP/QGEP#198]
the view vw_qgep_reach takes a very loooooooong time to be done in qgis

**Comment by m-kuhn** [comment]
Can you try if this view is faster:

https://raw.githubusercontent.com/QGEP/datamodel/37b238b48aabfd33b2c52178bc32caa9dc675aa4/view/vw_qgep_reach.sql

**Comment by m-kuhn** [comment]
The following code retrieves features inside a view extent. It works quite fast here.

```
SELECT * FROM qgep.vw_qgep_reach
WHERE ST_Intersects(progression_geometry, ST_MakeEnvelope(750300, 263281, 750632, 263460, 21781));
```

**Comment by m-kuhn** [comment]
Can you enable logging on the postgres database? This will let us know, what SQL queries are sent from QGIS and for slow (more than 3 seconds in the post linked below) queries log additional debug output to analyze the problem.

http://gis.stackexchange.com/a/158862/9839

**Comment by kfischerar** [comment]
when in od_maintenance_event setting all active_zone to NULL it's much better means faster
