### ISSUE TITLE
Pictures for wastewater structures 

### ISSUE THREAD

**Issue by sjib** [QGEP/QGEP#199]
- Datamodel side, do we need a new table linked to wastewater structure or do we attach it to a maintenance event? 
- If it's the second one, how do we choose the "favorite" picture(s) which are shown on the wastewater structure's form?
- Implementation with relations and external resource widget

**Comment by sjib** [comment]
There are already two tables in the datamodel ([extension KEK] (https://github.com/QGEP/datamodel/blob/master/04_vsa_kek_extension.sql)):

**od_file**: Allows to link to any table of the datamodel with the following attributes: 
* class (name of the table/class)
* identifier (name of the datafile e.g. image.jpg)
* kind (type of file e.g. video or picture, etc. values could be standardized if needed with a value list), * object (obj_id of object in the reference table/class), relativ_path (additional path on the data_media)

Favourite picture could be selected with e.g. last_modified attribute

**od_data_media**: can be used for any kind of media (digital or analog)
* identifier (servername or volume label for digital media, name of folder if paper folder), 
* kind (kind of data_media)
* path (e.g. \\server\videos if server, Zugriffspfad zum Datenträger. z.B. DVD-Laufwerk -> D: , Server -> \\server\videos, Harddisk -> c:\videos . Kann auch eine URL sein. Bei einem analogen Videoband leer / Zugriffspfad zum Datenträger. z.B. DVD-Laufwerk -> D: , Server -> \\server\videos, Harddisk -> c:\videos . Kann auch eine URL sein. Bei einem analogen Videoband leer / Chemin d’accès au support de données, p. ex. lecteur DVD -> D: , - serveur -> \\ server\videos , disque dur -> c:\videos , Peut aussi être une URL. Pour une bande vidéo analogique: vide';
* location (location of server or location of analog media (e.g. address or office number)

**Comment by varrieta** [comment]
From our side, we need to link one or more pictures to a wastewater structure (we give the path of the picture). Thus the file od_data_media would work just fine.

But does it have to be linked to a maintenance event or could it be linked just to a wastewater_structure (didn't see any FK..) ?

**Comment by sjib** [comment]
Because we cannot make foreign keys in the data model from od_file to each of the 80 plus classes, the link information is stored in the attributes _class_ and _object_ of od_file. So you are free to link to any class in the data model (maintenance or wastewater_structure). If you want to link to both then you have to add the information about your e.g picture twice (two datasets).

**Comment by varrieta** [comment]
Ok so I guess it would work like that. But then could it be added to the tab so that when you add a new structure you could directly link picture to it?

**Comment by sjib** [comment]
Sounds like a good idea, to have a "media link" tab, that would implement this function to all forms (whether it be the vw_qgep_cover / reach or any other form, where we edit data). The function "media link" could either be started with a preselected value for class or in other cases could give all or a limited list of classes (so that you can choose whether the e.g. picture belongs to the manhole, the cover, the reach, the channel, the maintenance event.

@m-kuhn Does this look like something you can implement?
What do other think? Any needs and opinions?

**Comment by varrieta** [comment]
Yes it would work fine for our needs

**Comment by m-kuhn** [comment]
I will have to check how to work with this kind of data defined foreign key (target table in an attribute).
It would be easy if the class is just left empty (obj_id should be unique anyway). If not we'll have to implement code to deal with this situation either on the database or in QGIS.

I don't think there's a "add to all forms" possibility right now either, so let's focus on the ones where we need it in a first step (vw_qgep_cover and vw_qgep_reach, I guess...).

**Comment by sjib** [comment]
The pictures to a specific object are selected like this: SELECT od_file where object = obj_id of selected object.

**Comment by m-kuhn** [comment]
Linked to

 * vw_qgep_wastewater_structure
 * vw_qgep_channel

Relation on a separate new tab similar to structure parts.

**Comment by m-kuhn** [comment]
Also do the same for vw_qgep_reach

**Comment by m-kuhn** [comment]
@varrieta please add a screenshot :)

**Comment by varrieta** [comment]
![picture_file](https://cloud.githubusercontent.com/assets/20111558/19648718/57a3ab1a-9a03-11e6-89b3-a3ec6224b945.PNG)

It is now possible to add one or more pictures to wastewater_structure elements.

**Comment by sjib** [comment]
Add this feature to the documentation e.g. here 
https://qgep.github.io/docs/user-guide/digitizing/digitizingwastewaterstructures.html#further-attributes-and-classes

**Comment by varrieta** [comment]
Done
