### ISSUE TITLE
minidump when digitizing drainage channel

### ISSUE THREAD

**Issue by schorsch2** [QGEP/QGEP#202]
I try to digitize an new drainage channel as described in http://qgep.github.io/docs/user-guide/digitizing/digitizingdrainagechannel.html. After choosing  “Digitize Drainage Channel” I get a minidump.
Qgis 2.14.3
quep 0.5.11

**Comment by m-kuhn** [comment]
Would it be possible to try again with 2.16?
I will be working on reviewing some problems with this tool, but they just result in the tool not working properly and not directly in a crash.

**Comment by schorsch2** [comment]
Shure, I will try 2.16.

**Comment by schorsch2** [comment]
The result is a python-error:
`Fehler bei der Ausführung folgenden Codes:
import qgepplugin

feature = QgsMapLayerRegistry.instance().mapLayer('od_wastewater_structure').getFeatures( QgsFeatureRequest().setFilterExpression( 'obj_id = \'{}\''.format( '' ) ) ).next()
qgepplugin.ui.forms.digitizeDrainageChannel(feature.id(), 'od_wastewater_structure')


Traceback (most recent call last):
  File "", line 3, in 
StopIteration


Python-Version:
2.7.4 (default, Apr  6 2013, 19:54:46) [MSC v.1500 32 bit (Intel)]

QGIS-Version:
2.16.0-Nødebo 'Nødebo', d0b3e39`

**Comment by m-kuhn** [comment]
Can you open the vw_qgep_cover layer properties, go to the tab "Aktionen", double click the actions and in the python code replace

    [% "ws_obj_id" %]

with

    [% "obj_id" %]

**Comment by m-kuhn** [comment]
@varrieta it's probably the same for you.
If one of you can confirm this fixes the error, I'll upload a new project file

**Comment by m-kuhn** [comment]
@schorsch2 
sidenote: better change the language of your QGIS installation to English, we are still having some troubles with the plugin when the language is set to something else (confirmed at least with German).

**Comment by varrieta** [comment]
Hi Matthias,
Changing the actions python code made the wastewater structure disappear and froze the layer.. So I can't tell if it helped..  
I also change the language from French to English, but it didn't help neither..

**Comment by varrieta** [comment]
*changed

**Comment by schorsch2** [comment]
With the suggestions obove it works for me.

**Comment by m-kuhn** [comment]
It depends on the database version. The latest version requires this change, so I'll integrate it into the demo project.

@varrieta can you do the following steps:

 1. Select the layer vw_qgep_cover
 2. Open a python console (In the plugins menu)
 3. Enter `[f.name() for f in iface.activeLayer().fields()]`
 4. Copy the result here

**Comment by varrieta** [comment]
here is the answer:
[u'obj_id', u'brand', u'cover_shape', u'diameter', u'fastening', u'level', u'cover_material', u'positional_accuracy', u'sludge_bucket', u'venting', u'co_identifier', u'remark', u'renovation_demand', u'last_modification', u'fk_dataowner', u'fk_provider', u'ws_type', u'co_obj_id', u'identifier', u'accessibility', u'contract_section', u'financing', u'gross_costs', u'inspection_interval', u'location_name', u'records', u'ws_remark', u'renovation_necessity', u'replacement_value', u'rv_base_year', u'rv_construction_type', u'status', u'structure_condition', u'subsidies', u'year_of_construction', u'year_of_replacement', u'fk_owner', u'fk_operator', u'_label', u'depth', u'dimension1', u'dimension2', u'upper_elevation', u'manhole_function', u'material', u'surface_inflow', u'channel_usage_current', u'channel_function_hierarchic', u'manhole_orientation', u'bypass', u'special_structure_function', u'stormwater_tank_arrangement', u'highwater_level', u'relevance', u'terrain_level', u'waterlevel_hydraulic', u'absorption_capacity', u'defects', u'distance_to_aquifer', u'effective_area', u'emergency_spillway', u'kind', u'labeling', u'seepage_utilization', u'vehicle_access', u'watertightness', u'wn_obj_id', u'backflow_level', u'bottom_level', u'wn_identifier', u'wn_remark', u'wn_last_modification', u'wn_fk_dataowner', u'wn_fk_provider']

**Comment by m-kuhn** [comment]
For you the update is required as well.

which QGIS version are you using?

**Comment by varrieta** [comment]
2.15.0

**Comment by m-kuhn** [comment]
Can you update to 2.16? It's the latest stable release :)

**Comment by varrieta** [comment]
Yep, just did it but the layer vw_qgep_cover is still frozen :(

**Comment by m-kuhn** [comment]
What exactly means "the layer is frozen"?

**Comment by varrieta** [comment]
![ff](https://cloud.githubusercontent.com/assets/20111558/16832685/a81058f8-49ab-11e6-92a2-952eb66a72f7.PNG)

The layer doesn't appear on the screen and you can't edit it anymore..

**Comment by m-kuhn** [comment]
Can you check the layer properties => general => scale based visibility.

It should be 1:5000 / 1:1

**Comment by varrieta** [comment]
It works, thanks !! 
But why did the scale changed?

**Comment by m-kuhn** [comment]
Looks like an upgrade problem from 2.14 to 2.16. This will need to be
investigated.
