### ISSUE TITLE
Anlagekataster (QGIS report)

### ISSUE THREAD

**Issue by sjib** [QGEP/QGEP#209]
I started to use print composer to create a information object "Anlagekataster". You find a first edition of it below including the .qpt file. 

This is just as a first idea how to create reports in the print composer with attribute tables. Any comments and improvements are welcomed.
https://www.dropbox.com/s/i2fx1wuzuaxnxyv/anlagekataster.pdf?dl=0
https://www.dropbox.com/s/iblefriiyg16h8p/anlagekataster.qpt?dl=0

Are there other ways to do such a task in QGIS?

**Comment by m-kuhn** [comment]
Print composer is the most generic approach. Can you add it to the main
QGEP repository in the folder project/composers?

**Comment by sjib** [comment]
Has anyone already used [JasperReports](http://community.jaspersoft.com/wiki/jasperreports-library-samples#Subreport_Sample)?
Could this also be a tool to help us?
Any experience with QGIS like 

- Sourcepole (there seems to be a plugin)?  http://planet.qgis.org/planet/tag/jasperreports/ or

- Bernhard  Ströbl (https://www.fossgis.de/konferenz/2014/programm/attachments/507_jasper-reports.pdf)

**Comment by andreasneumann** [comment]
JasperReports is a powerful tool based on Java.

Given that it is an additional tool and has its separate learning curve (both for us at the project level and for our users), I would suggest to
- investigate if QGIS Atlas is good enough for our purpose (immediately available)
- wait for QGIS 3.x where there will be a reporting tool built into QGIS (no date yet, probably Q2 2017

QGIS 2.16 got JSON suport in QGIS Atlas to collect all information of table relations. In addition, there is aggregate support in 2.16, which may be useful for us, esp. when working with these relations.

Regarding QGIS Atlas I am quite knowledgeable and can give an introduction if you want one.

@sjib - is there an example available for how an "Anlagekataster" report should/could look like? Can you share one?

**Comment by sjib** [comment]
@andreasneumann Example - see dropbox links in my first post

**Comment by sjib** [comment]
And the original is here: http://www.imanagement.org/de/pdf/1.020.pdf
Other kinds we would need you can find here: http://www.imanagement.org/de/anwendung/nachname.html (List at the bottom with all kind of information objects needed for a GEP (still the way we defined it with first generations QGEP).

**Comment by sjib** [comment]
We would also need the possibility to add e.g. a sum (total of costs), not only the cost attribute per channel. 
Or calculate a percentage, add a "Kuchendiagramm" or something like this.

**Comment by m-kuhn** [comment]
-1 for a tool based on java

best solution if we can do it with qgis atlas
or use a python based tool like reportlab

**Comment by m-kuhn** [comment]
@sjib

Ping:
> Can you add it to the main QGEP repository in the folder project/composers?

This way we have things all here for improvements for review and improvements.

**Comment by sjib** [comment]
Should be done: https://github.com/QGEP/QGEP/blob/master/project/composers/anlagekataster.qpt
Or is this the wrong place?

**Comment by m-kuhn** [comment]
Perfect, thanks!
