### ISSUE TITLE
add value_english_description etc. to qgep.is_value_list_base

### ISSUE THREAD

**Issue by tudorbarascu** [QGEP/QGEP#210]
Hi,

By looking at some of the values in the vl_\* tables some of them need extra comments to know the exact meaning or to further shed some light on what they mean.

For instance, in the `qgep.vl_reach_elevation_determination` table 3 values exist:
- unknown
- innacurate
- accurate

The **is_dictionary_od_values** table is supposed to be like a merge of all the vl_\* tables.

However, only in this table you can find the value_description_en etc. that sheds the light on what accurate etc. mean:
e.g. accurate in french is **+/- 6 cm, lors de la détermination du tracé par différentes mesures, le triple, c'est-à-dire +/- 18 cm**

To me it makes sense to create the `value_description_en`, `value_description_fr` (and all the others that are missing .. class_id,  attribute_id ..) to the `qgep.is_value_list_base` table and turn the `is_dictionary_od_values` into a view.

Thoughts on this?

This came up as I needed/need to be more effective when adding Romanian values and I want to make a pull request with an sql file having the ro values. Seeing that the **value_ro** column exists in the `is_dictionary_od_values` but not in the vl_\* tables means unnecessary work: SQL inserts/updates in the sql commands I'm generating.

**Comment by tudorbarascu** [comment]
I can do it if I get a go from you guys.
@sjib I can also help with a script to transfer from the SQL model to your excel sheet and back.

**Comment by sjib** [comment]
I will check it tomorrow and come back to you

 

Von: Tudor Bărăscu [mailto:notifications@github.com] 
Gesendet: Samstag, 6. August 2016 16:56
An: QGEP/QGEP
Cc: Stefan; Mention
Betreff: Re: [QGEP/QGEP] add value_english_description etc. to qgep.is_value_list_base (#210)

 

I can do it if I get a go from you guys.
@sjib <https://github.com/sjib>  I can also help with a script to transfer from the SQL model to your excel sheet and back.

**Comment by sjib** [comment]
I can just update the datamodel so that vl_* tables will also have value_ro and abbr_ro to follow the current philosophie. 
With your suggested change I do not know if this means other changes needed. Any comments from @m-kuhn @andreasneumann @3nids

**Comment by m-kuhn** [comment]
For usage in QGIS (value relation widget) it's easiest to have things in their different vl_xxx tables.
I don't think we are using the is_dictionary_od_values table at all. We could as well just drop it if all the information is in the vl_ tables.

Sidenote:
> One day I'd like to handle translations outside the database directly on transifex and extend the value relation widget with translation support. But let's keep that out of the focus for now.

**Comment by tudorbarascu** [comment]
@sjib If you're going to update the vl_* tables to also have the **value_ro** and **abbr_ro** columns you can use ``git revert c01f826be340595659c1dad06ed05a3f7f1320d3`` so that you null the commit that does the same (with ALTER TABLE commands).

@m-kuhn Actually, the is_dictionary_od_values currently has some extra details that are not in the vl_* tables (description of some values etc.), I described this at the very beginning of the issue.

These extra details are also not currently used (but they should be). For instance, if I open up any of the value table it would have been very nice to see there the advance description of some values instead of going to the is_dictionary_od_values and find the correspondence.

**Comment by m-kuhn** [comment]
> @m-kuhn Actually, the is_dictionary_od_values currently has some extra details that are not in the vl_* tables (description of some values etc.), I described this at the very beginning of the issue.

I meant to write

We could as well just drop it *once* all the information is in the vl_ tables.

;)

**Comment by sjib** [comment]
solved with https://github.com/QGEP/datamodel/pull/39
