### ISSUE TITLE
vw_nework_segment missing in template_db.dump

### ISSUE THREAD

**Issue by varrieta** [QGEP/QGEP#211]
As the title says, the view vw_network_segment is missing when restoring template_db.dump to create a new qgep database..

**Comment by tudorbarascu** [comment]
@varrieta the newest data model needs postgis 2.3. I also got vw_network_segment missing when restoring the data model and @m-kuhn pointed me to this.
You are probably having the same issue, so please retry with postgis 2.3.

**Comment by varrieta** [comment]
Indeed I do have postgis 2.2, I'll update the version! Thanks :)
