### ISSUE TITLE
setting fk's in od_catchment_area

### ISSUE THREAD

**Issue by kfischerar** [QGEP/QGEP#215]
there are max 4 fk to set, where the area is associated

matthias made a usefull tool for wastewater-structures. we need the same to connect the catchment area to wastewater_node (and reach)

**Comment by m-kuhn** [comment]
![connect_catchment_area](https://cloud.githubusercontent.com/assets/588407/19478028/1fc70bb8-9541-11e6-831e-21f96884e514.png)
