### ISSUE TITLE
Network following not working for reach to reach connection

### ISSUE THREAD

**Issue by varrieta** [QGEP/QGEP#217]
We are having trouble with the network following tool when a reach is connected directly to another without passing through a structure (see example below for upstream following):

![network1](https://cloud.githubusercontent.com/assets/20111558/17695134/7b7dd570-63a7-11e6-96b8-72c9ade8b6d9.PNG)

![network2](https://cloud.githubusercontent.com/assets/20111558/17695135/7ca4186a-63a7-11e6-831e-6b74f707ea2e.PNG)

 We have created a wastewater_node at the connection emplacement, both of the reaches are connected to this node

**Comment by m-kuhn** [comment]
For cases like here, reaches can be directly connected to other reaches without a node. Can you delete the node and use the tool to connect wastewater network elements?

**Comment by varrieta** [comment]
Yes but then I won't be precise in the position of the connection?

**Comment by m-kuhn** [comment]
It also looks like the reaches in question are part of the secondary network which (according to the recommendations) should be connected as "blind connection" i.e. without node. So removing the node is actually the proper solution in this case.

The distance in percent between start and end is geometrically computed internally (that's why rebuilding the network tables takes so long).

**Comment by varrieta** [comment]
Not sure to get it. I understand why we need to remove the node, but then how can I digitize the reach with a precise horizontal positioning? What I mean is that I won't know the exact position of the connection.. (not sure that I made my self clear)

**Comment by m-kuhn** [comment]
The coordinates are known from the line geometry with as much precision as you draw/like. Maybe it's me who is missing something.

**Comment by varrieta** [comment]
Yes but the network geometry has to be drawn using the network node, right?

**Comment by varrieta** [comment]
I will explain better. Usually we go on the field, we mesure the start and end points of the reaches. Then we import these points in the database and then draw the reach in the QGIS project between the nodes
(does it helps? ^^)

**Comment by m-kuhn** [comment]
I think I understand.
When on the field you probably collect a lot of points that do not directly translate to wastewater nodes and are just "helpers" for digitizing.
I'd recommend to paste them onto a temporary layer that you use for snapping/orientation and only copy the wastewater nodes to the database while dumping everything else after digitizing.
In the future there will probably be a module (@3nids I think there's some development going on in this direction for qwat?)

**Comment by varrieta** [comment]
Yes that what I was meaning.
Ok we see know, and we will start working with an additional layer just for the drawing of the pipes. Thanks Matthias

**Comment by sjib** [comment]
@varrieta Is this solved? If yes please close

**Comment by varrieta** [comment]
@sjib Yes it is
