### ISSUE TITLE
Splitting features

### ISSUE THREAD

**Issue by m-kuhn** [QGEP/QGEP#219]
An error is raised that the obj_id (and identifier) is not unique.

Roadmap:
- Does it work with Ctrl+C/Ctrl+V?
  - Is this a workaround?
- Can we take the same approach for splitting
- Do we need a unique constraint?

CC @andreasneumann for the unique constraint

**Comment by varrieta** [comment]
Ctrl+C/Ctrl+V doesn't work for me, again it raises that the obj_id is not unique..

**Comment by m-kuhn** [comment]
From a user perspective, what would be the desired way to deal with the conflicting fields?

* obj_id : I guess generating a new default value without user intervention
* identifier : 
  * asking for a new one?
    * for only one of the two objects?
    * if yes, does it matter which one?
  * insert `NULL` (empty)

**Comment by varrieta** [comment]
I agree on generating a new default value without user intervention. 
For the identifier, it could propose which one to keep? or it would be to complicated?

**Comment by 3nids** [comment]
It could be an option of the split feature tool: if a field has a constraint value, open the attribute table with the two features (otherwise just don't).

**Comment by m-kuhn** [comment]
> For the identifier, it could propose which one to keep?

Do you have an idea in mind how to do that? Would it be ok if one becomes `NULL`?

> It could be an option of the split feature tool: if a field has a constraint value, open the attribute table with the two features (otherwise just don't).

 think it should be straightforward for the user to see what he needs to adjust, so opening the attribute table with 30+ attributes (talking about the vw_qgep_reach layer here) might be a bit of an overkill.

**Comment by urskaufmann** [comment]
Since now i have never had an user-defined identifier for a channel or a reach. for me the identifier has to be filled in from the system.  if the identifier should be something like upper-manhole-lower-manhole, then you have to rename both parts, if you split a channel or reach. Thats why i think, it's not a good idea to have such rules...

**Comment by varrieta** [comment]
Same in our case, we only have user-defined identifier for nodes or structures... 

What I have in mind is to propose to the user if he want to keep the current value for both reach or enter one or two new values.. 
But in our case, we also never have identifier for reaches (only  for nodes or structures), so maybe just inserting null values would be enought?

**Comment by m-kuhn** [comment]
F.Y.I.
I'm currently discussing a solution for this.

**Comment by 3nids** [comment]
One question on the side. When we split reaches with attached observations from inspection TV, what do we do with their distance field? It would be nice to have a way of automatically dispatch the damages and adapt their distances.....

**Comment by urskaufmann** [comment]
nearly the some problem, if the reach was already splitted between two manholes and you make TV. From TV inspection you will get the distances from one manhole. the operateur does not now, where the second reach begins. You have two reaches with e.g 10 and 15m length and you will get data of a 25m channel.

**Comment by 3nids** [comment]
I handle this in the plugin I made to import data, that is the least.
To tackle this, I suppose we need to make a dedicated tool?

**Comment by m-kuhn** [comment]
Depends on QGIS 3. Offer from @nyalldawson is accepted.

**Comment by m-kuhn** [comment]
Workaround: remove the identifier before splitting.

**Comment by sjib** [comment]
@varrieta Can you document the workaround with some screenshots?

**Comment by m-kuhn** [comment]
QGIS 3 just received the update to respect default values when splitting features. The datamodel has been updated appropriately as well.

So it's just a question of using Linux to install QGIS 3.0 or have some patience until it appears on Windows as well.

Next job: make it optional to create a new wastewater node and channel. And update foreign keys to preserve topology.

**Comment by sjib** [comment]
Operational with 3.0

**Comment by mdouchin** [comment]
Answering to @m-kuhn 
> Workaround: remove the identifier before splitting.

This is an illustration of the situation as following:
-[Oa]------------Ra------------[Ob]-
becomes
-[Oa]----Ra1----[Oc]----Ra2----[Ob]-

I have tried in QGIS 2.18, but I have no error on the identifier part, but on the od_reach_point unique object id constraint **pkey_qgep_od_reach_point_obj_id**

I tried to delete the **rp_from_obj_id** and **rp_to_obj_id** in the reach form before splitting, but it seems this is not taken into account by the underlying trigger.

Has anyone found a way of achieving this in future 2.18 LTR ?

**Comment by urskaufmann** [comment]
Test to split a reach in QGIS 3.2.2. 
I get this error:

Layer vw_qgep_reach: PostGIS-Fehler beim Attributhinzufügen: FEHLER: Einfügen oder Aktualisieren in Tabelle »reach_point« verletzt Fremdschlüssel-Constraint »rel_reach_point_wastewater_networkelement« DETAIL: Schlüssel (fk_wastewater_networkelement)=(NULL) ist nicht in Tabelle »wastewater_networkelement« vorhanden. CONTEXT: SQL-Anweisung »INSERT INTO qgep_od.reach_point( obj_id , elevation_accuracy , identifier , level , outlet_shape , position_of_connection , remark , situation_geometry , last_modification , fk_dataowner , fk_provider , fk_wastewater_networkelement ) VALUES ( COALESCE(NEW.rp_from_obj_id,qgep_sys.generate_oid('qgep_od','reach_point')) -- obj_id , NEW.rp_from_elevation_accuracy -- elevation_accuracy , NEW.rp_from_identifier -- identifier , NEW.rp_from_level -- level , NEW.rp_from_outlet_shape -- outlet_shape , NEW.rp_from_position_of_connection -- position_of_connection , NEW.rp_from_remark -- remark , ST_Force2D(ST_StartPoint(NEW.progression_geometry)) -- situation_geometry , NEW.rp_from_last_modification -- last_modification , NEW.rp_from_fk_dataowner -- fk_dataowner , NEW.rp_from_fk_provider -- fk_provider , NEW.rp_from_fk_wastewater_networkelement -- fk_wastewater_networkelement ) RETURNING obj_id« PL/pgSQL-Funktion qgep_od.vw_qgep_reach_insert() Zeile 3 bei SQL-Anweisung

**Comment by varrieta** [comment]
Working here with 3.2.3

**Comment by urskaufmann** [comment]
Confirm: not working with 3.4.6. For me this seems to be the same problem as with the "reuse last entered attribute values" option.

**Comment by m-kuhn** [comment]
Please change the configuration in the project. In the widget configuration of vw_qgep_reach.

On the follwing attributes, activate `NOT NULL`, `UNIQUE` (enforce both) constraints:

 - rp_from_obj_id
 - rp_to_obj_id
 - fk_wastewater_structure
