### ISSUE TITLE
History (Undo) for database

### ISSUE THREAD

**Issue by m-kuhn** [QGEP/QGEP#22]
How should this be solved?
- A table with a view showing the most recent and active entries
- A table where all the insert/update/delete modifications are saved per attribute

Interesting entry on stackoverflow:
http://stackoverflow.com/questions/1662355/dynamic-foreign-keys-how-to-implement

**Comment by m-kuhn** [comment]
Back to Denis

**Comment by sjib** [comment]
Is this the current progress of this work?
https://github.com/qwat/pg-history-viewer

**Comment by haubourg** [comment]
@sjib 
Yes, this is the plugin client for history audit. The functions are currently pending here https://github.com/2ndQuadrant/audit-trigger/pull/26 but the repo seems dead. 
We will port that in the plugin repository probably for a more convenient packaging, and have someone fix the plugins issues starting on monday.

**Comment by sjib** [comment]
How about this project that was presented at the User meeting last week: https://www.qgis.ch/de/ressourcen/anwendertreffen/2017/postgis-versionsverwaltung-horst-duester

**Comment by haubourg** [comment]
I think pg_version or pg_versionning plugins address another use case which is concurrent editing on the same area by different users. This is heavier and suppose that the user is familiar with the versionning concepts. 
It also implies additional view to handle the versioning system which would require to be sure that the trigger system is compatible with it. That said, if the need occurs to really have concurrent branches, like editing offline, version handling for reconciliation is a good idea (but Matthias know much more than me about that)

**Comment by m-kuhn** [comment]
There are different tools and approaches out there for this purpose.
Major thing to consider are foreign keys and that we have a lot of logic in the database (in views and triggers).

It was the first time I heard about pgvs at the presentation this week, so I don't know anything more than in the presentation.
Do you already have something implemented on qwat side?

**Comment by haubourg** [comment]
@m-kuhn QWAT uses only history viewer to log transactions only. It currently has some issues on plugin's side, and the main one for QGEP is that it doesn't work inside the transaction group, we have to see how this could be possible. 

the versioning use case is described here, but I'm not the expert in that area: http://oslandia.com/en/2013/07/13/qgis-versioning-plugin/

**Comment by m-kuhn** [comment]
From a quick read, this could be critical for qgep.

> Withing the PostGIS database, the views on revisions must be read-only  and historized tables should not be edited directly.

Though I'm pretty sure our views could be adapted to work with the versioning.

**Comment by haubourg** [comment]
+1 this, our thick; database design for QWAT-QGEP would require specific adaptations compared to the generic plugin(s) logic. Note that I didn't play with Sourcepole's plugin so it might be designed quite differently..

**Comment by m-kuhn** [comment]
@lbartoletti can this be closed with the latest audit triggers and plugin?

**Comment by ponceta** [comment]
pg history viewer is now the history tool for database.

I'll make a small demo on next codesprint if possible (gentle ping @sjib )
