### ISSUE TITLE
add cover

### ISSUE THREAD

**Issue by kfischerar** [QGEP/QGEP#222]
we have to add a new cover to an existing wastewater_structure.

we load vw_cover, add feature: we get just a empty, simple mask. it's possible to fill but you have to know a lot of things --> it should open a prefilled mask or at least a list with the valid data

**Comment by m-kuhn** [comment]
Can you be more specific what you would like to have pre-filled when creating a new cover?

**Comment by m-kuhn** [comment]
From what I think, it should be possible to open the form on vw_qgep_wastewater_structure, go to the cover tab and click the + button. What's missing there is the option to add a geometry, currently only attributes are supported.

**Comment by sjib** [comment]
@kfischerar how would you like to be able to add the geometry?
@m-kuhn Could it also be a way to do this by creating a cover on the cover layer (as point) and then use the connection tool to connect it to the correct wastewater structure?

**Comment by urskaufmann** [comment]
I just write the docu to this problem and I will update the cover form with the valuelist

**Comment by sjib** [comment]
@urskaufmann Is this done?

**Comment by urskaufmann** [comment]
done, pullrequest for docu is sent

**Comment by urskaufmann** [comment]
please close
