### ISSUE TITLE
connect cover

### ISSUE THREAD

**Issue by kfischerar** [QGEP/QGEP#223]
the button "Connect wastewater networkelements" should also be able to connect an newly added cover to an existing wastewater_structure

**Comment by m-kuhn** [comment]
Identify an existing cover on vw_qgep_cover and use the "identify feature" button on the form. Click on an existing cover of the target wastewater structure.

![link-cover](https://cloud.githubusercontent.com/assets/588407/19558595/a65c0f6c-96cb-11e6-917a-9739802b5f39.png)
