### ISSUE TITLE
Adding automatic savepoints to a transaction for each edit action

### ISSUE THREAD

**Issue by tudorbarascu** [QGEP/QGEP#225]
This would permit the return to previous save points.

See also #221

**Comment by tudorbarascu** [comment]
@m-kuhn can you add the "Upstream" tag please?

**Comment by m-kuhn** [comment]
That! would! be! awesome!

**Comment by m-kuhn** [comment]
Is this done?

**Comment by haubourg** [comment]
@m-kuhn From my knowledge, transaction groups in QGIS do that since @vmora restored the undo/redo feature for transaction groups in 3.0.

**Comment by m-kuhn** [comment]
Thx @haubourg 
exactly my understanding as well
