### ISSUE TITLE
Reshape tool merging feature

### ISSUE THREAD

**Issue by varrieta** [QGEP/QGEP#227]
When trying to extend a reach and connect it to an existing wastewater_structure, other reaches already connected to the wastewater_structure will merge with the extended reach.

**Comment by sjib** [comment]
Is there any adaption neeed? To what feature or tool?

**Comment by m-kuhn** [comment]
@varrieta can you just reshape the reach until somewhere close to the WS and then move the last node onto it in a separate step?

Or we'll need to define the specific behavior of the reshape tool (I don't have enough experience with it out of the box to see all the critical points).

**Comment by varrieta** [comment]
@m-kuhn just tried, and yes it would work that way. You then need to add a third step that is to use the "connect wastewater networkelements" tool to connect the reshaped reach and the structure itself.
