### ISSUE TITLE
postgis error when moving covers

### ISSUE THREAD

**Issue by oliver-ch** [QGEP/QGEP#228]
> Layer vw_qgep_cover: PostGIS error while changing geometry values: FEHLER: First argument must be a LINESTRING CONTEXT: SQL-Anweisung „UPDATE qgep.od_reach RE SET progression_geometry = ST_SetPoint( RE.progression_geometry, 0, -- SetPoint index is 0 based, PointN index is 1 based. ST_TRANSLATE(ST_PointN(RE.progression_geometry, 1), ST_X(NEW.situation_geometry) - ST_X(OLD.situation_geometry), ST_Y(NEW.situation_geometry) - ST_Y(OLD.situation_geometry ) ) ) WHERE fk_reach_point_from IN ( SELECT RP.obj_id FROM qgep.od_reach_point RP LEFT JOIN qgep.od_wastewater_networkelement NE ON RP.fk_wastewater_networkelement = NE.obj_id WHERE NE.fk_wastewater_structure = NEW.obj_id )“ PL/pgSQL-Funktion qgep.vw_qgep_cover_update() Zeile 136 bei SQL-Anweisung

`ST_SetPoint` needs a linestring as input and we are now using curves therefore the error. Converting the curves to lines with `ST_CurveToLine` solves the issue, however it won't let me convert the line back to a curve using `ST_LineToCurve`.

**Comment by m-kuhn** [comment]
Does `ST_ForceCurve` work better?

**Comment by oliver-ch** [comment]
Yes it does. However if it is used with an actual curve it will result into splitting it up into small pieces.
