### ISSUE TITLE
3D geometry columns

### ISSUE THREAD

**Issue by m-kuhn** [QGEP/QGEP#232]
Do we need separate 2D and 3D columns? Can we just have one 3D column which has no trouble being home for 2D geometries as well?

Proposal: remove all 3D columns and redefine the main columns to have a Z value as well.

**Comment by sjib** [comment]
We need to be flexible to be able to handle a mix of 2D and 3D data in the same project. Not all data will be in 3D right away. So the question is how to handle this the easiest way. What options does QGIS offer for this?

**Comment by m-kuhn** [comment]
I wouldn't be aware of a limitation of storing 2D information in a 3D column on PostGIS side.

**Comment by m-kuhn** [comment]
ST_Force2D

and

    ST_Force3D

Test pasting of 2D features into 3D layers first

**Comment by sjib** [comment]
Currently we create geometry colums like this:

> SELECT

 AddGeometryColumn('qgep', 'od_reach', 'progression_geometry', 21781, 'COMPOUNDCURVE', 2, true);
CREATE INDEX in_qgep_od_reach_progression_geometry ON qgep.od_reach USING gist (progression_geometry );
COMMENT ON COLUMN qgep.od_reach.progression_geometry IS 'Start, inflextion and endpoints of a pipe / Anfangs-, Knick- und Endpunkte der Leitung / Points de départ, intermédiaires et d’arrivée de la conduite.';
SELECT AddGeometryColumn('qgep', 'od_reach', 'progression3d_geometry', 21781, 'COMPOUNDCURVE', 3, true);
CREATE INDEX in_qgep_od_reach_progression3d_geometry ON qgep.od_reach USING gist (progression3d_geometry );
COMMENT ON COLUMN qgep.od_reach.progression3d_geometry IS 'Start, inflextion and endpoints of a pipe (3D coordinates) / Anfangs-, Knick- und Endpunkte der Leitung (3D Koordinaten) / Points de départ, intermédiaires et d’arrivée de la conduite (coordonnées 3D)';

> 
Do we just change the regular 2D definition with the 3D definition? This might be confusing in the future.
Or do we just skip the 2D definition and do everything with the 3D attribute names where they allready exist in the (INTERLIS) datamodell?
Any comments? @andreasneumann @m-kuhn @3nids @urskaufmann 

http://postgis.net/docs/AddGeometryColumn.html

**Comment by sjib** [comment]
@varrieta as discussed today please make a sql update script to add a new column (with 3D geometry type), copy old geometry, delete old geometry, rename new geometry with old name
@m-kuhn How can I assign @varrieta - she does not show up in the list

**Comment by sjib** [comment]
I will update the model skript for new releases

**Comment by varrieta** [comment]
Here is the sql to move from 2d to 3d geometries, let me know if it works 
[change_to_3d.zip](https://github.com/QGEP/QGEP/files/713248/change_to_3d.zip)

**Comment by m-kuhn** [comment]
Thank you!
Could you add this to the https://github.com/QGEP/datamodel repository in the folder `fixes` and add it to `scripts/db_setup.sh` (click on the "fork" button to make a copy of the repo, then edit your copy of the repository and make a "pull request").

**Comment by varrieta** [comment]
Sorry but I don't understand what you want me to change in the db_setup.sh?

**Comment by m-kuhn** [comment]
On line 65 add

    psql "service=${PGSERVICE}" -v ON_ERROR_STOP=1 -f ${DIR}/fixes/fix_3d_geometry.sql

**Comment by varrieta** [comment]
ok just did! :)

**Comment by m-kuhn** [comment]
Thanks to @varrieta the datamodel and demodata are updated and a migration script is available.

I wonder now, if all data should be 3D. For the reach points we have an attribute with the Z coordinate, so either we drop the Z coordinate again or we enforce it from the attribute.

**Comment by sjib** [comment]
Where there is an attribute with a corresponding z value (level) we should not create a 3D coordinate – else we are starting to store data twice – which will create problems. VSA-DSS and sia405 are currently only 2.5 D models with their extensions 3D.

**Comment by m-kuhn** [comment]
With 2.5D you are referring to 2D + attribute?

**Comment by sjib** [comment]
Yes –  attribute having a z- coordinate like level.

**Comment by sjib** [comment]
@m-kuhn Can you add a reference now to the final solution and update?

**Comment by sjib** [comment]
https://github.com/QGEP/datamodel/commits/master/fixes/fix_3d_geometry.sql

**Comment by sjib** [comment]
I think we should generally discuss this issue for the future. Will Perimeters like canton, municipality, planning_zones etc. also come with 3D coordinates in the future? Or is this data, that anyway will not be integrated anymore in QGEP because it is stored in other systems?

**Comment by m-kuhn** [comment]
Are there reasons to keep these in 3D?

Anyway, for polygons the z values would only be safed for the borders. There would be a TIN datatype for keeping more data but I guess that's out of scope.

**Comment by sjib** [comment]
Current datamodel will be corrected like in [fix 3d](https://github.com/QGEP/datamodel/blob/master/fixes/fix_3d_geometry.sql)

`ALTER TABLE qgep.od_wastewater_structure ADD COLUMN detail_geometry_geometry geometry('CURVEPOLYGON', :SRID);
CREATE INDEX in_qgep_od_wastewater_structure_detail_geometry_geometry ON qgep.od_wastewater_structure USING gist (detail_geometry_geometry );
COMMENT ON COLUMN qgep.od_wastewater_structure.detail_geometry_geometry IS 'Detail geometry especially with special structures. For manhole usually use dimension1 and 2. Also with normed infiltratin structures.  Channels usually do not have a detail_geometry. / Detaillierte Geometrie insbesondere bei Spezialbauwerken. Für Normschächte i.d. R.  Dimension1 und 2 verwenden. Dito bei normierten Versickerungsanlagen.  Kanäle haben normalerweise keine Detailgeometrie. / Géométrie détaillée particulièrement pour un OUVRAGE_SPECIAL. Pour l’attribut CHAMBRE_STANDARD utilisez Dimension1 et 2, de même pour une INSTALLATION_INFILTRATION normée.  Les canalisations n’ont en général pas de géométrie détaillée.';
ALTER TABLE qgep.od_wastewater_structure ADD COLUMN detail_geometry3d_geometry geometry('CURVEPOLYGONZ', :SRID);
CREATE INDEX in_qgep_od_wastewater_structure_detail_geometry3d_geometry ON qgep.od_wastewater_structure USING gist (detail_geometry3d_geometry );
COMMENT ON COLUMN qgep.od_wastewater_structure.detail_geometry3d_geometry IS 'Detail geometry (3D) especially with special structures. For manhole usually use dimension1 and 2. Also with normed infiltratin structures.  Channels usually do not have a detail_geometry. / Detaillierte Geometrie (3D) insbesondere bei Spezialbauwerken. Bei Normschächten mit Dimension1 und 2 arbeiten. Dito bei normierten Versickerungsanlagen. Kanäle haben normalerweise keine Detailgeometrie. / Géométrie détaillée (3D) particulièrement pour un OUVRAGE_SPECIAL. Pour l’attribut CHAMBRE_STANDARD utilisez Dimension1 et 2, de même pour une INSTALLATION_INFILTRATION normée.Les canalisations n’ont en général pas de géométrie détaillée.';`

to 
`ALTER TABLE qgep.od_wastewater_structure ADD COLUMN detail_geometry_geometry geometry('COMPUNDCURVEZ', :SRID);
CREATE INDEX in_qgep_od_wastewater_structure_detail_geometry_geometry ON qgep.od_wastewater_structure USING gist (detail_geometry_geometry );
COMMENT ON COLUMN qgep.od_wastewater_structure.detail_geometry_geometry IS 'Detail geometry (3D) especially with special structures. For manhole usually use dimension1 and 2. Also with normed infiltratin structures.  Channels usually do not have a detail_geometry. / Detaillierte Geometrie insbesondere bei Spezialbauwerken. Für Normschächte i.d. R.  Dimension1 und 2 verwenden. Dito bei normierten Versickerungsanlagen.  Kanäle haben normalerweise keine Detailgeometrie. / Géométrie détaillée particulièrement pour un OUVRAGE_SPECIAL. Pour l’attribut CHAMBRE_STANDARD utilisez Dimension1 et 2, de même pour une INSTALLATION_INFILTRATION normée.  Les canalisations n’ont en général pas de géométrie détaillée.';`
