### ISSUE TITLE
Problem with invalid fields when value missing

### ISSUE THREAD

**Issue by varrieta** [QGEP/QGEP#240]
When we create a wastewater_structure element, we should be able to click on the "OK" button even if the "level" field is NULL because sometimes the value is missing

**Comment by m-kuhn** [comment]
Possible solutions for this are currently being discussed in https://github.com/qgis/QGIS/pull/3673#issuecomment-256268230.

I guess you would rather prefer to remove the constraints altogether until we can make them optional?

**Comment by varrieta** [comment]
Yes I think it would be better, for the moment

**Comment by m-kuhn** [comment]
Removed the constraint from the demo project for now.

Optional constraints will be in QGIS 3.0, see qgis/QGIS#3673 

What we could do for now is something like the following picture: special formatting of bad values in the attribute tables:

![screenshot from 2015-12-01 10-17-09](https://cloud.githubusercontent.com/assets/660191/15634697/8965e652-25ca-11e6-8f51-83c079951226.png)

Which values are required for a new manhole/cover/wastewater node combination? ( CC @urskaufmann )

**Comment by sjib** [comment]
Requirements for different tasks are defined in the [SIA405 2015] (http://www.webnorm.ch/null/null/sia%202015/d/2012/D/Product) - Minimal requirements for Leitungskataster (LK) - x in colum of object catalogue. And for Werkinformation (WI).
For a GEP there are two minimum requirements defined in the [Wegleitung GEP Daten] (https://www.vsa.ch/publikationen/shop/produkt/wegleitung-gep-daten/) - case A (Abwasserverband) and T (Trägerschaft).

**Comment by sjib** [comment]
`QGIS Upstream` issues have been solved. @varrieta can we close this? And open another issue if we want to add requirements to the project file.
