### ISSUE TITLE
attribute type of od_file.identifier

### ISSUE THREAD

**Issue by varrieta** [QGEP/QGEP#242]
The type of the attribute od_file.identifier is character varying(40), I think it is too small. Access path to file are often much longer.

**Comment by 3nids** [comment]
from the model, one should use relative_path for the path.

If we want to respect this, we need to extend the external resource widget in QGIS to support this. i.e. make the relative path support expressions. I wanted to ask @m-kuhn to do this. It should not be too complicated but won't be available before QGIS 3.0.

**Comment by m-kuhn** [comment]
sounds like a good plan.
can we make a view mimic  this behaviour for now?

**Comment by varrieta** [comment]
Duplicate of #369
