### ISSUE TITLE
Problem with geometry type (MultiPoint) of  vw_qgep_wastewater_structure

### ISSUE THREAD

**Issue by varrieta** [QGEP/QGEP#243]
I'm having trouble digitizing a new wastewater_structure because of the geometry type ''Multipoint'':

_Layer vw_qgep_wastewater_structure: PostGIS error while adding features: ERREUR: Geometry type (MultiPoint) does not match column type (Point) CONTEXT: instruction SQL « INSERT INTO qgep.vw_wastewater_node( obj_id , backflow_level , bottom_level , situation_geometry , identifier , remark , last_modification , fk_dataowner , fk_provider , fk_wastewater_structure ) VALUES ( NEW.wn_obj_id , NEW.backflow_level , NEW.bottom_level , NEW.situation_geometry , COALESCE(NULLIF(NEW.wn_identifier,''), NEW.identifier) , NEW.wn_remark , NOW() , COALESCE(NULLIF(NEW.wn_fk_provider,''), NEW.fk_provider) , COALESCE(NULLIF(NEW.wn_fk_dataowner,''), NEW.fk_dataowner) , NEW.obj_id ) » fonction PL/pgsql qgep.vw_qgep_wastewater_structure_insert(), ligne 166 à instruction SQL_ 

ps:I just downloaded the latest datamodel and gqs project.

**Comment by m-kuhn** [comment]
Thanks for the report.

Sorry, the fix was ready but not yet in the repository.

Either reinstall the datamodel (when regenerated in 5 minutes)

or run the following sql file on your db:

https://raw.githubusercontent.com/QGEP/datamodel/master/view/vw_qgep_wastewater_structure.sql

**Comment by varrieta** [comment]
Ok, I will! Thanks Matthias :)
