### ISSUE TITLE
Gully

### ISSUE THREAD

**Issue by max-trolliet** [QGEP/QGEP#246]
Hi,
I was wondering how to deal with the gullies. It is in the vl_manhole_function. But is it considered a manhole? How is it linked to a slurry_collector like it often is the case?

**Comment by sjib** [comment]
The VSA-DSS distinguishes between [manholes] (https://www.vsa.ch/nc/glossar/fr/terms/main/136/) and [special_structures] (https://www.vsa.ch/nc/glossar/fr/terms/main/146/)
The difference is, whether the wastewater structure is built from normed elements or not.

Gully ( Einlaufschacht / [chambre_avec_grille_d_entree] (https://www.vsa.ch/nc/glossar/fr/terms/both/202/) 
Slurry_collector ([Schlammsammler] (https://www.vsa.ch/nc/glossar/de/terms/both/326/) / depotoir
