### ISSUE TITLE
Topology not working

### ISSUE THREAD

**Issue by varrieta** [QGEP/QGEP#248]
When constructing new data into QGEP, it happens that the topology  isn't created correctly  (see example below where I use upstream button). Then even if I use the "connect wastewater networkelements" button, I can't recreate the correct topology.

![capture1](https://cloud.githubusercontent.com/assets/20111558/20338441/80554d4e-abd7-11e6-9897-32dc5307715f.JPG)

![capture2](https://cloud.githubusercontent.com/assets/20111558/20338442/81bb32ac-abd7-11e6-8ed3-dc5e603338c5.JPG)

![capture3](https://cloud.githubusercontent.com/assets/20111558/20338443/830c9cae-abd7-11e6-8807-63f823816bff.JPG)

**Comment by m-kuhn** [comment]
Did you click the "recreate topology" (SQL icon I think) button?

**Comment by varrieta** [comment]
Yes! I even ran the SQL from the database

**Comment by m-kuhn** [comment]
I have a suspicion...
Can you check the forms for PVC100 and PVC120, on the *reach points* tabs, check for the rp_from_fk_wastewater_networkelement for PVC120 and rp_to_fk_wastewater_networkelement for PVC100.

**Comment by varrieta** [comment]
PVC 100 : rp_to_fk_wastewater_networkelement = ch16yyrfRE001845
PVC 120 : rp_from_fk_wastewater_networkelement = ch16yyrfRE001844

**Comment by m-kuhn** [comment]
The data looks reasonable.

So it looks like there's a bug in the network tracking views.

**Comment by varrieta** [comment]
What is strange is that with some cases it works and some others it doesn't..

**Comment by m-kuhn** [comment]
The possible situations are the following ones:

 * reach connected to wastewater node (fk_wastewater_networkelement points to an id like `ch16yyrfWN...`)
 * reach connected to reach (Y connection, blind connection) (fk_wastewater_networkelement points to an id like `ch16yyrfRE...`)
 * reach connected to reach: case here (fk_wastewater_networkelement points to an id like `ch16yyrfRE...`)

**Comment by varrieta** [comment]
For the first situations (reach connected to wastewater node), it seems to always work

**Comment by varrieta** [comment]
Wait i found a solution: when using the "connect wastewater networkelements" button, I connected the reach PVC 100 with the reach point between PVC 100 and PVC 120 instead of connecting it to the reach PVC 120.

![capture](https://cloud.githubusercontent.com/assets/20111558/20340952/58f12c3e-abe4-11e6-872b-c75eac57b241.JPG)

**Comment by m-kuhn** [comment]
Can you paste the new foreign key?

**Comment by varrieta** [comment]
mmh.. now I have the same thing than before.. strange!

**Comment by varrieta** [comment]
I mean it isn't working again

**Comment by varrieta** [comment]
Ok now it works again and I have the foreign key:
PVC 100 : rp_to_fk_wastewater_networkelement = ch16yyrfRE001844
PVC 120 : rp_from_fk_wastewater_networkelement = ch16yyrfRE001844

**Comment by m-kuhn** [comment]
Is there a reach between the two? I thought they are directly connected.

On the form on the Reach tag, there's an object id, can you check the ids of PVC 100 and PVC 120?

**Comment by varrieta** [comment]
No they are directly connected. 

PVC 100: obj_id = ch16yyrfRE001844
PVC 120: obj_id = ch16yyrfRE001845

**Comment by m-kuhn** [comment]
so according to your message above, PVC 100 is now connected to itself, so doing a loop ;)

**Comment by varrieta** [comment]
Yes, exactly ^^

**Comment by m-kuhn** [comment]
I guess you can fix that on your side (draw the line from one reach to the other, not to the end point).

But I admit a feedback in this situation would be good.

**Comment by varrieta** [comment]
Which line do you mean?

**Comment by m-kuhn** [comment]
Connect elements: line from PVC 100 to PVC 120 -> check "reach point to"

**Comment by varrieta** [comment]
Yes but in this case, if I do that, it doesn't work.

**Comment by varrieta** [comment]
It work only if PVC 100 is connected to itself..

**Comment by m-kuhn** [comment]
can you select both records, "save as geopackage" only selection and attach the file here?

**Comment by varrieta** [comment]
[reach.zip](https://github.com/QGEP/QGEP/files/595107/reach.zip)

In this case it doesn't work again.. :(

**Comment by m-kuhn** [comment]
I guess the PVC 200 downstream has the obj_id `ch16yyrfRE001843` and the node of the cover upstream has the obj_id `ch16yyrfWN002442`. Can you verify that.

If this is true, can you change the field rp_to_fk_wastewater_networkelement of the reach `ch16yyrfRE001844` from `ch16yyrfRE001844` to `ch16yyrfRE001845` (Because right now it's still a loop).

**Comment by varrieta** [comment]
Yes, you are right about the obj_id of the PVC 200 and the node.

Nevertheless, I changed the rp_to_fk_wastewater_networkelement of PVC100 to ch16yyrfRE001845 but it still doesn't work.

**Comment by m-kuhn** [comment]
Can you run one more test, please.

Move the connection of PVC 100 a bit further down, so it's not a direct connection, but a Y connection (the upper end of PVC 120 will be dangling but forget about that for the moment, it's just for the test...).

I want to know if there's a problem with network tracking of directly connected reaches (when I developed it, I think I only thought of and tested blind Y-connections).

**Comment by varrieta** [comment]
Just did.. the result is weird ^^

![capture](https://cloud.githubusercontent.com/assets/20111558/20429762/e47057b4-ad90-11e6-9384-fa8700fd17a0.JPG)

**Comment by m-kuhn** [comment]
:joy: that's nice!

can you send me a database dump?

**Comment by varrieta** [comment]
haha okay :)

**Comment by sjib** [comment]
@varrieta Please provide cases which still do not work

**Comment by m-kuhn** [comment]
The downstream reach (ch16yyrfRE001845) is connected to the upstream reach (ch16yyrfRE001844) in the reach_point_from. Correcting this (I created a new wastewater_node and connected the reach_point_from to this) also fixes the network tracking.

1. @urskaufmann @sjib should we prevent setting reach_point_from to another reach?

**Comment by urskaufmann** [comment]
If you read "Wegleitung GEP-Daten", then this case exists not. So the answer is yes, the reach_point_from should not be connected to another reach.
But I do not understand, why this is a Problem for the network tracking. Before Wegleitung GEP-Daten (2013) I had this Connection in most of my data and GEPView-network-tracking worked well

**Comment by m-kuhn** [comment]
When there are multiple reaches connected without wastewater node in a channel (e.g. change in material), the *reach point from* is not connected (i.e. it is NULL)? (I only thought of blind connections yesterday).

**Comment by sjib** [comment]
You are not allowed to connect two reaches via a reach_point. If you want to connect two reaches without a wastewater_node you have to use reach-reach topology (meaning that the TO reach_point of the reach connects with fk_wastewater_network_element to the next reach (instead of to  a wastewater_node). A reach_point cannot be connected to several reaches. This case is only allowed for secondary wastewater networks (SAA). In the primary system you always need a wastewater_node between reaches.

See also Wegleitung GEP Daten Beilage 4, 3.1.1.2 Topology  

@urskaufmann please review this comment.

**Comment by m-kuhn** [comment]
The problems only appear when the *reach point from* is set to a reach that does not touch the from point geometrically (see image above). It's mainly a graphical issue, based on the fact that we try to insert missing pieces into our network topology graph (reach points not on top of wastewater nodes, blind connections ...)

 1. So we can either fix the graph creation code to work with malformed data
 2. Help the user to produce good data
 3. Do both

I would go for number 2 and document somewhere that something like in number 1 you should check your topology connections for .

**Comment by m-kuhn** [comment]
Topology
=======

**The reach point from is never connected to another reach**. When there is a change in material (or similar) the reach point from is set to NULL.

Code
====

* Update the connect network element tool that it warns when someone tries to connect the reach point from to a reach (and propose to set to NULL).
* Update the wizard to always connect the *reach point to* in such cases and never the *reach point from*

Documentation
===========

Insert the above screenshot with a description of the issue and recommend the user to review their topology.

**Comment by varrieta** [comment]
Indeed, when creating the topology for these reaches, I would always connect the two reaches in one sens (_to) and the other (_from)...

I agree with Matthias, prevent the user from producing wrong topology by documenting the problem would be good. I can take care of the documentation if you want?

**Comment by sjib** [comment]
@varrieta yes - please do so
