### ISSUE TITLE
QGEP SRID MN95

### ISSUE THREAD

**Issue by varrieta** [QGEP/QGEP#252]
Hi,
Since Canton of Neuchâtel recently moved to MN95, I will have to update our data and modify QGEP SIRD to MN95. I was wondering if it would be good to directly do the change in the general QGEP datamodel?

**Comment by 3nids** [comment]
In qwat it is à parameter upon db creation in the shell script.

**Comment by kfischerar** [comment]
hi,
we have to move as well to LV95 (21821 to 2056). until now i didn't find a
solution for windows-version. may be we do it like this:
1. create a shp with obj_id and geometry
2. go to the REFRAME service
3. transform the SHP to SQL
4. import into the table
5. rename/remove old geometry

any easier solution is appreciated :-)


2016-11-18 11:28 GMT+01:00 varrieta <notifications@github.com>:

**Comment by varrieta** [comment]
Do you have FME ?
I was thinking to:
1. Pass the table through FME (Postgis - reframe projector - Postgis) 
2. Rename/remove old geometry 

But I didn't tried yet :)

**Comment by urskaufmann** [comment]
for me, there is only one real solution: ITF-export - REFRAME - ITF-Import.
INTERLIS-Import/export must run without exception anyway. Then it's no problem to do the reframe

**Comment by kfischerar** [comment]
i completly agree with urs

of course FME would be an alternative, but it's not open source ;-)

2016-11-18 14:08 GMT+01:00 urskaufmann <notifications@github.com>:

**Comment by m-kuhn** [comment]
or directly inside postgis?

**Comment by kfischerar** [comment]
i think the necessary function ST_FINELTRA is available only for linux (no
windows)
see also the very good blog #8 et al from stefan ziegler

2016-11-18 16:42 GMT+01:00 Matthias Kuhn <notifications@github.com>:

**Comment by kfischerar** [comment]
i wrote a batch file to create a new database from scratch, i will send it to matthias so he integrates it at a good place in the github, maybe you have to adapt path etc
[kf_inst_db.zip](https://github.com/QGEP/QGEP/files/642463/kf_inst_db.zip)
[kf_changeTo_2056.zip](https://github.com/QGEP/QGEP/files/642464/kf_changeTo_2056.zip)

i have a sql file that changes the srid vom 21781 (=av03) to 2056 (=LV95), the database must be EMPTY, @m-kuhn .... same procedure

if you want to work with LV95 you also have to check your xy.qgs and change from 21781 to 2056 as well

maybe the files are attached ;-)

**Comment by 3nids** [comment]
LV95 can be set in datamodel upon creation thanks to #27 
Demo data still in LV03
Example of script to translate project to LV95 https://github.com/sige-riviera/qgep_sige/blob/0ed75e37ac6c49725c3124cd5513187e8db78b95/translate_project/translate.py#L103-L122

Closing as this is not an issue anymore.
