### ISSUE TITLE
Change od_cover.depth from [mm] to [m]

### ISSUE THREAD

**Issue by m-kuhn** [QGEP/QGEP#253]
See https://github.com/QGEP/QGEP/issues/238#issuecomment-262264106

`qgep.od_cover.depth` is currently of type `smallint` / unit type `[mm]`. This should be changed to `numeric`  / unit type `[m]`.

Questions
=======

* What precision and maximum value is required? 999.999 m (as in `numeric(6, 3)`)?
* The fields is not dynamically created by a view but hardcoded in `03_qgep_db_dss.sql`. Since it says "calculated", is this information redundant? E.g. `cover.level - node.bottom_level` would make sense, but in case of multiple nodes this is ambiguous.
* There are other tables that have this attribute as well. To me it looks like this should be either on the cover or the wastewater structure but not both.
  * qgep.od_manhole.depth
  * qgep.od_discharge_point.depth
  * qgep.od_special_structure.depth
  * qgep.od_infiltration_installation.depth

**Comment by varrieta** [comment]
- For our data, numerci(6,3) would be clearly enough.
- I would say it should be on the wastewater structure since it needs both cover.level and node.bottom_level to be calculated

**Comment by urskaufmann** [comment]
- 99.999m or 999.999
- wastewater structure
- for me, depth is the difference between cover.level and the minimum of all connected node.bottom_level and reachpoint.level. If there is more than one cover, then take the maximum cover.level.

**Comment by m-kuhn** [comment]
So, depth is a derived value which should be read-only, calculated between as `main_cover.level - min(node.bottom_level)`?

**Comment by varrieta** [comment]
I agree with that!
