### ISSUE TITLE
slope,length not filled in automatically into my view but it' calculated (vertical section)

### ISSUE THREAD

**Issue by Marpingen** [QGEP/QGEP#255]
There's one thing wich I can't figure out. When I'm done with the digitizing of my reach, I can see a few informations but there are also some informations which I'm missing. Like the lenght or slope. 

Just to give you an overview of my recent work.
I imported all cover (with the informations like level, bottom level,location etc.) of my region with the database into QGIS. Now I'm trying to do the reachs, wich I'm supposed to do manually. But what I recognized is, that a few informations which could be taken out of my cover aren't taken automatically. Like bottom level and addionally the lenght and slope aren't impoted into my view wastewater structure. 

I've seen that the vertical section has calculated slopes and lenght. But where in the database is this saved and why is this not imported into my view "reach"?  I mean so I have to fill it in twice (wastewater structure and reach). 

Do you guys know something about this problem?

![automatisch hohe gefalle](https://cloud.githubusercontent.com/assets/23099048/20801339/cec51a14-b7e8-11e6-8b98-19502dde1358.jpg)

**Comment by Marpingen** [comment]
I actually found a way to import my informations trough the database. But this question still remains. In my point of view that should be filled in automatically.

**Comment by m-kuhn** [comment]
Does it make sense to automatically insert the bottom_level to the reach point levels?
Or would this give an impression that there is data which has not actually been measured?
I assume there are two different attributes because they are not always equal.

Alternatively we could also show the level of the wastewater node (bottom level) next to the reach point level to make it transparent to the user.

CC @sjib @urskaufmann

**Comment by urskaufmann** [comment]
In "normal" case, I do not fill the bottom_level in the wasterwater_node_table. If I have the data, I just work with the reach_point_level.
If I have just a buttom_level, then I use this value also for in- and out-reachpoint_levels.
I use the bottom_level just with special_structures (eg. pumps) where the out-reachpoint_level is higher than the bottom_level.
There should not be an automatic insert of a value into an other field. The user must start such a function knowingly and just for selected covers (bottom_levels) AND for selected reaches.

**Comment by Marpingen** [comment]
thank you. I actually just found out that the slope is calculated and filled in automatically as soon as I've filled in enough informations.
