### ISSUE TITLE
unable to set level of a cover

### ISSUE THREAD

**Issue by kfischerar** [QGEP/QGEP#256]
we installed the latest version qgep from scratch, incuding demodata. now it's not possible to change the level of a cover. can anyone confirm that ?

**Comment by m-kuhn** [comment]
Can you run https://github.com/QGEP/datamodel/blob/45e4734943316231102ff1bdf45b222be3051eb6/view/vw_qgep_wastewater_structure.sql on your database and check if the problem is fixed?

Thanks
