### ISSUE TITLE
Oracle

### ISSUE THREAD

**Issue by kfischerar** [QGEP/QGEP#260]
i have a request to use QGEP with oracle as database.
i think qgis in generell supports oracle spatial so it should be possible. we have a lot of functionality in postgres and we would have to build that in oracle as well, i can't rate that.
question:
is it technically possible to use oracle in stead of postgres ?
if yes:
can anyone make a rough estimate about the cost ?

**Comment by m-kuhn** [comment]
it means porting the datamodel to oracle, including all the views. it also means implementing transactions and server side default values for oracle within qgis.
it's all things which can be done in a couple of weeks. it also means, that all database changes in the future will need to be compatible with multiple databases (e.g. project generator) so the cost will not just be one-time.

**Comment by kfischerar** [comment]
i thougt so ...
postgres is OUR database for development and daily business.
if anyone wants to use oracle its possible. to bring our actual state to oracle costs approximatly CHF 20'000, can anyone confirme that ?

**Comment by m-kuhn** [comment]
Yes, for starters, that would be an approximate amount

**Comment by andreasneumann** [comment]
Personally I think we should concentrate on making QGEP usable (in a productive environment) with PostgreSQL and once that is working fine we can investigate other databases. It would complicate things too much  if we now also introduce Oracle support while the main version for PostgreSQL isn't really fully finished (if it can be finished at all).

**Comment by kfischerar** [comment]
i fully agree. postgres is our dev-environment. all additional expenses would go to the client

**Comment by 3nids** [comment]
closing, this can be re-open in time I think
