### ISSUE TITLE
Reach labeling issue when zooming

### ISSUE THREAD

**Issue by varrieta** [QGEP/QGEP#272]
It happens that the label indicates the wrong direction for certains zoom (see example below)

![capture1](https://cloud.githubusercontent.com/assets/20111558/22143376/1e4e0450-defa-11e6-84b9-facaf5e5c6f4.JPG)
In this example, the reach indicates the right direction.

![capture2](https://cloud.githubusercontent.com/assets/20111558/22143377/1e5374b2-defa-11e6-90f5-75659bef2874.JPG)
Then when zooming it indicates the other

**Comment by m-kuhn** [comment]
If you disable simplification in the layer properties, does that help?

**Comment by varrieta** [comment]
No it doesn't

**Comment by varrieta** [comment]
(the example comes from the same database I gave you, reach ch16yyrfRE001221

**Comment by m-kuhn** [comment]
can you disable "Labels" > "Rendering" > "Feature Options" > "Merge connected lines to avoid duplicate labels", that helped here.

**Comment by m-kuhn** [comment]
Pull request is open to prevent the combination of *line direction symbols* and *line merging*
