### ISSUE TITLE
Adding 3D reaches issue

### ISSUE THREAD

**Issue by varrieta** [QGEP/QGEP#277]
When creating new reaches with QGIS, I get this error:

_Layer vw_qgep_reach: PostGIS error while adding features: ERREUR: Column has Z dimension but geometry does not_ 

Did I miss something to modify in the project .qgs?

**Comment by 3nids** [comment]
can you try with the new project?

**Comment by max-trolliet** [comment]
Did you force the data in 3D? Had the same problem with the change of datamodel but seems to work now that Z=0 (or any default value)

**Comment by 3nids** [comment]
viewing data worked fine, but adding/updating was not possible I suppose.

**Comment by varrieta** [comment]
Thanks Denis, it works!

**Comment by 3nids** [comment]
👌

**Comment by sjib** [comment]
I have a similar problem with the INTERLIS import when adding geometry:

> INSERT INTO qgep.od_wastewater_structure
> (
> obj_id, accessibility, contract_section, detail_geometry_geometry, financing, gross_costs, identifier, inspection_interval, location_name, records, remark, renovation_necessity, replacement_value, rv_base_year, rv_construction_type, status, structure_condition, subsidies, year_of_construction, year_of_replacement, fk_owner, fk_operator, last_modification, fk_dataowner, fk_provider)
> SELECT obj_id, 
> CASE WHEN Zugaenglichkeit = 'ueberdeckt' THEN 3444 ---- 3444  covered
> WHEN Zugaenglichkeit = 'unbekannt' THEN 3447 ---- 3447  unknown
> WHEN Zugaenglichkeit = 'unzugaenglich' THEN 3446 ---- 3446  inaccessible
> WHEN Zugaenglichkeit = 'zugaenglich' THEN 3445 ---- 3445  accessible
> END AS Zugaenglichkeit, zugaenglichkeit, baulos, detailgeometrie, 
> CASE WHEN Finanzierung = 'oeffentlich' THEN 5510 ---- 5510  public
> WHEN Finanzierung = 'privat' THEN 5511 ---- 5511  private
> WHEN Finanzierung = 'unbekannt' THEN 5512 ---- 5512  unknown
> END AS Finanzierung, finanzierung, bruttokosten, bezeichnung, inspektionsintervall, standortname, akten, bemerkung, 
> CASE WHEN Sanierungsbedarf = 'dringend' THEN 5370 ---- 5370  urgent
> WHEN Sanierungsbedarf = 'keiner' THEN 5368 ---- 5368  none
> WHEN Sanierungsbedarf = 'kurzfristig' THEN 2 ---- 2  short_term
> WHEN Sanierungsbedarf = 'langfristig' THEN 4 ---- 4  long_term
> WHEN Sanierungsbedarf = 'mittelfristig' THEN 3 ---- 3  medium_term
> WHEN Sanierungsbedarf = 'unbekannt' THEN 5369 ---- 5369  unknown
> END AS Sanierungsbedarf, sanierungsbedarf, wiederbeschaffungswert, wbw_basisjahr, 
> CASE WHEN WBW_Bauart = 'andere' THEN 4602 ---- 4602  other
> WHEN WBW_Bauart = 'Feld' THEN 4603 ---- 4603  field
> WHEN WBW_Bauart = 'Sanierungsleitung_Bagger' THEN 4606 ---- 4606  renovation_conduction_excavator
> WHEN WBW_Bauart = 'Sanierungsleitung_Grabenfraese' THEN 4605 ---- 4605  renovation_conduction_ditch_cutter
> WHEN WBW_Bauart = 'Strasse' THEN 4604 ---- 4604  road
> WHEN WBW_Bauart = 'unbekannt' THEN 4601 ---- 4601  unknown
> END AS WBW_Bauart, wbw_bauart, 
> CASE WHEN Status = 'ausser_Betrieb' THEN 3633 ---- 3633  inoperative
> WHEN Status = 'in_Betrieb' THEN 8493 ---- 8493  operational
> WHEN Status = 'in_Betrieb.provisorisch' THEN 6530 ---- 6530  operational.tentative
> WHEN Status = 'in_Betrieb.wird_aufgehoben' THEN 6533 ---- 6533  operational.will_be_suspended
> WHEN Status = 'tot.aufgehoben_nicht_verfuellt' THEN 6523 ---- 6523  abanndoned.suspended_not_filled
> WHEN Status = 'tot.aufgehoben_unbekannt' THEN 6524 ---- 6524  abanndoned.suspended_unknown
> WHEN Status = 'tot.verfuellt' THEN 6532 ---- 6532  abanndoned.filled
> WHEN Status = 'unbekannt' THEN 3027 ---- 3027  unknown
> WHEN Status = 'weitere.Berechnungsvariante' THEN 6526 ---- 6526  other.calculation_alternative
> WHEN Status = 'weitere.geplant' THEN 7959 ---- 7959  other.planned
> WHEN Status = 'weitere.Projekt' THEN 6529 ---- 6529  other.project
> END AS Status, status, 
> CASE WHEN BaulicherZustand = 'unbekannt' THEN 3037 ---- 3037  unknown
> WHEN BaulicherZustand = 'Z0' THEN 3363 ---- 3363  Z0
> WHEN BaulicherZustand = 'Z1' THEN 3359 ---- 3359  Z1
> WHEN BaulicherZustand = 'Z2' THEN 3360 ---- 3360  Z2
> WHEN BaulicherZustand = 'Z3' THEN 3361 ---- 3361  Z3
> WHEN BaulicherZustand = 'Z4' THEN 3362 ---- 3362  Z4
> END AS BaulicherZustand, baulicherzustand, subventionen, baujahr, ersatzjahr, sia405_abwasser_2015_2_d_340.objid_lookup('Organisation', eigentuemerref::int),  sia405_abwasser_2015_2_d_340.objid_lookup('Organisation', betreiberref::int),  
> FROM sia405_abwasser_2015_2_d_340.Abwasserbauwerk
>     LEFT JOIN sia405_abwasser_2015_2_d_340.vw_sia405_baseclass_metaattribute ON sia405_abwasser_2015_2_d_340.Abwasserbauwerk.t_id = vw_sia405_baseclass_metaattribute.t_id;
> 
> 

FEHLER:  Column has Z dimension but geometry does not

********** Error **********

FEHLER: Column has Z dimension but geometry does not
SQL state: 22023

Should the above fix fix this also or do I have to change geometry beforehand?

**Comment by 3nids** [comment]
Issue is not related. You should make sure to give a 3D geometry (for instance by using ST_Force3D).

**Comment by sjib** [comment]
Thanks it worked!

Adapting 

...

> SELECT obj_id,
> CASE WHEN Zugaenglichkeit = 'ueberdeckt' THEN 3444 ---- 3444 covered
> WHEN Zugaenglichkeit = 'unbekannt' THEN 3447 ---- 3447 unknown
> WHEN Zugaenglichkeit = 'unzugaenglich' THEN 3446 ---- 3446 inaccessible
> WHEN Zugaenglichkeit = 'zugaenglich' THEN 3445 ---- 3445 accessible
> END AS Zugaenglichkeit, zugaenglichkeit, baulos, **ST_Force3D (detailgeometrie)**,
