### ISSUE TITLE
Problem maintenance/damage

### ISSUE THREAD

**Issue by kfischerar** [QGEP/QGEP#282]
if i open my existing project with the latest qgep_en.qgs i get a list of missing tables/views:
vw_qgep_damage
vw_qgep_maintenance
vl_damage_connection
vl_damage_manhole_manhole_damage_code
vl_damage_manhole_manhole_shaft_area
so i add the three vl-tables and try to execute vw_qgep_maintenance.sql.
i get an error:
FEHLER:  Typ „qgep.maintenance_type“ existiert nicht
LINE 8: ...xamination.obj_id IS NOT NULL THEN 'examination'::qgep.maint...
resp.
FEHLER:  Typ „qgep.damage_type“ existiert nicht
LINE 8: ...  WHEN manhole.obj_id IS NOT NULL THEN 'manhole'::qgep.damag...

may be there is still anything missing ?

**Comment by m-kuhn** [comment]
Ping @3nids

**Comment by 3nids** [comment]
this should be solved now!
