### ISSUE TITLE
Visualization of foreign keys for certain tables

### ISSUE THREAD

**Issue by m-kuhn** [QGEP/QGEP#284]
* reach point -> wastewater node
* catchment area -> wastewater node (including attribute for which foreign key)
* connection object (Anschlussobjekt?) -> wastewater node (Anschlussobjekt needs to be included into the project first)

**Comment by sjib** [comment]
There seem to be a bunch of foreign keys and their relations that are missing in the demo project and empty schema. I need to update the https://github.com/QGEP/datamodel/blob/master/03_qgep_db_dss.sql

e.g. missing
-- 23.2.2017 sb missing in datamodel qgep

ALTER TABLE qgep.od_river_bank ADD COLUMN fk_water_course_segment varchar (16);
ALTER TABLE qgep.od_river_bank ADD CONSTRAINT rel_river_bank_water_course_segment FOREIGN KEY (fk_water_course_segment) REFERENCES qgep.od_water_course_segment(obj_id) ON UPDATE CASCADE ON DELETE cascade;

ALTER TABLE qgep.od_river_bed ADD COLUMN fk_water_course_segment varchar (16);
ALTER TABLE qgep.od_river_bed ADD CONSTRAINT rel_river_bed_water_course_segment FOREIGN KEY (fk_water_course_segment) REFERENCES qgep.od_water_course_segment(obj_id) ON UPDATE CASCADE ON DELETE cascade;

ALTER TABLE qgep.od_water_course_segment ADD COLUMN fk_watercourse varchar (16);
ALTER TABLE qgep.od_water_course_segment ADD CONSTRAINT rel_water_course_segment_watercourse FOREIGN KEY (fk_watercourse) REFERENCES qgep.od_river(obj_id) ON UPDATE CASCADE ON DELETE cascade;

ALTER TABLE qgep.od_water_catchment ADD COLUMN fk_aquifier varchar (16);
ALTER TABLE qgep.od_water_catchment ADD CONSTRAINT rel_water_catchment_aquifier FOREIGN KEY (fk_aquifier) REFERENCES qgep.od_aquifier(obj_id) ON UPDATE CASCADE ON DELETE set null;

ALTER TABLE qgep.od_water_catchment ADD COLUMN fk_chute varchar (16);
ALTER TABLE qgep.od_water_catchment ADD CONSTRAINT rel_water_catchment_chute FOREIGN KEY (fk_chute) REFERENCES qgep.od_surface_water_bodies(obj_id) ON UPDATE CASCADE ON DELETE set null;
...

**Comment by sjib** [comment]
solved with model UpdateDatamodel 20170703
