### ISSUE TITLE
make all varchar length limited fields as unlimited text?

### ISSUE THREAD

**Issue by 3nids** [QGEP/QGEP#289]
It is quite tedious to have close to no flexibility in the DB regarding field length.
I would propose to make them all unlimited text:

* better flexibility
* no disk-space issue on PG
* increasing their length directly is generally not possible as there are some triggers depending on them.

opinions?

**Comment by haubourg** [comment]
Agreed, text is a better and more flexible replacement to varchar in postgres.

**Comment by tudorbarascu** [comment]
+1

**Comment by sjib** [comment]
is this just a different data type or would this change the field length? Identifiers have a limit to 20 characters as you want to have them limited in your map.
INTERLIS has also limits of amounts of TEXT that we cannot change and would be cut off in transfer.

**Comment by sjib** [comment]
Here is a suggestion how to still have a limit on text using DOMAIN: https://www.depesz.com/2010/03/02/charx-vs-varcharx-vs-varchar-vs-text/ 
Any experience with that?

**Comment by 3nids** [comment]
the idea is rather have no limits.
We would live obj_id as is, as there is no interest in increasing size.
Cut off might happen with interlis transfer, but I am not sure we should limit usability base on the limitation of one possible exchange format.

**Comment by sjib** [comment]
Proposal: request an extension of the field length from the SIA

    @3nids prepares a list with fields for extension, @sjib discusses this proposal with SIA/VSA.

**Comment by sjib** [comment]
List of fields:
- [x] [od_file.identifier](https://github.com/QGEP/QGEP/issues/286) - increase length to 80
- [ ] please add

**Comment by ponceta** [comment]
On the client side, I would restrict the char fields to 255 char for "exportable" fields and allow more as exceptions.

**Comment by sjib** [comment]
Remark fields are often "missused" and a lot of that information should go into an existing attribut. Limiting these fields helps to have the data where you really want it (and can then really use it) - and a migration is a good occasion to do so.

**Comment by ponceta** [comment]
@sjib 99% aggrees with you... Will have to translate the existing ones to corresponding fields... 
Regex queries here I come! ;) For the remaining 1% I'll extend the text length.

**Comment by 3nids** [comment]
closing this issue, any change is welcome as a PR 
now that we have PUM integrated, it should be much easier
