### ISSUE TITLE
Digitization of second reach or wastewater structure not possible

### ISSUE THREAD

**Issue by urskaufmann** [QGEP/QGEP#294]
When option "reuse last attributes" is on, then QGIS reuse the last values also for unique fields (obj_id, identifier). Like that you can not save a second record.

"Workaround": do not use the option "reuse last attributes"...

**Comment by haubourg** [comment]
Or it could be handled in the triggers by skipping any value provided from QGIS and letting the sequence do its job. 
The "reuse last value" option is a true time saver, that would be worth the change.

**Comment by m-kuhn** [comment]
I think that's no longer an issue with 3.0 anyway.

**Comment by urskaufmann** [comment]
Very confused that  it is still/again an issue  . I thought I did test it with QGIS 3 or 3.2.
Now I get the errors with QGIS 3.4.x an datamodel 1.1.1 and 1.2.0.

When digitizing the second  reach:
Layer vw_qgep_reach: PostGIS error while adding features: FEHLER: doppelter Schlüsselwert verletzt Unique-Constraint »pkey_qgep_od_reach_point_obj_id« DETAIL: Schlüssel »(obj_id)=(00000000RP000008)« existiert bereits. CONTEXT: SQL-Anweisung »INSERT INTO qgep_od.reach_point( obj_id , elevation_accuracy , identifier , level , outlet_shape , position_of_connection , remark , situation_geometry , last_modification , fk_dataowner , fk_provider , fk_wastewater_networkelement ) VALUES ( COALESCE(NEW.rp_from_obj_id,qgep_sys.generate_oid('qgep_od','reach_point')) -- obj_id , NEW.rp_from_elevation_accuracy -- elevation_accuracy , NEW.rp_from_identifier -- identifier , NEW.rp_from_level -- level , NEW.rp_from_outlet_shape -- outlet_shape , NEW.rp_from_position_of_connection -- position_of_connection , NEW.rp_from_remark -- remark , ST_StartPoint(NEW.progression_geometry) -- situation_geometry , NEW.rp_from_last_modification -- last_modification , NEW.rp_from_fk_dataowner -- fk_dataowner , NEW.rp_from_fk_provider -- fk_provider , NEW.rp_from_fk_wastewater_networkelement -- fk_wastewater_networkelement ) RETURNING obj_id« PL/pgSQL-Funktion qgep_od.vw_qgep_reach_insert() Zeile 10 bei SQL-Anweisung 

And there is also the fk_wastewater_networkelement reused, even though there is snapping to a new node and the script in the fk_wastewater_networkelement-field is not changed!

When digitizing the second wastewater_structure:
Layer vw_qgep_wastewater_structure: PostGIS error while adding features: FEHLER: doppelter Schlüsselwert verletzt Unique-Constraint »pkey_qgep_od_structure_part_obj_id« DETAIL: Schlüssel »(obj_id)=(1)« existiert bereits. CONTEXT: SQL-Anweisung »INSERT INTO qgep_od.structure_part ( obj_id , identifier , remark , renovation_demand , fk_dataowner , fk_provider , last_modification , fk_wastewater_structure ) VALUES ( COALESCE(NEW.obj_id,qgep_sys.generate_oid('qgep_od','cover')) -- obj_id , NEW.identifier , NEW.remark , NEW.renovation_demand , NEW.fk_dataowner , NEW.fk_provider , NEW.last_modification , NEW.fk_wastewater_structure ) RETURNING obj_id« PL/pgSQL-Funktion qgep_od.vw_cover_insert() Zeile 3 bei SQL-Anweisung SQL-Anweisung »INSERT INTO qgep_od.vw_cover( obj_id , brand , cover_shape , diameter , fastening , level , material , positional_accuracy , situation_geometry , sludge_bucket , venting , identifier , remark , renovation_demand , last_modification , fk_dataowner , fk_provider , fk_wastewater_structure ) VALUES ( NEW.co_obj_id , NEW.co_brand , NEW.co_shape , NEW.co_diameter , NEW.co_fastening , NEW.co_level , NEW.co_material , NEW.co_positional_accuracy , ST_GeometryN( NEW.situation_geometry, 1 ) , NEW.co_sludge_bucket , NEW.co_venting , COALESCE(NULLIF(NEW.co_identifier,''), NEW.identifier) , NEW.co_remark , NEW.co_renovation_demand , NOW() , NEW.fk_dataowner , NEW.fk_provider , NEW.obj_id )« PL/pgSQL-Funktion qgep_od.vw_qgep_wastewater_structure_insert() Zeile 186 bei SQL-Anweisung

**Comment by urskaufmann** [comment]
Seems to be a QGIS problem : QGIS Feature Request #21576

**Comment by sjib** [comment]
@urskaufmann is it this feature request https://github.com/qgis/QGIS/issues/21576 ? Nothing has been going on there. Is this still an issue? Else please close.

**Comment by urskaufmann** [comment]
There is still a problem with identifier and obj_id, when checking "reuse last attributes" in the QGIS options, because QGIS expandes the last obj_id with "_1" to great the unique value out of the last obj_id.
It works when using the "reuse last value" option with the fields (in Layer properties - attribut form), where this behaviour is really wanted and not with the general QGIS option.
And in the obj_id-field should be the constraints (Restriktionen) as in the picture:
![image](https://user-images.githubusercontent.com/1257403/201036506-9db8be28-c268-4273-912f-e73c568c8eb6.png)
