### ISSUE TITLE
OIDPREFIX  ?

### ISSUE THREAD

**Issue by ponceta** [QGEP/QGEP#296]
Hi,

@m-kuhn where do I find the OID prefix for Pully, Belmont or SIGIP?

**Comment by max-trolliet** [comment]
I think that Stefan is in charge of this. 

I could also use the one for Prilly. Does it have to be put in the datamodel? Or just added for each of us?

**Comment by sjib** [comment]
You have to add your OID data in this table

https://github.com/QGEP/datamodel/blob/master/02_oid_generation.sql

> -- sample entry for the City of Uster - you need to adapt this entry later for your own organization
> INSERT INTO qgep.is_oid_prefixes (prefix,organization,active) VALUES ('00000000','Invalid',TRUE);
> INSERT INTO qgep.is_oid_prefixes (prefix,organization,active) VALUES ('ch11h8mw','Stadt Uster',FALSE);
> INSERT INTO qgep.is_oid_prefixes (prefix,organization,active) VALUES ('ch15z36d','SIGE',FALSE);
> INSERT INTO qgep.is_oid_prefixes (prefix,organization,active) VALUES ('ch13p7mz','Arbon',FALSE);

and set the OID you want to use in your project to TRUE.

**Comment by sjib** [comment]
TO DO: Add this info to documentation

**Comment by ponceta** [comment]
https://www.interlis.ch/fr/dienste/oid-bestellen NEW url for ordering OID

**Comment by sjib** [comment]
see also https://teksi.github.io/wastewater/installation-guide/workstation.html#if-you-are-a-data-owner-add-your-own-oid-to-the-project
