### ISSUE TITLE
Missing views for subclasses of individual_surface (Einzelflächen)

### ISSUE THREAD

**Issue by urskaufmann** [QGEP/QGEP#299]

**Comment by urskaufmann** [comment]
Under QGEP/datamodel/views are a lot of SQL-Files for views. I think that most of them to not support  deleting class AND superclass (e.g. vw_access_aid, vw_benching). After deleting the access_aid in the report of vw_qgep_wastewater_structure, there is still the record of the structure_part in the database

**Comment by sjib** [comment]
CREATE OR REPLACE RULE vw_access_aid_ON_DELETE AS ON DELETE TO qgep.vw_access_aid DO INSTEAD (
  DELETE FROM qgep.od_access_aid WHERE obj_id = OLD.obj_id;
DELETE FROM qgep.od_structure_part WHERE obj_id = OLD.obj_id;

How to improve this VIEW so it works?

**Comment by sjib** [comment]
@urskaufmann 
Is this still an issue?

https://github.com/QGEP/datamodel/blob/master/view/additional_views/vw_fountain.sql looks quite good to me. Can you check?

**Comment by urskaufmann** [comment]
vw_individual_surface is tested and now in datamodell 1.4.0.  Other views for connection_objects (fountain, building) not tested, but looks good.
