### ISSUE TITLE
Adding postgis-layer to qgep-project

### ISSUE THREAD

**Issue by urskaufmann** [QGEP/QGEP#300]
Can not add layers with the yellow sign (see Picture), e.g. vw_overflow_pump
![unbenannt](https://cloud.githubusercontent.com/assets/1257403/24602559/9b5ed040-185d-11e7-9ede-ead7f2108e92.PNG)

**Comment by kfischerar** [comment]
may be you have to make some more selections in the columns:
Spatial Type, SRID, Feature ID

2017-04-03 11:09 GMT+02:00 urskaufmann <notifications@github.com>:

**Comment by urskaufmann** [comment]
I had to choose the field obj_id as "Objektkennung". Then it works.

Is it not possible to define the views with the field obj_id as "Objektkennung".

**Comment by m-kuhn** [comment]
Views don't have a primary key, only tables have.
What we could probably do is add some heuristics to QGIS that checks for often-used field names for the primary key there (but since this is not really reliable, so I wonder if it will be accepted) or use some other helpers like a special tag in the comment `COMMENT ON COLUMN qgep.vw_xyz.obj_id "[primary_key] This is the primary key of this table. Don't you dare to mess around with it!";`.

**Comment by sjib** [comment]
OBJ_ID already has this comment:
`COMMENT` ON COLUMN qgep.re_maintenance_event_wastewater_structure.obj_id IS 'INTERLIS STANDARD OID (with Postfix/Präfix) or UUOID, see `www.interlis.ch';`
I can add [primary_key] to that.

**Comment by sjib** [comment]
Added comment with last data model update.
@m-kuhn Any other input from my side needed?

**Comment by m-kuhn** [comment]
Do we want to invest a day of work to make QGIS handle this kind of comment annotations?

**Comment by sjib** [comment]
What would be the benefit - can you describe that first - besides the use case of @urskaufmann

**Comment by m-kuhn** [comment]
Properly commented views could be added without manually selecting the primary key. Just like regular tables.

**Comment by urskaufmann** [comment]
I think it's important, that it is documented, how to add the themes to the project. Then it's P3, not P1...

**Comment by sjib** [comment]
Should we add this here in the documentation: https://qgep.github.io/docs/user-guide/layerexplanations/index.html
2.1.2 Adding a layer to QGEP (new chapter)

**Comment by sjib** [comment]
Doku added.
