### ISSUE TITLE
Manhole _orientation purpose

### ISSUE THREAD

**Issue by mdouchin** [QGEP/QGEP#312]
There is a column _orientation in the manhole table, but it is not yet used in the QGIS project in expressions to rotate the cover.

The use of the underscore tells me this field should be calculated, but I found no triggers nor function to process it.

Is this field a first step to further improvement ? I could improve the project and propose a PR if the purpose of this field is to rotate the symbol.

**Comment by andreasneumann** [comment]
Hi @mdochin 

Fields starting with an underscore are not part of the official model.

When I was still active in the QGEP project we had the requirement in Uster to properly rotate some manholes (typically with the bisector angle of incoming/outgoing reaches - when there are only 1 incoming/outgoing). I remember that this is non-standard for now, but may, at a later stages become part of the standard. @sjib can tell you more about it.

I believe for most cases the rotation could be auto-calculated with this bisector angle.

I am also in Essen and we can discuss things a bit further - although I am not part of the QGEP project anymore - officially.

**Comment by mdouchin** [comment]
Hi @andreasneumann . Thanks for your reply. Unfortunately I am not in Essen :-(
I agree with you for the possibiliy to calculate this angle automatically, only when there is only 2 reaches concerned.

In my case, I have data coming from Autocad, so there is an angle in radians I could use to fill in this `_orientation` field.

Thanks for this clarification !

**Comment by sjib** [comment]
No big comment from my side. Right now I have no other request for VSA-DSS or SIA405 to add this.

Is radians a good unit for all systems? Then we should add a comment to _orientation to define this.

@mdouchin: Cann you add a screenshot to document your case?
