### ISSUE TITLE
Quick and dirty scripts to translate the QGIS project file

### ISSUE THREAD

**Issue by mdouchin** [QGEP/QGEP#313]
I am using QGEP for a french public entity, and I have made a python script that can be run to translate the project. It is not the most elegant way, nor is complete, but it helps.

To use it:
* Copy to **qgep_en.qgs** project to e.g. **qgep_fr.qgs**. Please do not use it directly withou any backup :)
* Use the following sed commands ( shell) to replace some parameters. I have not yet integrated theses changes in the python script. Or use a text viewer and simply search and replace *Value="value_en"* by *Value="value_fr"*

```bash
# value relation
sed -i 's/Value="value_en"/Value="value_fr"/g' qgep_fr.qgs
# labels
sed -i 's/;material_abbr_en/;material_abbr_fr/g' qgep_fr.qgs
```

* Load the tables **qgep.is_dictionary_od_field** and **qgep.is_dictionary_od_table** in the QGIS project.
* Run the script in Processing (add it with the toolbox tools) and choose the right layer in the 2 comboboxes.
* You can also check some checkboxes to reset the layers title back to None, the layer names back to the table names, and the alias to None, if you want to revert back the changes. But be aware this wont totally revert the project back to the previous state (use your backup instead)

Here is the script : https://gist.github.com/mdouchin/b3d0105ec99f51a4a02fc1977f60d28a

I would also like to add an option to set the projection of all the layers to the local projection instead of the swiss one, and then update the layers extents and project extent. At present, I use these sed commands instead

```bash
# projection
sed -r 's#\+proj=somerc \+lat_0=46\.95240555555556 \+lon_0=7\.439583333333333 \+k_0=1 \+x_0=600000 \+y_0=200000 \+ellps=bessel \+towgs84=674\.4,15\.1,405\.3,0,0,0,0 \+units=m \+no_defs#\+proj=lcc +lat_1=48.25 +lat_2=49.75 +lat_0=49 +lon_0=3 +x_0=1700000 +y_0=8200000 +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +units=m +no_defs#g' -i  qgep_fr.qgs
sed -r 's#srsid>1919<#srsid>1768<#g' -i qgep_fr.qgs
sed -r 's#srid>21781<#srid>3949<#g' -i  qgep_fr.qgs
sed -r 's#authid>EPSG:21781<#authid>EPSG:3949<#g' -i  qgep_fr.qgs
sed -r 's#CH1903 / LV03#RGF93 / CC49#g' -i  qgep_fr.qgs
sed -r 's#projectionacronym>somerc<#projectionacronym>lcc<#g' -i  qgep_fr.qgs
sed -r 's#>bessel<#>GRS80<#g' -i  qgep_fr.qgs
sed 's#EPSG\:21781#EPSG:3949#g' -i qgep_fr.qgs
sed 's#srid=21781#srid=3949#g' -i qgep_fr.qgs
```

This is obviously quick and dirty ;) , and completely dedicated to my use case (here I replaced EPSG:21781 by EPSG:3949 )

**Comment by 3nids** [comment]
I will try to give a more complete description but I have something a bit more advanced that deal with translation and projection issues 
See https://github.com/qwat/QGEP-customizer
Will discuss to move it to Qgep repo.

**Comment by mdouchin** [comment]
Nice !
Thanks for sharing this. I would give it a try, and propose some improvements via PR if I have further needs

**Comment by mdouchin** [comment]
A quick question on this: why are many translated string in french UPPERCASE ? Is it a requirement for a dedicated user, or is it from historical sotftware ? I could help correct this if needed

**Comment by kfischerar** [comment]
i have a general question: does your (linux-?)python extension allways work
in win7 as well ?

2017-04-27 17:45 GMT+02:00 Denis Rouzaud <notifications@github.com>:

**Comment by 3nids** [comment]
@mdouchin I can't recall which part is upper case. Part of the translation if "official" from the VSA, part of it is done in the customizer.

@kfischerar the customizer runs in two parts:
 1. the bash script reads the config and update part of the python code
 2. qgis is launched (by the bash) with the python code to run

Part 2 would work as is on Windows. For part 1, it *might* work in Osgeo4W shell. Other possibility would be to make a QGIS plugin that does this job. It shouldn't be too complicate to achieve.

**Comment by haubourg** [comment]
@mdouchin we now have a native translation of the project file . See #408 I suppose this issue can be closed.

**Comment by sjib** [comment]
@mdouchin Is this still an issue? Else please close - thanks.

**Comment by mdouchin** [comment]
Nope, we can indeed close it. Thanks
