### ISSUE TITLE
Error in vw_qgep_wastewater_structure_update()

### ISSUE THREAD

**Issue by varrieta** [QGEP/QGEP#314]
In the trigger below, vw_qgep_wastewater_structure_update(), shouldn't it be  _remark = NEW.wn_remark_ instead of  _remark =  NEW.remark_ ? 

> UPDATE qgep.vw_wastewater_node NO1
>     SET
>     backflow_level = NEW.backflow_level
>     , bottom_level = NEW.bottom_level
>     -- , situation_geometry = NEW.situation_geometry -- Geometry is handled separately below
>     , identifier = NEW.identifier
>     , **remark = NEW.remark**
>     -- , last_modification -- Handled by triggers
>     , fk_dataowner = NEW.fk_dataowner
>     , fk_provider = NEW.fk_provider
>     -- Only update if there is a single wastewater node on this structure
>     WHERE fk_wastewater_structure = NEW.obj_id AND
>     (
>       SELECT COUNT(*)
>       FROM qgep.vw_wastewater_node NO2
>       WHERE NO2.fk_wastewater_structure = NO1.fk_wastewater_structure
> ) = 1;

**Comment by m-kuhn** [comment]
Sounds about right, would you like to create a pull request? Or shall I adjust it?

**Comment by varrieta** [comment]
Ok, just commited a pull request
