### ISSUE TITLE
Length effective VS slope_per_mill calculation

### ISSUE THREAD

**Issue by mdouchin** [QGEP/QGEP#315]
I need some precision about the use of length and slope for **vw_qgep_reach**
At present, the slope is calculated via the view (see references of SQL definition of columns and views at the bottom of this text) from the length_effective and the altitude of start and end reach points.

It means:
* the real effective length of the reach must be known (because it cannot be determined via projected distance calculation), probably from the historical data ?
* the length_effective is not recalculated when the user modifies the geometry via QGIS editing tools.

I was wondering if we should not work the other way, by calculating dynamically the length_effective when rp levels are not null with the data from
* rp_from.level
* rp_to.level
* ST_Length( re.progression_geometry )

![length_profile](https://cloud.githubusercontent.com/assets/3492210/25485910/d68ac27c-2b5f-11e7-8b12-555751e2dfb0.jpg)

This would provide direct feedback when editing the reach layer.
I understand we could need to keep the length_effective if this comes from a datasource, but I would do it in another old_length_effective or something

Here are the SQL commands
```sql
-- od_channel
COMMENT ON COLUMN od_channel.pipe_length IS 'yyy_Baulänge der Einzelrohre oder Fugenabstände bei Ortsbetonkanälen / Baulänge der Einzelrohre oder Fugenabstände bei Ortsbetonkanälen / Longueur de chaque tuyau ou distance des joints pour les canalisations en béton coulé sur place';

-- od_reach
COMMENT ON COLUMN od_reach.length_effective IS 'yyy_Tatsächliche schräge Länge (d.h. nicht in horizontale Ebene projiziert)  inklusive Kanalkrümmungen / Tatsächliche schräge Länge (d.h. nicht in horizontale Ebene projiziert)  inklusive Kanalkrümmungen / Longueur effective (non projetée) incluant les parties incurvées';

-- vw_qgep_reach definition
-- [...]
    re.length_effective,
        CASE
            WHEN ((rp_from.level > (0)::numeric) AND (rp_to.level > (0)::numeric)) THEN round((((rp_from.level - rp_to.level) / re.length_effective) * (1000)::numeric), 1)
            ELSE NULL::numeric
        END AS slope_per_mill,
-- [...]
```

And the expression used in QGIS project to label **vw_qgep_reach**

```sql
CONCAT(
COALESCE("material_abbr_en"|| ' ',''),
COALESCE("width"||' ', ''),
COALESCE("length_effective"|| 'm ', ''),
COALESCE("slope_per_mill"||'‰','' )
)```

**Comment by m-kuhn** [comment]
I'm not sure I completely understand the question (and to which point it's a question and where the proposal starts).

From my understanding:

* The purpose of `length_effective` is to add the possibility to set real (measured) values, when available.
* The default for this field is the value measured from the projected data (for the most common case when no better data is available). This default value could be improved by taking from/to levels into account.

Does this already answer your question or is there more to it?

**Comment by mdouchin** [comment]
The question was on the purpose of `length_effective` -> you answered it, by saying it is is made for storing real measurements.
When you say the default is taken from projected data, you mean when you import data from another datasource ? I cannot see in any SQL files how this "default" value is set ( I looked in field definition, comments, triggers, etc.).

The proposal was to have a way to set this `length_profile` whenever the `reach.progression_geometry` is updated. My **new** proposal is to add a new field `calculated_length_profile` which would be automatically calculated ( via triggers or inside the view). This calculated field would be used instead of the other one if there is no measured value ( via a CASE WHEN in QGIS label definition )

The main goal here is to always have this length profile data, whenever we add or modify any reaches (without a real world measurement in the field)
I can propose a PR for this in datamodel if you agree

**Comment by m-kuhn** [comment]
As in this?

    COALESCE( length_effective, ST_Length(progression_geometry) ) As length -- read-only length

I am also slightly leaning towards leaving `length_effective` empty if we don't have the data instead of filling it with calculated data (which is no longer valid if the reach geometry changes).

The current proposal is from @urskaufmann , so I would like to get his thoughts on this also.

**Comment by mdouchin** [comment]
Ok, the `length` you mention is is the view `vw_network_segment` and not in the view vw_qgep_reach as I expected.
But in the QGIS project, the label of vw_qgep_reach is defined with `length_effective` not with the reference of `vw_network_segment.length_calc`

I would rather calculate the `length_calc` in `vw_qgep_reach` to be used in label, but by taking into account the reach points level as described in my funny figure above.

+1 to leave `length_effective` empty if no data is provided from source data or field.

**Comment by m-kuhn** [comment]
Yes, that would need be a new field in `vw_qgep_reach` that doesn't exist yet, the one in `vw_network_segment` is unrelated.

**Comment by mdouchin** [comment]
Ok, I will propose a PR for this new field

**Comment by urskaufmann** [comment]
The offical definition is: Laenge_effektiv: Tatsächliche schräge Länge (d.h. nicht in horizontale Ebene projiziert) inklusive Kanalkrümmungen
The problem of this definition is, that you need 3D coordinates of every vertex of the reach to calculate this length. If you have only one vertex with just 2D, you have this length not.
The difference between diagonal length and horizontal length is for 99% to 99.9% of the reaches in the measuring accuracy (except in Wengen and Mürren...). 
In GEPView, I calculate length_effective from the 2D-coordinates/the shape of the reach. And I recalculate it automaticly, if the user changes the shape, so the slope can always be calculated with this field and if I summarize this field over a selection, I get the value a expected.

One idea of this field in earlier days was, that you can edit this value, if you have a measured value and just digitized a generalized shape with no vertex between the manholes. I think, if you work with GIS-Tools, that can no more be a reason to not recalculate the length from the shape in the database.

For me, in QGEP the length_effective must be recalculated from 2D-coordinates after every change of geometry.

**Comment by m-kuhn** [comment]
> For me, in QGEP the length_effective must be recalculated from 2D-coordinates after every change of geometry.

In this case, will the custom values in Wengen and Mürren be lost after a change in geometry?

**Comment by urskaufmann** [comment]
I have no custom values in Mürren, Wengen. It does not work, if some of the reaches have custom values and others have recalculated values. You can not calculate the slope, you can not Transfer this data to hydraulic programs etc.

**Comment by m-kuhn** [comment]
The proposal above would work with custom values:

* The field `length_effective` is empty if no custom value is known
* The field `length` is calculated. It corresponds to `length_effective` if present or the geometry length if not.

You can then use the second one (which is never empty) for slope calc, transfer to hydraulic programs etc.

**Comment by urskaufmann** [comment]
This works within QGEP. Length should be always recalculated, if the geometry is changed.

If you export data with INTERLIS, then length_effective will be used. There should be once a function to copy length_effective from length for selected reaches.

**Comment by m-kuhn** [comment]
I still have troubles to completely understand.

* The requirement for the field `length_effective` was created for the need to (sometimes) specify manual values.
* Your proposal is to always set the field `length_effective` from the geometry if I understand correctly.

To me this sounds like it is defeating the original purpose and leaving us with a field that contains redundant data that is very easy to recalculate at any time.

Is this correct so far?

If yes, I think we should decide

 * if the need for manually specified values is no longer there, I would rather try to get it out of the data model (and leave it to the database designer if recalculation is cheaper than caching)
 * if the need for manually specified values is still there, let's find a way (like my proposal from above. A field `length_measured` which is writable by the user and can be left empty. A field `length_effective` which is read-only/calculated and defined by `COALESCE(length_measured, ST_Length(progression_geometry)`. When exported to interlis or hydraulic software, `length_effective` can be used).
 * fill the field with the length of the line just because the model requires us to do so.

If no, please help me understand :)

**Comment by m-kuhn** [comment]
# Updated proposal

* The field `length_effective` is calculated from `rp_from.level`, `rp_to.level` and `ST_Length(progression_geometry)` and is `NULL` for cases where one of these variables is not available.
  * It will be made read-only in QGIS.
  * A trigger will update the field.
  * If possible on the view, a comment should be added about the rules that are applied for this.
* A separate (derived, readonly) field `_length_horizontal` is available in the view `vw_qgep_reach` this is never empty (`COALESCE(ST_Length(progression_geometry), 0)`).

# Reasoning

* The need for manually entered values is no longer a requirement with modern GIS software. Still this field is a requirement from the data model and shall be filled whenever possible.
* There is a need for a user to have a field to calculate and filter on (e.g. find short reaches that possibly are corrupted data/leftovers), hence the second field that is always present.

**Comment by sjib** [comment]
Proposal 2: Gelbdruck to skip attribute length_effective in future.

**Comment by m-kuhn** [comment]
## Roadmap

* `length_effective` is read-only and calculated for now (@m-kuhn)
* Gelbdruck to remove `length_effective` from the Interlis model (@sjib)

**Comment by sjib** [comment]
Added request as Gelbdruck 419: https://www.vsa.ch/fachbereiche-cc/siedlungsentwaesserung/vsa-dss/gelbdrucke/

**Comment by m-kuhn** [comment]
Thanks for all the Gelbdrucke @sjib

**Comment by varrieta** [comment]
I don't remember if I was supposed to but I can modify the trigger!

@m-kuhn Should I modify the update and insert trigger of the vw_qgep_wastewater_structure or create a function as for the depth?

**Comment by m-kuhn** [comment]
https://stackoverflow.com/a/34255739/2319028

**Comment by varrieta** [comment]
#55
