### ISSUE TITLE
function_hierarchic - Purpose of primary and secondary classification ?

### ISSUE THREAD

**Issue by mdouchin** [QGEP/QGEP#316]
The **function_hierarchic** field has the following items

```csv
"value_name"

"pwwf.collector_sewer"
"pwwf.main_drain"
"pwwf.main_drain_regional"
"pwwf.other"
"pwwf.renovation_conduction"
"pwwf.residential_drainage"
"pwwf.road_drainage"
"pwwf.unknown"
"pwwf.water_bodies"

"swwf.other"
"swwf.renovation_conduction"
"swwf.residential_drainage"
"swwf.road_drainage"
"swwf.unknown"
```

I cannot find in SQL comments or in dictionary table the purpose of such classification ? What determines which reaches must be primary, and which ones must be secondary ? Is it related to swiss law, or is this distinction needed for QGEP features ?

I would think the reaches of a group of cities with is own water treatment facility would be considered as secondary, keeping primary only for bigger networks ?

**Comment by urskaufmann** [comment]
The Definition in "Wegleitung GEP-Daten (VSA)" is:
Primäre Abwasseranlagen (PAA)
Die PAA umfassen alle Leitungen eines Kanalnetzes, für die eine
**hydraulische Berechnung** durchgeführt wird, und die auf ihnen
liegenden Knoten, Überläufe und Förderaggregate. Alle Leitungen,
Knoten, Überläufe und Förderaggregate in Fliessrichtung unterhalb
einer PAA sind ebenfalls PAA. Ebenfalls zu den PAA zählen
gewässerrelevante Einleitstellen, auch wenn die Zuleitungen SAA
sind.
Sekundäre Abwasseranlagen (SAA)
Die SAA bestehen aus allen Leitungen, Knoten, Überläufen und
Förderaggregaten, die nicht PAA sind.

**Comment by mdouchin** [comment]
Thank @urskaufmann for your help. Unfortunately, my german from school is a bit rusted. 
I understood that the primary network is defined as the one on which hydraulic calculations would be made ? What are these calculations ? How is it used in QGIS Qgep tool ?

**Comment by andreasneumann** [comment]
@mdouchin - a general rule is that waste-water pipes that are below a street or public square and that collect waste-water from private-parcels are primary (PAA) while pipes on private parcels leading from a building towards the street are secondary (SAA). Everything downstream from a PAA can't be SAA anymore. In addition, pipes that lead into creeks/rivers are considered PAA. SAA pipes usually don't have elevations on nodes. But of course there can be exceptions.

**Comment by andreasneumann** [comment]
Secondary pipes are typically hydraulically not very relevant.

**Comment by urskaufmann** [comment]
You can not make hydraulic calculations in QGEP. You will have to export the PAA(-wastewater-structures) to special programs as Mike Urban for this calculations. But it is very important to fix early enough the boundary between PAA and SAA, because you should connect catchments only to PAA.

**Comment by sjib** [comment]
More details to PAA and SAA definition:

- https://www.vsa.ch/nc/glossar/term/Primaere_Abwasseranlagen_%28PAA%29/

 -> there is also French doku available.

- https://www.vsa.ch/nc/glossar/term/SAA/
