### ISSUE TITLE
Prefixes in vw_qgep_* views

### ISSUE THREAD

**Issue by m-kuhn** [QGEP/QGEP#318]
# Proposal

Every column in a `vw_qgep_*` view should be prefixed with the source table.

E.g. `vw_qgep_wastewater_structure`:

 * `brand` > `co_brand`
 * `cover_shape` > `co.cover_shape`
 * ...

# Options

## Superclass

It's still an open question if the superclass fields should also be prefixed. On a view that already has the name `wastewater_structure` in the name, a user will implicitly assume this as the source table for an unprefixed field.

## Merged fields

Some fields are merged like

    COALESCE( ss.upper_elevation, dp.upper_elevation, ii.upper_elevation ) AS upper_elevation

Should they be

 * Prefixed with the parent `ws_uppwer_evelevation`
 * Be multiplicated `ss_uper_evelevation`, `dp_upper_elevation`, `ii_upper_elevation` (caveat, we already have many, many, many fields in the table #295 )
 * Be prefixed with all of them `ss_dp_ii_upper_elevation`
 * Better ideas?

## Questions

Is this a problem for existing code?

In particular for migration tools (@varietta, @3nids , @ponceta )?

**Comment by varrieta** [comment]
An other possibility could be to use the parent prefix and add an other prefix to specifiy that it is a merged attribute, for example: `ws_mg_upper_elevation`

Fo me, no particular problem for the migration tools, I'll just have to update the name of the attributes in the SQLs.

**Comment by m-kuhn** [comment]
> An other possibility could be to use the parent prefix and add an other prefix to specifiy that it is a merged attribute, for example: ws_mg_upper_elevation

Yes, that's a good idea. What I'm a bit afraid of is that the names get too long when you have to type them for a query and to find something that is intuitive to use and understand.

PS: my personal favorite is to drop the prefix for the main table and subclasses wherever possible

Compare

* Give me all records from `vw_qgep_wastewater_structure` where `"year_of_construction" < 1990`
* Give me all records from `vw_qgep_wastewater_structure` where `"ws_year_of_construction" < 1990`

I think both are quite easy to understand and the first one is shorter.

Sorry, @varrieta ;)

**Comment by urskaufmann** [comment]
@m-kuhn 
For the view vw_qgep_wastewater_structure it is shorter and intuitive. 
If you lock at the other important view (vw_qgep_reach) there is the question, what is the main table (reach as in the view-name) and then you will have the same 31 fields of the class wastewater-structure as in the other view, but with prefix.
In vw_qgep_reach it is not so intuitive. And if it is not in every view the same rule, it is also not intuitive...

**Comment by m-kuhn** [comment]
I think for `vw_qgep_reach` the main class should be reach (and what is inherited from network element) and the others should be prefixed with a wastewater structure (`ws`) prefix. Or even with a `ch`annel prefix (completely ignoring that in theory a manhole could be linked, I guess that's ok, correct me if not).

It should be intuitive enough, don't you think?

There are other alternatives:

* Remove prefixes for classes that are on the 1-side of a relation. (i.e. there is one wastewater_structure per reach, while the manhole and node of a structure are more of a small hack to facilitate the initial digitalization)
* The alternative would be to completely prefix any column everywhere in any table (also in `od_`tables) - which would be coherent but I'm not sure it's worth it.

**Comment by m-kuhn** [comment]
Conclusion

Prefixes for all the columns except for the main one.

Wastewater structure:

 * vw_qgep_wastewater_structure.mh_function
 * vw_qgep_wastewater_structure.co_level
 * vw_qgep_wastewater_structure.gross_costs

**Comment by ponceta** [comment]
After renaming, it is possible that some of the field translations will fall on qgs project. But since these names will be more explicit, it won't be a worry.

:+1:
