### ISSUE TITLE
Manhole - Photos needed to understand functions and types

### ISSUE THREAD

**Issue by mdouchin** [QGEP/QGEP#319]
Hi all,

I am working with QGEP for a french group of cities, and sometimes the highly skilled users cannot understand some concept or vocabulary, because they cannot speak english nor german, and because they do not understand well some "fr_CH" french words. They make sense, but do not correspond each time to the local vocabulary.

This leads to few guesses to determine how to categorize some objects, such as manhole.

For example, this is a picture of a very common structure called "Avaloir" in France, where the cover is on the sidewalk and a grid is on the road.

![avaloir_bis](https://cloud.githubusercontent.com/assets/3492210/25956182/56270a34-366b-11e7-8edf-b71083bc4ee7.jpg)

but I cannot determine if it is

* a manhole with function "rain_water_manhole" (value id = 3267)
* a manhole with function "manhole" ,(value id = 204) and "type" =  "intake_from_side" , id 2740
* something else ?

I would improve then the documentation with a table of manhole functions and types, add this picture, and let anyone improve it with more pictures

**Comment by andreasneumann** [comment]
@sjib - does VSA have material with photos explaining different waste-water structures?

**Comment by sjib** [comment]
Some issues have already been discussed in the official VSA-DSS discussion forum (in German): https://www.vsa.ch/nc/interaktiv/forum/ansicht/single_conf/kategorie/3/konfig/2/
This may give you some hints. 
A documentation as proposed would be helpful for everyone - may be you can start in French and we can translate it als in German and French.
If we place it at a location where we could both link from the QGEP documentation but also from the forum (more model oriented and not product oriented) this would give the widest benefit. Is there an easy to use plattform that allows easy translation and easy integration of pictures?

**Comment by sjib** [comment]
Specific issues in the forum: 
[Spezialbauwerk mit Oberflächenzulauf](https://www.vsa.ch/nc/interaktiv/forum/ansicht/single_thread/kategorie/3/konfig/2/thread/264/)
Another source is the VSA Glossary:
[Einlaufschacht](https://www.vsa.ch/nc/glossar/term/Einlaufschacht/) / [Chambre avec grille d'entrée](chambre_avec_grille_d_entree (M))
etc.

So the foto from above is not enough - you would need to know what is below (profile / layout)

**Comment by sjib** [comment]
The image at the top is **not** a rain_water_manhole - this is at the bottom of the pipe that is coming down from the roof of the house (Chambre se trouvant entre l'évacuation des eaux des bien-fonds et du réseau des canalisations, à l'arrivée d'un tuyau de descente. Souvent de taille inférieure que des chambres avec grille d'entrée)

**Comment by m-kuhn** [comment]
> If we place it at a location where we could both link from the QGEP documentation but also from the forum (more model oriented and not product oriented) this would give the widest benefit. Is there an easy to use plattform that allows easy translation and easy integration of pictures?

This is a good idea.

The first idea that comes to my mind is to do it similar to the QGEP documentation.
A test could be done to use githubs integrated markdown editor which allows easier integration of pictures than rst. The main caveat is if/how translation of markdown works (on transifex).

**Comment by mdouchin** [comment]
Thanks for your answers. 

I like the idea of storing the images in a dedicated github repository accessible for everyone. But I think it would be time consuming to create entries for all objects needing a description. I think we should instead use the content of the table **is_dictionary_od_values** which has already translated labels and descriptions of objects.

We could add some fields in the table, or via a vector join, to store the photo filename.

We could then open the table **is_dictionary_od_values** in QGIS, configure the edit type for the illustration field with **Photo** , and then use QGIS attribute table in form view to see each feature field name, abbreviation in many languages, and also see the picture

**Comment by mdouchin** [comment]
Some test with Github CSV support : https://gist.github.com/mdouchin/c1b0f5777dfad903154b4f6bbdefae8c
We could COPY FROM this kind of CSV instead of using INSERTS when populating an empty QGEP database. This would let users see this data.

**Comment by sjib** [comment]
Good idea, we then could define a folder, where we have images with the value ID e.g. 
cover.sludge_bucket = existing
105 	15 	278 	422 	cover 	sludge_bucket 	existent 	existent
would have be 422.png and if we have more than one 422_1.png (is there an easy code to look up all the image with this name pattern 422*.png/jpg/gif ?

**Comment by sjib** [comment]
For the attribute definitions we could use the VSA Glossary and write code:

IF isexisting (https://www.vsa.ch/nc/glossar/term/**Attributname**) then display link, else no link
e.g. https://www.vsa.ch/nc/glossar/term/Haltung/ or https://www.vsa.ch/nc/glossar/term/troncon/

**Comment by sjib** [comment]
For the VSA discussion forum I could find out whether we could add tags to each discussion and then could link them.

**Comment by sjib** [comment]
New link for VSA Glossary: https://vsa.ch/glossar/
please reopen if still an issue.
