### ISSUE TITLE
Interlis import

### ISSUE THREAD

**Issue by andreasneumann** [QGEP/QGEP#32]
Currently we can import Interlis 1 with ogr2ogr into Postgis.

We need to improve the importer for better usability and more options.

**Comment by m-kuhn** [comment]
Still waiting for Pirmin

**Comment by sjib** [comment]
KF contacts Primin again. Please describe current status in detail.

**Comment by sjib** [comment]
Alternative tools: [ili2pg from Eisenhut] (http://www.eisenhutinformatik.ch/interlis/ili2pg/)

**Comment by m-kuhn** [comment]
@kfischerar import done by end of 2015

**Comment by sjib** [comment]
Pirmin has updated his plugin: http://blog.sourcepole.ch/2016/03/22/verarbeitung-von-interlis-daten-mit-qgis/

**Comment by sjib** [comment]
Sucessful INTERLIS Import and Export with VSA-DSS 2015 and 2008
Documentation see https://qgep.github.io/docs/admin-guide/data-import/interlisimport.html
and
https://qgep.github.io/docs/admin-guide/data-export/interlisexport.html

**Comment by sjib** [comment]
- Add scripts to new folder migration
- Document if LV95 instead of LV03
