### ISSUE TITLE
Question : where to store bottom wastewater structure material

### ISSUE THREAD

**Issue by ponceta** [QGEP/QGEP#323]
In 10% of wastewater structures, the bottom material is different from the structure material. Is there a way to store it in QGEP?

**Comment by sjib** [comment]
No, not yet – you have to use the comments

**Comment by sjib** [comment]
If it is a manhole you could also just describe it with the reach material, if this is the same within the manhole

**Comment by sjib** [comment]
@max-trolliet Check with VSA norm on constructing manholes

**Comment by varrieta** [comment]
@max-trolliet Could you find an answer about that?

**Comment by max-trolliet** [comment]
It seems it is more conventional than normativ. I checked with my contacts at Holinger Lausanne. We did not find anything solid in SIA or VSA norms. I see them this afternoon once more, I'll post the result of the investigation.

**Comment by sjib** [comment]
Why would you be interested in this and want to document it?
- to know how the manhole is constructed?
- for hydraulic reasons?
- ...

**Comment by urskaufmann** [comment]
Suggestion until there is no explizit field: use the comment field of table benching/structure_part

**Comment by max-trolliet** [comment]
I'd say it is more for digitizing purpose... If there was something in a constructive norme, then it could be set to defaultly put the same material. The user would then only have to specify if the materials are different. 

As it does not seem to be the case, the user can still do it in both fields. It's not such an important loss of time
