### ISSUE TITLE
Editing View broken, possibly due to virtual fields

### ISSUE THREAD

**Issue by ponceta** [QGEP/QGEP#325]
Hi,

I destroyed my view vw_qgep_wastewater_structure using some virtual fields in my qgs project.

At least my data were not impacted.

Should we put a warning somewhere to prevent that? Or get a hierarchy to avoid users to modify the datamodel?

**Comment by m-kuhn** [comment]
Can you explain in more detail what you have done and what the effect was?

**Comment by ponceta** [comment]
I added two virtual columns
`long`  -> `$length`
and
coord ->
'concat($x," \n",$y," \n".level,"")'

This resulted is a modification of the `vw_qgep_wastewater_structure`

**Comment by m-kuhn** [comment]
What kind of modification? Virtual fields should not affect the database in no way at all.

**Comment by ponceta** [comment]
That's my opinion too.

But QGIS is adding some modifications in a way I do not understand yet.

I've another issue which has a similar behaviour :
https://github.com/QGEP/QGEP/issues/326 but no virtual fields are involved.

**Comment by ponceta** [comment]
Should be fixed with https://github.com/QGEP/QGEP/issues/336

**Comment by m-kuhn** [comment]
The next release of QGIS 2.18 (as well as QGIS 3.0) will no longer suffer from this problem, regardless of user roles. https://github.com/qgis/QGIS/commit/93396153bb6c427f4d48e167049f5f3b4e7ab058

**Comment by ponceta** [comment]
Nice, thanks! this means 2.18.15? I'll take a look at the master in the meantime.

**Comment by m-kuhn** [comment]
Exactly, landed last week and will be in 2.18.15.

**Comment by ponceta** [comment]
On the 8th of december if release agenda is correct https://www.qgis.org/fr/site/getinvolved/development/roadmap.html
