### ISSUE TITLE
Edit broken on reaches due to a change in the view vw_qgep_reach

### ISSUE THREAD

**Issue by ponceta** [QGEP/QGEP#326]
My users got this error

`Couche Tronçons: 
Erreur PostGIS lors de l'ajout d'entité : ERREUR: l'enregistrement « new » n'a pas de champs « accessibility » CONTEXT: instruction SQL « INSERT INTO qgep.od_wastewater_structure ( obj_id , accessibility , contract_section -- , detail_geometry_geometry , financing , gross_costs , identifier , inspection_interval , location_name , records , remark , renovation_necessity , replacement_value , rv_base_year , rv_construction_type , status , structure_condition , subsidies , year_of_construction , year_of_replacement , last_modification , fk_dataowner , fk_provider , fk_owner , fk_operator ) VALUES ( COALESCE(NEW.fk_wastewater_structure,qgep.generate_oid('od_channel')) -- obj_id , NEW.accessibility , NEW.contract_section -- , NEW.detail_geometry_geometry , NEW.financing , NEW.gross_costs , NEW.identifier , NEW.inspection_interval , NEW.location_name , NEW.records , NEW.remark , NEW.renovation_necessity , NEW.replacement_value , NEW.rv_base_year , NEW.rv_construction_type , NEW.status , NEW.structure_condition , NEW.subsidies , NEW.year_of_construction , NEW.year_of_replacement , NEW.last_modification , NEW.fk_dataowner , NEW.fk_provider , NEW.fk_owner , NEW.fk_operator ) RETURNING obj_id » fonction PL/pgsql qgep.vw_qgep_reach_insert(), ligne 64 à instruction SQL`

I inspected it and it appears that the view has changed :

see the diff here: https://www.diffchecker.com/UWVeqqij
right is the original view
left is the modified view

**Comment by m-kuhn** [comment]
I don't see any way that QGIS could be doing this. I don't think QGIS even knows how to spell `ALTER VIEW`.

@3nids could it be that the translation and config script has introduced this change?

**Comment by 3nids** [comment]
this is really strange
the translation script is just [setting the aliases](https://github.com/QGEP/customizer/blob/master/customizer.py#L163), I don't think this could affect the field names.

**Comment by ponceta** [comment]
![image](https://user-images.githubusercontent.com/8614223/26879110-2ddf1226-4b90-11e7-9ce3-c923a51bddc1.png)

When modifying aliases in the reach layer form, we sometimes get these 77 error messages for the 77 fields and the view is broken afterwards.

**Comment by haubourg** [comment]
Hi, I reproduce when changing the field name, not the alias. 
In Postgres it changes the view definition by adding an alias to the field name.. 
If you are trying to change the alias column in QGIS, then something is mixed up underneath between alias and field names. 
That wouldn't be totally surprising, I've seen issues when ordering the field tab, constraints got saved on the wrong rows.;

**Comment by m-kuhn** [comment]
I think this is an upstream QGIS error that is triggered when you go to "Layer Properties -> Fields" and then click on the table headers to sort it differently.

**Comment by ponceta** [comment]
Should be fix with https://github.com/QGEP/QGEP/issues/336

**Comment by m-kuhn** [comment]
Fixed with https://github.com/qgis/QGIS/commit/93396153bb6c427f4d48e167049f5f3b4e7ab058
