### ISSUE TITLE
Minidumps are current when editing with QGIS

### ISSUE THREAD

**Issue by ponceta** [QGEP/QGEP#327]
Open QGEP, go into edit mode, click add feature, QGIS crashes.

Open QGEP, go into edit mode, wait 5-10 seconds, click add feature, all goes well.

If you wait wait wait it seems that it is quite stable, but it's slow.

**Comment by m-kuhn** [comment]
I assume this should be fixed with

https://github.com/qgis/QGIS/pull/5440

**Comment by ponceta** [comment]
Solved with performance improvements in https://github.com/QGEP/QGEP/issues/308
