### ISSUE TITLE
It is not possible to cut a reach

### ISSUE THREAD

**Issue by ponceta** [QGEP/QGEP#328]
Actually, it is not possible to cut a reach in two parts using the dedicaced QGIS tool

![image](https://user-images.githubusercontent.com/8614223/26922588-d7941500-4c3f-11e7-9fb8-d57a11efdaa7.png)

**Comment by m-kuhn** [comment]
Can you be more precise about what you mean with "not possible"?

**Comment by m-kuhn** [comment]
Possible duplicate of https://github.com/QGEP/QGEP/issues/219?

**Comment by ponceta** [comment]
Duplicate of #219
