### ISSUE TITLE
Interlis export

### ISSUE THREAD

**Issue by andreasneumann** [qgep/QGEP#33]
Need for an easy to use Interlis export.

Pirmin Kalberer (Sourcepole) will work on SEXTANTE improvements regarding Interlis.

**Comment by m-kuhn** [comment]
What is the status of this?

**Comment by sjib** [comment]
Successful export to INTERLIS2.3 VSA-DSS and SIA405 Abwasser (Waste water) using ili2pg Version 2.5.1

**Comment by m-kuhn** [comment]
How can I trigger an export?

**Comment by m-kuhn** [comment]
What is the status of this?

**Comment by sjib** [comment]
I created a new folder interlis with the scripts for creating the export schema and then using ili2pg for exporting to sia405abwasser.

https://github.com/QGEP/datamodel/pull/22

**Comment by sjib** [comment]
@m-kuhn Where does this show up?

**Comment by m-kuhn** [comment]
@where does what show up?

**Comment by sjib** [comment]
My INTERLIS folder https://github.com/QGEP/datamodel/pull/22

**Comment by sjib** [comment]
@m-kuhn I can recommit that - where should I place the folder interlis. As subfolder of datamodel or migration?

**Comment by m-kuhn** [comment]
What do you think about a new folder `export` in the main `QGEP` repository?

**Comment by sjib** [comment]
https://github.com/QGEP/QGEP/export and then also https://github.com/QGEP/QGEP/import - looks good to me

**Comment by m-kuhn** [comment]
This works.

Next step: make it more accessible from the user interface (A menu entry or processing functionality).

**Comment by m-kuhn** [comment]
First step: upload SQL files to the repository.

Thanks @sjib

**Comment by sjib** [comment]
Decision: Implement the export in the plugin. Store necessary sql Files here: https://github.com/QGEP/qgepplugin/sql/export/interlis

**Comment by sjib** [comment]
Idea: Add a processing algorithm to launch the export. QGEP Plugin adds this to the Processing tools.
Maybe need to change the schema name with a variable

**Comment by sjib** [comment]
Get specific version of ili2pg with start of process
