### ISSUE TITLE
Digitize wastewater structure not working

### ISSUE THREAD

**Issue by varrieta** [QGEP/QGEP#331]
I can digitize the structure but when I right click to validate I get the following error: 

`Couche od_wastewater_structure: Erreur PostGIS lors de la modification de géométrie: ERREUR: Dimensions mismatch in lwcollection CONTEXT: fonction SQL "st_geomfromwkb", instruction 1`

**Comment by m-kuhn** [comment]
Are you based on the normal database model?
I remember you had some Z coordinate modifs...

**Comment by varrieta** [comment]
Indeed, it seems that I still have od_wastewater_structure in 3D, I'll put it back in 2D and let you know

**Comment by max-trolliet** [comment]
The last database model I downloaded last week is still in 3D I think...  :   detail_geometry_geometry geometry(CurvePolygonZ,21781) is it really the case?

**Comment by sjib** [comment]
#232

**Comment by varrieta** [comment]
I updated my datamodel as it should, with only od_reach and od_wastewater_structure having 3D geometry but an error remain when I try to digitize a surface:

![image](https://user-images.githubusercontent.com/20111558/27957191-93c6e7ae-631d-11e7-95f0-cfea730109ad.png)

Could it be related to this?
https://issues.qgis.org/issues/15470
