### ISSUE TITLE
Network following tool - summing up data

### ISSUE THREAD

**Issue by sjib** [QGEP/QGEP#353]
- sum up attributes like length, flow_time, ...
- sum up connected attributes like catchment area, inhabitants etc.
- ...

**Comment by sjib** [comment]
@urskaufmann - send GEPView documentation to @m-kuhn

**Comment by sjib** [comment]
Define how it should work till next meeting. Start implementation Q1/2018

**Comment by sjib** [comment]
Use Cases:
1.       Fliesszeit / flow time
wir kennen die fliesszeit in einer haltung und sollten jetzt wissen, wie lange es von Pkt 1 bis Pkt B dauert à aufsummieren mit Zwischenresultat (Dauer)
Beispiel: von Beginn Haltung a bis Ende Haltung e dauert es 60
Haltung                Fliesszeit             Dauer  
a             10           10
b             5             15
c              15           30
d             10           40
e             20           60
 
2.       Einzugsgebiet einer Einleitstelle / Catchement above node into river
wie gross ist die Fläche (EZG) die bei einer Einleittelle ins Gewässer kommen ?
Vorgehen: Netzverfolgung up, angeschlossene EZG markieren, dann summieren
 
bei 2. kann ich mir schon helfen, bei  1 auch, ist aber sehr mühsam …

**Comment by m-kuhn** [comment]
# Following todays discussions

Focus on flow times in a first step.

# Input data

* Raw hydraulic calculation tool output. Needs to be imported into `od_measurement_series`, `od_measurement_result` and `od_measuring_point` (potentially `od_measureing_device` in a followup step)
* A `od_wastewater_node` as reference point
* A `series` from which to take measurements
* A selection of reaches
* (The network graph)

# Output data

* A table with
 * point geometries
 * summed up results
 * foreign key to a reach (the reach for which the matching point is the `fk_reach_point_from`, so the reach below the calcualted flow time point)

# Datamodel adjustments

* New column `fk_wastewater_networkelement` in `od_measureing_point` to link the series and measurement result to a reach.

**Comment by m-kuhn** [comment]
@kfischerar can you send us some data to test this?

**Comment by m-kuhn** [comment]
Depends on https://github.com/QGEP/QGEP/issues/410

**Comment by 3nids** [comment]
fake demo data:
`CREATE TABLE qgep_od.flow_times AS SELECT obj_id AS fk_reach, random() * 9 + 1 as flow_time FROM qgep_od.reach;`

**Comment by 3nids** [comment]
yes since 1.0.0
