### ISSUE TITLE
Labels in vw_qgep_wastewater_structure

### ISSUE THREAD

**Issue by urskaufmann** [QGEP/QGEP#356]
If there is more than one cover or more than one node connected to a wastewater_structure, there are to many identical labels.
![eindeckel](https://user-images.githubusercontent.com/1257403/30338756-fa7f0450-97ec-11e7-9c16-68837cef8272.PNG)
one cover, two nodes -> two labels

![einabwasserknoten](https://user-images.githubusercontent.com/1257403/30338787-16072a72-97ed-11e7-9316-2e692a11c48c.PNG)
two covers, one node  -> two labels

![zweideckel](https://user-images.githubusercontent.com/1257403/30338807-2c57310a-97ed-11e7-93a3-f4bea31c82f5.PNG)
two covers, two nodes  -> four labels

**Comment by varrieta** [comment]
@sjib @m-kuhn Priority 2019 Bugfix

**Comment by m-kuhn** [comment]
Wait for implementation of geometry generator for labels project to be implemented in QGIS 3.8

**Comment by m-kuhn** [comment]
Sounds very similar to both of them, yes

**Comment by sjib** [comment]
@m-kuhn (QGIS 3.8 is out now)[http://blog.qgis.org/2019/07/23/qgis-3-8-zanzibar-is-released/] - can this be solved now?

**Comment by haubourg** [comment]
> @m-kuhn [QGIS 3.8 is out now](http://blog.qgis.org/2019/07/23/qgis-3-8-zanzibar-is-released/) - can this be solved now?

This would raise a minimum requirement for QGIS 3.8 then. Or will QGIS be nice and tolerant for LTR users ?

**Comment by m-kuhn** [comment]
For those who want "nice labels" QGIS 3.8 will be the minimum requirement.
For anyone else I think things will continue to work the way they did before (no guarantee for this statement, that's just a guess, maybe we need to fine tune some incompatible options but I can't think of any right now)

**Comment by m-kuhn** [comment]
Meanwhile we have

- geometry generators for labels
- single point wastewater structures
- customizable labels pending (https://github.com/QGEP/datamodel/pull/127)

Can we close this issue?
