### ISSUE TITLE
Connect wastewater network element

### ISSUE THREAD

**Issue by max-trolliet** [QGEP/QGEP#363]
Hi everyone, 

What is the function of the "Connect wastewater network element" tool? 

It seems to correctly connect the reaches to the node, but shouldn't it also fill the reach with the reachpoint identifier (from/to)? Do I have to do it manualy? The wizzard (not working on my install... I'm working on it)

**Comment by m-kuhn** [comment]
It only needs to set a foreign key (fk_wastewater_networkelement on reach_point_from and reach_point_to, with the obj_id). I'm not aware of anything related to the identifier.

**Comment by m-kuhn** [comment]
Also the wizard doesn't do anything there

**Comment by varrieta** [comment]
Most of the time, the rp_from_level of a reach is equal to the rp_from_node.bottom_level. 

It could be great that the tool propose to the user to directly update the rp_from_level with the bottom_level.

Same for rp_to_level of course.

Maybe doable during the code sprint?

**Comment by varrieta** [comment]
Maybe in contradiction with #361

**Comment by ponceta** [comment]
@varrieta Not in contradiction, #361 is about the way used to achieve such a goal (via plugin or via db intelligence / native qgis mechanisms.) 

About retrieving altitude value, that was the idea of https://github.com/QGEP/QGEP/issues/406 which sould be in next plugin release.

**Comment by varrieta** [comment]
Shouldn't we close this issue (solved by #361 )?
