### ISSUE TITLE
Allow adjusting reach geometry when a reach point foreign key changes

### ISSUE THREAD

**Issue by max-trolliet** [QGEP/QGEP#366]
Hi,

It could be nice to have an option for the Connect wastewater networkelement tool to snap the end point of a reach to the manhole/node/etc that we connect it to with the tool. This means not only connecting the element as it does now, but correct the geometry if it is wrong or inaccurate. 

This would be a real time saving tool after a migration or when receiving data to insert in the dB. 

As now we have to connect the elements, move the end point of the line etc. 

I know I am kind of "the less clicks, the best" ;)

**Comment by sjib** [comment]
Should be solved with new processing tool "snap reach geometry" in https://github.com/QGEP/qgepplugin/releases/tag/v0.7.1

**Comment by sjib** [comment]
@max-trolliet Please test and check
