### ISSUE TITLE
Enlarge identifiers

### ISSUE THREAD

**Issue by ponceta** [QGEP/QGEP#368]
At least problematic for reaches in Pully since our naming convention for those is the concatenation from upstream node and downstream nodes identifiers.

Eg. `"RC 022_cff-PP 630_cff"`

Is this used by others?

Thoughts?

**Comment by sjib** [comment]
Yes we were discussing to enlarge this to 41 (20 + 20 + 1)

**Comment by sjib** [comment]
Problem is, that identifier is an attribute of wastewater_structure respectively wastewater_network_element. So when we enlarge it there to e.g. TEXT*41  it is also enlarged in the subclasses (channel resp. reach) and then we have to restrict the text length in the subclasses manhole and wastewater node to TEXT*20 with a rule to not create a problem.

**Comment by ponceta** [comment]
This is a VSA won't fix? I close it since I worked around.
