### ISSUE TITLE
Traduction

### ISSUE THREAD

**Issue by ponceta** [QGEP/QGEP#370]
There are actually no reviewers for the French translation.

This means that despite the good work that has been done on the translators side, there's still no traduction available for the users. 

![image](https://user-images.githubusercontent.com/8614223/32285167-c56fd528-bf29-11e7-89d1-ec0db3b98e66.png)

![image](https://user-images.githubusercontent.com/8614223/32285195-d690c75e-bf29-11e7-9f35-b22beeee5fa0.png)

![image](https://user-images.githubusercontent.com/8614223/32285242-0054d12a-bf2a-11e7-9686-06f691696869.png)

**Comment by m-kuhn** [comment]
Does this concern plugin, docs or project?

**Comment by ponceta** [comment]
A bit of both IMHO.

**Comment by m-kuhn** [comment]
Ok, mainly it should be completely translated.
The question of reviewing is as far as I know optional for transifex, so unless we need this quality control I would focus on completeness first (and then require it, depending of if we can and want to afford the required resources!)

**Comment by ponceta** [comment]
I was mislead, I thought translation had to be reviewed before beeing available. This is then fine. Reviewers will be named when the translators community will be bigger! ;) Completeness is then the next goal, I agree,
