### ISSUE TITLE
Wastewater structure and networkelement should not share same identifier and remark

### ISSUE THREAD

**Issue by ponceta** [QGEP/QGEP#375]
This is an understanding question :

Actually, wastewater structure and networkelement have the same identifier and remark field.

Both are actually inserted and updated as unique fields.

https://github.com/QGEP/datamodel/blob/master/view/vw_qgep_reach.sql#L247-L248
https://github.com/QGEP/datamodel/blob/master/view/vw_qgep_reach.sql#L365-L369

What is the purpose of this duplicated information since networkelement has a foreign key which linked it to ?

https://github.com/QGEP/datamodel/blob/master/view/vw_qgep_reach.sql#L394

**Comment by urskaufmann** [comment]
That seems to be a mistake.
There are remark and identifier fields in class networkelement and wastewater structure, but this are different fields and should have different content.
If the fields in the view have the discussed prefix (#318) that shows the class they are from, such problems would by earlier recognized

**Comment by ponceta** [comment]
Will be fixed with https://github.com/QGEP/datamodel/pull/53

**Comment by ponceta** [comment]
Fixed with https://github.com/QGEP/datamodel/pull/68
