### ISSUE TITLE
Plan code sprint

### ISSUE THREAD

**Issue by m-kuhn** [QGEP/QGEP#377]
13.12.2017

## TODO

* [x] Doodle
* [x] Invite participants
* [x] Book room
* [x] Organize lunch

Confirmed participation:
 * AP
 * MK
 * MT
 * SB
 * UK
 * VA

**Comment by sjib** [comment]
Please add tasks for codesprint here to this milestone: https://github.com/QGEP/QGEP/milestone/11

**Comment by varrieta** [comment]
Who should we invite? Should we fixe wed. 13th ?

**Comment by m-kuhn** [comment]
The room is booked at ImpactHub Bern, Wed, 13
The qwat team is informed about the event

**Comment by haubourg** [comment]
Hi @ponceta told me about that yes. I'll unfortunately be on my way to the QGIS User Meeting in France this particular day.

**Comment by haubourg** [comment]
I think @dsavary might be interested a lot

**Comment by ponceta** [comment]
@m-kuhn there is still a miss before this gets really started...
- [ ] Improvize afterwork bier
(I turn 30 the day after so... ;) )

**Comment by haubourg** [comment]
@ponceta  ow, I wish I could be there !

**Comment by dsavary** [comment]
Unfortunately, I can't come to the code sprint meeting.

**Comment by m-kuhn** [comment]
@ponceta I think the checkbox can only be clicked after the event, it's hard to organize improvization ;)

**Comment by max-trolliet** [comment]
I'll be there, hoping I can be of some help. Python is not that easy to take a grasp on...

**Comment by kfischerar** [comment]
I'm sorry, i can't be in Bern tomorrow but i'm sure you will do a good job.
Thank's for your work!
all the best, koni

2017-12-07 16:37 GMT+01:00 Maxime Trolliet <notifications@github.com>:
