### ISSUE TITLE
Action to inverse reaches

### ISSUE THREAD

**Issue by varrieta** [QGEP/QGEP#380]
The project should propose an action to inverse the selected reaches geometry and their from and to node. 
Currently working on it.

**Comment by m-kuhn** [comment]
Good to hear. Can you comment on the approach you are implementing?

**Comment by varrieta** [comment]
I started from the action we learned with Denis at the PyQGIS course. 

For now I can inverse the geometry of the selected reaches:

```
# a python script as a layer action to reverse selected lines

# get the layer you are working on
layer = QgsMapLayerRegistry.instance().mapLayer("test20171124164132560")

# initialize the feature list
selected_f = [ ]
selected_f = layer.selectedFeatures()

# loop over the results when executing the request
if layer:

  for f in selected_f:
    # get the geometry of the feature as a polyline (vector of points)
    geom = f.geometry().asPolyline()
    # reverse the line
    geom.reverse()
    # recreate a geometry
    geom = QgsGeometry.fromPolyline(geom)

    layer.changeGeometry(f.id(), geom)
    layer.triggerRepaint()
```
I wanted to finish with a `if layer.changeGeometry(f.id(), geom):` in the for loop but couldn't make it work

**Comment by m-kuhn** [comment]
I was thinking it would be nice to have a processing algorithm instead, so it could be integrated into import workflows (e.g. filter based on `rp_from_level < rp_to_level` and then invert)

**Comment by varrieta** [comment]
The problem is that even if it shouldn't happen, sometimes the rp_to_level is really higher than the rp_to_level...

But maybe we could have both?

**Comment by m-kuhn** [comment]
The logic was just an example, to be defined for each use case individually. The point is, with processing it can be integrated in models.

**Comment by haubourg** [comment]
Jumping in. Why not using a database stored procedure for that and simply call that from the action.?
That's what we do in another project. Works well and will works more easily on a web client.

**Comment by m-kuhn** [comment]
Also a doable approach.
The way to trigger this could still be a processing algorithm.

To "generalize" the topic a bit:

* Add a new "call stored procedure" processing algorithm
* Add the possibility to configure exposure of processing algorithms as feature (etc) actions

**Comment by haubourg** [comment]
Yep, 
we have an API schema storing only an API interface based on stored procedure . 
here is one to invert pipes (in french, we didn't have any choice). I removed code parts related to some business logic there:
```
-- Function: api_maj.inverser_sens_ecoulement(uuid)

-- DROP FUNCTION api_maj.inverser_sens_ecoulement(uuid);

CREATE OR REPLACE FUNCTION api_maj.inverser_sens_ecoulement(t_id uuid)
  RETURNS void AS
$BODY$
 declare
         tbl text;
 begin
  
         -- inverser noeud amont et aval (et géométrie)
         update ouvrage.troncon
            set geometrie = st_reverse(geometrie)
                , noeud_amont_id = noeud_aval_id
                , noeud_aval_id = noeud_amont_id
          where id = t_id;
         -- mise à jour de l'abscisse de tous les ouvrages liés
         foreach tbl in array array[['be', 'br', 'bp', 'pk', 'ps', 'puits', 'refuge', 'src']] loop
             execute 'update ouvrage.' || tbl || ' set abscisse = 1 - abscisse where troncon_id = $1'
             using t_id;
         end loop;

  $BODY$
  LANGUAGE plpgsql VOLATILE
  COST 100;

COMMENT ON FUNCTION api_maj.inverser_sens_ecoulement(uuid) IS '-- Inverse le sens d''écoulement d''un tronçon
-- Met à jour l''abscisse des éléments liés à ce tronçon';

```

Note that this plays well with transaction groups, and here is the code for a 2.18 layer action calling it:
```

# coding: utf8 
from qgis.gui import QgsMessageBar

try :
    registry = QgsMapLayerRegistry.instance()
    layer = registry.mapLayer('[% @layer_id %]')
        
    # checks if editable
    if  layer.isEditable():
        layer.startEditing()
        tr_id = '[%id%]'
                      
        # trigger the stored procedure doing the real work
        sql = 'SELECT api_maj.inverser_sens_ecoulement(\''+ tr_id + '\');'# gets current transaction
        transaction = layer.dataProvider().transaction()
        transaction.executeSql(sql)
        
        # force redraws 
        layer.triggerRepaint()

    else :
        qgis.utils.iface.messageBar().pushMessage("Info", u'Passer la couche en édition pour inverser le tronçon', level=QgsMessageBar.WARNING)


except :
    qgis.utils.iface.messageBar().pushMessage("Erreur",  u"Impossible de inverser le tronçon", level=QgsMessageBar.CRITICAL)
    raise

```

I would miss the ability to hide / show actions programatically (those action don't make sense in read only mode)

**Comment by m-kuhn** [comment]
> I would miss the ability to hide / show actions programatically (those action don't make sense in read only mode)

That would be an additional feature request besides the ones listed above? Yes, I agree. Adding an expression for this would be great.

**Comment by haubourg** [comment]
filed! https://issues.qgis.org/issues/17581

**Comment by varrieta** [comment]
Great, let's make it work at the code sprint then :)

**Comment by haubourg** [comment]
Shouldn't be too hard :)
![anim](https://user-images.githubusercontent.com/1629853/33366814-b2f83916-d4ec-11e7-9852-ac339f47f53a.gif)

Caveats in QGIS 2.18 were:
- if using only those actions, without any native edit tool before didn't informed QGIS that there was something to save. Fixed with adding a flag in QgsTransaction.ExecuteSQL.
- Undo / Redo wasn't working with transaction groups >  fixed also 
- Calling QgsTransaction.ExecuteSQL didn't allow to name the action in the undo/redo stack. Waiting for a merge in the current soft freeze context.

**Comment by max-trolliet** [comment]
We should also have something to invert the reach point only (without the geometry). I have some cases of reaches which are digitized in the right way, but their RP seems to be incorrect.

**Comment by max-trolliet** [comment]
Will inverting the direction of reaches correct the topology? I'm testing the upstrem downstream, and it is kind of funny how it behaves for now with my data.

**Comment by m-kuhn** [comment]
> We should also have something to invert the reach point only (without the geometry). I have some cases of reaches which are digitized in the right way, but their RP seems to be incorrect.

Reach points are created by vw_qgep_reach, always in flow direction. If you are not directly inserting into reach and reach point tables, there should be no trouble.

> Will inverting the direction of reaches correct the topology? I'm testing the upstrem downstream, and it is kind of funny how it behaves for now with my data.

Define "kind of funny" ;)

**Comment by max-trolliet** [comment]
![image](https://user-images.githubusercontent.com/13679128/33485294-1f14c10e-d6a6-11e7-9259-dbddf471ef86.png)
quick example using downstream. That is what I call kind of funny.

**Comment by varrieta** [comment]
What is the from_node of the reach with label "CN 41.37m" ?

**Comment by max-trolliet** [comment]
![image](https://user-images.githubusercontent.com/13679128/33487838-e823484c-d6ae-11e7-87db-03a0bccb09c0.png)

Here's the rp from for this reach.

**Comment by ponceta** [comment]
Assuming correct wastewater structure points as support for our reach.

- The od_reach object has 2D geometry, it just has to be inverted.
- The od reach_point objects are 2D points with level as 3D, we consider these in this case as correct.
- The od_reach object has a link to both from/to od_reach_point through their identifiers this has to be inverted.

**Comment by ponceta** [comment]
```
# a python script as a layer action to reverse selected lines

# get the layer you are working on
layer = QgsMapLayerRegistry.instance().mapLayer("vw_qgep_reach")

# start editing
layer.startEditing()

# initialize the feature list
selected_f = [ ]
selected_f = layer.selectedFeatures()

# loop over the results when executing the request
if layer:

  for f in selected_f:
    # get the geometry of the feature as a polyline (vector of points)
    geom = f.geometry().asPolyline()
    # reverse the line
    geom.reverse()
    # recreate a geometry
    geom = QgsGeometry.fromPolyline(geom)

    layer.changeGeometry(f.id(), geom)
    
    old_point_from = "[%rp_from_obj_id%]"
    old_point_to = "[%rp_to_obj_id%]"
	
    f['rp_from_obj_id'] = old_point_to
    f['rp_to_obj_id'] = old_point_from
	
    layer.updateFeature(f)
    layer.commitChanges()
	
```

This logic works on od_reaches layer but not on vw_qgep_reach since rp_obj_id are not updated.

**Comment by ponceta** [comment]
See https://github.com/QGEP/datamodel/blob/master/view/vw_reach.sql#L116-L134

**Comment by ponceta** [comment]
I leave here the working function for qgep.od_reach
```
# a python script as a layer action to reverse selected lines

# get the layer you are working on
layer = QgsMapLayerRegistry.instance().mapLayer("od_reach20171213105150775")

# start editing
layer.startEditing()

# initialize the feature list
selected_f = [ ]
selected_f = layer.selectedFeatures()

# loop over the results when executing the request
if layer:

  for f in selected_f:
    # get the geometry of the feature as a polyline (vector of points)
    geom = f.geometry().asPolyline()
    # reverse the line
    geom.reverse()
    # recreate a geometry
    geom = QgsGeometry.fromPolyline(geom)

    layer.changeGeometry(f.id(), geom)
    
    old_point_from = "[%fk_reach_point_from%]"
    old_point_to = "[%fk_reach_point_to%]"
	
    f['fk_reach_point_from'] = old_point_to
    f['fk_reach_point_to'] = old_point_from
	
    layer.updateFeature(f)
    layer.commitChanges()

```

I started to do it from the db side as suggested by @haubourg I'll add more asap

**Comment by varrieta** [comment]
This work but the st_reverse function doesn't seems to work on 3D compound curve, had to go back to linesting and again curve.

Postgis side:

```
-- Function: qgep.api_reverse_reach(text)

-- DROP FUNCTION qgep.api_reverse_reach(text);

CREATE OR REPLACE FUNCTION qgep.api_reverse_reach(_obj_id text)
  RETURNS void AS
$BODY$
BEGIN
 
         -- reverse from and to node and geometry
         update qgep.od_reach
            set progression_geometry = ST_ForceCurve(ST_Reverse(ST_CurvetoLine(progression_geometry)))
                , fk_reach_point_from = fk_reach_point_to
                , fk_reach_point_to = fk_reach_point_from
          where obj_id = _obj_id;

END;
$BODY$
  LANGUAGE plpgsql VOLATILE
  COST 100;
ALTER FUNCTION qgep.api_reverse_reach(text)
  OWNER TO postgres;
```
QGIS side:

```
# coding: utf8 
from qgis.gui import QgsMessageBar

try :
    registry = QgsMapLayerRegistry.instance()
    re_lyr = registry.mapLayer('[% @layer_id %]')
        
    # checks if editable
    if  re_lyr.isEditable():
        re_lyr.startEditing()
        _obj_id = '[%obj_id%]'
                      
        # trigger the stored procedure doing the real work
        sql = 'SELECT qgep.api_reverse_reach(\''+ _obj_id + '\');'# gets current transaction
        transaction = re_lyr.dataProvider().transaction()
        transaction.executeSql(sql)
        
        # force redraws 
        re_lyr.triggerRepaint()

    else :
        qgis.utils.iface.messageBar().pushMessage("Info", u'Toggle editing', level=QgsMessageBar.WARNING)


except :
    qgis.utils.iface.messageBar().pushMessage("Erreur",  u"Impossible to reverse the reach", level=QgsMessageBar.CRITICAL)
    raise
```

**Comment by varrieta** [comment]
The code above doesn't works when using on an existing reach (that has already been saved once). 
It does inverse the geometry but when I want to register, it get back to the initial geometry.

![capture](https://user-images.githubusercontent.com/20111558/35611313-f8803e08-0664-11e8-9297-a85934f8b06e.PNG)

![capture1](https://user-images.githubusercontent.com/20111558/35611317-fa36a61a-0664-11e8-8fcf-e01f7c7c7d19.PNG)
The geometry is inversed using the action

![capture3](https://user-images.githubusercontent.com/20111558/35611318-fb99c33e-0664-11e8-9d93-939acf8cb779.PNG)
The geometry get back to initial when registering. Doesn't even ask to register, as anything would have been changed

Any ideas? @haubourg @m-kuhn @3nids

**Comment by haubourg** [comment]
@varrieta what QGIS version are you using? 

There is a trap in QGIS 2.x, there is no way to notify QGIS to mark the layer as dirty. That's why we exactly did [this](https://github.com/qgis/QGIS/pull/5376) in QGIS 3. 
The workaround I found in QGIS 2 was to update a field with the same value as before. This is rather ugly, but works. Just add something like this before executing the transaction :
```
  # fake update of a field to dirty editbuffer (temporary workaround)
        fake_field_name = 'id'
        request = QgsFeatureRequest().setFilterFid(fid)
        feature = next(layer.getFeatures(request))
        fake_value = feature.attribute(fake_field_name)
        fake_field_id = feature.fieldNameIndex(fake_field_name)
        layer.editBuffer().changeAttributeValue(fid, fake_field_id, fake_value)
```

**Comment by varrieta** [comment]
Thanks @haubourg, the workaround does work (code below) !

2 possibilities now:

- Add the inverse action with the workaround and keep in mind that we need to modify it when we move to QGIS 3

- Wait for QGIS 3 to implement the action

What do you think @m-kuhn @3nids ?
 
```
# coding: utf8 
from qgis.gui import QgsMessageBar

try :
    registry = QgsMapLayerRegistry.instance()
    re_lyr = registry.mapLayer('[% @layer_id %]')
        
    # checks if editable
    if  re_lyr.isEditable():
        re_lyr.startEditing()
        _obj_id = '[%obj_id%]'
                      
        # fake update of a field to dirty editbuffer (temporary workaround until qgis 3)
        fake_field_name = 'obj_id'
        fid = 0
        request = QgsFeatureRequest().setFilterFid(fid)
        feature = next(re_lyr.getFeatures(request))
        fake_value = feature.attribute(fake_field_name)
        fake_field_id = feature.fieldNameIndex(fake_field_name)
        re_lyr.editBuffer().changeAttributeValue(fid, fake_field_id, fake_value)

        # trigger the stored procedure doing the real work
        sql = 'SELECT qgep.api_reverse_reach(\''+ _obj_id + '\');'# gets current transaction
        transaction = re_lyr.dataProvider().transaction()
        transaction.executeSql(sql)
        
        # force redraws 
        re_lyr.triggerRepaint()

    else :
        qgis.utils.iface.messageBar().pushMessage("Info", u'Toggle editing', level=QgsMessageBar.WARNING)


except :
    qgis.utils.iface.messageBar().pushMessage("Erreur",  u"Impossible to reverse the reach", level=QgsMessageBar.CRITICAL)
    raise
```

**Comment by m-kuhn** [comment]
I think we should push the SQL function to the datamodel (once it's stable again) and implement the processing means (a generic algorithm + a model to preconfigure the generic algorithm for this function/use-case?)

**Comment by haubourg** [comment]
@m-kuhn  Not sure I get the point of having processing algorithm there. Can you explain the code design behind that idea ? 
Thx!

**Comment by m-kuhn** [comment]
Use case 1

* Select reaches to invert -> launch processing algorithm to trigger db functionality

Use case 2

* Promote any (feature based) processing algorithm to a feature action

**Comment by varrieta** [comment]
+1 for pushing the SQL function

**Comment by haubourg** [comment]
@m-kuhn got it thanks. 
That means algorithms should be able to either work in the current transaction group, or open their own when the project in not using transaction groups, and then trigger a canvas refresh right? 
Should that be an option or an automatic behavior with an automatic detection of the db connection ?

**Comment by m-kuhn** [comment]
Pretty much, yes. I guess it should be possible to autodetect, and if we run into troubles we can still introduce options. Not sure if the canvas refresh is something the algorithm should invoke explicitly, it should rather somehow notify the layer (or have it autodetect) that data changed and trigger the refresh via these means.

**Comment by haubourg** [comment]
So, is Processing mature enough to handle this algorithm in 2.18 branch or is that solution only for a QGIS 3.x target? 

If not so, should we go for a 2.18 simple layer action and plan to switch to the algorithm when switching QGEP to QGIS 3? Or are we in a gray zone here?

**Comment by urskaufmann** [comment]
tested the new "change reach direction"-tool in plugin 1.1.3. After selecting some reaches and starting the tool, the labels of the reaches (flow direction arrow) and of the wastewater_structures (I -level gets O -level and O - level gets I -level) change, as expected. And the vw_qgep_reach is editable. 
If I then save the changes, all the labels switch immediately back. I can not save the changes of the tool :-(

**Comment by m-kuhn** [comment]
See https://github.com/QGEP/qgepplugin/issues/24 for a workaround

**Comment by ponceta** [comment]
Using processing and qgepplugin 1.1.10 on QGIS 3.4.8

![image](https://user-images.githubusercontent.com/8614223/58786499-ff610a00-85e7-11e9-94cf-8b016df278ef.png)

**Comment by m-kuhn** [comment]
For reference, [the above error](https://github.com/QGEP/QGEP/issues/380#issuecomment-498158128) is linked to "transaction mode" being disabled on the project.
