### ISSUE TITLE
Add a control checkbox for structures (ws and reaches)

### ISSUE THREAD

**Issue by ponceta** [QGEP/QGEP#383]
In Pully, we have the need for a checkbox to see if a structure has been controlled / validated by the operation service. This is useful for a responsibility transfert from GIS to sanitation experts.

Is this a need in other organisations?

**Comment by max-trolliet** [comment]
What kind of controle on what kind of structure? 

For public network we have the inspection, at the end of construction, then it is supposed to be inspected in a 5-10y time. For private network it is different, with the change from mixed ww to separeted waters. We ask for the TV report and check on field stuff like U4/V4 (SIA 190) profile around reaches... 

Could the check be done by inserting a field Maintenance, giving the date of the last inspection?

**Comment by sjib** [comment]
I suggest to use the maintenance_event class to store such information. As this could be more than a one time thing.

**Comment by sjib** [comment]
Here some more details as a suggestion:
- maintenance_event.kind = examination
- maintenance_event.status = [planned -> accomplished ]
- maintenance_event.reason = "validation"
-...
@ponceta Does this help?

**Comment by ponceta** [comment]
@sjib Thanks for the tips! About maintenance, we lack of documentation about how to handle these entities : http://qgep.github.io/docs/en/user-guide/editing/maintenance_events.html 

As we discussed this in Pully, we have two distinct processes and both can have interactions with the other.

One is the **maintenance process** (ideally described by QGEP actually) with indeed informations like inspections, repairs, interventions.

The other is what I would call the **data update process** which is not only about editing but about communication between both services, but I'll try to play with the maintenance events first to see how it works.
