### ISSUE TITLE
[VSA] Why are there so many different values to determine precision

### ISSUE THREAD

**Issue by ponceta** [QGEP/QGEP#384]
There are actually many tables with different value lists for positional accuracy assessment :

ex :
vl_cover_positionnal_accuracy
vl_reach_elevation_determination
vl_horizontal_positioning

with each time different descriptive values.

When applying this to our daily job, it appears that what is needed is to know if you can dig directly or not (accurate or not). 

The precision of the measured point is stored in a gps database rather than in the operationnal database.

How do others feels about this?

What we think in Pully is that it would be better to store the link to the gps measurement and store the definite value (0.26 cm as example).

**Comment by max-trolliet** [comment]
I think it is directly from the VSA - SDEE model. But I share the concern. It could be simpler.

**Comment by sjib** [comment]
This comes from the VSA-SDEE model.
An accuracy for (x,y) and z has not the same precision. This also depends on the method. Therefore there are different value lists. But we introduced here absolute values to be able to compare objects that have been measured with different methods (GPS, digitizing, theodolite, measuring tape, ...)
Reach.Elevation.determination is originally only a value to define the drawing parameter (precise _______, imprecise - - - - line)

**Comment by sjib** [comment]
![deckel lagegenauigkeit](https://user-images.githubusercontent.com/1265865/34124936-01c6f292-e435-11e7-8e01-48d8793b20a3.png)
![haltung lagebestimmung](https://user-images.githubusercontent.com/1265865/34124937-01e339ca-e435-11e7-9de0-e193d8b15290.png)
![haltung hoehenbestimmung](https://user-images.githubusercontent.com/1265865/34124938-01fb5f1e-e435-11e7-8787-3e87dc0fb5f4.png)

**Comment by ponceta** [comment]
Thanks for the explanation.

As I understand, there are mainly two distinct accuracies 2D and 3D, depending on the acquisition method.

This enables to describe the accuracy of the measurement point, and therefore the overall position accuracy of the object.

IMHO we have here a conflict of interest between geomaticians and network operators because some want the qualitative value of the measurement accuracy (+-10cm, ...) and others want the qualitative value of the structure position accuracy (precise or not -> can or can't I dig there)

**Comment by ponceta** [comment]
Would it be at least possible to unify value lists for horizontal accuracy (2D) and unify value lists for vertical  accuracy (Z)?

Or are there some other limitations?

**Comment by sjib** [comment]
Measuring horizontally and vertically do not have the same accuracy range. Z values are less precise usually.

**Comment by m-kuhn** [comment]
I guess this is what @ponceta proposed

 * One list of accurracies for horizontal
 * One list of accurracies for vertical

@ponceta please correct me if I'm wrong

**Comment by ponceta** [comment]
@m-kuhn You're exactly right, the idea is to have planimetric precision and altimetric precision values, which is detailled enough.
