### ISSUE TITLE
[plugin] Digitizing reaches does not allows default values

### ISSUE THREAD

**Issue by ponceta** [QGEP/QGEP#385]
When digitizing reaches with qgep wizard, forms defined default values are not taken into account.

![plugin_reaches](https://user-images.githubusercontent.com/8614223/33718817-0b1d6b48-db5f-11e7-9abd-47c27c005038.gif)

Editing with the wizard is avoiding standard snapping indicators too.

**Comment by m-kuhn** [comment]
This will be solved if we get rid of the wizard. Do you need this to be solved on the 2.18 version already?

**Comment by ponceta** [comment]
Yes I know, that's one issue that will be fixed by editing without the wizard. I hope this will not be mandatory for 2.18.X

**Comment by ponceta** [comment]
(I think it'll be soon time to weight pros and cons for qgis 3 migration, but it would be great to have a QGIS 3.0 one day too, and not a 2.99999!)

**Comment by ponceta** [comment]
Fixed by https://github.com/QGEP/qgepplugin/issues/6 thanks @3nids
