### ISSUE TITLE
tables dispatch in distinct schema

### ISSUE THREAD

**Issue by 3nids** [QGEP/QGEP#391]
We propose to spread the tables in distinct schemas. The main reason behind this is to be able to easily define roles and their corresponding rights (see #336).

Here is a proposal of schemas:
* system (`qgep_sys`)
* metadata (`qgep_mtd`)
* value lists (`qgep_val`)
* network data (`qgep_ned`)
* management data (`qgep_man`)

The dispatch is done in this file:
https://docs.google.com/spreadsheets/d/1-yWfWM8OSx21DxcynIg5TR9pdpaeA8QpqQKweveE6vs/edit?usp=sharing
Please add comments in it if needed (there is no write access, only commenting is allowed).

**Comment by 3nids** [comment]
I am not sure about tables txt_text and txt_smbol.

**Comment by sjib** [comment]
In VSA-DSS we have diffent extensions:

- I  would rather distinguish between additional rights to view VSA-KEK or to manage VSA-KEK (and any other extensions in the future)
This would allow to give the right to add someone who maintains the waste water system to file a new maintenance event that is needed or to say, that it was implemented (e.g. cleaning was done ...)

- This  role should maybe also be allowed to set the attribute renovation_demand of structure_part

Maybe @kfischerar, @varrieta and @urskaufmann know more who is dealing with what data in which role.

**Comment by sjib** [comment]
I would try to name the roles similar to qwat also - at least the ones that are the same

**Comment by 3nids** [comment]
@sjib 

> I would rather distinguish between additional rights to view VSA-KEK or to manage VSA-KEK 

yes, that is the idea behind the proposed repartition

The question can be summarized as:
* the easy solution: all od tables in the same schema with the same rights
* separate network/geometry table from inspection/management (KEK) tables in 2 distinct schemas but then deal with column specific rights such as renovation_demand of structure_part, as you pointed.

**Comment by vpicavet** [comment]
Hi, @sjib and @3nids : is there still something blocking on this subject ? Can we go ahead ? We have time constraints now on some prototype where this issue is crucial.

**Comment by urskaufmann** [comment]
I have no experience with multi-roles. The easy solution (all od tables in the same schema with the same rights) is ok for me.

**Comment by 3nids** [comment]
ok, I'd say let's go down this route first then (which is roughly the same as qwat).
If there is a need for a finer grain later on we can still improve this.

If there is no objection, I will:

1. update the creation scripts (waiting for a further rewrite from @sjib )
2. create the roles
3. creation a migration script
4. update the project

**Comment by 3nids** [comment]
pull request for part 1: https://github.com/QGEP/datamodel/pull/61

**Comment by varrieta** [comment]
For now on I had to use only two different roles: r or r/w. 
Ok for me to define the schemas as in QWAT

**Comment by haubourg** [comment]
Hi, @elemoine and I tested the dispatch script on our side. 
It works correctly, though Eric found some potential issues. Latest PR  https://github.com/QGEP/datamodel/pull/64 submits fixes for that. 

As QGEP datamodel is not really semantically versionned, we did test only one source datamodel.

**Comment by 3nids** [comment]
thanks for the patch, it's merged

**Comment by haubourg** [comment]
Hi @3nids,  qgep-bot have failing travis processes wth the most recent changes.
Any idea of what's failing?

**Comment by haubourg** [comment]
Yes sorry, 
here in QGEP repo: https://github.com/QGEP/QGEP/pulls
you have many "Datamodel update" PR's made by qgep-bot failing.

**Comment by haubourg** [comment]
And the error seems related to the new schemas: 
`````
$ pip install psycopg2 --quiet
install.2
6.69s$ pip install pyyaml --quiet
before_script.1
0.00s$ printf "[pg_qgep]\nhost=localhost\ndbname=qgep\nuser=postgres" > ~/.pg_service.conf
before_script.2
0.22s$ psql -c 'CREATE DATABASE qgep;' -U postgres
CREATE DATABASE
before_script.3
0.82s$ psql -c 'CREATE EXTENSION postgis;' -U postgres -d qgep
CREATE EXTENSION
before_script.4
0.04s$ psql -c 'CREATE EXTENSION hstore;' -U postgres -d qgep
CREATE EXTENSION
before_script.5
2.05s$ pg_restore -O -d qgep data/testdata.dump
before_script.6
2.97s$ $TRAVIS_BUILD_DIR/datamodel/scripts/db_setup.sh &>/dev/null
0.02s$ $TRAVIS_BUILD_DIR/scripts/migrate.sh
ERROR:  relation "qgep.is_oid_prefixes" does not exist
LINE 1: UPDATE qgep.is_oid_prefixes SET active=TRUE WHERE prefix='ch...
               ^
`````

**Comment by 3nids** [comment]
we have to do the migration on the demo data. Do you want me to do it?

**Comment by sjib** [comment]
Yes please do
-- 
Diese Nachricht wurde von meinem Android Mobiltelefon mit GMX Mail gesendet.Am 13.02.18, 19:38, Denis Rouzaud <notifications@github.com> schrieb:
we have to do the migration on the demo data. Do you want me to do it?

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/QGEP/QGEP","title":"QGEP/QGEP","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/QGEP/QGEP"}},"updates":{"snippets":[{"icon":"PERSON","message":"@3nids in #391: we have to do the migration on the demo data. Do you want me to do it?\r\n"}],"action":{"name":"View Issue","url":"https://github.com/QGEP/QGEP/issues/391#issuecomment-365362071"}}}
