### ISSUE TITLE
Linking picture not working on newly created reaches

### ISSUE THREAD

**Issue by varrieta** [QGEP/QGEP#392]
When you digitize a new reach, you can't directly link a picture to it, the link get lost when you validate the formular. You then have to re-open the formular of the reach and link the picture. 

It might be because the relation is done with ws_obj_id as the referenced field.

**Comment by max-trolliet** [comment]
I'm working on it with od_file and vw_file. It should be linked to #369

**Comment by varrieta** [comment]
Duplicate of #369

**Comment by varrieta** [comment]
@m-kuhn @sjib Priority 2019 Bugfix

**Comment by m-kuhn** [comment]
TODO:

Check the default value definition of the base view (wastewater structure / reach)

**Comment by m-kuhn** [comment]
On first sight, the default value is there. Might be a "filter" on object type issue. To be investigated in more detail.

**Comment by ponceta** [comment]
https://github.com/QGEP/QGEP/commit/de16c920ea7d26effed7ba5da742e7bcab38271f Should fix the problem. @varrieta Try, assess and close issue?
