### ISSUE TITLE
Linking several structure to a maintenance event in one shot

### ISSUE THREAD

**Issue by varrieta** [QGEP/QGEP#400]
Is it possible to select several structures and link them to a maintenance event ??

**Comment by varrieta** [comment]
I created an action that gives the user the possibility to create a maintenance event and link it to selected structures on the map.

The code seems to work well but when I try to add the relation into the re_maintenance_event_wastewater_structure layer I get an error saying: 

> Couche re_maintenance_event_wastewater_structure: Erreur PostGIS lors de l'ajout d'entité: ERREUR: valeur trop longue pour le type character varying(16)

But the value I try to insert are the wastewater_structure_id and maintenance_event_id, so there shouldn't be a problem there.

Any ideas? @m-kuhn @3nids @ponceta

Here is the code: 

```
from qgis.utils import iface

#Add n:m relation
#Create a new maintenance event and link it to the selected features

#Define layers
maintenance_lyr = QgsMapLayerRegistry.instance().mapLayer('od_maintenance_event20180212171049766')
relation_lyr = QgsMapLayerRegistry.instance().mapLayer('re_maintenance_event_wastewater_structure')
structure_lyr = QgsMapLayerRegistry.instance().mapLayer('vw_last_cleaning_event20180209144355613')

#Define a function that add a relation in the relation layer
def addrelation(fId):
    
    #get maintenance event feature attributes
    iterator = maintenance_lyr.getFeatures(QgsFeatureRequest().setFilterFid(fId))
    maintenance_f = next(iterator)
    maintenance_a = []
    maintenance_a = maintenance_f.attributes()
    
    #get the selected features in structure layer and loop over selected features
    selected_f = [ ]
    selected_f = structure_lyr.selectedFeatures()
    for structure_f in selected_f:
        #get selected structure attributes
        structure_a = []
        structure_a = structure_f.attributes()
        
        #Add relation between maintenance event and structure
        #declare fields then create the feature and add it
        with edit(relation_lyr):
            fields = relation_lyr.pendingFields()
            new_feat = QgsFeature(fields)
            new_feat[1] = structure_a[0]
            new_feat[2] = maintenance_a[0]
            
            relation_lyr.addFeatures([new_feat])
    
#Add new maintenance event
if not maintenance_lyr.isEditable():
    iface.actionToggleEditing().trigger()
maintenance_lyr.startEditing()
iface.setActiveLayer(maintenance_lyr)
iface.actionAddFeature().trigger()
 
# Run the function that add the relation
iface.activeLayer().featureAdded.connect(addrelation)
```

**Comment by sjib** [comment]
May be the additional obj_id makes troubles
https://github.com/QGEP/datamodel/blob/74c65a844fb005a599eeb8ee91db381bf282cd9d/03_qgep_db_dss.sql#L53

May be re_maintenance_event would not need an obj_id

**Comment by varrieta** [comment]
From the database structure, re_maintenance_event is related to od_maintenance_event.obj_id so I don't think it is the problem.

**Comment by varrieta** [comment]
The problem comes from the re_maintenance_event_wastewater_structure.obj_id that doesn't get generated by the sequence. Strange since it should be NULL

**Comment by varrieta** [comment]
It works now, maybe it could be implemented in the demo projet during codesprint2

**Comment by varrieta** [comment]
- Long term solution: a qgis tools will be developped by Oslandia, sponsored by QWAT. Release might be QGIS 3.12.

- Short term solution: button in plugin

**Comment by ponceta** [comment]
@varrieta @m-kuhn 

I can now tell you that it is now possible to add/remove a filtered set of features using qgis standard relation tools. (QGIS 3.12.X and later)

A possible use case:

1. Select entities you want to link to a parent
2. Open the parent form and go to the relationnal widget and click `edit` 
![image](https://user-images.githubusercontent.com/8614223/80377263-54aaa780-889b-11ea-9384-fa1ac6e9e224.png)
 followed by `link child features`
![image](https://user-images.githubusercontent.com/8614223/80377303-64c28700-889b-11ea-926a-32a02e1888cb.png)
3. filter only selected entities and click OK.

Otherwise, you can filter and select entites at step 3. instead of 1.

![image](https://user-images.githubusercontent.com/8614223/80377042-fe3d6900-889a-11ea-8aa6-3b0b99235542.png)

**Comment by ponceta** [comment]
https://changelog.qgis.org/en/qgis/version/3.12/#improve-feature-selection-dialog
