### ISSUE TITLE
Maintenance in vw_qgep_ws is missing

### ISSUE THREAD

**Issue by max-trolliet** [QGEP/QGEP#402]
Hi,

I just realized that the subform for maintenance is missing in the project. Is it something that occured to you as well? Need to correct that for the project ? 
![image](https://user-images.githubusercontent.com/13679128/35976714-458a3492-0ce1-11e8-89dc-ccf549810097.png)

**Comment by urskaufmann** [comment]
It is fixed.  
But if you have a multi-selection of reaches or wastewater_structures, it shows just the related events from one record. And if you try multi-editing, then the tabs with relations are empty.  I think this is a QGIS limitation.  
Hope that this limitation can be removed in the future... (P2?)

**Comment by m-kuhn** [comment]
Ok, I'll close this issue in this case.
Can you open a new, clean one @urskaufmann ?
