### ISSUE TITLE
Project does'nt match demodata

### ISSUE THREAD

**Issue by lbartoletti** [QGEP/QGEP#407]
Downloading demodata, if you restore the backup and use the project, project cry because can't find layers.

Seems project use new API and demodata still with olda API.

**Comment by sjib** [comment]
@3nids Can you look into this?

**Comment by sjib** [comment]
@lbartoletti see also https://github.com/QGEP/QGEP/issues/390

**Comment by ponceta** [comment]
@lbartoletti @3nids linked to the dispatch into new schemas?

**Comment by lbartoletti** [comment]
@ponceta Yes.

**Comment by ponceta** [comment]
https://github.com/QGEP/QGEP/issues/391

**Comment by m-kuhn** [comment]
@3nids did you already put work into this?

**Comment by 3nids** [comment]
this should be fixed now

**Comment by lbartoletti** [comment]
Thank you @3nids 

Only one warning at startup
![image](https://user-images.githubusercontent.com/7521540/39596433-a1e232bc-4f12-11e8-9553-eb2aa585d6ce.png)

But I think it's related to #334 (qgep_v1.0.1_data_and_structure_sample.backup was used to test the new project).

**Comment by urskaufmann** [comment]
In my opinion, the new view-fieldnames are not corrected in the actual project. So the stiles and the input-forms don't work as they should.

**Comment by m-kuhn** [comment]
@3nids do you think this can be done automated or do we need some manual work here?

**Comment by 3nids** [comment]
@ponceta @urskaufmann 
I will take care next week of fixing the project to the new datamodel (concentrating this week on QGIS before feature freeze for 3.2)
