### ISSUE TITLE
Translation of project file

### ISSUE THREAD

**Issue by sjib** [QGEP/QGEP#408]

**Comment by ponceta** [comment]
I would wait for QGIS CH User group Multilingual project files

![image](https://user-images.githubusercontent.com/8614223/38678179-999a7c9e-3e60-11e8-80f2-e2c8035f14a3.png)

**Comment by sjib** [comment]
@m-kuhn How far develped is this? https://github.com/qgis/QGIS-Enhancement-Proposals/issues/90

**Comment by sjib** [comment]
Does this also supports publication of data in other languages e.g. in a Webviewer?

**Comment by m-kuhn** [comment]
> Does this also supports publication of data in other languages e.g. in a Webviewer?

Not without additional development effort, but on QGIS server this should be a small overhead.

> @m-kuhn How far develped is this? qgis/QGIS-Enhancement-Proposals#90

CC @signedav

**Comment by signedav** [comment]
It's in development. Basics like creation of ts file and translation of layername, fieldaliases etc. are done, but it needs more integration before I'll  make a Pull Request.

**Comment by sjib** [comment]
@signedav Any updates on this issue?

**Comment by signedav** [comment]
Oh yes. See here we published a small description of that feature https://opengis.ch/de/2018/09/11/qgis-speaks-a-lot-of-languages/

**Comment by m-kuhn** [comment]
See also https://github.com/QGEP/QGEP/releases/tag/v6.2

**Comment by haubourg** [comment]
Hi there. Are there any guidelines somewhere from the translation teams? I wanted to help in QGEP to French area. I see that we have no space, accent or Title case in the translated string. Is this on purpose to help with exporting to our � shapefile ?
Should we add some guidelines in transifex or in the wiki?

**Comment by sjib** [comment]
@haubourg Please connect with @m-kuhn and Daniel Hollenweger (Triform) - they worked on this

**Comment by haubourg** [comment]
@sjib  Thanks for the pointer Stefan.

**Comment by m-kuhn** [comment]
@haubourg shapefile is not of concern, if anything, it's more the writing expressions part where we are slightly worried about introducing non ascii chars.

**Comment by haubourg** [comment]
@m-kuhn ok, then you confirm staying to lowercase, ascii and no space is on purpose then. Thanks. Given the state of the feature, I think it would be worth testing full UTF8 and then test if with miss some `"` in the expressions. Do you expect any other type of failure with expressions?

**Comment by m-kuhn** [comment]
I am confident that we don't hit any issues with expressions we deliver. I am more worried about expressions being written by end users
