### ISSUE TITLE
Database response mechanism / Transactions

### ISSUE THREAD

**Issue by andreasneumann** [QGEP/QGEP#41]
Key part to implement edition of the data. Implementations for manhole, reach and special structure. Should be one the first/next things to implement.

**Comment by m-kuhn** [comment]
Implemented upstream

**Comment by m-kuhn** [comment]
*Status (QGIS 2.10)*

 * A transaction can be started
 * Native (postgres) SQL can be sent directly
 * Layers can be added
 * Layer changes will be sent through the transaction
 * Transactions can be commited and rolled back

*Problems*

 * A layer which is in a transaction still needs to be manually set into edit mode. Instead, any layer in a transaction should be automatically set to edit mode
 * If a feature gets added (via postgis provider, not native SQL) we need to find a way to receive its database-generated attributes for immediate actions.

**Comment by m-kuhn** [comment]
Fixed upstream
