### ISSUE TITLE
QGEP Releases / Releases Manager / Changelog

### ISSUE THREAD

**Issue by ponceta** [QGEP/QGEP#413]
With the new pum tool comes the changelog and release mechanic to be set.

For that we need a release manager who assess release tag and list bugfixes and devs from version to version.

Ping @3nids @m-kuhn @haubourg @tudorbarascu @andreasneumann @urskaufmann @max-trolliet @varrieta @sjib @kfischerar @vpicavet @elemoine 

What we want to achieve:
https://github.com/qwat/qwat-data-model/releases

Both release managers for qwat and qgep should be able to discuss frequently to achieve logical decisions in terms of network management in QGIS.

**Comment by m-kuhn** [comment]
@3nids has recently been working on this and put this into place for the data model at https://github.com/QGEP/datamodel/releases

It's integrated with PUM and release notes /changelog are available, infrastructure wise we should be ready. There will be an announcement as soon as https://github.com/QGEP/datamodel/pull/68 is merged

This leaves the question about the release manager and role definition. I think it would make sense to have someone with broad postgres knowledge as well as pum experience, expert knowledge about (water) network management and contact to the qwat group.

**Comment by ponceta** [comment]
Since we now have https://github.com/QGEP/datamodel/releases I suggest to close this. If the use of a nominated Release manager is required, feel free to reopen this.
