### ISSUE TITLE
the option to initialize a database with roles is not documented

### ISSUE THREAD

**Issue by haubourg** [QGEP/QGEP#417]
Hi, 
I just realized that when using db_setup.sh, I had no role created even if the PR adding role management was tested and merged. 
Then I discovered PR https://github.com/QGEP/datamodel/pull/62  that adds an option to enable role creation. 
This needs to be documented, many users may miss that feature.

**Comment by 3nids** [comment]
moved to proper repo 
https://github.com/QGEP/docs/issues/56
