### ISSUE TITLE
Cleanup old scripts in QGEP/scripts

### ISSUE THREAD

**Issue by haubourg** [QGEP/QGEP#419]
Hi, I realize we have script duplication between QGEP/scripts and QGEP/datamodel/script submodule. 

We need to get rid of the QGEP/scripts that are 3 years old . They are of course broken and causing confusion for users just not lauching the right scripts

**Comment by haubourg** [comment]
And I'm confused, `table_dispatch.sh` is older in datamodel submodule that in QGEP repo. 
@3nids can you clarify this?

**Comment by 3nids** [comment]
in QGEP it was the script for the project, in datamodel for the.... datamodel ;)

**Comment by 3nids** [comment]
I removed the 2 scripts which were causing confusion.
I think the others are doing no harm at the moment.
OK to close?
