### ISSUE TITLE
Demodata release 1.0.1-5 - restore not working

### ISSUE THREAD

**Issue by sjib** [QGEP/QGEP#421]
I tried to restore qgep_v1.0.1-5_structure_and_demo_data.backup with postgres 10 and pgadmin 4. I can select the file and restore - but then there is nothing in the qgep schema. 
- Which role do I have to select? qgep?
- any other hints

**Comment by 3nids** [comment]
Can you paste here the command that pgadmin runs and the output of it?

**Comment by sjib** [comment]
![postgres10_restore_success2](https://user-images.githubusercontent.com/1265865/41003244-8f7d80f4-6916-11e8-8ecb-0a7ed021dda5.jpg)

**Comment by 3nids** [comment]
no issue here

![image](https://user-images.githubusercontent.com/127259/41040308-0b30a8cc-696a-11e8-97a2-e66e803fb3c8.png)

Tested on PostgreSQL 10.3
The dump is from PG 9.6.8. 

Can you check the version number of PG in the properties of the server:

![image](https://user-images.githubusercontent.com/127259/41040413-56e93a2c-696a-11e8-8bff-3f165db3df9e.png)

**Comment by urskaufmann** [comment]
I tried the qgep_v1.0.1-5_structure_with_value_lists.sql and got this error:
![unbenannt](https://user-images.githubusercontent.com/1257403/41559050-6b6f4b22-7332-11e8-82be-5006384a01c8.PNG)
I tried then also the qgep_v1.0.1-5_structure_and_demo_data.backup and this worked (PostgreSQL 9.4.17, 
Then first the qgep-plugin (0.74) was greyed out and QGIS crashed if I tried to update zu qgep-plugin 0.75. It seems that the update then was done, when I used my database based on the 1.0.1.4 release. And know it works also with the demodata based on release 1.0.1.5

Why I wanted to use the sql: I had in the Database release 1.0.1.4 no records in the qgep_sys-schema. And so you can not add new records (ypu also have to set the rights in the qgep_sys-schema as normal user!).

**Comment by kfischerar** [comment]
I tried to restore the qgep_v1.0.1-5_structure_and_demo_data.backup and
failed (win7, PostgreSQL 9.4.5; PostGIS 2.3.0, pgAdminIII) with:

*C:\Program Files\PostgreSQL\9.4\bin\pg_restore.exe --host localhost --port
5432 --username "postgres" --dbname "test" --no-password  --verbose
"X:\99xx\9925_QGIS_Projekt\daten_von_extern\180619_datamodel\qgep_v1.0.1-5_structure_and_demo_data.backup"*



*pg_restore: [archiver] unsupported version (1.13) in file headerProcess
returned exit code 1.*


then I tried another computer and it worked (win10, PostgreSQL 9.6.9;
PostGIS 2.4.4, pgAdmin4) now i have to learn something about pgAdmin4 ...


2018-06-18 22:11 GMT+02:00 urskaufmann <notifications@github.com>:

**Comment by max-trolliet** [comment]
Is this release needing to be on PostgreSQL 9.6, and if so do we need pgAdmin4? 

This would mean a change in IT infrastructure which might not be as easy for everyone as it seems... mostly for communities having a small IT team which does not know a thing about GIS. For bigger ones it might have to go to "decisions" that can take quite a time...

**Comment by kfischerar** [comment]
if we really need a change: we should think about PostgreSQL 10 ?

**Comment by m-kuhn** [comment]
> You need to upgrade your local postgres to get the last security patch from the 2018-03-01, [...] you need one of the last releases 10.3, 9.6.8, 9.5.12, 9.4.17, and 9.3.22. 

https://stackoverflow.com/a/49064959/2319028

There is no requirement on the pgAdmin version, both pgAdmin 3 and pgAdmin 4 work.

**Comment by kfischerar** [comment]
on win10: if you follow the guide you get pg 9.6.9
pgAdmin3 doesn't support that version ...


2018-06-20 8:00 GMT+02:00 Matthias Kuhn <notifications@github.com>:

**Comment by m-kuhn** [comment]
* Is this a warning or an error? I also get a warning from pgAdmin3 about version support, but it still works.
* Is there a problem with postgres 10?

**Comment by kfischerar** [comment]
it's just a warning
until now i work with 9.6, no experience wit pg 10

2018-06-20 8:11 GMT+02:00 Matthias Kuhn <notifications@github.com>:

**Comment by 3nids** [comment]
just be careful to distinguish the client version from the database version.
and
> If you are using a third-party tool, such as PgAdmin, to restore the provided dump file, the restore may not succeed even with the installed Postgres version being up to date. This is due to third-party tools often bundling their own versions of the pg_restore binary, that may not be up to date.
