### ISSUE TITLE
Four relations have a non declared SRID after QGEP setup 

### ISSUE THREAD

**Issue by haubourg** [QGEP/QGEP#423]
I just ran a 1.0.2 db_setup and realized than 4 geometries in 4 views have no explicit SRID :

-----------------------------------------------------
vw_network_node;detail_geometry
vw_network_segment;progression_geometry
vw_network_segment;detail_geometry
vw_organisation;perimeter_geometry
-----------------------------------------------------

It can be checked with a `select * from public.geometry_columns where srid = 0`

**Comment by haubourg** [comment]
I edited the issue with the relevant column names.

**Comment by ponceta** [comment]
- [X] vw_organisation;perimeter_geometry is OK now.

vw_network_node;detail_geometry
vw_network_segment;progression_geometry
vw_network_segment;detail_geometry

Still SRID less

**Comment by ponceta** [comment]
2019-12-23T09:12:08     WARNING    Le type d'entité ou le srid pour progression_geometry de "qgep_od"."vw_network_segment" n'a pas pu être déterminé. (QGIS Warning)

**Comment by 3nids** [comment]
@ponceta can you try with https://github.com/QGEP/datamodel/pull/124
