### ISSUE TITLE
QGEP Datamodel : How to create a custom field

### ISSUE THREAD

**Issue by ponceta** [QGEP/QGEP#427]
Having a custom field should now be possible using PUM.

For example in Pully we store the bottom_material of a wastewater_structure, when it is different from the wastewater_structure material.

To do this in QWAT (http://qwat.readthedocs.io/en/latest/developer-guide/local_customizations.html), we add a prefix (to identify the customization) before the field name (ex. : pully_bottom_material ) and add it to the corresponding table.

Then we regenerate the edition views and the attribute is automatically added. 

This enables a bit of flexibility to the datamodel without changing it completely to others.

Of course **the first step** is to **ask for** a datamodel change or at least **express** a need and look with others if this need is not required elsewhere (**sharing is the key to success**).

Linked to : https://github.com/QGEP/QGEP/issues/365, https://github.com/QGEP/QGEP/issues/368,

**Comment by sjib** [comment]
also with  #414

**Comment by sjib** [comment]
see comment https://github.com/QGEP/QGEP/issues/365#issuecomment-399991364

**Comment by ponceta** [comment]
**Follow steps linked to :**

https://qgep.github.io/docs/admin-guide/db-customization/index.html

**Example** :

**SQL :**

```
ALTER TABLE qgep_od.wastewater_node
ADD COLUMN pully_bottom_material integer;
```

Move to datamodel directory.

**Recreate views**

`./view/create_views.py --pg_service pg_qgep --srid 2056`
