### ISSUE TITLE
New attribute : bottom_material

### ISSUE THREAD

**Issue by ponceta** [QGEP/QGEP#428]
@sjib Here's what I have in the Topobase datamodel :

"Aucun" -> "none"
"Autre" -> "other"
"Béton" -> "concrete"
"Ciment" -> "cement"
"Inconnu" -> "unknown"
"PVC" -> "plastic"

**Comment by sjib** [comment]
For a "Gelbdruck" it would be nice if the value list matches with other value lists that describe the same material (manhole.material or reach.material). 

 INSERT INTO qgep_sys.dictionary_od_values (class_id, attribute_id, value_id, table_name, field_name, value_name, value_name_en, shortcut_en, value_name_de, shortcut_de, value_name_fr, shortcut_fr, value_name_it, shortcut_it, value_name_ro, shortcut_ro, value_description_en, value_description_de, value_description_fr, value_description_it, value_description_ro) VALUES (31,156,5081,'**reach**','**material**','plastic_PVC','plastic_PVC','PVC','Kunststoff_Polyvinilchlorid','PVC','matiere_synthetique_PVC','PVC','materiale_sintetico_PVC','PVC','plastic_PVC','','yyy_Ein Polymerisatkunstoff, der hart, weich oder niedrig­molekular eingestellt werden kann. In der Abwassertechnik als Rohstoff für Rohre verwendet. (arb)','Ein Polymerisatkunstoff, der hart, weich oder niedrig­molekular eingestellt werden kann. In der Abwassertechnik als Rohstoff für Rohre verwendet. (arb)','polychlorure de vinyle','Policloruro di vinile','');

(45,4539,4541,'**manhole**','**material**','concrete','concrete','','Beton','','beton','','zzz_Beton','','beton','',' ','','','','');
 INSERT INTO qgep_sys.dictionary_od_values (class_id, attribute_id, value_id, table_name, field_name, value_name, value_name_en, shortcut_en, value_name_de, shortcut_de, value_name_fr, shortcut_fr, value_name_it, shortcut_it, value_name_ro, shortcut_ro, value_description_en, value_description_de, value_description_fr, value_description_it, value_description_ro) VALUES (45,4539,4542,'manhole','material','plastic','plastic','','Kunststoff','','matiere_plastique','','zzz_Kunststoff','','materie_plastica','',' ','','','','');
 INSERT INTO qgep_sys.dictionary_od_values (class_id, attribute_id, value_id, table_name, field_name, value_name, value_name_en, shortcut_en, value_name_de, shortcut_de, value_name_fr, shortcut_fr, value_name_it, shortcut_it, value_name_ro, shortcut_ro, value_description_en, value_description_de, value_description_fr, value_description_it, value_description_ro) VALUES (45,4539,4543,'manhole','material','unknown','unknown','','unbekannt','','inconnu','','sconosciuto','','necunoscut','',' ','','','','');
INSERT INTO qgep_sys.dictionary_od_values (class_id, attribute_id, value_id, table_name, field_name, value_name, value_name_en, shortcut_en, value_name_de, shortcut_de, value_name_fr, shortcut_fr, value_name_it, shortcut_it, value_name_ro, shortcut_ro, value_description_en, value_description_de, value_description_fr, value_description_it, value_description_ro) VALUES (45,4539,4540,'manhole','material','other','other','','andere','','autre','','altro','','altul','',' ','','','','');

**Comment by sjib** [comment]
@ponceta What exactly would the bottom material describe differntly to manhole.material? Can you add a sketch file to illustrate?

**Comment by sjib** [comment]
Please reopen if still an issue and explain.
