### ISSUE TITLE
Data model: dataowner and provider

### ISSUE THREAD

**Issue by andreasneumann** [QGEP/QGEP#43]
Almost any od_xx table has the two attributes "dataowner" and "provider". Currently these are only text fields. I think it would be more elegant if these could be relations to the table "od_organisation" - With the current setup there is a lot of duplication and it is harder to update the information of the dataowner and provider.

Any thoughts?

**Comment by m-kuhn** [comment]
Waiting for Interlis Import => then update the model to the newest model by @sjib => then import and migrate and verify

**Comment by m-kuhn** [comment]
Currently there are two fields for each

 * dataowner
 * fk_dataowner

Not sure this is what we want?

**Comment by andreasneumann** [comment]
I believe the VSA-DSS model has the dataowner field as varchar/text, but we discussed that we would prefer the fk_dataowner foreign key to the organization table.

So, we should get rid of the dataowner column and add this to an export view, when we will need the text representation instead of the foreign key.

But the export views are not top priority, currently.

**Comment by sjib** [comment]
Discuss in meeting 19.10.2015 (https://github.com/QGEP/QGEP/wiki/Meeting-2015-10-19)

**Comment by sjib** [comment]
Take out dataowner and dataprovider field in datamodel

**Comment by 3nids** [comment]
@sjib what would be the delay for this?

**Comment by sjib** [comment]
In working on the INTERLIS Export / Import we found out, that it is really challenging, when we always have to link the organization table into all the queries when exporting or importing data. So we think it would be helpful to keep the dataowner / provider as a field that we can fill with the current identifier of the related dataset in organization while exporting or importing and delete it, when we have pre- or postprocessed dataowner and provider an created the necessary fs_* (postprocess while importing) or matched the identifier of organization (preprocess in the export process). 

 

Does this disturbs any other development that you are doing?

**Comment by m-kuhn** [comment]
In this case, wouldn't it be preferable to either create the field at the start / end of an import/export process and delete it in the end?
This way the risk of mistaking this for authoritative data when it is out of sync will be reduced.

**Comment by 3nids** [comment]
@sjib sorry not following, what prevents from using views for export and trigger for import?

**Comment by sjib** [comment]
Adapted in https://raw.githubusercontent.com/QGEP/datamodel Release 26.4.2016
