### ISSUE TITLE
reach_point update from vw_qgep_reach (qgep v1.1.0)

### ISSUE THREAD

**Issue by varrieta** [QGEP/QGEP#435]
Reach_point can't be updated through vw_qgep_reach with qgep V1.1.0. Can anyone confirm that?

I get the following:

> Couche vw_qgep_reach: Erreur PostGIS lors de la modification d'attribut : ERREUR: annulation de la requête à cause du délai écoulé pour l'exécution de l'instruction CONTEXT ...

EDIT:
It does work if you fill the rp information while inserting a new reach

**Comment by haubourg** [comment]
+1 I have that error too

**Comment by 3nids** [comment]
I updated reach points (their identifier) via the view in QGIS and did not encounter any error.
Can you describe the steps to reproduce?

**Comment by urskaufmann** [comment]
I think its the same error as I described in #425. With V1.1.0 and the demodata I can edit a reach, if both reachpoints have a fk_wastewater_networkelement. If there is no fk_wastewater_networkelement, then I get the turning "no response" cursor (keine Rückmeldung) as long as I wait.

Second Problem: Using the qgep_v1.1.0_structure_with_value_lists.sql I get the error below, the qgep_v1.1.0_structure_and_demo_data.backup worked
![error](https://user-images.githubusercontent.com/1257403/42623528-a0c93976-85b2-11e8-9e14-b1cd6105e710.PNG)

**Comment by varrieta** [comment]
@3nids Did the same as you: 

1. Open the form of a reach in vw_qgep_reach
2. Modify the  rp_to.fk_wastewater_networkelement 
3. Clic OK 

I also tried with the connect_element tool but I got the same issue

**Comment by varrieta** [comment]
Fixed by pull request #77
Thanks @3nids
