### ISSUE TITLE
Definition of Stammkarten

### ISSUE THREAD

**Issue by sjib** [QGEP/QGEP#438]
Define necessary data/views for Stammkarten reports based on layout of Wegleitung GEP-Daten

**Comment by kfischerar** [comment]
at the moment i tell evereybody that they should use the vsa-exemple and not invent a new formular... in practice we won't hava data for all fields in the beginning but during working on a gep-project the amount of data will grow

**Comment by sjib** [comment]
Extension of datamodel and functionality: Stammkarten (KF): Basic concept of Stammkarten was discussed and the following steps agreed on: a) model relation of each block of Stammkarten to VSA-DSS and Stammkarten extension (SB), b) Creation of needed queries for each block (xx) c) Creation of Report that uses the various blocks (concept, test Stammkarte) (MK) d) Implementation of all different Stammkarten (KF). SB and KF make quotation for steps until end of January. Then define implementation process.

**Comment by sjib** [comment]
Each log_card consist of various blocks: This is the overview of which information block is needed for each log_card.
![informationsbloecke_pro_stammkarte](https://user-images.githubusercontent.com/1265865/59102657-090ea880-892d-11e9-9d50-f205406e2ac0.jpg)

**Comment by ponceta** [comment]
![image](https://user-images.githubusercontent.com/8614223/63428155-2543c100-c417-11e9-9ebf-e6c388c2246b.png)

@kandre @varrieta in French

**Comment by ponceta** [comment]
After a few tests on the newly developped QGIS reporting module, here are my first comments : 

![image](https://user-images.githubusercontent.com/8614223/63584375-1e46bb00-c59d-11e9-86df-2d3fee46250e.png)

This is very promising but there are some misunderstandings in the translated interface, especially with headers and footers which don't appear on the result pages. Either these are not headers and footers or theres something unclear on how set up sections, groups, headers and footers.

Tested on 3.4.11

**Comment by sjib** [comment]
Should be followed up with tww developments: https://github.com/teksi/wastewater/discussions/240

**Comment by ponceta** [comment]
Will therefore not be implemented QGEP side.

**Comment by sjib** [comment]
Yes
