### ISSUE TITLE
Problem installing datamodel 1.1.1

### ISSUE THREAD

**Issue by urskaufmann** [QGEP/QGEP#442]
I could not restore the 1.1.1 demodata with the structure_and_demo_data.backup  until I have created a new database named qgep-prod!

-> update of documentation needed or at least a short hint in the releases

I have also an error if I execute the structure_with_value_lists.sql:
FEHLER:  Syntaxfehler bei »1«
LINE 24956: 1 1001 3432 dryweather_downspout diameter diameter Durchmess...
            ^
********** Error **********

FEHLER: Syntaxfehler bei »1«
SQL state: 42601
Character: 900894

**Comment by 3nids** [comment]
Have you created the posgtis and hstore extensions on the newly created DB?
Can you give more info on output when you try to restore the backup?

**Comment by urskaufmann** [comment]
Yes, I have. Hope these files help:
![1newdb](https://user-images.githubusercontent.com/1257403/44334197-27c0b300-a471-11e8-9406-a570b8d49da0.PNG)
![2restore1](https://user-images.githubusercontent.com/1257403/44334206-30b18480-a471-11e8-9d7e-db63df716931.PNG)
![3restore2](https://user-images.githubusercontent.com/1257403/44334214-36a76580-a471-11e8-84f3-48a68082308d.PNG)
[message.txt](https://github.com/QGEP/QGEP/files/2301977/message.txt)

**Comment by 3nids** [comment]
I think this is an expected output, there are some issues with restoring materialized views.
Can you try `REFRESH MATERIALIZED VIEW qgep_od.vw_network_segment;` after this process and let me know if it works.
If yes, that means the whole restore went fine.

We have some ideas on how to solve this, but this will require some funding.

**Comment by urskaufmann** [comment]
In my first comment I wrote about a database named qgep-prod. Correct is qgep_prod. With qgep_prod, I could install the demo-data and had therefor the new structure.

After the message I send you above, there is no schema in the database, so I can refresh nothing.
After installing in qgep_prod, I have of course made this refresh materialized view and the properties of all three qgep-schemas and then it works with the project.

**Comment by 3nids** [comment]
We now require PG 9.6+ for the backup which is the preferred approach.

For older version, you might want to try the plain SQL files.

**Comment by kfischerar** [comment]
win10, PG 9.6.9, pgAdmin 4.3.2 --> import qgep_v1.1.1 ....backup worked
with schema qgep_prod

Am Mo., 20. Aug. 2018 um 17:27 Uhr schrieb Denis Rouzaud <
notifications@github.com>:

**Comment by sjib** [comment]
Is it database qgep_prod AND schema qgep_prod?

**Comment by urskaufmann** [comment]
database qgep_prod. You have not to create any schema.

**Comment by sjib** [comment]
Import successfull in Database qgep_prod (not schema - Thanks @urskaufmann )
Tables and views were created. Log has the following errors - see next post:

**Comment by sjib** [comment]
a) pg_restore: [Archivierer (DB)] Fehler in Phase PROCESSING TOC:
pg_restore: [Archivierer (DB)] Fehler in Inhaltsverzeichniseintrag 7173; 1262 18010 DATABASE qgep_prod postgres
pg_restore: [Archivierer (DB)] could not execute query: FEHLER:  ungültiger Locale-Name: »en_US.UTF-8«
    Die Anweisung war: CREATE DATABASE qgep_prod WITH TEMPLATE = template0 ENCODING = 'UTF8' LC_COLLATE = 'en_US.UTF-8' LC_CTYPE = 'en_US.UTF-8';

**Comment by sjib** [comment]
b) pg_restore: [Archivierer (DB)] Fehler in Inhaltsverzeichniseintrag 7165; 0 41575 MATERIALIZED VIEW DATA vw_network_segment postgres

    Die Anweisung war: REFRESH MATERIALIZED VIEW qgep_od.vw_network_segment;

**Comment by sjib** [comment]
c) pg_restore: [Archivierer (DB)] could not execute query: FEHLER:  Funktion st_curvetoline(public.geometry, integer) existiert nicht
ZEILE 1: SELECT ST_CurveToLine($1, 32::integer)
                ^
TIP:  Keine Funktion stimmt mit dem angegebenen Namen und den Argumenttypen überein. Sie müssen möglicherweise ausdrückliche Typumwandlungen hinzufügen.
ANFRAGE:  SELECT ST_CurveToLine($1, 32::integer)
KONTEXT:  SQL-Funktion »st_curvetoline« beim Inlining

**Comment by sjib** [comment]
To which schemas do I have to grant privileges? (https://qgep.github.io/docs/installation-guide/database-initialization.html#restore-demo-datamodel): Are these two steps (privileges and grant wizard)? Or is this the same?

Update privileges for the database

    Right click the qgep schema
    Properties -> Privileges Tab > Grant USAGE to group qgep. You can also do this as a query: GRANT USAGE ON SCHEMA qgep TO GROUP qgep;
    Click Grant Wizard …
    Selection, click Check All
    Privileges
        Group qgep
        Choose ALL

**Comment by urskaufmann** [comment]
qgep_od, qgep_vl, qgep_sys
because you write to all of them

**Comment by sjib** [comment]
And second step for privileges:
GRANT ALL ON schema qgep_od TO postgres;
GRANT ALL ON schema qgep_sys TO postgres;
GRANT ALL ON schema qgep_vl TO postgres;

**Comment by schoeller** [comment]
I tried on Win10, Postgres 9.6.10, Postgis 2.4 the following

```
createdb.exe -U postgres qgep_test
psql.exe -U postgres qgep_test
CREATE EXTENSION hstore;
CREATE EXTENSION postgis;
psql.exe -U postgres -d qgep_test -1 -f .\qgep_v1.1.1_structure.sql

```
I do not receive any error messages. When dropping a previously created qgep_prod database and doing

```
createdb.exe -U postgres qgep_prod
psql.exe -U postgres qgep_prod
CREATE EXTENSION hstore;
CREATE EXTENSION postgis;
pg_restore.exe -U postgres -d qgep_prod -1 .\qgep_v1.1.1_structure_and_demo_data.backup
```

I receive the error

```
pg_restore: [Archivierer (DB)] Fehler in Phase PROCESSING TOC:
pg_restore: [Archivierer (DB)] Fehler in Inhaltsverzeichniseintrag 7165; 0 41575 MATERIALIZED VIEW DATA vw_network_segment postgres
pg_restore: [Archivierer (DB)] could not execute query: FEHLER:  Funktion st_curvetoline(public.geometry, integer) existiert nicht
ZEILE 1: SELECT ST_CurveToLine($1, 32::integer)
                ^
TIP:  Keine Funktion stimmt mit dem angegebenen Namen und den Argumenttypen Ã¼berein. Sie mÃ¼ssen mÃ¶glicherweise ausdrÃ¼ckliche Typumwandlungen hinzufÃ¼gen.
ANFRAGE:  SELECT ST_CurveToLine($1, 32::integer)
KONTEXT:  SQL-Funktion Â»st_curvetolineÂ« beim Inlining
    Die Anweisung war: REFRESH MATERIALIZED VIEW qgep_od.vw_network_segment;
```

**Comment by sjib** [comment]
@schoeller Das ist im Moment so. Wenn die Tabellen erzeugt werden und Sie Daten drin haben, dann sind Sie soweit, wie man im Moment kommen kann. 

Lassen Sie die fehlende MATERIALIZED VIEW manuell nochmals laufen, siehe Issue #409 und ersetzen Sie die Variable :SRID durch 2056 (für das neue Schweizer Koordinatensystem) 
Um das Projekt zu öffnen holen Sie sich das Projektfile von hier: https://github.com/QGEP/QGEP/blob/master/project/qgep_en.qgs

**Comment by sjib** [comment]
@3nids What about 
pg_restore: [Archivierer (DB)] could not execute query: FEHLER:  Funktion st_curvetoline(public.geometry, integer) existiert nicht
ZEILE 1: SELECT ST_CurveToLine($1, 32::integer)
                ^
TIP:  Keine Funktion stimmt mit dem angegebenen Namen und den Argumenttypen Ã¼berein. Sie mÃ¼ssen mÃ¶glicherweise ausdrÃ¼ckliche Typumwandlungen hinzufÃ¼gen.
ANFRAGE:  SELECT ST_CurveToLine($1, 32::integer)
KONTEXT:  SQL-Funktion Â»st_curvetolineÂ« beim Inlining

https://postgis.net/docs/ST_CurveToLine.html

**Comment by 3nids** [comment]
@sjib do you have the complete log?

**Comment by sjib** [comment]
[backup1.1.1_restore_log.txt](https://github.com/QGEP/QGEP/files/2460987/backup1.1.1_restore_log.txt)
![backup1 1 1_restore_qgep_prod3_st_curve](https://user-images.githubusercontent.com/1265865/46678963-2cd6ee80-cbe6-11e8-95ac-766e6790e770.jpg)
![backup1 1 1_restore_qgep_prod2_materialized_view](https://user-images.githubusercontent.com/1265865/46678964-2cd6ee80-cbe6-11e8-8f85-a7c472a801f0.jpg)
![backup1 1 1_restore_qgep_prod1](https://user-images.githubusercontent.com/1265865/46678965-2cd6ee80-cbe6-11e8-91e8-024f2c2b50c5.jpg)
![backup1 1 1_restore_qgep_prod](https://user-images.githubusercontent.com/1265865/46678966-2d6f8500-cbe6-11e8-9b7e-1bd377d54f51.jpg)

**Comment by sjib** [comment]
@3nids Does this help?

**Comment by sjib** [comment]
Yes, I have data.

**Comment by m-kuhn** [comment]
Closing for now as the issue seems to be related to postgres version

@urskaufmann will update the database server and then comment if there is still an issue

**Comment by urskaufmann** [comment]
@kfischerar  told me, that he has the same problem with postgres 11. I tried out on mac os with postgres 10 and had the same error message as described in my first post.  @kfischerar could install with the sql, when using a bat-file and not with opening and running the sql-file in the pgadmin.
I can install now (even with postgres 9.4) with this bat-file, that generates the db and installs the sql:

rem bat and sql in the same directory

set db=qgep-test
set PATH=%PATH%;C:\Program Files\PostgreSQL\9.4\bin
rem set PGPASSWORD=ourPWD for userPostgres

createdb -U postgres %db%
CREATE EXTENSION hstore;
CREATE EXTENSION postgis;
psql -U postgres -h localhost -d %db% -f qgep_v1.2.0_structure_with_value_lists.sql
PAUSE

to do: update of the documentation, chapter Database Initalisation
