### ISSUE TITLE
Reaches: pipe_profile widget Value relation vs. Relation reference

### ISSUE THREAD

**Issue by tudorbarascu** [QGEP/QGEP#448]
Hi,

Is there a reason why the reaches ``fk_pipe_profile`` widget has the ``relation reference`` type and not a ``value relation`` one?
I am just wondering if there's something I'm missing as it looks it's being used as a simple value relation.
So, why the complexity?

Thank you!

**Comment by m-kuhn** [comment]
IIRC because it allows adding new profiles directly from there.

**Comment by tudorbarascu** [comment]
@m-kuhn Thank you! Then I guess enabling it in the demo project would be good, right?

**Comment by m-kuhn** [comment]
Enabling what, the add feature property?
If yes, feel free to make a PR.

**Comment by m-kuhn** [comment]
:)
