### ISSUE TITLE
Manhole or Special structure?

### ISSUE THREAD

**Issue by ponceta** [QGEP/QGEP#453]
What and where can I find special wastewater structure definition? And difference between manhole and special wastewater structure?

It is not obvious for me and it seems that two wastewater structures can have same function but different type which is pretty dangerous if users are not well aware of what goes where.

![image](https://user-images.githubusercontent.com/8614223/46739466-e397a500-cca0-11e8-945f-33b2e4326c54.png)

**Comment by urskaufmann** [comment]
Look at the VSA - Glossar: Ouvrage_special and chambre standard:
https://www.vsa.ch/nc/fr/glossaire/fr/terms/both/147/
https://www.vsa.ch/nc/fr/glossaire/fr/terms/both/136/

**Comment by sjib** [comment]
In the German definition there is an additonal important info:
Modelldefinition

Der Normschacht (manhole) ist die Verbindung mit einfacher Geometrie (Schacht mit Kreis- oder Ellipsenprofil) zweier Kanäle. Im Gegensatz zu [Spezialbauwerk](https://www.vsa.ch/nc/glossar/term/Spezialbauwerk/).
Objekte der Klasse Normschacht werden über das Attribut Funktion weiter spezifiziert. Wertebereich siehe Datenmodell VSA-DSS.

**Comment by sjib** [comment]
A manhole is a "normed" wastewater structure, a special structure is NOT normed (and often needs a detailed geometry to be described). In contrary a manhole can be descriebed with dimension1 and 2.

**Comment by sjib** [comment]
All those definitions you can also find in the metainformation tables of QGEP. Or check the VSA-SDEE Objectcatalogues of the [VSA-SDEE Norm](https://www.vsa.ch/fr/publications/shop/produkt/structure-des-donnees-dans-levacuation-des-eaux-des-agglomerations-vsa-sdee/)  (you can get it in the VSA-Shop)

**Comment by ponceta** [comment]
Thanks for the explanations and refs!

This means that on the left side `rail_track_gully`, `slurry_collector`, `gully` and `rain_water_manhole` are always or at least most of the time characterized as "normed" wastewater structures?

And on the right side `bolders_bedload_catchement_dam`, `side_access`, `cesspit`, ... are always or at least most of the time characterized as "not normed" wastewater structures?

And in the middle we have wastewater stuctures which can be either one or the other like `manhole`, `oil_separator`, `stormwater_overflow`, ...
