### ISSUE TITLE
Error when digitize a detailed geometry

### ISSUE THREAD

**Issue by urskaufmann** [QGEP/QGEP#454]
Get this error when chosing digitize in the contextmenu of a wastewater structure

![image](https://user-images.githubusercontent.com/1257403/46764087-caf8b080-ccdb-11e8-8098-5f8c5a554a1e.png)

**Comment by ponceta** [comment]
Replace :

```
ws_lyr = QgsMapLayerRegistry.instance().mapLayer('od_wastewater_structure')
feature = ws_lyr.getFeatures( QgsFeatureRequest().setFilterExpression( 'obj_id = \'{}\''.format( '[% "obj_id" %]' ) ) ).next()
ws_lyr.startEditing()
ws_lyr.setSelectedFeatures([feature.id()])
qgis.utils.iface.setActiveLayer(ws_lyr)
qgis.utils.iface.actionAddPart().trigger()

```

with:

```
ws_lyr = QgsProject.instance().mapLayer('od_wastewater_structure')
feature = next(ws_lyr.getFeatures( QgsFeatureRequest().setFilterExpression( 'obj_id = \'{}\''.format( '[% "obj_id" %]' ) ) ))
ws_lyr.startEditing()
ws_lyr.selectByIds([feature.id()])
qgis.utils.iface.setActiveLayer(ws_lyr)
qgis.utils.iface.actionAddPart().trigger()
```

**Comment by m-kuhn** [comment]
Can you revert the last line and post the python error you get?

**Comment by ponceta** [comment]
import qgepplugin 

feature = next(QgsProject.instance().mapLayer('od_wastewater_structure').getFeatures(QgsFeatureRequest().setFilterExpression( 'obj_id = \'{}\''.format( 'ch176dc9WS016892' ) ) )) 
qgepplugin.ui.forms.digitizeDrainageChannel(feature.id(), 'od_wastewater_structure')

Traceback (most recent call last):
  File "", line 4, in 
AttributeError: module 'qgepplugin.ui' has no attribute 'forms'

**Comment by m-kuhn** [comment]
Does this work?

`qgepplugin.gui.forms.digitizeDrainageChannel(feature.id(), 'od_wastewater_structure')`

**Comment by ponceta** [comment]
```
import qgepplugin 

feature = next(QgsProject.instance().mapLayer('od_wastewater_structure').getFeatures(QgsFeatureRequest().setFilterExpression( 'obj_id = \'{}\''.format( 'ch176dc9WS021255' ) ) )) 
qgepplugin.gui.forms.digitizeDrainageChannel(feature.id(), 'od_wastewater_structure') 

Traceback (most recent call last):
  File "", line 4, in 
AttributeError: module 'qgepplugin.gui' has no attribute 'forms'
```

**Comment by urskaufmann** [comment]
@sjib @m-kuhn Priority 2019 Bugfix

**Comment by ponceta** [comment]
@sjib @m-kuhn Priority 2019 Bugfix

**Comment by ponceta** [comment]
Flag for codesprint?
