### ISSUE TITLE
qgep_import.vw_manhole

### ISSUE THREAD

**Issue by varrieta** [QGEP/QGEP#455]
In qgep_import.vw_manhole: 
inlet/outlet_#_clear_hight should be an integer instead of numeric(6.3) and inlet/outlet_#_depth_m numeric(7,3) instead if numeric(6,3).

**Comment by signedav** [comment]
Thanks for that @varrieta - I will care about.

**Comment by m-kuhn** [comment]
Fixed in https://github.com/QGEP/datamodel/pull/85 ?

**Comment by signedav** [comment]
Yes

**Comment by m-kuhn** [comment]
Thanks.

FYI, you can also auto-close issues in other repos with

```
Fix https://github.com/QGEP/QGEP/issues/455
```
