### ISSUE TITLE
Function UPDATE qgep_od.wastewater_structure crashes if there is no cover

### ISSUE THREAD

**Issue by sjib** [QGEP/QGEP#457]
The function UPDATE qgep_od.wastewater_structure of https://github.com/QGEP/datamodel/blob/master/06_symbology_functions.sql crashes, if there is no related cover in fk_main_cover. This can happen when data is imported e.g. from INTERLIS.:

> ERROR:  FEHLER:  Einfügen oder Aktualisieren in Tabelle »wastewater_structure« verletzt Fremdschlüssel-Constraint »rel_wastewater_structure_cover«
> DETAIL:  Schlüssel (fk_main_cover)=(ch13p7mzCO001707) ist nicht in Tabelle »cover« vorhanden.
> CONTEXT:  SQL-Anweisung »UPDATE qgep_od.wastewater_structure ws
>   SET _depth = depth
>   FROM (
>     SELECT WS.obj_id, CO.level - COALESCE(MIN(NO.bottom_level), MIN(RP.level)) as depth
>       FROM qgep_od.wastewater_structure WS
>       LEFT JOIN qgep_od.cover CO on WS.fk_main_cover = CO.obj_id
>       LEFT JOIN qgep_od.wastewater_networkelement NE ON NE.fk_wastewater_structure = WS.obj_id
>       RIGHT JOIN qgep_od.wastewater_node NO on NO.obj_id = NE.obj_id
>       LEFT JOIN qgep_od.reach_point RP ON RP.fk_wastewater_networkelement = NE.obj_id
>       WHERE _all OR WS.obj_id = _obj_id
>       GROUP BY WS.obj_id, CO.level
>   ) ws_depths
>   where ws.obj_id = ws_depths.obj_id«
> PL/pgSQL-Funktion qgep_od.update_depth(text,boolean) Zeile 6 bei SQL-Anweisung
> PL/pgSQL-Funktion qgep_od.on_cover_change() Zeile 20 bei EXECUTE
> 
> 
> SQL state: 23503

Check whether Function could be improved to avoid crash in this case:

**Comment by m-kuhn** [comment]
Can you provide steps to reproduce?

**Comment by m-kuhn** [comment]
@sjib is this still an issue or can this be closed?
