### ISSUE TITLE
QGEP datamodel Version and Release

### ISSUE THREAD

**Issue by ponceta** [QGEP/QGEP#458]
According to @3nids 's commit on https://github.com/QGEP/datamodel/commit/b2a28d91cda77923c252c717a72628832a5f10a4

QGEP datamodel should be in 1.1.2.

But actually there's no release 1.1.2 available.

QGEP qgis project is pointing towards datamodel 1.0.1.

There's maybe a need of coherency here.

IMHO, 1.X releases should be updated on QGEP qgs project

1.X.Y releases should have a small release and changelog comment. (what has been fixed!)

**Comment by sjib** [comment]
@3nids is this solved generally or which specific steps would need to be implemented?

**Comment by ponceta** [comment]
1.1.1 commit for release is https://github.com/QGEP/datamodel/commit/f61cfdceb34a5fb1df7435b51bd22adaac859fee

That's how I understand @3nids 's commit to 1.1.2 as current version for pum and travis checks.

QGEP Project should be updated and validated to 1.1.1 but that's another question.
