### ISSUE TITLE
Can't modify labels in QGEP issues

### ISSUE THREAD

**Issue by ponceta** [QGEP/QGEP#463]
According to what was discussed today, we (qgep_group) should be able to edit labels in qgep issues to set 2019 enhancement and bugfixing.  @m-kuhn could you or someone create a team of users with such privileges.

Otherwise we can just ping both @sjib and @m-kuhn  on any issues we want to consider in 2019.

**Comment by m-kuhn** [comment]
Labelling is connected to "write" permission on github.
I think we should not give everyone (potentially destructive) write permission on the repository. I would propose to the "add a comment and ping" approach.

**Comment by sjib** [comment]
Task for the group members until 25.1.2019: 
Check thru the two lists above and indicate your preferences for P1 issues in using the comment: 
"@sjib @m-kuhn Priority 2019 Candidate" for this list [P1](https://github.com/QGEP/QGEP/issues?q=is%3Aopen+is%3Aissue+label%3AP1)
and 
"@sjib @m-kuhn Priority 2019 Bugfix" for this list [Error](https://github.com/QGEP/QGEP/issues?q=is%3Aopen+is%3Aissue+label%3AError)
