### ISSUE TITLE
QGEP project 3.4

### ISSUE THREAD

**Issue by varrieta** [QGEP/QGEP#467]
The qgis project will have to be ported to QGIS 3.4 (maybe during codesprint)

Some other things to do at the time:
- [x] Add quarantine layer (qgep_import) in the project

Feel free to edit the post and add your points

**Comment by ponceta** [comment]
Regarding QGIS 3, for your information, I've opened 2 issues on QGIS :

https://issues.qgis.org/issues/18138
(Blocking for 3D on QGIS advanced numerisation)
https://issues.qgis.org/issues/21390
(Forgotten PointZ class for Z snapping)

**Comment by m-kuhn** [comment]
Can we close this issue or is there something remaining?
