### ISSUE TITLE
Advanced Digitizing and QGIS crash

### ISSUE THREAD

**Issue by urskaufmann** [QGEP/QGEP#469]
Info for those who use advanced digitizing:
Turn off the "Show snapping tooltips" (Settings - Options - Digitizing - Snapping). Otherwise QGIS will freeze with Win (7) if you work with advanced digitizing and snapping on. No such problem on Mac!.
But after using advanced digitizing with snapping on, I get a QGIS crash on Exit QGIS (on Win and Mac system).

**Comment by haubourg** [comment]
Hi @urskaufmann , what QGIS version are you using?

**Comment by urskaufmann** [comment]
3.4.4   (look also QGIS Bug report 21144)

**Comment by sjib** [comment]
@urskaufmann Still an issue?

**Comment by urskaufmann** [comment]
Yes, it is. Tested with QGIS 3.6.2 on Win 7. And it is also still open in https://github.com/qgis/QGIS/issues/28962

**Comment by ponceta** [comment]
https://github.com/qgis/QGIS/pull/30287

Fixed it?

**Comment by urskaufmann** [comment]
QGIS 3.4.13: seems to be fixed.
