### ISSUE TITLE
[datamodel] LineStringZ instead of CurveCompoundZ for reaches

### ISSUE THREAD

**Issue by ponceta** [QGEP/QGEP#471]
When I see
  https://github.com/QGEP/datamodel/blob/76cf0d9ed5faf798ae4548c6fed906d6e01a9ab2/view/vw_qgep_reach.sql#L98

I ask myself what is the purpose of having Complex Curve geometry as geometry type when progression geometry is a linear approximation [ST_CurveToLine](https://postgis.net/docs/ST_CurveToLine.html) forced to the Curve format with [ST_ForceCurve](https://postgis.net/docs/ST_ForceCurve.html).

Much complexity for what purpose?

What are the advantages of this geometry type?

**Comment by m-kuhn** [comment]
As far as I know it's a requirement from the VSA-DSS model, @sjib will know more.

We originally exposed the curved type but there was some limitation in postgis why we had to switch to exposing it as straight lines and as long as a) nobody needs the curved type and b) we don't have a real issue with curved type, we'll probably stick to this way.

**Comment by ponceta** [comment]
Why not ST_ForceCurve ONLY when exporting to ili?

Export views?

**Comment by sjib** [comment]
I think about it

**Comment by kfischerar** [comment]
please, don't forget INTERLIS, anytime before changing anything ;-)

Am Do., 28. Feb. 2019 um 20:40 Uhr schrieb Stefan <notifications@github.com

**Comment by ponceta** [comment]
> please, don't forget INTERLIS, anytime before changing anything ;-)

We won't! ;)

**Comment by ponceta** [comment]
As @m-kuhn says, it's easy to do nothing since it does not bring any problem yet.

For me, having to convert type like it's done brings useless complexity which is already a problem (but maybe not prio1 for sure).

I close this then. To be reopened if we face troubles due to conversions or else.

Thanks all for your inputs!
