### ISSUE TITLE
Performance Issues when changing owner

### ISSUE THREAD

**Issue by ponceta** [QGEP/QGEP#472]
I had to correct the owner on some reaches and I got some latency issues.

I tried then this request on the whole database

UPDATE qgep_od.vw_qgep_reach
SET ws_fk_owner = 1;

And I crashed QGIS.

I tried it on pgadmin and get a huge time for this request

![image](https://user-images.githubusercontent.com/8614223/53171743-df32af80-35e3-11e9-8fa9-11e103479a36.png)

The explain gives me something like this :

"Update on vw_qgep_reach  (cost=14508.55..25630.42 rows=54117 width=1886)"
"  ->  Hash Left Join  (cost=14508.55..25630.42 rows=54117 width=1886)"
"        Hash Cond: ((re.fk_pipe_profile)::text = (pp.obj_id)::text)"
"        ->  Hash Left Join  (cost=14492.47..21956.63 rows=54117 width=1868)"
"              Hash Cond: ((ws.obj_id)::text = (ch.obj_id)::text)"
"              ->  Hash Right Join  (cost=13199.38..19884.65 rows=54117 width=1820)"
"                    Hash Cond: ((ne.obj_id)::text = (re.obj_id)::text)"
"                    ->  Hash Right Join  (cost=2289.96..7748.09 rows=60976 width=1149)"
"                          Hash Cond: ((ws.obj_id)::text = (ne.fk_wastewater_structure)::text)"
"                          ->  Seq Scan on wastewater_structure ws  (cost=0.00..4031.29 rows=72629 width=964)"
"                          ->  Hash  (cost=1527.76..1527.76 rows=60976 width=185)"
"                                ->  Seq Scan on wastewater_networkelement ne  (cost=0.00..1527.76 rows=60976 width=185)"
"                    ->  Hash  (cost=10232.96..10232.96 rows=54117 width=688)"
"                          ->  Hash Right Join  (cost=6856.02..10232.96 rows=54117 width=688)"
"                                Hash Cond: ((rp_to.obj_id)::text = (re.fk_reach_point_to)::text)"
"                                ->  Seq Scan on reach_point rp_to  (cost=0.00..1915.24 rows=81824 width=234)"
"                                ->  Hash  (cost=6179.56..6179.56 rows=54117 width=471)"
"                                      ->  Hash Right Join  (cost=2802.63..6179.56 rows=54117 width=471)"
"                                            Hash Cond: ((rp_from.obj_id)::text = (re.fk_reach_point_from)::text)"
"                                            ->  Seq Scan on reach_point rp_from  (cost=0.00..1915.24 rows=81824 width=234)"
"                                            ->  Hash  (cost=2126.17..2126.17 rows=54117 width=254)"
"                                                  ->  Seq Scan on reach re  (cost=0.00..2126.17 rows=54117 width=254)"
"              ->  Hash  (cost=780.82..780.82 rows=40982 width=65)"
"                    ->  Seq Scan on channel ch  (cost=0.00..780.82 rows=40982 width=65)"
"        ->  Hash  (cost=12.70..12.70 rows=270 width=68)"
"              ->  Seq Scan on pipe_profile pp  (cost=0.00..12.70 rows=270 width=68)"

If this is a pure fictive call, changing owner on hundred reaches is quite time demanding (~30 seconds) and a real use case.

**Comment by m-kuhn** [comment]
That doesn't look good. Tell us if we should have a closer look.

**Comment by urskaufmann** [comment]
I confirm. Not only if I change the owner-field. Its slow on every field in multiedit-mode (with vw_qgep_reach or vw_qgep_wastewater_structure). Some tests:
Change 175 of 1675 records in vw_qgep_reach
- 1 field: 12"
- 2 fields: 26" (if saved before, when not safed before, I have stopped after 3')

Change 33 of 1675 records in vw qgep_reach
- 3 fields: 7"

If I make the changes not in vw_qgep_reach, but in vw_channel (change 174 of 1676)
- 4 fields: 5"

**Comment by ponceta** [comment]
@m-kuhn yes please!

**Comment by ponceta** [comment]
Seems not to be an issue anymore. (QGEP datamodel 1.3.0)
