### ISSUE TITLE
QGEP update to 1.2.0

### ISSUE THREAD

**Issue by ponceta** [QGEP/QGEP#474]
These are some hints when migrating to QGEP 1.2.0 on an existing qgs project:

Reaches form : 
Add default values for vw_qgep_reach `rp_from level` and `rp_to_level` :
`if(z(end_point($geometry))='nan', NULL, z(end_point($geometry)))`

`if(z(start_point($geometry))='nan', NULL, z(start_point($geometry)))`

Geometries : 
Point -> PointZ (wastewater nodes and covers)
Multipoint -> MultipointZ (wastewater_structures)

@signedav if you did some more adjustements on the demo project please let us know and feel free to edit this post. The diff is too large on github for the qgs file.

**Comment by signedav** [comment]
It's stored with a newer QGIS (3.4.4) - that's why it has so many changes...

**Comment by ponceta** [comment]
Hints for history. This does not need to be open anymore.
