### ISSUE TITLE
(Update) Wincan 2 qgep with QGIS 3.X

### ISSUE THREAD

**Issue by ponceta** [QGEP/QGEP#475]
Going full QGIS 3.X requires wincan 2 qgep to be updated.

Who is currently using wincan 2 qgep?

It would be the occasion to adopt it to qgep repo if @3nids agree and consider it as part of QGEP (following updates, releases, etc...).

https://github.com/3nids/wincan2qgep

**Comment by urskaufmann** [comment]
I did not use it, but can be interesting. Think of the new version wincan VX that is totally different to wincan V8. I don't know, if it's not better do use VSA-KEK instead if directly connect to wincan VX.

**Comment by sjib** [comment]
![vsa_kek_erweiterung](https://user-images.githubusercontent.com/1265865/59104033-b7681d00-8930-11e9-948b-5c21119a6db9.jpg)

**Comment by sjib** [comment]
Workflow with existing data in VSA-DSS: Overview

![stammdaten_vorhanden3](https://user-images.githubusercontent.com/1265865/59104256-66a4f400-8931-11e9-8e6f-793507ea5de0.jpg)
![stammdaten_vorhanden](https://user-images.githubusercontent.com/1265865/59104257-673d8a80-8931-11e9-9980-007184098b04.jpg)
![stammdaten_vorhanden2](https://user-images.githubusercontent.com/1265865/59104258-673d8a80-8931-11e9-86e9-a5e882ba9fdf.jpg)

Further details in here:
[VSA-DSS_Transferdatensatz_INTERLIS2_Erlaeuterungen_Kap6.pdf](https://github.com/QGEP/QGEP/files/3265868/VSA-DSS_Transferdatensatz_INTERLIS2_Erlaeuterungen_Kap6.pdf)

**Comment by sjib** [comment]
Requirements following Code Sprint in August can be found here https://github.com/QGEP/QGEP/wiki/Wincan-data-import-to-QGEP---QGIS

**Comment by sjib** [comment]
@3nids Is this enough for an quotation?

**Comment by 3nids** [comment]
yes, we will produce one as soon as the migration of existing plugin to QGIS 3 is achieved, by end of next week

**Comment by urskaufmann** [comment]
Tried to new qgis3 plugin.
When I choose the xml-file I get this error:
![image](https://user-images.githubusercontent.com/1257403/64454041-37e21980-d0ea-11e9-9906-72b42536f023.png)

**Comment by 3nids** [comment]
This should be ok in 1.0.4. which version do you have? It's already a few hours old ;)

**Comment by urskaufmann** [comment]
1.0.1  :-(

**Comment by urskaufmann** [comment]
Works with 1.0.4! It did not show me that there is a new version. I had to uninstall and install again.

I can now match channels. But when I press import I get an error message:
![image](https://user-images.githubusercontent.com/1257403/64461637-07a47600-d0fe-11e9-8b55-a00370071636.png)

Can it be, that the codes are not good (its old data, no ENxx codes)?

**Comment by 3nids** [comment]
Yes, the RA code isn't found in the code table.
We would have to add extra support to these.
If needed, you can fill another issue for this. If it's just a matter of adding extra codes in the list, it shouldn't be a big deal.

**Comment by urskaufmann** [comment]
I have now a project with correct codes, but I get other errors (e.g. null value in s_pipewidth). I added values in s_pipewidth in the xml-file, but when importing, I get again errors:
_2019-10-10T08:19:36     WARNING    Traceback (most recent call last):
              File "C:/Users/kau/AppData/Roaming/QGIS/QGIS3\profiles\test/python/plugins\wincan2qgep\gui\databrowserdialog.py", line 333, in on_importButton_clicked
              df['channel_damage_code'] = int(damage_code_to_vl(observation['OpCode']))
             TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'_

My conclusion: in wincan are many ways to fill in the values (s_pipewidth, s_pipedia, s_profile ...). If the wincan-project is not 100% as the plugin expects the data, then the plugin works not.
For me a clear vote for standardized data-import with INTERLIS VSA-KEK.

**Comment by ponceta** [comment]
I can close this since it works with limitations but standardized data import via INTERLIS VSA-KEK will be developped in the future.
