### ISSUE TITLE
1.2.0 Wastewater displacement bug

### ISSUE THREAD

**Issue by ponceta** [QGEP/QGEP#476]
Moving a wastewater structure in QGEP 1.2.0 destroys the geometry :

![bug_move_wastewaterstructure](https://user-images.githubusercontent.com/8614223/53550125-409fd480-3b36-11e9-81e2-4bb5362d83d4.gif)

MultiPointZ ((nan nan nan))

Moving cover and wastewater node works fine.

Moving reaches works fine.

**Comment by m-kuhn** [comment]
@signedav can you have a look?

**Comment by signedav** [comment]
Thanks @ponceta I can reproduce that. I will investigate...

**Comment by signedav** [comment]
Seems that `ST_TRANSLATE` cannot handle `NaN`:
```
SELECT ST_AsText( ST_TRANSLATE(ST_SetSRID(ST_MakePoint(500, 900, 'NaN'), 2056), 10, 20 ) )
```
or
```
SELECT ST_AsText( ST_TRANSLATE(ST_SetSRID(ST_MakePoint(500, 900, 'NaN'), 2056), 10, 20, 0 ) )
```
leads to:
```
"POINT Z (nan nan nan)"
```
I'll make a workaround...
