### ISSUE TITLE
OID generation fails for vw_cover QGIS 3.X

### ISSUE THREAD

**Issue by ponceta** [QGEP/QGEP#477]
OID generation fails when creating a new cover on QGIS 3.X

![image](https://user-images.githubusercontent.com/8614223/53569701-17e30380-3b65-11e9-9d36-554a07f87543.png)

This will block the user to validate the cover form.

**Comment by sjib** [comment]
In the [vw_cover.sql](https://github.com/QGEP/datamodel/blob/master/view/vw_cover.sql) is a statement that should automatically generate an new OBJ_ID: 
qgep_sys.generate_oid('qgep_od','cover')

`CREATE
 OR REPLACE FUNCTION qgep_od.vw_cover_insert()
  RETURNS trigger AS
$BODY$
BEGIN
  INSERT INTO qgep_od.structure_part (
             obj_id
           , identifier
           , remark
           , renovation_demand
           , fk_dataowner
           , fk_provider
           , last_modification
           , fk_wastewater_structure
           )
     VALUES ( COALESCE(NEW.obj_id,qgep_sys.generate_oid('qgep_od','cover')) -- obj_id
           , NEW.identifier
, NEW.remark`

**Comment by ponceta** [comment]
Known bug, fixed thx to @tudorbarascu on QGIS 3.4.6

Workaround, define default value as 1 in attribute form, will be overwritten by the trigger.

**Comment by ponceta** [comment]
![image](https://user-images.githubusercontent.com/8614223/54105584-bb3cdf80-43d3-11e9-913c-6ba170a0c534.png)

**Comment by m-kuhn** [comment]
@ponceta is this fixed?

**Comment by ponceta** [comment]
Yes! Thank you!

**Comment by ponceta** [comment]
Good to know, it is now (QGIS 3.4.6) possible to soften constraints on QGIS side by not enforcing these.
