### ISSUE TITLE
Action to digitize additionnal cover / node

### ISSUE THREAD

**Issue by ponceta** [QGEP/QGEP#478]
We need to be able to add extra covers and wastewater nodes for a specific wastewater structure.

Is it possible with a python action?

_The best case would be to add directly a new geometry with the relationnal widget (QGIS core wished functionnality)_

![image](https://user-images.githubusercontent.com/8614223/53571852-2849ad00-3b6a-11e9-8ed2-caa2b4251e3a.png)

**Comment by m-kuhn** [comment]
Should be possible with to achieve with Python code, but having it in core would be even better of course!

**Comment by ponceta** [comment]
This is under developpement financed by QWAT group.

https://git.oslandia.net/Oslandia-utilities/demandes_qwat_qgep/issues/22

I close this since we won't require these actions anymore!
