### ISSUE TITLE
Error on db_setup.sh

### ISSUE THREAD

**Issue by schoeller** [QGEP/QGEP#480]
Dear all,

I created an empty database called `qgep` checked out the datamodel as of today and then called

``
./scripts/db_setup.sh -f –r –s 25832 –PGSERVICE="host=MYHOST port=5432 dbname=qgep user=MYDBOWNER password=MYPASSWD"
``

After a long list of commits the following error is thrown:

``
09_qgep_dictionaries.sql:642: ERROR:  value too long for type character varying(20)
``

I am running postgres 9.6.11 and postgis 2.4.4

Any assistance is appreciated.

**Comment by sjib** [comment]
I tried to reproduce this error with https://raw.githubusercontent.com/QGEP/datamodel/master/09_qgep_dictionaries.sql but I do  succeed and don't get an error message. 

Can you provide more details?

**Comment by schoeller** [comment]
A diff between above URL and the local contents are empty, thus I conclude content is identical. Querying the database delivers
```
qgep=# SELECT version();
                                                           version                                                           
-----------------------------------------------------------------------------------------------------------------------------
 PostgreSQL 9.6.11 on x86_64-pc-linux-gnu (Debian 9.6.11-1.pgdg80+1), compiled by gcc (Debian 4.9.2-10+deb8u1) 4.9.2, 64-bit
(1 row)
```
as well as
```
qgep=# SELECT PostGIS_Version();
            postgis_version            
---------------------------------------
 2.4 USE_GEOS=1 USE_PROJ=1 USE_STATS=1
(1 row)
```
I have no further details at hand. I have to work myself into this matter.

**Comment by m-kuhn** [comment]
What's the output of the encoding (in pgAdmin)?

```
SHOW SERVER_ENCODING
```

**Comment by schoeller** [comment]
@m-kuhn: The output on the command is
```
qgep=# SHOW SERVER_ENCODING;
 server_encoding 
-----------------
 SQL_ASCII
(1 row)
```
After dropping the database I recreated it using
```
createdb -E UNICODE -T template0 qgep
```
Checking for the encoding within the database gives
```
qgep=# SHOW SERVER_ENCODING;
 server_encoding 
-----------------
 UTF8
(1 row)
```
Now the script terminates without error. Thanks a lot for the hint. I create a pull request under https://github.com/QGEP/docs/pull/69
