### ISSUE TITLE
Processing Tool "Snap reach geometry"

### ISSUE THREAD

**Issue by urskaufmann** [QGEP/QGEP#481]
I tried do update the docu for this tool, but I do not find out, what it is doing.
I get errors when I choose vw_wastewater_node as "wastewater node layer", there is no error if I choose vw_qgep_wastewater_structure.
I get errors, if one of the selected reaches is allready connected on both sides to wastewaternetwork elements. If I clear at least one if these fk, there is no error.
But in my opinion, there is no move of vertex (snapping) or change in fk-attributes.
Who works with this tool and knows how?

**Comment by m-kuhn** [comment]
The tool is correctly used with vw_wastewater_node but was never updated to QGIS 3. Done now.
