### ISSUE TITLE
Error on insert_views.sh

### ISSUE THREAD

**Issue by schoeller** [QGEP/QGEP#486]
After having created a fresh database the script ```insert_views.sh``` is executed from the export directory to generate export views. The following error is thrown:
```
insert_views.sh: 6: insert_views.sh: Bad substitution
DROP SCHEMA
CREATE SCHEMA
ERROR:  column vw_qgep_wastewater_structure.special_structure_function does not exist
LINE 326: ..._structure_function special_structure_function ON qgep_od.vw...
                                                               ^
```

**Comment by sjib** [comment]
@schoeller Is this still an issue with the latest release?

**Comment by schoeller** [comment]
@sjib having checked out the datamodel as of today an error is thrown on database generation
```
Traceback (most recent call last):
  File "/home/sebastian/Dokumente/2880-Bandung/2019-06-04/datamodel/scripts/../view/create_views.py", line 6, in <module>
    from pirogue.join import Join
ModuleNotFoundError: No module named 'pirogue'
```
The module from https://github.com/opengisch/pirogue is suspected missing and installed through
```
pip3 install pirogue
```
A second run for database initialisation finishes. From the export directory the PGSERVICE is defined
```
export PGSERVICE=pg_qgep
```
The script is called and throws the following error
```
./insert_views.sh 
DROP SCHEMA
CREATE SCHEMA
ERROR:  column vw_qgep_wastewater_structure.special_structure_function does not exist
LINE 329: ..._structure_function special_structure_function ON qgep_od.vw...
```

**Comment by sjib** [comment]
@3nids can you check on this?
