### ISSUE TITLE
error new vw_wastewater_node and vw_cover

### ISSUE THREAD

**Issue by urskaufmann** [QGEP/QGEP#487]
Wanted to add a new wastewater_node in layer vw_wastewater_node (add point feature): got this error:
Layer vw_wastewater_node: PostGIS error while adding features: FEHLER: Column has Z dimension but geometry does not

**Comment by urskaufmann** [comment]
The same with vw_cover

**Comment by m-kuhn** [comment]
Did you change the qgep project or database version?

**Comment by urskaufmann** [comment]
Database version is 1.2.0
Project is not changed. Tried now also with last project from Github: the same

**Comment by m-kuhn** [comment]
CC @signedav
