### ISSUE TITLE
Clone or download datamodel without metaproject folder

### ISSUE THREAD

**Issue by tproduit** [QGEP/QGEP#489]
When one downloads or clones `datamodel`, the folder `metaproject` remain empty. As a result some views are not installed. You have to clone or download `metaproject` separately.

**Comment by m-kuhn** [comment]
git submodules need to be initialized. Maybe this would deserve some developer docs.

**Comment by 3nids** [comment]
you need to run `git submodule update --init --recursive``
the dependency should be removed soon.
