### ISSUE TITLE
[QGIS] snapping indexing issue moving wastewater structure, cover and node 

### ISSUE THREAD

**Issue by ponceta** [QGEP/QGEP#492]
When moving wastewater structure, node and cover, I get some indexing issues when editing.

Snapping of elements is sometimes complicated :

![image](https://user-images.githubusercontent.com/8614223/57021768-7859f400-6c2d-11e9-9a56-759cad330569.png)

On the above image, cover has been displaced to the reaches intersection, the wastewater situation_geometry is updated visually but QGIS still thinks it is on previous position (blue point).

Moving the blue point to the intersection will bring back the wastewater structure snapping point to the right spot. Wastewater structure will then move normally. Otherwise, reloading the project will do the fix.

**Comment by 3nids** [comment]
@m-kuhn a use-case for the PG notification?

**Comment by m-kuhn** [comment]
I think some work has been done using layer dependencies for qwat recently. Maybe it's just the dependency configuration which is missing.

**Comment by ponceta** [comment]
> I think some work has been done using layer dependencies for qwat recently. Maybe it's just the dependency configuration which is missing.

@m-kuhn this should be fixed using layer dependencies? We'll give it a try today!

-> Could be a possible improvement of the .qgs project when migrating to QGIS 3 

https://github.com/QGEP/QGEP/issues/467

**Comment by ponceta** [comment]
![image](https://user-images.githubusercontent.com/8614223/58781617-b6f01f00-85dc-11e9-95d4-95f945e4793f.png)

Setting dependencies fix visual and maybe other stuff but actually not the snapping indexing issue.

**Comment by m-kuhn** [comment]
@ponceta it would be nice to schedule this on time for QGIS 3.10. Can you raise this issue with qwat, according to our discussion?

**Comment by ponceta** [comment]
@m-kuhn I've raised the issue to QWAT. 

https://git.oslandia.net/Support-projects/helpdesk_qwat_qgep/issues/75

@haubourg could you please check with Matthias that we go the same way towards an enhancement in QGIS 3.10?

**Comment by lbartoletti** [comment]
@haubourg @ponceta @m-kuhn For memory, this causes problems for the plugin too.

**Comment by m-kuhn** [comment]
Yes

**Comment by haubourg** [comment]
@m-kuhn @ponceta @lbartoletti  The grant application is designed to address the issue that we spotted long time ago but didn't manage to find anyone willing to fund the (hard) fix. @mhugo and @troopa81 will be working on this. I hope we can make it for 3.10 but currently we don't have working slots before september, when the feature freeze is the 30 of august. I check if we can postpone something else, no guarantee at this time though.

**Comment by m-kuhn** [comment]
@haubourg is there a QEP for the proposal?

**Comment by ponceta** [comment]
@haubourg please update the information here too about priorization of this over some qwat group devloppments. Thanks a lot for coordinating the efforts toward this enhancement/bugfixing.

**Comment by haubourg** [comment]
@ponceta So we confirm we could postpone tasks so that the snapping cache issue will be addressed in 3.10. Many thanks for this. 

@m-kuhn as for now the QEP is not opened. @mhugo and @troopa81 will work on this. I let them push implementation details there

**Comment by ponceta** [comment]
This seems much better on QGIS 3.9.0

Thanks!

I used circular dependencies between cover, wastewater_structure and wastewater_nodes and it works quite when moving these entities.

**Comment by haubourg** [comment]
> This seems much better on QGIS 3.9.0
> 
> Thanks!
> 
> I used circular dependencies between cover, wastewater_structure and wastewater_nodes and it works when moving these entities.

This is a great relief! It was really a blocker to me for most applications. /me happy!
