### ISSUE TITLE
Update datamodel initialization procedure

### ISSUE THREAD

**Issue by ponceta** [QGEP/QGEP#493]
Two small things due to recent developpment : https://github.com/QGEP/datamodel/pull/95

 - [ ] pirogue package installation 
Adapt Readme : `pip install --user pirogue`
 - [ ] run_sql has to be launched from the datamodel/ folder 
Adapt readme (warn user of specify `cd datamodel`) of enable relative path
```
Traceback (most recent call last):
  File "/home/pulmexa/qgep_sigip/datamodel/scripts/../view/create_views.py", line 87, in <module>
    qgep_wastewater_structure_extra=args.qgep_wastewater_structure_extra)
  File "/home/pulmexa/qgep_sigip/datamodel/scripts/../view/create_views.py", line 44, in create_views
    run_sql('view/drop_views.sql', pg_service, variables)
  File "/home/pulmexa/qgep_sigip/datamodel/scripts/../view/create_views.py", line 17, in run_sql
    sql = open(file_path).read()
FileNotFoundError: [Errno 2] No such file or directory: 'view/drop_views.sql'
```

the `run_sql` requires to be in datamodel folder to be exectuted without error.

Still testing, other points may be added today.

**Comment by 3nids** [comment]
first point addressed in https://github.com/QGEP/docs/pull/81
second point is already mentionned in docs: https://qgep.github.io/docs/installation-guide/database-initialization.html#generate-the-data-model (`cd datamodel`)

**Comment by ponceta** [comment]
Thanks for fixes!
