### ISSUE TITLE
Error in datamodel drop_view.sql

### ISSUE THREAD

**Issue by sjib** [QGEP/QGEP#494]
Duplicate line:
https://github.com/QGEP/datamodel/blob/be599f0d156d7ee138ed228739127d4aefa67afd/view/drop_views.sql#L58-L59

DROP VIEW IF EXISTS qgep_od.vw_waste_water_treatment_plant;
DROP VIEW IF EXISTS qgep_od.vw_waste_water_treatment_plant;

Should be 
DROP VIEW IF EXISTS qgep_od.vw_waste_water_treatment_plant;
DROP VIEW IF EXISTS qgep_od.vw_waste_water_association;

to have all 7 subclasses included

**Comment by sjib** [comment]
https://github.com/QGEP/datamodel/blob/be599f0d156d7ee138ed228739127d4aefa67afd/view/drop_views.sql#L61
-- overlfows
typo please change to 
-- overflows

**Comment by sjib** [comment]
Line 59 should not be deleted but changed to: qgep_od.vw_waste_water_association

Should be
DROP VIEW IF EXISTS qgep_od.vw_waste_water_treatment_plant;
DROP VIEW IF EXISTS qgep_od.vw_waste_water_association

waste_water_association is also a subclass of organisation

**Comment by m-kuhn** [comment]
Fixed
