### ISSUE TITLE
Prorities 2019 2

### ISSUE THREAD

**Issue by sjib** [QGEP/QGEP#495]
![qgep_prios_2019_1_excel](https://user-images.githubusercontent.com/1265865/59111410-441ad700-8941-11e9-9fcf-6c5b1093f0a5.jpg)

**Comment by m-kuhn** [comment]
Is that an issue or for reference / last meeting log?

Is the year in the title correct? ;)

**Comment by sjib** [comment]
Yes - I need an issue to upload an image (-: . For details see https://github.com/QGEP/QGEP/wiki/Meeting-2019-06-03

**Comment by m-kuhn** [comment]
Should we close it again now this image is uploaded?
Or is there a particular action that needs to be done first (that is not part of another specific ticket)?

**Comment by m-kuhn** [comment]
Thanks :)
