### ISSUE TITLE
Install QGEPPlugin 1.1.12 in a new user profile

### ISSUE THREAD

**Issue by urskaufmann** [QGEP/QGEP#497]
"It would be good to tell us in the new issue if it also happens on a clean new QGIS profile and if others are experiencing the same."

If I try to install qgep plugin in QGIS 3.4.8 with a new user profile, I get this errormessage:
Erweiterungsinstallation schlug fehl: Error transferring https://github.com/QGEP/qgepplugin/releases/download/1.11.12/qgepplugin.1.11.12.zip - server replied: Not Found

![error installing](https://user-images.githubusercontent.com/1257403/59967887-454b2700-9531-11e9-89a9-b08aa9426304.PNG)

**Comment by m-kuhn** [comment]
Should be fixed. Can you try again?

**Comment by urskaufmann** [comment]
works now! Thanks
