### ISSUE TITLE
reachpoint level set to 4000

### ISSUE THREAD

**Issue by urskaufmann** [QGEP/QGEP#498]
- I restored the demodata 1.3.0

- did take the project from https://github.com/QGEP/QGEP/blob/master/project/qgep_en.qgs

- (could not test with new profile -> #497 )

- added a new reach with the wizard and no snapping at the from_reachpoint (the first new reach in this project on my computer) and I get 4000m as reachpoint-level:
![reachpointlevel4000](https://user-images.githubusercontent.com/1257403/59967951-44ff5b80-9532-11e9-9a19-661d2b7a1078.PNG)

QGIS 3.4.8, Win 7 Pro, Postgres 9.6.

**Comment by urskaufmann** [comment]
the same with new profile

**Comment by urskaufmann** [comment]
thanks, works now if there is no snapping (-> NULL) and if there is a node with bottom_level.

If I snap to a node with NULL as buttom_level, I get this error:
Python error: An error has occurred while executing Python code: See message log (Python Error) for more details.

 WARNING    Traceback (most recent call last):
              File "C:/Users/kau/AppData/Roaming/QGIS/QGIS3\profiles\test/python/plugins\qgepplugin\tools\qgepmaptooladdfeature.py", line 132, in cadCanvasReleaseEvent
              self.right_clicked(event)
              File "C:/Users/kau/AppData/Roaming/QGIS/QGIS3\profiles\test/python/plugins\qgepplugin\tools\qgepmaptooladdfeature.py", line 337, in right_clicked
              level = level if not math.isnan(level) else NULL
             TypeError: must be real number, not QVariant

**Comment by m-kuhn** [comment]
Can you test 1.1.14

**Comment by urskaufmann** [comment]
Thanks, is ok now
