### ISSUE TITLE
Error with Delta scripts

### ISSUE THREAD

**Issue by urskaufmann** [QGEP/QGEP#499]
Wanted to update my 1.2.0-data to 1.3.0 with these delta-sql.
The delta_1.2.1_fix_vw_qgep_wastewater_structure.sql was not successful:
![delta_1 2 1_fix_vw_qgep_wastewater_structure](https://user-images.githubusercontent.com/1257403/59968122-a7595b80-9534-11e9-9190-c58223f2b562.PNG)

The delta_1.3.0_import_trigger.sql was not successful:
![delta_1 3 0_import_trigger](https://user-images.githubusercontent.com/1257403/59968125-c22bd000-9534-11e9-8072-c91266bda373.PNG)

The delta_1.3.0_remove_old_views.post.sql was then successful, also the delta_1.3.1_delete_channel_when_no_reach.sql

**Comment by m-kuhn** [comment]
These scripts have not been designed to be run manually. You could replace `%(SRID)s` with 2056. I don't think we can do a lot except for making it easier to run pum.

**Comment by urskaufmann** [comment]
Ok. But some weeks ago a guy told me to run these sql if I can not run pum on windows ;-)

I got also an error with delta_1.3.1_delete_channel_when_no_reach.sql at a second try.
The solution is to replace the %% in Line 26 with just one %.
With this delta, it's possible to delete a reach without having dead data left in the database: cross at the ceiling, this is great!
When testing I had no remark 'Removing channel (%) since no reach is left'.
Is this line 26 in the sql necessary?
