### ISSUE TITLE
Plugin : Connect tool does not connect Reach Point From anymore

### ISSUE THREAD

**Issue by ponceta** [QGEP/QGEP#502]
Is it a change in feature or a bug :

![image](https://user-images.githubusercontent.com/8614223/60528463-c6a27680-9cf4-11e9-92c8-64a66e47cd3e.png)

Using QGEP Plugin 1.1.12 On QGEP 1.3.0 Datamodel.

**Comment by m-kuhn** [comment]
If you connect to a reach (blind connection) only TO is allowed.
If you connect to a node both are allowed (and there is a preference on where you start to drag the line on the source reach: closer to the start point it will modify reach point from, closer to the end point it will modify reach point to)

**Comment by ponceta** [comment]
@m-kuhn Thanks!

![Connect_tool](https://user-images.githubusercontent.com/8614223/60579283-0b74ee80-9d83-11e9-9bb1-9fd8964fc62f.gif)

I've made a small gif to show how to trigger ReachPointFrom! Thanks for the information!

I'm still trying to understand exactly the connection logic between wastewater elements but thats not a technical issue.
