### ISSUE TITLE
Error in qgep_v1.3.0_structure.sql and qgep_v1.3.0_structure_with_value_lists.sql

### ISSUE THREAD

**Issue by sjib** [QGEP/QGEP#504]
>     NEW._url = replace(NEW._url, '\', '/');

![qgep_v1 3 0_structure sql_error_line_26764](https://user-images.githubusercontent.com/1265865/60997048-241e6f00-a356-11e9-8c32-004d4028e1d8.png)
This line (6129) in qgep_v1.3.0_structure_with_value_lists.sql seems not to be valid SQL as the markup shows all code afterwards in grey:

What do I need to adjust?

Same error in [qgep_v1.3.0_structure_with_value_lists.sql](https://github.com/QGEP/datamodel/releases/download/1.3.0/qgep_v1.3.0_structure_with_value_lists.sql)

**Comment by urskaufmann** [comment]
Can not confirm.
In Notepad++ I have no greyed code.
And I just created a new database with schema 1.3.0 with the bat-file as described in the docu 1.3.1.2

**Comment by sjib** [comment]
Workaround: SQL works when running it from batch line instead of Query window in pgAdmin4

> set db=qgep-new
> set port=5433
> set PATH=%PATH%;C:\Program Files\PostgreSQL\9.6\bin
> 
> createdb -U postgres -p %port% %db%
> psql -U postgres -h localhost -p %port% -d %db% -f qgep_v1.3.0_structure_with_value_lists.sql
> PAUSE
