### ISSUE TITLE
Connect tool might lead to null geometry on reach point

### ISSUE THREAD

**Issue by ponceta** [QGEP/QGEP#506]
We did not reproduce this.

Nevertheless there's something bothering me is that a reach point is allowed to have a NULL geometry.

**Comment by ponceta** [comment]
Lack of specific details, to be reopened if needed.

**Comment by 3nids** [comment]
Did you try again?

**Comment by ponceta** [comment]
Yep, I didn't encounter any errors. But I have geometric NOT NULL constraints now, I'll reopen if I get any error message.

https://github.com/QGEP/QGEP/issues/510#issuecomment-514174848
