### ISSUE TITLE
Demo project

### ISSUE THREAD

**Issue by sjib** [QGEP/QGEP#51]
Description here: https://github.com/qgep/QGEP/wiki/Demo-project

**Comment by m-kuhn** [comment]
Make cover manhole foreign key work properly

**Comment by sjib** [comment]
Catchement migration 2008 to 2012 - see description on how to migrate https://github.com/qgep/QGEP/blob/master/migration/README.md

**Comment by sjib** [comment]
You can download the latest demo dataset [here] (https://github.com/QGEP/data/archive/demodata.zip)
