### ISSUE TITLE
[datamodel] Add basic integrity constraints on mandatory geometries

### ISSUE THREAD

**Issue by ponceta** [QGEP/QGEP#510]
QGEP datamodel should ensure some basic integrity on its entities, especially mandatory fields like geometry:

I would suggest to add a minimal NOT NULL constraint on geometry on these 3 tables : 

- [x] wastewater_node (situation_geometry)
- [x] cover (situation_geometry)
- [x] reach (progression_geometry)
- [x] reach_point (situation_geometry)

I faced this issue since wastewater_nodes and reach_points can't have NULL geometries since this is mandatory for topology view (vw_network_segment) in :

```
SELECT wn_from.obj_id,
    wn_from.obj_id AS from_obj_id,
    rp_from.obj_id AS to_obj_id,
    wn_from.bottom_level,
    st_linefrommultipoint(st_collect(wn_from.situation_geometry, rp_from.situation_geometry)) AS progression_geometry
    FROM qgep_od.reach
    LEFT JOIN qgep_od.reach_point rp_from ON rp_from.obj_id::text = reach.fk_reach_point_from::text
    LEFT JOIN qgep_od.wastewater_node wn_from ON rp_from.fk_wastewater_networkelement::text = wn_from.obj_id::text
     WHERE reach.fk_reach_point_from IS NOT NULL AND wn_from.obj_id IS NOT NULL
```

Thoughts?

**Comment by varrieta** [comment]
I think it would be a good thing to implement!
We sometimes have the problem with the reaches. When someone delete all the nodes, the reach disapear but is still in the database..

**Comment by ponceta** [comment]
Fix https://github.com/QGEP/datamodel/pull/104
