### ISSUE TITLE
Error on "Reuse last entered values" function

### ISSUE THREAD

**Issue by signedav** [QGEP/QGEP#514]
When "Reuse last entered values" is activ in Digitizing settings of QGIS, the following error occurs on creating a new "vw_gep_wastewater_structure" feature:
```
 CRITICAL    Layer vw_qgep_wastewater_structure : PostGIS error while adding features: ERROR: duplicate key value violates unique constraint "pkey_qgep_od_structure_part_obj_id"
             DETAIL: Key (obj_id)=(ch13p7mzSP221218) already exists.
             CONTEXT: SQL statement "INSERT INTO qgep_od.structure_part ( 
[...]
             ) RETURNING obj_id"
             PL/pgSQL function qgep_od.ft_vw_cover_insert() line 3 at SQL statement
             SQL statement "INSERT INTO qgep_od.vw_cover (
              obj_id
[...]
```

When I check in the form, there is on the section "Main Cover/Node" the `co_obj_id` containing the old value. This is not the case on section "Wastewater Structure" on `obj_id`. Why not? What is the difference?

**Comment by urskaufmann** [comment]
I think you have to set the constraints for co_obj_id as in the picture:
![constraints](https://user-images.githubusercontent.com/1257403/62730789-fc87f880-ba20-11e9-80ca-a20fe189fb3e.PNG)

**Comment by kfischerar** [comment]
perfect, solved!
@m-kuhn: please correct in xy.qgs (project-file)
thx

**Comment by urskaufmann** [comment]
I have changed this allready in qgep_en.qgs  with pull request 501 (together with other changes).
@m-kuhn  referenced PR 501 to PR 500, and this PR 500 has 2 failed checks. Means is pending.

My changes are in the layer-style of the two mainlayers. Would it not be a good help to provide this layer-styles for users to upgrade there working-project?

by the way: in the docu is no more link or hint where to get this project-file.

**Comment by m-kuhn** [comment]
* For export of styles a new feature request has been opened #515 
* Regarding #500 , that's ready for me, just waiting for some last clarifications regarding datamodel version handling. Next to the patches from #501 it will also include translated project files.
