### ISSUE TITLE
issue on obj_id definitions sequences different when using edition views

### ISSUE THREAD

**Issue by ponceta** [QGEP/QGEP#519]
When defining an entity in the vw_qgep_wastewater_structure 6 elements will be created :
* 1 wastewater_structure
* 1 manhole / special_structure / infiltration_installation / discharge_point
    * 1 wastewater_networkelement _(through vw_wastewater_node)_
    * 1 wastewater_node _(through vw_wastewater_node)_
    * 1 structure_part _(through vw_cover)_ 
    * 1 cover _(through vw_cover)_

Obj_id will be
* prefix + WS + XXXXXX
* prefix + WS + XXXXXX
    * **prefix + WN + XXXXXX**
    * **prefix + WN + XXXXXX**
    * **prefix + SP + XXXXXX**
    * **prefix + SP + XXXXXX**

But when I create a wastewater node from the vw_wastewater_node, I get
* **prefix + WE + XXXXXX in wastewater_networkelement**
* **prefix + WE + XXXXXX in wastewater_node**

AND when I create a cover from vw_cover I get 
* **prefix + CO + XXXXXX in structure_part**
* **prefix + CO + XXXXXX in cover**

What is the purpose of this? Bug or feature?

I've made up a small resume for making it a bit clearer

![image](https://user-images.githubusercontent.com/8614223/63954399-58bfc480-ca83-11e9-9cff-023e6a37c626.png)

**Comment by urskaufmann** [comment]
Didn't remark this before. Not logical. 
With this shortcut of the class in the obj_id you get a little more info about the object. From this side it would be interesting to have the shortcut of the subclass in the obj_id (CO instead of SP). With the wastewater-structure-class is the problem, that you can change the subclass (e.g. from manhole to special structure) but the obj_id can not be changed. So WS is in this case ok.

**Comment by ponceta** [comment]
This is a problematic when I try to connect topologically my elements :

![image](https://user-images.githubusercontent.com/8614223/65246845-9c8c7380-daef-11e9-8c7a-39ae48d77fe1.png)

I'm actually not sure to know why wastewater structure 853 is refered as ch176dc9**WE**005573

when wastewater structure 6768 is refered as ch176dc9**WS**006585

It's probably due to mapping scripts :

https://github.com/VilleDePully/qgep_sigip/blob/master/migration/topologie.sql

**Comment by urskaufmann** [comment]
I'm not sure, if this is the reason: the rp_*_fk is a fk to the wastewaternode (-> WE). On your picture you show the wastewaterstructure (-> WS). Normally structure and node have the same identifier (853), but it is not the same field.

**Comment by ponceta** [comment]
About covers

![image](https://user-images.githubusercontent.com/8614223/67081170-f2a81180-f196-11e9-902c-a4bbaa16dcc0.png)

About wastewater nodes
![image](https://user-images.githubusercontent.com/8614223/67081478-8679dd80-f197-11e9-8887-1eeec9712fa0.png)

@m-kuhn @3nids Could you make sure that this is fixed when updating the datamodel?

I'm a bit afraid of having different id sequences in common tables!

**Comment by 3nids** [comment]
this should have been fixed by https://github.com/QGEP/datamodel/pull/116 and https://github.com/QGEP/datamodel/pull/119
can you test and report?

**Comment by ponceta** [comment]
Tested in Pully, works fine, thanks for the fix and the help!

(require pirogue update  
`pip3 install pirogue --upgrade`)

**Comment by 3nids** [comment]
@ponceta glad to read, thanks for the feeback.
