### ISSUE TITLE
Issue with QGEP plugin installation

### ISSUE THREAD

**Issue by varrieta** [QGEP/QGEP#520]
I have installed QGIS 3.4.11 for one of my collegues but the QGEP plugin doesn't appear in the extension.

I also have this version of QGIS on my computer but I can find QGEP in the extensions. 

QGIS 3.4.11
Plugin url: https://raw.githubusercontent.com/QGEP/repository/master/plugins.xml

**Comment by 3nids** [comment]
plugin is in Experimental, you should turn experimental plugins on.

**Comment by varrieta** [comment]
I did

**Comment by varrieta** [comment]
Could Python 3 be missing althought I used OS-Geo for the update?

**Comment by varrieta** [comment]
well I had the wrong url.. I used our old doc.. damned
