### ISSUE TITLE
[Datamodel] Error in vw_catchment_area_connections

### ISSUE THREAD

**Issue by urskaufmann** [QGEP/QGEP#521]
On opening the view in pgAdmin I get this error:

ERROR:  FEHLER:  Geometry has Z dimension but column does not
--

I think must by since wastewaternode is 3Dgeometry.

**Comment by ponceta** [comment]
@urskaufmann I'll try to import my catchment areas and see if I can see what's wrong.

Could be a codesprint issue.

**Comment by urskaufmann** [comment]
I added the vw_catchment_area_connections together with layer catchment_area and vw_individual_surface (database 1.4.0). The effect is, that I can no more digitize catchment_areas or individual_surface: after defining the polygon I get the Feature Attributes form, can fill in and press OK. But then there is no new record and no error.  In the QGIS-message log - PostGIS are messages about database errors. It's not really obvious, that vw_catchment_area_connections has an effect on the digitizing of vw_individual_surface.
So - do not add the vw_catchment_area_connection-layers to a qgep-project until this bug is solved.

**Comment by m-kuhn** [comment]
@urskaufmann can you paste the database errors?

> It's not really obvious, that vw_catchment_area_connections has an effect on the digitizing of vw_individual_surface.

That is more than surprising indeed...

**Comment by urskaufmann** [comment]
![error with vw_ca_connections](https://user-images.githubusercontent.com/1257403/71825285-d2a03400-309b-11ea-9ea2-32d93349b5a0.PNG)

The warning message 15:38:09 is when I load the vw_catchment_area_connenction layer in the project.  
Strange: I can now add new records. The behaviour is not the same as three days before.
