### ISSUE TITLE
ne_ prefix in vw_qgep_reach

### ISSUE THREAD

**Issue by ponceta** [QGEP/QGEP#522]
Following actual logic, attributes coming from network element table in the reach view should be prefixed as ne_identifier and ne_remark.

I looked for identifier and remark in the table reach and I was confused not to find these.

If I understand it well, ne_identifier and ne_remark are used for the reach and ws_identifier and ws_remark are used for the channel, right?

**Comment by urskaufmann** [comment]
Strictly speaking you are right. For me, the superclass and the subclass belong together. We use also  co_identifier and co_remark and not the structure_part prefix SP.

**Comment by ponceta** [comment]
Makes sense to me, thanks!
