### ISSUE TITLE
QGIS does not load all features of wastewater_structure

### ISSUE THREAD

**Issue by 3nids** [QGEP/QGEP#523]
from former issue: https://github.com/QGEP/QGEP/issues/507#issuecomment-513216412

![image](https://user-images.githubusercontent.com/8614223/61536061-09be5280-aa34-11e9-9de5-621f86757056.png)

If your layer is loaded in CurvePolygonZ (manually through project editing), the action will fail since QGIS doesn't recognize the NULL geometries entities. And of course CurvePolygon layer will fait to edit since postgis is requiring CurvePolygonZ.

**Comment by 3nids** [comment]
@ponceta what is the postgis version of your server (not the client)? I couldn't replicate the issue here, both with QGIS 3.4 and 3.9. I suspect this could have been fixed in PG.

**Comment by ponceta** [comment]
"PostgreSQL 9.6.14, compiled by Visual C++ build 1800, 64-bit"
"POSTGIS="2.3.0 r15146" GEOS="3.5.0-CAPI-1.9.0 r4090" PROJ="Rel. 4.9.1, 04 March 2015" GDAL="GDAL 2.1.1, released 2016/07/07" LIBXML="2.7.8" LIBJSON="0.12" RASTER"

But QWAT and QGEP are working on the same server and QWAT works fine .

I've solved part of the problem by using setting `estimatedmetadata=true` to both <datasource> and <layer-tree-item> I have now the correct feature count.

Nevertheless I face the same issue as before even on a blank project since when loading attribute tables on QGIS :

![image](https://user-images.githubusercontent.com/8614223/65671990-909d3600-e048-11e9-8307-1be60817a149.png)

I think this is somehow related to the fact that I can't load Z layers properly from QGIS (I edited the geometry type manually in the QGIS project).

I still can't test with demo project since demo dump restore fails because :

```
pg_restore: [archiver (db)] could not execute query: ERREUR:  la fonction st_curvetoline(public.geometry, integer) n'existe pas
LINE 1: SELECT ST_CurveToLine($1, 32)
               ^
HINT:  Aucune fonction ne correspond au nom donné et aux types d'arguments.
Vous devez ajouter des conversions explicites de type.
QUERY:  SELECT ST_CurveToLine($1, 32)
CONTEXT:  fonction SQL « st_curvetoline » durant « inlining »
    Command was: REFRESH MATERIALIZED VIEW qgep_od.vw_network_segment;

WARNING: errors ignored on restore: 1
```
Related to :
https://github.com/QGEP/QGEP/issues/334

**Comment by m-kuhn** [comment]
Can you juts ignore the error and run the command manually in an SQL interface (e.g. pgadmin)?

```
REFRESH MATERIALIZED VIEW qgep_od.vw_network_segment;
```

**Comment by ponceta** [comment]
pgAdmin4 does not allow to ignore errors.

I'll try with pg_restore like Travis does.

**Comment by 3nids** [comment]
> pgAdmin4 does not allow to ignore errors.

By default, I think it does ignore errors. At least the option is available:
![image](https://user-images.githubusercontent.com/127259/65765156-bc431d80-e127-11e9-92a0-fb92b27bb50b.png)

> QWAT works fine

this is expected since QWAT doesn't use any curved polygons.

> "PostgreSQL 9.6.14, compiled by Visual C++ build 1800, 64-bit"
"POSTGIS="2.3.0 r15146" GEOS="3.5.0-CAPI-1.9.0 r4090" PROJ="Rel. 4.9.1, 04 March 2015" GDAL="GDAL 2.1.1, released 2016/07/07" LIBXML="2.7.8" LIBJSON="0.12" RASTER"

I wonder if it could be a newer version of postgis which solve this. Are you able to try with a more recent server? (I tested with your data and couldn't replicate the issue).

**Comment by ponceta** [comment]
I solved the problem, this was linked to QGIS management of 3D entities and an issue in the geometry_column tables, not the table itself but the permissions linked to it.

In my QGEP db, qgep user had no access to public.geometry_columns...

**Solved using:**
```
GRANT ALL ON TABLE public.geometry_columns TO postgres;	
GRANT SELECT ON TABLE public.geometry_columns TO PUBLIC;
```

**Comment by ponceta** [comment]
> By default, I think it does ignore errors. At least the option is available:

Yes, but fails anyway

> I wonder if it could be a newer version of postgis which solve this. Are you able to try with a more recent server? (I tested with your data and couldn't replicate the issue).

That's because I get rid of ST_CurveToLine and curve geometries! 

We can close this.

**Comment by sjib** [comment]
May be good to add this solution to the admin doc and the doc to install the demo project - I think you are not the only that did hot have these permissions set

**Comment by ponceta** [comment]
That's a general postgis issue but we should ensure that creating a postgis database in newer versions of postgis set the correct rights to the public shema and the public geometry columns and geography columns.

I tested this on a freshly created database on postgres 9.6 :

CREATE Database test_postgis;
CREATE EXTENSION postgis;

Public geometry and geography columns are set according to what is expected here.

@3nids you're the only one who can close this.
