### ISSUE TITLE
Calculate depth is inactive (Pully_custom temp)

### ISSUE THREAD

**Issue by ponceta** [QGEP/QGEP#526]
After model updates, I don't get the depth calculation updated

Probably due to symbology functions (activate / deactivate).

A standard query using same function as qgep_od.update_depth() returns the right results.

Having a function to launch depth calculation for the whole database could be a plus!

![image](https://user-images.githubusercontent.com/8614223/67076224-03ec2080-f18d-11e9-9ecb-88f002aa2f9c.png)

**Comment by m-kuhn** [comment]
Can you describe which steps lead to non-updated depths?

> Having a function to launch depth calculation for the whole database could be a plus!

There is already the following:

```
SELECT qgep_od.update_depth(NULL, true);
```

**Comment by ponceta** [comment]
This is not the case anymore. No exact clue why, I'll comment here if I find anything regarding this.
