### ISSUE TITLE
qgep_od.catchment_area surface precision

### ISSUE THREAD

**Issue by GruBoe** [QGEP/QGEP#528]
Surface precision in gep_od.catchment_area should be set to 4 instead of 2.

**Comment by sjib** [comment]
ALTER TABLE qgep_od.catchment_area ADD COLUMN surface_area  decimal(8,2) ;
change to
ALTER TABLE qgep_od.catchment_area ADD COLUMN surface_area  decimal(8,4) ;

https://github.com/QGEP/datamodel/blob/677ec0422f2a9dba4979274490430c2d1a848fa3/03_qgep_db_dss.sql#L2669

**Comment by sjib** [comment]
Also in municipality.total_surface

ALTER TABLE qgep_od.municipality ADD COLUMN total_surface  decimal(8,2) ;
change to
ALTER TABLE qgep_od.municipality ADD COLUMN total_surface  decimal(10,4) ;

https://github.com/QGEP/datamodel/blob/677ec0422f2a9dba4979274490430c2d1a848fa3/03_qgep_db_dss.sql#L2669

    Flaeche: 0.0000 .. 100000.0000 [Units.ha];  !! Fläche ohne Seeanteil

**Comment by sjib** [comment]
See Blaudrucke https://www.vsa.ch/fachbereiche-cc/siedlungsentwaesserung/vsa-dss/blaudrucke
May be there are more updates needed from there.
