### ISSUE TITLE
Bugfixing QGEP2SWMM Plugin

### ISSUE THREAD

**Issue by sjib** [QGEP/QGEP#531]
Add bugs for QGEP2SWMM Plugin

**Comment by GruBoe** [comment]
Following information is missing in *.imp-File:
max. Depth (depending on cover level)
Diameter-Information musst be in Meters. Now the Millimeter-Info is written into the *.imp-File.
SAA Information not necessary in SWMM. Should be omitted.

**Comment by tproduit** [comment]
**Max Depth:**
Currently the max depth in the junctions is computed as follow (https://github.com/tproduit/datamodel/blob/swmm_views/swmm_views/vw_swmm_junctions.sql): 
`co.level - wn.bottom_level AS maxdepth` w
where co is the couvercle and wn the water node. If one of these two values is null the maxdepth is null.

* Is the formula correct? Or should we use the water level (if this information is available)?

**Comment by tproduit** [comment]
> Diameter-Information musst be in Meters. Now the Millimeter-Info is written into the *.imp-File.

This is solved, the view vw_swmm_xsections is updated

**Comment by GruBoe** [comment]
Max Depth:
I think your formula is right. But my result in "maxdepth" is [null]. Is there something wrong with the join itself?

**Comment by tproduit** [comment]
> SAA Information not necessary in SWMM. Should be omitted.

A constraint on the `wastewater_structure._function_hierarchic` is added.

**Comment by tproduit** [comment]
> Max Depth:
> I think your formula is right. But my result in "maxdepth" is [null]. Is there something wrong with the join itself?

Do you have null values in every row? With the demo_data, there are some null values but only where the cover level or the bottom level is not defined.
You can check with this request: `
-- manholes
SELECT
	wn.obj_id as Name,
	coalesce(wn.bottom_level,0) as InvertElev,
        co.level, wn.bottom_level,
	(co.level-wn.bottom_level) as MaxDepth,
	NULL::float as InitDepth,
	NULL::float as SurchargeDepth,
	NULL::float as PondedArea,
	ws.identifier || ', ' || ws.remark as description,
	ma.obj_id as tag,
	wn.situation_geometry as geom
FROM qgep_od.manhole ma
LEFT JOIN qgep_od.wastewater_structure ws ON ws.obj_id::text = ma.obj_id::text
LEFT JOIN qgep_od.wastewater_networkelement we ON we.fk_wastewater_structure::text = ws.obj_id::text
LEFT JOIN qgep_od.wastewater_node wn on wn.obj_id = we.obj_id
LEFT JOIN qgep_od.cover co on ws.fk_main_cover = co.obj_id
WHERE wn.obj_id is not null
AND ws._function_hierarchic in (5066, 5068, 5069, 5070, 5064, 5071, 5062, 5072, 5074)
`

**Comment by GruBoe** [comment]
> > Max Depth:
> > I think your formula is right. But my result in "maxdepth" is [null]. Is there something wrong with the join itself?
> 
> Do you have null values in every row? With the demo_data, there are some null values but only where the cover level or the bottom level is not defined.
> You can check with this request: `-- manholes SELECT wn.obj_id as Name, coalesce(wn.bottom_level,0) as InvertElev, co.level, wn.bottom_level, (co.level-wn.bottom_level) as MaxDepth, NULL::float as InitDepth, NULL::float as SurchargeDepth, NULL::float as PondedArea, ws.identifier || ', ' || ws.remark as description, ma.obj_id as tag, wn.situation_geometry as geom FROM qgep_od.manhole ma LEFT JOIN qgep_od.wastewater_structure ws ON ws.obj_id::text = ma.obj_id::text LEFT JOIN qgep_od.wastewater_networkelement we ON we.fk_wastewater_structure::text = ws.obj_id::text LEFT JOIN qgep_od.wastewater_node wn on wn.obj_id = we.obj_id LEFT JOIN qgep_od.cover co on ws.fk_main_cover = co.obj_id WHERE wn.obj_id is not null AND ws._function_hierarchic in (5066, 5068, 5069, 5070, 5064, 5071, 5062, 5072, 5074)`

There are values in "invertlev" and "bottom_level" where "maxdepth" is empty.

**Comment by tproduit** [comment]
> There are values in "invertlev" and "bottom_level" where "maxdepth" is empty.

What about level (co.level)?

**Comment by GruBoe** [comment]
> > There are values in "invertlev" and "bottom_level" where "maxdepth" is empty.
> 
> What about level (co.level)?
The column is called "level", right? there is [null] as well. By the way the columns "maxdepth", "initdepth", "surchargedepth", "pondedarea" are also [null]. The other columns do have values.

**Comment by tproduit** [comment]
> The column is called "level", right? there is [null] as well. By the way the columns "maxdepth", "initdepth", "surchargedepth", "pondedarea" are also [null]. The other columns do have values.

It looks like the height of the main cover (cover.level) is not provided in your data. is it possible?

**Comment by GruBoe** [comment]
> > The column is called "level", right? there is [null] as well. By the way the columns "maxdepth", "initdepth", "surchargedepth", "pondedarea" are also [null]. The other columns do have values.
> 
> It looks like the height of the main cover (cover.level) is not provided in your data. is it possible?

No, I already checked that. There is level information in qgep_od.cover, column "level".

**Comment by tproduit** [comment]
> No, I already checked that. There is level information in qgep_od.cover, column "level".

I checked on some manhole of the demo data: the maxdepth computed is similar to the value qgep_od.wastewater_structure._depth. This is what we want, isn't it?

**Comment by GruBoe** [comment]
> > No, I already checked that. There is level information in qgep_od.cover, column "level".
> 
> I checked on some manhole of the demo data: the maxdepth computed is similar to the value qgep_od.wastewater_structure._depth. This is what we want, isn't it?

qgep_od.wastewater_structure._depth is [null] in my data. Do I have to comupute this column first?

**Comment by tproduit** [comment]
> qgep_od.wastewater_structure._depth is [null] in my data. Do I have to comupute this column first?

No, it should be computed automatically.  I compute the maxdepth in the same way the value _depth is computed. I guess that a value is missing in your data. Maybe the bottom level? In QGIS do you have a value in the tab Wastewater node (select the waste water node) >bottom level?

**Comment by GruBoe** [comment]
> > qgep_od.wastewater_structure._depth is [null] in my data. Do I have to comupute this column first?
> 
> No, it should be computed automatically. I compute the maxdepth in the same way the value _depth is computed. I guess that a value is missing in your data. Maybe the bottom level? In QGIS do you have a value in the tab Wastewater node (select the waste water node) >bottom level?

In QGIS there is level-information for cover and bottom provided in the taps "Deckel" and "Abwasserbauwerke" but in the second tap "Main Cover/Node" there is no information at all. DE_Kote and AK_Sohlenkote are NULL.

**Comment by urskaufmann** [comment]
This looks like the bug from #430 . If there are more than one structure parts (e.g. 1 cover and 1 access aid), then there are no values shown in wn-fields. Be careful, in those cases you can delete data.
@m-kuhn : #430 is closed, but the new datamodel is not available. When will it be available?

**Comment by GruBoe** [comment]
> This looks like the bug from #430 . If there are more than one structure parts (e.g. 1 cover and 1 access aid), then there are no values shown in wn-fields. Be careful, in those cases you can delete data.
> @m-kuhn : #430 is closed, but the new datamodel is not available. When will it be available?

Hmm, this means PUM will be part of the solution...

**Comment by m-kuhn** [comment]
@urskaufmann we decided to release when the multipoint fix is in place (https://github.com/QGEP/QGEP/issues/532). We can schedule this for end of November.

@GruBoe we can also offer this as an update service for you if you would like to get this update done earlier.

**Comment by m-kuhn** [comment]
@sjib can this issue be closed? Are there open points that should be migrated to specific issues?

**Comment by sjib** [comment]
I don't see any.

**Comment by sjib** [comment]
Habe mir übrigens letzthin angeschaut, was das SWMM aus meinen Daten macht (obwohl ich SWMM nicht kenne und nicht habe und deshalb auch nicht abschliessend urteilen kann). Mit ziemlich grosser Sicherheit ist die **Doku nicht à jour**. Ich nehme an, dass da nach dem Schreiben der Doku noch einiges am Plugin geändert wurde, dass man jetzt noch aktualisieren müsste.

Und dann glaube ich festgestellt zu haben (wenn ich die SWMM-Views anschaue), dass die Einzugsgebiete wohl noch nicht vollständig (auf allen **4 Fremdschlüsseln** zu den Abwassernetzelementen) unterstützt werden. Irgendwie müsste man doch wählen können, ob man Ist oder geplant verwenden will und vermutlich müssten ja Einzugsgebiete auch doppelt vorkommen (und dann müsste vermutlich irgendwie eine Lösung für doppelte Bezeichnungen aufgezeigt oder dokumentiert sein). 

Auch gibt es noch **fixe Ersatzwerte** in den Views, die nicht aus der Datenbank kommen.
Gehe davon aus, dass da noch Arbeit nötig ist.

**Comment by m-kuhn** [comment]
@sjib I think we should open specific new issues for 

1. the foreign keys
2. the documentation
3. the substitution values

and close this placeholder issue

**Comment by sjib** [comment]
- [ ] Foreign keys see new issue https://github.com/QGEP/QGEP/issues/559

- [ ] Documentation

- [ ] Substitution values
