### ISSUE TITLE
QGIS : Draw a circular wastewater structure

### ISSUE THREAD

**Issue by ponceta** [QGEP/QGEP#537]
QGIS 3.4.13

Since actual drawing of detailled_geometry_geometry from wastewater_structures is drawing a part of a geometry and using the shape digitalisation toolbar is not available for parts of geometry, I can't draw circle shaped wastewater structures.

![image](https://user-images.githubusercontent.com/8614223/69344244-58dcf400-0c6f-11ea-9769-f8769ab128f6.png)

![image](https://user-images.githubusercontent.com/8614223/69344753-3a2b2d00-0c70-11ea-9ffe-5b0b29ae3c3f.png)

**Comment by ponceta** [comment]
Temp Python workaround by @lbartoletti :

```
from qgis.gui import QgsMapToolCapture
from qgis.utils import iface 
from PyQt5 import QtWidgets

class AddCircleFromCenterDiameter(QgsMapToolCapture):
    def __init__(self, canvas, layer, feat):
        self.canvas = canvas
        self.feature = feat
        self.layer = layer
        QgsMapToolCapture.__init__(self, self.canvas, iface.cadDockWidget(), QgsMapToolCapture.CapturePoint)

    def canvasPressEvent( self, e ):
        point = self.mapPoint(e)
        if not point.is3D():
            point.addZValue(float(QgsSettings().value( "/qgis/digitizing/default_z_value" , 0 )))
        val, ok = QtWidgets.QInputDialog.getDouble(None, "Input circle's diameter", "Diameter")
        if ok:
            circle = QgsCircle.fromCenterDiameter(point, val)
            self.layer.changeGeometry(self.feature.id() , QgsGeometry(circle.toPolygon() ))
        self.stopCapturing()    

ws_lyr = QgsProject.instance().mapLayer('od_wastewater_structure')
feature = next( ws_lyr.getFeatures( QgsFeatureRequest().setFilterExpression( 'obj_id = \'{}\''.format( '[% "obj_id" %]' ) ) ) )
ws_lyr.startEditing()
ws_lyr.selectByIds([feature.id()])
qgis.utils.iface.setActiveLayer(ws_lyr)
add_circle = AddCircleFromCenterDiameter( iface.mapCanvas(), ws_lyr, feature )
iface.mapCanvas().setMapTool( add_circle )
```

**Comment by m-kuhn** [comment]
If this is something required for production, I wouldn't mind adding something like that as a new action on the wastewater structure layer, like the rectangle tool we have.

From what I heard from @urskaufmann etc, there was no requirement for circular structures (mostly adding a point symbol for covers is enough). Can you let us know your use case?

**Comment by ponceta** [comment]
The goal here is to fix QGIS, the python action is only a short term solution.

The cover is often not aligned with the wastewater structure center. (slightly shifted)

On the cadastral part, we must know the spatial extent/occupancy of our network.

**Comment by urskaufmann** [comment]
Mostly means in case the diameter is up to 1500mm. If diameter is 2000 or more (some slurry_collectors/Schlammsammler) I draw also a circle as geometrie.

**Comment by m-kuhn** [comment]
Thanks for the clarification. Fixing it upstream sounds great.

Since it will likely take quite some time before this fix appears in an LTR (QGIS 3.16), does it make sense to ship this within the qgep project meanwhile?

**Comment by haubourg** [comment]
> Since it will likely take quite some time before this fix appears in an LTR (QGIS 3.16), does it make sense to ship this within the qgep project meanwhile?

I'd be +1 on shipping the action with the project.

**Comment by lbartoletti** [comment]
@m-kuhn @ponceta actions are exposed to QgisInterface: https://github.com/qgis/QGIS/pull/33628

**Comment by m-kuhn** [comment]
@lbartoletti will that help to digitize on an existing wastewater structure?

**Comment by lbartoletti** [comment]
@m-kuhn it will simplify my previous code. With QGIS 3.12 the action will be like the addPart action something like:

```
ws_lyr = QgsProject.instance().mapLayer('od_wastewater_structure')
feature = next( ws_lyr.getFeatures( QgsFeatureRequest().setFilterExpression( 'obj_id = \'{}\''.format( '[% "obj_id" %]' ) ) ) )
ws_lyr.startEditing()
ws_lyr.selectByIds([feature.id()])
qgis.utils.iface.setActiveLayer(ws_lyr)
qgis.utils.iface.actionCircleCenterPoint().trigger()
```

**Comment by ponceta** [comment]
@lbartoletti since the updated VM should be base on LTR version, I would propose to add your first python action to the wastewater layer for now and add either the second one OR the future mechanism next year.

**Comment by sjib** [comment]
@ponceta https://github.com/qgis/QGIS/pull/33628 has been merged. Can you document how it looks today and then close this issue?

**Comment by ponceta** [comment]
I tried it today on QGIS and had some interesting bugs.

![Digitize_circular_geometry_qgep](https://user-images.githubusercontent.com/8614223/223731147-04f82f27-fe8f-43e9-8cda-f7ca6a913c7e.gif)

**Comment by ponceta** [comment]
QGIS 3.30 Bugy too : Different error.

![image](https://user-images.githubusercontent.com/8614223/223744151-12f6f60d-3193-4dcf-992d-60dabb176efb.png)

**Comment by urskaufmann** [comment]
Circle is not a circle: looks like the circle is cut out by another surface. Looks like a snapping setting...

**Comment by ponceta** [comment]
Since 3.34.8. this is natively supported by QGIS and now well supported.
