### ISSUE TITLE
NaN value does not fit well with QGIS forms

### ISSUE THREAD

**Issue by ponceta** [QGEP/QGEP#539]
QGIS 3.4.13 Win 10 x64

When snapping to a nan value :

![image](https://user-images.githubusercontent.com/8614223/70219708-8f257380-1745-11ea-9932-782d77109ad8.png)

Impossible de valider les changements pour la couche Tronçons

Erreurs : ERREUR : 1 entités non ajoutées.
  
Erreur du fournisseur de données :
      Erreur PostGIS lors de l'ajout d'entité : ERREUR:  la colonne « nan » n'existe pas
    LINE 1: ...FALSE,NULL,NULL,NULL,'ch176dc9RP076246',NULL,NULL,nan,NULL,N...
                                                                 ^

**Comment by m-kuhn** [comment]
That's related to a default value expression that you use and not to something that is shipped with QGEP?

**Comment by ponceta** [comment]
> That's related to a default value expression that you use and not to something that is shipped with QGEP?

Probably,

Default value is :

```
with_variable(
   'result',	
	array_first(@snapping_results),
	if( 
	   layer_property(map_get(@result, 'layer'), 'name') in ('Couvercles', 'Ouvrages'),
	    z(geometry(get_feature(
		   'Noeuds_reseau', 
		   'fk_wastewater_structure', 
		   if(
				layer_property(map_get(@result, 'layer'), 'name') = 'Couvercles',
				attribute(get_feature_by_id('Couvercles', map_get(@result, 'feature_id')), 'fk_wastewater_structure'),
				attribute(get_feature_by_id('Ouvrages', map_get(@result, 'feature_id')), 'obj_id')
			)				
		))),
	   --z(geometry(get_feature_by_id(map_get(@result, 'layer'), map_get(@result, 'feature_id'))))
	   	   z( start_point( $geometry))
   )
)
```

Defined with the help of @3nids

**Comment by ponceta** [comment]
Fix in Pully, I asked @m-kuhn to search for a more general fix on QGIS.

```
with_variable(
'case_nan_value',
with_variable(
   'result',	
	array_first(@snapping_results),
	if( 
	   layer_property(map_get(@result, 'layer'), 'name') in ('Couvercles', 'Ouvrages'),
	    z(geometry(get_feature(
		   'Noeuds_reseau', 
		   'fk_wastewater_structure', 
		   if(
				layer_property(map_get(@result, 'layer'), 'name') = 'Couvercles',
				attribute(get_feature_by_id('Couvercles', map_get(@result, 'feature_id')), 'fk_wastewater_structure'),
				attribute(get_feature_by_id('Ouvrages', map_get(@result, 'feature_id')), 'obj_id')
			)				
		))),
	   --z(geometry(get_feature_by_id(map_get(@result, 'layer'), map_get(@result, 'feature_id'))))
	   	   z( start_point( $geometry))
   )
),
CASE WHEN @case_nan_value = 'nan' THEN NULL ELSE @case_nan_value END
)
```

**Comment by m-kuhn** [comment]
@ponceta the text edit widget has been adjusted to use NULL instead of NaN (in master)
