### ISSUE TITLE
Datamodel: vw_individual_surface.sql has error

### ISSUE THREAD

**Issue by urskaufmann** [QGEP/QGEP#540]
Got this error:
ERROR:  FEHLER:  Syntaxfehler bei ».« LINE 11:    IS.obj_id               ^   SQL state: 42601 Character: 206
--

IS as shortcut for individual_surface does not work.

And: pleace add this view to the datamodel, so I can use it in the demo-project

**Comment by 3nids** [comment]
If needed this view needs to be created using the automatic views creation (pirogue) and integrated into the update mechanism (dropping/recreating the views).
This is about 1h work.
Let me know if I should do it.

**Comment by m-kuhn** [comment]
@3nids please go ahead

**Comment by 3nids** [comment]
see https://github.com/QGEP/datamodel/pull/122
once merged, the view should still be added to the project.

**Comment by urskaufmann** [comment]
I will add it
