### ISSUE TITLE
VSA / Datamodel add sketch as file kind

### ISSUE THREAD

**Issue by ponceta** [QGEP/QGEP#541]
We would propose to 

 -  [x] add sketch as file kind

![image](https://user-images.githubusercontent.com/8614223/70708118-0b85fc80-1cda-11ea-966b-0c8456d310c9.png)

 - [x] And fix digital_vidoe as digital_video (typo)

**Comment by m-kuhn** [comment]
@sjib what's your opinion on this? something for the standard too?

**Comment by ponceta** [comment]
@sjib how can I suggest this to the VSA?

**Comment by sjib** [comment]
I have noted it - will be included in the coming release 2020 (about mid year)

**Comment by sjib** [comment]
Added in new Release [2019](https://www.vsa.ch/models/2019/VSA_KEK_2019_2_d_LV95-20210416.ili) and [2020](https://www.vsa.ch/models/2020/VSA_KEK_2020_2_d_LV95-20210503.ili) of VSA-KEK

Skizze was added with https://github.com/QGEP/datamodel/blob/83d652fb32767e2b304513326488bd478bf54cf0/delta/delta_1.5.6_kek_model_update_2008_2019.sql
