### ISSUE TITLE
SWMM program path

### ISSUE THREAD

**Issue by urskaufmann** [QGEP/QGEP#543]
when closing QGIS options, I get this message (I have no SWMM installed):
![swmm-err1](https://user-images.githubusercontent.com/1257403/71716384-db330900-2e14-11ea-8b2b-956bdc40e275.PNG)

**Comment by sjib** [comment]
When you don't have the SWMM file at that location you have to adapt the path or leave it empty

**Comment by m-kuhn** [comment]
This path is preconfigured in the plugin.
I would say we remove this preconfiguration and instruct people that *want* to use SWMM to configure the plugin for their system.

CC @tproduit

**Comment by tproduit** [comment]
@m-kuhn I created a pull request to solve this issue.

**Comment by m-kuhn** [comment]
@tproduit thanks a lot, it's merged.

Pro tip: If you add `fix https://github.com/QGEP/QGEP/issues/543` to the git commit message or the pull request title, issues will automatically be closed when they are merged.
