### ISSUE TITLE
GPKG Support?

### ISSUE THREAD

**Issue by Saijin-Naib** [QGEP/QGEP#545]
Is the data model potentially compatible with GPKG files for installations where a self/hosted PostGIS database isn't feasible?

**Comment by m-kuhn** [comment]
The implementation relies heavily on database logic (see https://github.com/QGEP/datamodel).

What we can propose 

- is a hosting service for you, contact us if you are interested
- While untested and not officially supported, [pglite](https://github.com/Oslandia/pglite) should be an option

**Comment by Saijin-Naib** [comment]
I took a quick look at the datamodel, and it is incredibly complex. I was hopeful that GPKG/Sqlite3 would have been mostly compatible, but I don't know enough about either SQL3 nor PostGIS to determine.

Hosting would require funding, so likely a non-starter.

pglite seems quite interesting. I'll look into that more.

**Comment by haubourg** [comment]
> I took a quick look at the datamodel, and it is incredibly complex. I was hopeful that GPKG/Sqlite3 would have been mostly compatible, but I don't know enough about either SQL3 nor PostGIS to determine.

Indeed, most applications based on QGIS and a robust database take benefit of the so called "thick database" approach - which was named so by Oracle :smile:  - and are difficult to port from one database to another one.  We have some project where we did some thick database approach using sqlite and spatialite. It works, but it reveals 3 to 4 times harder and longer to code. 

But in fact, putting this intelligence in QGIS plugins, or any other programming layer is not cheaper at all, you will have higher maintenance costs given the fast lifecycle of QGIS API.  

pglite could be a solution - but mainly was designed to workaround IT constraint that did not autorized any real server. 

I think the real solution will come from two approaches  : 

- always connected apps thanks to 4G/5G for dense and rich territories
- full postgresql support for android. It seems this is closer now :) https://twitter.com/termux/status/839539574854598656?s=20

**Comment by m-kuhn** [comment]
Add to the "real solution":

- file based (GeoPackage) checkouts of snapshots for particular use cases and synchronisation with the main database. In the short- to mid-term future we will have to work with data on sites without network coverage and without the need for the full dataset to be available for very specific use cases.

**Comment by m-kuhn** [comment]
I will close this issue as I don't think there is something we can do to "fix" it (generic GPKG support is not planned by anyone at the moment).

I'd prefer to open new issues for specific use cases (e.g. we need a new checkout interface for pipe cleaning with the following requirements: 1., 2., 3. ...)
