### ISSUE TITLE
QGIS3.10-Freeze when digitizing reach with wizard

### ISSUE THREAD

**Issue by urskaufmann** [QGEP/QGEP#546]
QGIS 3.10.x freeze after the first click with wizard - start data entry - reach. You can still move the (cross)cursor , and close the QGIS window.
No problem with wastewater structure or catchment area or when digitizing without wizard.
No problem with QGIS 3.4.x.
I tried also with new profile - but does not help.

**Comment by sjib** [comment]
![qgis_freeze3 10_koni](https://user-images.githubusercontent.com/1265865/73747583-008a9e00-4758-11ea-98f9-38958d194922.png)

**Comment by kandre** [comment]
I confirm I get the same error on QGIS 3.10.x with datamodel 1.4.

**Comment by olivierdalang** [comment]
Here's a fix : https://github.com/QGEP/qgepplugin/pull/47

@urskaufmann or @kandre are you able to test it and confirm it's working ?

**Comment by urskaufmann** [comment]
Yes it works. I can digitize reaches again.

**Comment by kandre** [comment]
@olivierdalang tested, it works again with this workaround, thanks.
