### ISSUE TITLE
Markerline and QGIS 3.10.2

### ISSUE THREAD

**Issue by urskaufmann** [QGEP/QGEP#549]
I have defined in the demo project the symbol of Layer vw_network_segment als markerline with marker placement on central point. Is useful to control the correct line direction.
With QGIS 3.10.2, if I turn on vw_network_segment as visible, QGIS shows this waiting bar and then there is no more work possible (qgis reagiert nicht).
![problem](https://user-images.githubusercontent.com/1257403/75013482-ae9a8580-5484-11ea-876e-263b32ea1bce.JPG)

If I change the marker placement to any other option than "on central point", it works. So the next best option is on central point of segments

**Comment by m-kuhn** [comment]
This could very well be fixed by https://github.com/qgis/QGIS/pull/34407
Could you try again with the next QGIS 3.10.3 release (to be released this weekend) and confirm if the issue still persists?

**Comment by urskaufmann** [comment]
I will test after holidays next week (-> 2. March)

**Comment by urskaufmann** [comment]
Not solved in QGIS 3.10.3. Still same behaviour. Works with on central point of segments, works not with on central point.

**Comment by m-kuhn** [comment]
Can you share the style as qml here?

**Comment by urskaufmann** [comment]
[vw_network_segment_on_central_point.zip](https://github.com/QGEP/QGEP/files/4277603/vw_network_segment_on_central_point.zip)

**Comment by urskaufmann** [comment]
Solved in QGIS 3.10.4
