### ISSUE TITLE
vw_network_segment: ERROR:  makeline: input must be a multipoint

### ISSUE THREAD

**Issue by sjib** [QGEP/QGEP#553]
Raphael imported data by INTERLS and gets this error when trying to "Refresh materialized view" with data vw_network_segment

> ERROR:  makeline: input must be a multipoint
> SQL state: XX000

We checked on all geometry data, about being with z-value. We found:
od_cover has coordinates everywhere but some are z = nan
reach_point has two missing coordinates and all coordinates with z = 0
wastewater_node there is one wn without coordinate and various with z = nan

If we follow [delta_1.4.0_geometry_not_null_constraints.sql](https://github.com/QGEP/datamodel/blob/master/delta/delta_1.4.0_geometry_not_null_constraints.sql) then it looks like a NULL coordinate is not possible anymore. Are we right?

**Comment by sjib** [comment]
@signedav - could you respond?

**Comment by m-kuhn** [comment]
Could you provide us with a demo data set (preferably pg dump) to have a look at this issue?

**Comment by sjib** [comment]
It is caused by empty geometry in wastewater_node. The new constraint should avoid this.
https://github.com/QGEP/datamodel/blob/master/delta/delta_1.4.0_geometry_not_null_constraints.sql
