### ISSUE TITLE
incorrect topology layer in some specific case

### ISSUE THREAD

**Issue by olivierdalang** [QGEP/QGEP#556]
In some specific cases (not sure why/when), the topology layer is incorrect, despite the reach from/to fields being correctly set. This leads to "path not found" errors with the profile tool and up/downstream tools.

Example with node ZG53 in Urs' dataset (path not found when starting from that node, but works when strating from one upstream node).

**Comment by urskaufmann** [comment]
Problem of ZG53: the second reach of Manhole ZG53 was not connected to the node ZG53, but to the reach ZG52-ZG53. So this reach overwrites the from_Obj_id of segment ZG52-ZG53 (no more the node, but the second reach).

An other (in a way similar) problem results, if there are two ore more reaches at the same point connected to another reach without node (Blindanschluss). The from_obj_id of the "main"reach can only have one value. Means network following shows not the expected result.

**Comment by olivierdalang** [comment]
As we understood during the code sprint, this issue is linked to invalid data, and it seems this wasn't due to the plugin as it doesn't seem to allow this type of errors.

So in the end I'm not really sure on what's expected for this issue ? Do we think these type of issues are very common for most users, or are they due to some specific migrations issue in the past ?

If we think this is common, what I could see is some kind of validation tool, which would be a set of queries to identify invalid data. In this case, we should probably start by making a list of these issues. Depending on the complexity of the queries, we could maybe also validate on the datamodel directly using a trigger.

If we don't think this is common, I'd suggest closing the issue as it's not really a QGEP issue directly.

**Comment by urskaufmann** [comment]
It's not the invalid data of the demoproject. And I can reproduce this type of error with the plugin very well. The thing is: a segment has one field from_obj_id and one field to_obj_id. If there are two objects to be connected at the same point, it does not work. The two examples I described above:
1. if there is at the end of a (first) reach another (second) reach connected direct (not over a node) and there is also a node, then in the from_obj_id-field is the node-obj_id overwritten by the reach-obj_id. If the second reach is just one millimeter "inside" of the first reach, then topology creates an additional node and every thing works. 
2. If there are 2 reaches (reach 2 and 3) connected to the first reach at exactly the same point (snapping!), then you have 2 reachpoints (which get vw_network_nodes) at the same place, but the segment can only connect to one of these nodes. If I split the first reach at the connenction point and add a wastewater_node, it would work. But I (and the VSA-Erfassungsgrundsätze) do not want to add such nodes in swwf-networks nor in pwwf-networks .

**Comment by m-kuhn** [comment]
Good points.
Having multiple blind connection at exactly the same spots has not been handled. The issue that multiple nodes in the network_node layer are created (where they should be collapsed into a single one) sounds reasonable.

> The thing is: a segment has one field from_obj_id and one field to_obj_id. If there are two objects to be connected at the same point, it does not work

That should not be an issue, as in the created network, there are no more blind connections. Everything is connected via nodes.

Another case I just found in the arbon demo data:

![par](https://user-images.githubusercontent.com/588407/76598107-652cdb80-6502-11ea-81cf-3871e3324f08.png)

Can you confirm that this is invalid data @urskaufmann

**Comment by urskaufmann** [comment]
Yes, that is not correct. They should not be connected to each other. At the end of both reaches should be a third reach (with or without wastewater node) or a wastewater_structure with node. And this two reaches should be connected to this third reach or to this node.
