### ISSUE TITLE
SWMM Views - Catchments planned / current

### ISSUE THREAD

**Issue by sjib** [QGEP/QGEP#559]
Adapt 09_vw_swmm_subcatchments.sql:
- [ ] qgep_swmm.vw_subcatchments - duplicate and make a version for qgep_swmm.vw_subcatchments_current and qgep_swmm.vw_subcatchments_planned

- [ ] same thing for qgep_swmm.vw_subareas

Add in processing tools:
- [ ] Add parameter in processing to select only planned or current catchments and subcatchments (fk_wastewater_networkelement_rw_current or fk_wastewater_networkelement_rw_planned) and dry weather flow (Catchment_area.population_density_current or Catchment_area.population_density_planned) (see #560 )

The inp file will then be created for the planned or the current status. If both are needed process has to be redone with other selection

**Comment by tproduit** [comment]
Should we also accordingly select the wastewater structures with status 7959; other.planned?

**Comment by tproduit** [comment]
I think that the simplest way to solve it is to:
-  have an input value in `SWMM Create Input` function to choose `current` or `planned`
-  add in the involved views an attribute state (`current` or `planned`) and select the objects to generate the input file.

**Comment by tproduit** [comment]
See also the discussion here: https://github.com/QGEP/QGEP/issues/592

**Comment by m-kuhn** [comment]
Agreed on https://github.com/QGEP/QGEP/issues/559#issuecomment-598169857

**Comment by sjib** [comment]
@tproduit Is this all solved now - can we close this issue?

**Comment by m-kuhn** [comment]
CC @olivierdalang you have been working on this?

**Comment by tproduit** [comment]
Yes these issues  are solved (once merged)

**Comment by m-kuhn** [comment]
@tproduit which pull request solves this?

**Comment by tproduit** [comment]
> 
> 
> @tproduit which pull request solves this?

https://github.com/QGEP/datamodel/pull/163
https://github.com/QGEP/qgepplugin/pull/55

**Comment by m-kuhn** [comment]
Can you edit these pull request descriptions and add `Fixes https://github.com/QGEP/QGEP/issues/559` to the description? That will help for the review process and will close this issue when merged.
