### ISSUE TITLE
SWMM Views - Default values only if no data available

### ISSUE THREAD

**Issue by sjib** [QGEP/QGEP#561]
Adapt 09_vw_swmm_subcatchments.sql:

qgep_swmm.vw_subareas:
- [x] get infiltration parameter from od_surface_runoff_parameters if available

**Comment by tproduit** [comment]
Adressed in https://github.com/QGEP/datamodel/pull/131

**Comment by tproduit** [comment]
@sjib can we close this issue as it should be solved?
