### ISSUE TITLE
SWMM Phase 2 requirements

### ISSUE THREAD

**Issue by tproduit** [QGEP/QGEP#564]
### Import computed values in the model

- Do we want / need to import the computed values:

    -  in the table `qgep_od.measurement_result`?

    -  Since the computed values are not real measurements should we consider to add new tables in the model to store them? Eventually in the `qgep_swmm` schema?

- Or do we keep the results outside from the model:
    - in SWMM output file?

    -  in another format (.csv)?

### Create QGIS project with appropriate symbology to link geometry and results 
If the results are stored in the database we will probably generate new views.

If the results are stored in another format we could create a QGIS Processing Modeler.

Which QGEP member could provide us some example of appropriate symbology?

@sjib

**Comment by m-kuhn** [comment]
Are these results something mostly for "internal use" or something that is expected to be delivered somewhere (via Interlis / xtf)?
Are these results something you will keep in an archive (e.g. calculations for 2020, calculations for 2025, ...), together with the inp/out files?

**Comment by sjib** [comment]
Für Simulationsresultate aus Hydraulikprogramm: 

Für jedes Abwasserbauwerk, welches Resultate erhalten soll, braucht es eine Messstelle.  
Oder braucht es eine neue Beziehung auf Abwassernetzelement, damit man auf Abwasserknoten und Haltung referenzieren kann? 

 
**Messtelle**:
Messtelle.Bezeichnung gleich setzen wir Bezeichnung Abwasserbauwerk (Kanal, Normschacht, Spezialbauwerk resp. Abwasserknoten / Haltung). 
 
Messtelle.Art {Text}: z.B. “SWMM Simulationen” - allenfalls auch allgemeiner "HydraulischeSimulationen" und dann erst mit Messreihe.Bezeichnung unterscheiden, damit man für andere Simulationsprogramme nicht eine zusätzliche Messstelle erfassen muss. Für physische Messstelle eigene Messstelle erfassen (dann eher aufs Bauwerk)
Messstelle.Zweck = technischer_Zweck 
Messstelle.AbwasserbauwerkRef  resp. AbwassernetzelementRef

 
**Messreihe**:
Messreihe.Art [andere, kontinuierlich, Regenwetter, unbekannt] - müsste man da noch etwas ergänzen? 

Messreihe.Bezeichnung {Text} Name des Szenarios z.B. “Regen z5 St. Gallen” (oder Messreihe.Bezeich 

Messreihe.Dimension {Text}: Dimension des Resultats z.B. l/s 

Messreihe.MessstelleRef 

 
**Messresultat**:
Entweder nur ein Wert oder auch ganze Zeitreihe des Szenarios 

Messresultat.Bezeichnung {Text}: z.B. “maximaler Durchfluss” 

Messresultat.Messart [andere, Durchfluss, Niveau, unbekannt]: für Simulation = andere 

Messresultat.Messdauer {s}: leer lassen oder Zeitschritt der Simulation einfügen 

Messresultat.Wert = z.B. 10.0 

Messresultat.Zeit = {Datum mit Uhrzeit dd.mm.jjjj hh:mm:ss} 

Messresultat.MessreiheRef 

 
**Messgeraet**:
Messgeraet – bei Simulationsresultaten nicht erfassen. Bei effektiven Messstellen erfassen. 

@tproduit @urskaufmann Was meint ihr?

**Comment by sjib** [comment]
There are also two attributes for hyrdraulic results directly on reach and node:
wastewater_node.backflow_level (Abwasserknoten.Rueckstaukote): 1. Relevant backflow level based on the calculation rain (dss) 2. Height below which special measures against backflow are to be taken within the property drainage system. (DIN 4045)

HydrBelastung_Ist: Dimensioning of the discharge divided by the normal discharge capacity of the line [%].

Der massgebende Regen ist bei einer Jährlichkeit von z=5 normalerweise

**Comment by sjib** [comment]
![subsystem messung](https://user-images.githubusercontent.com/1265865/78279420-c64f3a00-7517-11ea-887d-ee57aebd2a98.png)

**Comment by tproduit** [comment]
> **Messgeraet**:
> Messgeraet – bei Simulationsresultaten nicht erfassen. Bei effektiven Messstellen erfassen.

Should we insert here the name of the Software?

**Comment by sjib** [comment]
No I don't think. As this is not something physical. You have the software in the scenario

**Comment by tproduit** [comment]
Currently we load the following values (extracted from the **summary** , there is only one value stored for the maximum / average): 

### Nodes
* average_depth
* maximum_depth
* maximum_hgl (Maximum hydraulic head)
* time_max_day
* time_max_time
* reported_max_depth

### Links
* maximum_flow
* time_max_day
* time_max_time
* maximum_velocity
* max_over_full_flow
* max_over_full_depth

If I read you well, we will import the computed values in the current QGEP model like this:
* values > mesurement_results.value
* time_max_day, time_max_time > measurement_result.time
* Type of value (average_depth, maximum_depth ...) > measurement_result.remark? (We do not have measurement_result.description.)
* unit > measurement_series.dimension
* name of the simulation > measurement_series.remark (We do not have measurement_resultat.description.)

I must admit that I'm not conviced by trying to trick the current model to import the simulated values in the measurements tables. I would prefer to change the model to match our needs.

**Comment by sjib** [comment]
Solved with https://github.com/QGEP/qgepplugin/pull/60

**Comment by sjib** [comment]
Documentation of these new features: https://qgep.github.io/docs/qgep_swmm/Extract-Results.html and following chapters
