### ISSUE TITLE
[SQL] How to display the Xth photo from a wastewater structure

### ISSUE THREAD

**Issue by ponceta** [QGEP/QGEP#567]
I search to expose the first and second picture of a wastewater structure in an export view. (and maybe the Xth if needed)

What I achieved so far is to expose the first and the last picture, playing with min() and max() aggregate functions :

```
SELECT ws.obj_id,
min(file._url) AS url --First image URL
FROM qgep_od.vw_qgep_wastewater_structure ws 
LEFT JOIN qgep_od.vw_file file ON ws.obj_id = file.object
WHERE file.file_kind = '3772' --Filter only images
GROUP BY ws.obj_id
```

AND 

```
SELECT ws.obj_id,
max(file._url) AS url,
count(*) AS nbre_photos --usefull to avoid selecting the last image when it is the same as the first one.
FROM qgep_od.vw_qgep_wastewater_structure ws 
LEFT JOIN qgep_od.vw_file file ON ws.obj_id = file.object
WHERE file.file_kind = '3772'
GROUP BY ws.obj_id
```

**Comment by m-kuhn** [comment]
Hi @ponceta 

How is the order defined? The first uploaded picture (identified by lowest object id)?

**Comment by ponceta** [comment]
> Hi @ponceta
> 
> How is the order defined? The first uploaded picture (identified by lowest object id)?

Yes!

**Comment by m-kuhn** [comment]
I'll have a look :+1: 

It will be handled as "support request" in the first place. Can you clarify on the "feature" tag, is this meant to be of "public interest" and for integration into the main repository or as a customization for Pully?

**Comment by ponceta** [comment]
Thank you!

It is a specific "support request" for Pully, but it could be of some interest for others, that's why the "feature" tag.  Someone will maybe come in some times with the same need in the future.

**Comment by m-kuhn** [comment]
Something like this?

```
SELECT obj_id, url
FROM (
  SELECT ws.obj_id AS obj_id,
  file._url as url,
  rank() OVER (PARTITION BY ws.obj_id ORDER BY file.obj_id ASC) as file_index
  FROM qgep_od.vw_qgep_wastewater_structure ws 
  LEFT JOIN qgep_od.vw_file file ON ws.obj_id = file.object
  WHERE file.kind = 3772 -- Filter only images
) AS files
WHERE file_index = 2 -- Index starts at 1
```

**Comment by m-kuhn** [comment]
@ponceta is this sufficient?

**Comment by ponceta** [comment]
Yes thank you!

Works with : https://github.com/QGEP/datamodel/pull/135

Or 

SELECT obj_id, url
FROM (
  SELECT ws.obj_id AS obj_id,
  file._url as url,
  rank() OVER (PARTITION BY ws.obj_id ORDER BY file.obj_id ASC) as file_index
  FROM qgep_od.vw_qgep_wastewater_structure ws 
  LEFT JOIN qgep_od.vw_file file ON ws.obj_id = file.object
  WHERE file.file_kind = 3772 -- Filter only images --boring syntax
) AS files
WHERE file_index = 2 -- Index starts at 1
