### ISSUE TITLE
qgis to swmm

### ISSUE THREAD

**Issue by trasto21** [QGEP/QGEP#571]
i'm trying to use your plugin with qgis 3.12.2 but there are any missing content in the downloaded file. i need a procedure to import in swmm 5.1 from a qgis' shape file. i hope you can send me a solution.
thanks

Valerio

**Comment by m-kuhn** [comment]
Hi Valerio,

This is an integrated solution with a database backend. You will need to set up the complete infrastructure (https://qgep.github.io/docs/)

**Comment by trasto21** [comment]
thanks for the solution, i I hoped there was a procedure in localhost without needing to install a database server

**Comment by m-kuhn** [comment]
It may be possible to manually craft the input data structure required for the export. Better contact @tproduit or opengis for a support request about this topic.

**Comment by tproduit** [comment]
@trasto21 currently the export function read data stored in the QGEP datamodel. It will not work with ESRI shape file. You might be also interested in the plugin [qgis-swmm](https://github.com/Oslandia/qgis-swmm) but it also need you to import the data in a PostGIS database but is lighter than QGEP. It could be possible to use the existing code to read shape file but it would require a consequent job (that OpenGIS, oslandia or ig-group.ch could do if you are not a developer).
