### ISSUE TITLE
Refresh topology: Error : Status 7 when trying to refresh

### ISSUE THREAD

**Issue by MoritzBrennecke** [QGEP/QGEP#577]
In Journal de Messages: Postgis: 
WARNING    Requête erronée : REFRESH MATERIALIZED VIEW qgep_od.vw_network_node; a retourné 7 [ERREUR: la transaction est annulée, les commandes sont ignorées jusqu'à la fin du bloc de la transaction).
Same with qgep_od.vw_network_segment.
Checked writing rights with in postgres: Everything given.

**Comment by m-kuhn** [comment]
Can you retry with datamodel 1.5 and the latest plugin?

**Comment by MoritzBrennecke** [comment]
Updated datamodel (with our batch file), plugin and even the qgs file -> Same issue.

**Comment by m-kuhn** [comment]
This is related to the specific database setup. We will need to get more information from your database to see what's going on.

Can you execute the following command through db manager (in qgis) or pgadmin. Make sure you use the same login as configured in qgis to connect to the database.

```
REFRESH MATERIALIZED VIEW qgep_od.vw_network_node;
```

**Comment by MoritzBrennecke** [comment]
We configured TF_EDIT and not postgres. So the REFRESH MATERIALIZED VIEW qgep_od.vw_network_node; works. The error changed:
Error : Status 7 (ERREUR: droit refusé pour le schéma qgep_network
             LINE 1: SELECT qgep_network.refresh_network_simple();
User rights where granted using the grant wizard, and TF_EDIT could execute.
So what I did (and I don't think it is the right thing: Right click on the qgep_network schema -> Properties -> Security -> Give TF_EDIT right of usage and create. Worked.

**Comment by MoritzBrennecke** [comment]
NEW ERROR:
2020-06-22T11:58:33     CRITICAL    Error : Status 7 (ERREUR: la fonction st_line_substring(geometry, double precision, double precision) n'existe pas
             LINE 6: ST_Line_Substring(
              ^
             HINT: Aucune fonction ne correspond au nom donné et aux types d'arguments.
             Vous devez ajouter des conversions explicites de type.
             QUERY: INSERT INTO qgep_network.segment (segment_type, from_node, to_node, ne_id, geom)
              SELECT 'reach',
              sub2.node_id_1,
              sub2.node_id_2,
              obj_id,
              ST_Line_Substring(
              ST_CurveToLine(ST_Force2D(progression_geometry)), ratio_1, ratio_2
              )
              FROM (
              -- This subquery uses LAG to combine a node with the next on a reach.
              SELECT LAG(sub1.node_id) OVER (PARTITION BY sub1.obj_id ORDER BY sub1.ratio) as node_id_1,
              sub1.node_id as node_id_2,
              sub1.progression_geometry,
              LAG(sub1.ratio) OVER (PARTITION BY sub1.obj_id ORDER BY sub1.ratio) as ratio_1,
              sub1.ratio as ratio_2,
              obj_id
              FROM (
              -- This subquery joins blind node to reach, with "ratio" being the position of the node along the reach
              SELECT r.obj_id,
              r.progression_geometry,
              n.id as node_id,
              ST_LineLocatePoint(ST_CurveToLine(r.progression_geometry), n.geom) AS ratio
              FROM qgep_od.reach r
              JOIN qgep_network.node n ON n.ne_id = r.obj_id
              ) AS sub1
              ) AS sub2
              WHERE ratio_1 IS NOT NULL AND ratio_1 ratio_2
             CONTEXT: fonction PL/pgSQL qgep_network.refresh_network_simple(), ligne 36 à instruction SQL
             )

**Comment by m-kuhn** [comment]
The latest error looks like there is a problem accessing `postgis` functionality.
I assume postgis is installed to the default location, the `public` schema (otherwise there would be many more problems). Can you verify the permissions for the user in question for `EXECUTE` on schema `public`?

**Comment by MoritzBrennecke** [comment]
Granted UC rights to TF_EDIT and used grant wizard for all objects in schema public.
Same error.

**Comment by m-kuhn** [comment]
I think we need a remote desktop.

**Comment by m-kuhn** [comment]
`ST_Line_Substring` is a legacy name for postgis versions < 2.1 (2.1 was EOL 19.09.2017). The function should use the new name `ST_LineSubstring` instead.

**Comment by m-kuhn** [comment]
@MoritzBrennecke can you test if it fixes the problem if you execute the following snippet on your database?

https://github.com/QGEP/datamodel/blob/ecda2f8c4a6b3ddac466730ae3ec1fa6d6998975/delta/delta_1.5.1_fix_network_tracking_views.sql#L27-L137

**Comment by MoritzBrennecke** [comment]
Executing the yellow part (otherwise error) works and refresh toplogy gives this error: 2020-06-22T15:50:10     CRITICAL    Error : Status 7 (ERREUR: doit être le propriétaire de la vue matérialisée vw_network_node
             CONTEXT: instruction SQL « REFRESH MATERIALIZED VIEW qgep_od.vw_network_node »
             fonction PL/pgSQL qgep_network.refresh_network_simple(), ligne 106 à instruction SQL
             )

**Comment by MoritzBrennecke** [comment]
So if I choose TF_EDIT as "owner" of the materialized views, it works and even the profile tool. But shouldn't be postgres the owner?

**Comment by m-kuhn** [comment]
@olivierdalang I wonder if it would be easier to just drop the materialized views. I don't think they are needed any more and handling them seems to be tricky.
@MoritzBrennecke can you try to run https://gist.githubusercontent.com/m-kuhn/0d15e65b6dca6ff21241e2d4c850c9eb/raw/92bac92bcd709272b8af22c1904225a790a8a33b/refresh_network_simple.sql (reset the owner of the views to postgres and execute this script as postgres)

**Comment by MoritzBrennecke** [comment]
I did run the script, everything seems fine, but I still got the materialized views.

**Comment by m-kuhn** [comment]
Perfect :+1: they are not removed for now, just repaired.

**Comment by MoritzBrennecke** [comment]
You are sure the profile tool does not use the materialized view #583
