### ISSUE TITLE
PUM documentation

### ISSUE THREAD

**Issue by varrieta** [QGEP/QGEP#578]
PUM documentation on Opengis github (https://github.com/opengisch/pum) is more complete than the one we have in the QGEP documentation (https://qgep.github.io/docs/admin-guide/db-update-pum/index.html)

Wouldn't it be better to put a link to opengis PUM documentation? And only describe the qgep specification (if any) in the qgep doc? 

@ponceta should it be the same for QWAT?

**Comment by ponceta** [comment]
Did you encounter any troubles using PUM on QGEP or QWAT?

I propose this https://github.com/QGEP/docs/pull/127

**Comment by varrieta** [comment]
No any troubles using PUM with QGEP. Didn't try yet with QWAT

Thanks @ponceta for the mention. 

I also added QGEP/docs#128

The doc will have to be modified since windows can also be used now. I propose to close and refer to QGEP/docs#107
