### ISSUE TITLE
Hydraulik Streichwehr etc. in QGEP - Ergänzung Demoprojekt

### ISSUE THREAD

**Issue by sjib** [QGEP/QGEP#579]
Wo sind die verschiedenen hydraulischen Elemente in QGEP?

Dieser Teil des Modells ist bisher im Demoprojekt noch nicht fertig abgebildet. (Im Moment könnte man in dem Zusammenhang mindestens teilweise eher von QAbwasserLK und nicht von QGEP sprechen, aber die meisten bisherigen Anwender begnügen sich mit dem Werkplan...).

Dass diese Überlaufelemente in die Datenbank gehören und von dort zum Hydraulikprogramm exportiert werden, ist genau der richtige Weg.

Diese sollen der Doku oder dem Demoprojekt noch ergänzt werden:

Hier mal eine **Kurzanleitung**:

Die Views für die Überlaufklassen (Streichwehr, Leapingwehr, Förderaggregat, Drosselorgan) sind im Demoprojekt vorhanden und sie sollten auch konfiguriert sein (Wertbereiche, Wertlisten)

![Streichwehr](https://user-images.githubusercontent.com/1265865/85196078-ea7d1480-b2d7-11ea-9451-55f976a65d2b.PNG)

Was fehlt sind die Verknüpfungen. Diese müssen im Projekt/Eigenschaften/Relations definiert werden. Die Verknüpfung geht immer von vw_wastewater_node / obj_id zum z.B. vw_prank_weir / fk_wastewater_node.

![Projekteigenschaften](https://user-images.githubusercontent.com/1265865/85196091-fb2d8a80-b2d7-11ea-90bb-bf2b2d093d4d.PNG)

Sobald diese Verknüpfung im Projekt existiert, kann über den Layer vw_wastewater_node so ein Überlaufelement erfasst / geändert / gelöscht werden. Der zweite Fremdschlüssel "UeberlaufNach", welche diese Klassen haben, ist vermutlich mit QGIS-Bordmitteln kaum einfach zu erfassen. Am einfachsten im Moment diese Fremdschlüssel manuell hineinkopieren.

Im Prinzip steht das Überlaufelement dann auch unter der vw_qgep_wastewater_structure und dort unter wastewater_node zur Verfügung. Man kann dann aber nicht mehr grafisch auf den richtigen Abwasserknoten zugreifen, wenn man mehr als einen Knoten hat.

**Comment by urskaufmann** [comment]
Integrated in project file since June 2021, also  a chapter in the Docu
