### ISSUE TITLE
Forms for object oriented (Multiple) parent layers

### ISSUE THREAD

**Issue by m-kuhn** [QGEP/QGEP#58]
The relation reference widget needs to be improved to support object oriented parent tables.

E.g. a cover has a wastewater structure as parent. This can be of type manhole, special structure etc. This is a problem because depending on the type a different form needs to be shown.

An approach would be to define multiple relations for the same foreign key, pointing to different tables (views in our case). When searching for the parent feature a query is sent to all possible layers and the first found feature will be used (with the form of the appropriate layer).
When adding a feature, a combobox can be used to switch between the different possible layers.

**Comment by sjib** [comment]
write some python code for a custom identify tool that determines the proper waste water structure from a cover

**Comment by m-kuhn** [comment]
Resolved with vw_qgep_cover etc.
