### ISSUE TITLE
Channel detailed geometry

### ISSUE THREAD

**Issue by varrieta** [QGEP/QGEP#584]
It is written in the doc that detailed geometry shouldn't be created for channel.

http://qgep.github.io/docs/en/user-guide/digitizing/digitizingdetailedgeometry.html

@sjib  Why so and how to represent them then?

**Comment by sjib** [comment]
Usually there is enough information for the channel with the profile information you give it in the reach (clear_height, pipe_profile.height_width_ratio, pipe_profile.profile_type and the reach.progression)

An exception can be if you have a storage channel that is not a standard pipe. Then you could add a detailed_geometry as for a special_structure.
