### ISSUE TITLE
Moving wastewater node

### ISSUE THREAD

**Issue by varrieta** [QGEP/QGEP#585]
QGEP version 1.5

When moving the wastewater node of a structure, the reaches that are connected don't follow like they would do if the wastewater_structure was moved (image below).

![image](https://user-images.githubusercontent.com/20111558/86001843-c88a3d00-ba0f-11ea-9c73-873294ae6c0e.png)

![image](https://user-images.githubusercontent.com/20111558/86001886-d93ab300-ba0f-11ea-96ed-5bbed93b60f7.png)

Is that correct?

**Comment by m-kuhn** [comment]
Yes, this is by design.
Reaches and wastewater nodes do not necessarily need to be connected spatially, so it's possible to move them individually.

**Comment by varrieta** [comment]
Ok thanks Mathias
