### ISSUE TITLE
Delete reach not working

### ISSUE THREAD

**Issue by varrieta** [QGEP/QGEP#586]
When I create a reach and don't refresh the topology, I can delete it

As soon as I refresh the topology I can't delete it anymore and I get the error message below.

`
2020-07-01T14:30:58     WARNING    Requête erronée : DELETE FROM "qgep_od"."vw_qgep_reach" WHERE "obj_id"::text='ch19y4z2RE001322' a retourné 7 [ERREUR: UPDATE ou DELETE sur la table « wastewater_networkelement » viole la contrainte de clé étrangère
             « segment_ne_id_fkey » de la table « segment »
             DETAIL: La clé (obj_id)=(ch19y4z2RE001322) est toujours référencée à partir de la table « segment ».
             CONTEXT: instruction SQL « DELETE FROM qgep_od.wastewater_networkelement WHERE obj_id = OLD.obj_id »
             fonction PL/pgsql qgep_od.on_reach_delete(), ligne 11 à instruction SQL
             ]
`
(I'm working on one of my database in version 1.5)

**Comment by m-kuhn** [comment]
Thanks @varrieta 

What do you think, @olivierdalang `ON DELETE CASCADE`, no more fkey or something else?

**Comment by olivierdalang** [comment]
There's a missing `ON DELETE CASCADE` on the network views, proposed fix on PR

**Comment by DflGruBoe** [comment]
Is it fixed with version 1.5.2? @olivierdalang

**Comment by olivierdalang** [comment]
@DflGruBoe Yes it should be fixed
