### ISSUE TITLE
 A lot of CPU use when turning on Topology layer

### ISSUE THREAD

**Issue by sjib** [QGEP/QGEP#587]
Ich habe folgende Rückmeldung von einem Kunden, der QGEP am Testen ist:

Nach dem Anhaken von „Topology“ ist der Rechner zu 100% ausgelastet. Die vollständige Systemauslastung dauert sehr lange an. / When activating the Topology layer the computers CPU usage is very high.

![Topology_Rechnerauslastung_100](https://user-images.githubusercontent.com/1265865/86465756-91c76600-bd32-11ea-8576-9349eeef87d5.JPG)

Nach dem Abhaken von „Topology“ dauert der Wiederaufbau des Kanalnetzes (vw_qgep_reach) sehr lange – danach stürzt QGIS ab.

Bei mir selber sind es nicht 100% aber auch eine sehr hohe lange Auslastung. Beim Abklicken stürzt mir QGEP nicht ab, aber die hohe CPU Auslastung bleibt.

Was verursacht die hohe Aktivität der CPU mit QGIS? / What is the reason that QGIS is consuming that much CPU capacity when acitivating / deactivating the Topology layer?

**Comment by sjib** [comment]
![Absturz_2](https://user-images.githubusercontent.com/1265865/86466390-d0a9eb80-bd33-11ea-97f3-ec4f35e446eb.JPG)

**Comment by m-kuhn** [comment]
Kommt die Auslastung von QGIS oder von Postgis?

**Comment by urskaufmann** [comment]
Remembers me at the problem #549 
Is this with QGIS 3.10.3 or earlier?
Try this: Before turning on the topology change the symbol of  vw_network_segment. Change the definition of the markerline to somewhat else than placement on central point.

**Comment by sjib** [comment]
![vw_network_segment_markerline_placement_central_point](https://user-images.githubusercontent.com/1265865/86735038-c1c48100-c032-11ea-91e8-078a953da3c4.jpg)

**Comment by urskaufmann** [comment]
Genau, dort "auf Mittelpunkt" nicht verwenden wenn QGIS < 3.10.4. "auf Segmentmittelpunkten" geht.
