### ISSUE TITLE
Delete structure detailed geometry

### ISSUE THREAD

**Issue by varrieta** [QGEP/QGEP#590]
When you delete the detailed geometry of a structure, the structure itself get deleted.

**Comment by m-kuhn** [comment]
Can you provide detailed steps how you delete the structure?

**Comment by varrieta** [comment]
Sure,

1. Select the structure in the layer vw_qgep_wastewater_structure loaded with the field "detail_geometry_geometry" as geometry (picture below)
![image](https://user-images.githubusercontent.com/20111558/88297614-6667e380-cd00-11ea-8bbc-ceae3e29725f.png)


2. Delete the structure

I guess we should better cut the structure? Would the field "detail_geometry_geometry" be empty then?

**Comment by m-kuhn** [comment]
Use the "delete part" tool for this task.
Can I ask you to add this to the documentation?
