### ISSUE TITLE
Create a template for issues

### ISSUE THREAD

**Issue by ponceta** [QGEP/QGEP#597]
To enhance issues description, add a template for issues :
- [x] **Versions** used
OS : Win/Mac/Linux / QGIS : X.X.X (build_number) / datamodel : X.X.X / plugin : X.X.X
Hint comments to find versions
- [x] **Description** / What went wrong
- [x] **Expectation** / What was expected
- [x] **How to reproduce**
- [x] **Additional informations** and screenshots / error log (If appliable)

Please check before submitting (if possible)

- [x] Did you check for an existing issue?
- [x] Test with latest qgep datamodel and demodata and project?

Thoughts? Rewords?

Edited : add error log

**Comment by sjib** [comment]
Sounds good to me. Herr is how to include a template: https://docs.github.com/en/github/building-a-strong-community/configuring-issue-templates-for-your-repository

May be we should discuss other issue categories : Feature proposition, missing documentation, ...

**Comment by ponceta** [comment]
Some part of it could be managed like actually with labels.

https://docs.google.com/presentation/d/1guoX8ps1rhBQmwknDycv8Zs7Pu0APk39PzQPOASHv6I/edit#slide=id.p

@sjib maybe a codesprint4 label could be a good idea to see motivations towards next Codesprint on nov 6th.

**Comment by olivierdalang** [comment]
I'd add "error log (if applicable)", and maybe short comments about where to find the QGIS/datamodel/plugin versions.

**Comment by ponceta** [comment]
Please Checklist before submitting if possible

- [ ] Did you check for an existing issue?
- [ ] Test with latest qgep datamodel and demodata and project?

**Comment by ponceta** [comment]
![image](https://user-images.githubusercontent.com/8614223/98382765-e6b21a80-204b-11eb-8577-e2baf6429a5d.png)

**Comment by ponceta** [comment]
Let the user choose the pre-defined typology of issue, question or feature request.

Keep it simple for the user too.

**Comment by ponceta** [comment]
Thanks @olivierdalang
