### ISSUE TITLE
Selection of subnetwork and connected table based on various selection criteria

### ISSUE THREAD

**Issue by sjib** [QGEP/QGEP#603]
## General information

- Applicant:  Alexandre Bosshard and Stefan Burckhardt, coordinators and project leaders of the QWAT/QGEP group
- Developer: OPENGIS.ch GmbH
- User group referent: Urs Kaufmann, Holinger Thun
- Developments referent: Olivier Dalong, Opengis

### Graphical identity / Logo

_Illustrations if applicable._

### Description of users and administrators feature requirements

This feature should allow any GIS administrator or trained QGIS user to
a) Select a subnetwork and connected catchments and other linked tables
b) Choose from different selection criteria for subnetworks such as special structures upstreams and other

#### General requirements

See general requirements of [QGEP #600 ](https://github.com/QGEP/QGEP/issues/600).

#### Specific requirements (QGEP and VSA-KEK #600 and Selection of subnetworks only)

Necessary features:
Extension of the current plugin feature "Upstreams" and "Downstreams"

Selection criteria for subnetworks such as special structures upstreams:
- we have a function that allows to select a start point based on the vw_qgep_wastewater_structure to hightlight all elements **downstreams**
- we have a function that allows to select a start point based on the vw_qgep_wastewater_structure to hightlight all elements **upstreams**
- we would need additional functionality to **limit the selection upstreams or downstreams by a trigger criteria**: 
  -- select only until next special structure or 
  -- stammkarte or 
  -- as long as function_hierarchic is PAA_*
  -- etc. (to do discuss further use cases)
- Store this selection in QGIS for further actions.

Selection of subnetwork and connected catchements and other linked tables:
- QGEP cannot store the selection above currently to make further selections such as
  -- adding all connceted catchements
  -- adding all other network elements such as waste_water_node, BauwerksTeil, pumps, ... (whatever is linked in the data structure)
 -- summing up attribute values (existing feature)
 -- some more thoughts have already been discussed #216 

New function that allows to clicke on "Add connected elements" and a wizard where the user can change the proposed select all selection (e.g. only catchements).

This would be the basis to make a correct INTERLIS export e.g. for a TV inspection company or to another engineering company or the community or the canton. Some consideration and discussion about this has already taken place in #218 

Import:
- see #600 

Export
- see #600 

### Illustrations of the features and the requirements

_Schemes, screen captures, or any other illustrations._

Further details in here:
- gepview_doku Kapitel 2.5.3 - 2.5.5 zu diesen Themen: Netzverfolgung, Summieren, Stammkarten, Selektion erweitern. (UK)

### Feasibility study

Feasibility, options, alternatives and technical specificities

### Mutualisation 
_Mutualisation and possible impacts with other projects (QGIS, QWAT, QGEP)_

Selecting a subset of data in QGEP and having the option to 
- store it some way for temporary use
- do any operation with it such as QGIS operations or export or setting a comon attribut or whatever action 
could be interesting for different other daily workflows too.

## Cahier des charges et offres ( Developer)
Not shared on Github.

### Tenders

Not shared on Github.

### Timeline / deadlines

- [x] 01.09.2020 : Contract signature

- [x] 11.09.2020: Preliminary meeting for user needs

- [x] ~~30.09.2020~~: Draft for user needs and specifications

- [x] 30.10.2020: User needs and specifications delivered to the developer

- [x] 31.12.2020: 1st intermediate report to NGDI (Stefan)

- [x] 28.02.2021: VSA-KEK INTERLIS import/export interface release (and demo ?)

- [x] ~~30.01.2021~~31.03.2021: SIA 405 INTERLIS import/export interface release (and demo ?)

- [x] 31.03.2020 - 30.04.2021 : Quality control and bug fixing

- [x] 31.04.2021: 2nd intermediate report to NGDI (Stefan)

- [x] 31.05.2020: Users tests in customers' spatial data infrastructures

- [x] 30.06.2021: Corrections and bug fixing

- [x] 30.07.2021: Documentation release: 30.07.2021

- [x] 31.08.2021: Interfaces SIA 405 for QWAT and VSA-KEK for QGEP are operationnal and documented. 

- [x] 30.9.2021 Final report to NGDI (Stefan).

- [ ] Warranty period : to be adressed

### Versions of related softwares

- QGIS version: 3.16 or higher
- Database model version: QGEP and QWAT (1.5.6/1.3.6) or newer

Public issues links : 
- …

Helpdesk issues links : 
- …

### Dates de réalisation

- Tender reception date : 
- Tender validation date : 

## Documentation

Documentation links
- User manual : https://qgep.github.io/docs/admin-guide/interlis-io/index.html
- Administrator manual : https://qgep.github.io/docs/admin-guide/interlis-io/index.html

## Development and intégration

Link and comments from the developer about the product

- Deliverable : 
- Recommendations and comments : 
- Future prospects : 

## Conclusion

Conclusions from applicant, users or admins group

- Conclusion: 
- Future prospects: Improve selection to also select connected objects / classe e.g. catchment areas, hydraulic elements (weirs, pumps, etc.)

- Invoice date: 30.9.2021

**Comment by sjib** [comment]
NGDI project 20-18 _Échange de données sur les modèles standard de CH pour l’eau, les eaux usées et les PGEE comme base pour la conservation de la valeur des données sur les infrastructures_ finished. Final report see https://www.geo.admin.ch/de/ueber-geo-admin/leistungsauftrag/zweckgebundene-ngdi-mittel.html#ui-collapse-232

**Comment by urskaufmann** [comment]
The original idee ( Select a subnetwork and connected catchments and other linked tables) is not realised. Its only realised for INTERLIS export. I want to see the selection in QGIS and want to work with the selection in QGIS.
