### ISSUE TITLE
Why QGEP?

### ISSUE THREAD

**Issue by ponceta** [QGEP/QGEP#606]
As for QGIS, we're searching some key ideas to communicate about QGEP:

Please add your ideas !

- a professionnal tool
- has user experience
- fast and efficient
- customizable
- opensource

Ref : https://docs.qgis.org/3.10/en/docs/training_manual/foreword/foreword.html#why-qgis

Parent QWAT: https://github.com/qwat/QWAT/issues/309

**Comment by m-kuhn** [comment]
- scalable
- focus on data - visualize the reality
- know your underground
- standard compliance
- extensible
