### ISSUE TITLE
vw_qgep_overflow is not in the current project

### ISSUE THREAD

**Issue by 3nids** [QGEP/QGEP#607]
We have a view for overflows with a linear geometry between nodes defined by fk_wastewater_node and fk_overflow and also joining information in children tables (leapingweir, pump, prank_weir).
The view is currently not in the demo project.

But other views/tables are present, I would recommend to remove them in favor of the views.

Side question for @sjib: why is there a table overflow_char which seems to be 1:1 with overflow? why not merging the 2 tables?

**Comment by sjib** [comment]
Overflow_char is a separate table that has the overflow characteristics in it (CHARACTERISTIQUES_DEVERSOIR)
This are hydraulic data to define the overflow related to the water height. This is often not a linear curve.

**Comment by sjib** [comment]
@3nids What do you mean by other views/tables are present?

**Comment by 3nids** [comment]
> Overflow_char is a separate table that has the overflow characteristics in it (CHARACTERISTIQUES_DEVERSOIR)
This are hydraulic data to define the overflow related to the water height. This is often not a linear curve.

Yes, but I don't see a valid reason to have this in separate tables if it's 1:1 relation.

> What do you mean by other views/tables are present?

![image](https://user-images.githubusercontent.com/127259/95423143-e2a5b680-0940-11eb-9cb6-b2ee44532505.png)

**Comment by sjib** [comment]
This has historic reasons, as earlier we have had the status attribut of hydraulic_char_data in overflow_char and there a 0..n relation. I will take this as an input for VSA to think about a change. But backwards compatibility is sometimes also an argument (-:
