### ISSUE TITLE
Missing Triggers and Function in qgep_od 1.5.2

### ISSUE THREAD

**Issue by sjib** [QGEP/QGEP#608]
Dear all
What happended to the trigger and functions in the qgep_od schema?

![od_schema_1 5 2](https://user-images.githubusercontent.com/1265865/96453998-8afa2b80-121b-11eb-82a2-3e23e9da5adc.jpg)

We had quite a bunch of those in older versions:
![od_schema_1_4_x](https://user-images.githubusercontent.com/1265865/96454054-9b120b00-121b-11eb-8df0-01f394e165c2.jpg)

Any hint what I have to run to add those to an existing project?

**Comment by DflGruBoe** [comment]
We updated the database with pum 0.9.12! Maybe the error/problem happened there?

**Comment by sjib** [comment]
Could it be that pum used [qgep_sys.drop_symbology_triggers](https://github.com/QGEP/datamodel/blob/50150f72092bb835fbccd2ee7f2770095b8b98f8/06_symbology_functions.sql#L531)?

And we have to turn on the triggers again?

Can I just run FUNCTION qgep_sys.create_symbology_triggers that was created with 06_symbology_function.sql

https://github.com/QGEP/datamodel/blob/50150f72092bb835fbccd2ee7f2770095b8b98f8/06_symbology_functions.sql#L554 
or do we have to run the full 06_symbology_function.sql Query?

Any hints and advice from the community?

**Comment by m-kuhn** [comment]
Fixed by upgrading pgadmin.
