### ISSUE TITLE
Create nodes for detailled wastewater structures

### ISSUE THREAD

**Issue by ponceta** [QGEP/QGEP#609]
In Pully we have wastewater structure polygons with no wastewater node or cover attached.

This is a data error but this can't actually be fixed by our geomaticians because there's no simple tool to attach a wastewater node to a wastewater structure if there's no existing node or cover.

I suggest to add a simple python action to create a wastewater node from a wastewater structure.

Example Here :

![image](https://user-images.githubusercontent.com/8614223/96839491-8f0b9080-1449-11eb-8db7-dc82cb6dec52.png)

![image](https://user-images.githubusercontent.com/8614223/96839563-a9de0500-1449-11eb-83da-11a4a5199733.png)

![image](https://user-images.githubusercontent.com/8614223/96839796-f1fd2780-1449-11eb-94ee-0ed0b4afe660.png)

![image](https://user-images.githubusercontent.com/8614223/96842986-0e9b5e80-144e-11eb-86eb-87539e7b21ba.png)

```
node_lyr = QgsProject.instance().mapLayersByName('Noeuds_reseau')[0]
node_lyr.startEditing()
qgis.utils.iface.setActiveLayer(node_lyr)
qgis.utils.iface.actionAddFeature().trigger()
```

**Comment by ponceta** [comment]
Not so easy since the relationnal widget is filtering wastewater structures with an existing point geometry, which is exactly the point here.

We can't link it since the point we want to create does not exist yet. (pointception)

**Comment by m-kuhn** [comment]
> Not so easy since the relationnal widget is filtering wastewater structures with an existing point geometry, which is exactly the point here.

Isn't this fixed by https://github.com/QGEP/datamodel/pull/154 ?

**Comment by ponceta** [comment]
@m-kuhn I still miss one command, I'd like to preset the value fk_wastewater_structure of my "to be created" node to the value from the wastewater_structure obj_id I started from, is it possible?

**Comment by m-kuhn** [comment]
I think a remote desktop session to look at that would be best.

**Comment by ponceta** [comment]
Without any action, it is easier to set a relationship between 
**wastewater_strcture**.fk_main_wastewaternode
to
**wastewater_node**.obj_id
as described here :
![image](https://user-images.githubusercontent.com/8614223/103982256-6d39c400-5183-11eb-83d8-7a7f89f1d161.png)

Then with a simple relationship widget you can set the main node to the detailled wastewater_structure.

![image](https://user-images.githubusercontent.com/8614223/103982564-036dea00-5184-11eb-8d45-27833c8027bb.png)

used on QGEP 1.5.2.

Correct edition should provide the wastewater_structure node first using vw_qgep_wastewater_structure for edition, THEN adding a detailled polygon or additional nodes and covers.
