### ISSUE TITLE
Release 1.5.3 ?

### ISSUE THREAD

**Issue by ponceta** [QGEP/QGEP#610]
Hi there,

According to https://github.com/QGEP/datamodel/compare/v1.5.2...master

I think it would be wise to publish a 1.5.3 release before any further developments.

It would be wise to test actual master and discuss eventual issues on our next codesprint on 6.11.2020 in Pully.

**Comment by olivierdalang** [comment]
I'll prepare that (hopefully today, if not tomorrow)

**Comment by m-kuhn** [comment]
CC @DflGruBoe

**Comment by sjib** [comment]
https://github.com/QGEP/datamodel/releases/tag/1.5.3
