### ISSUE TITLE
Update all symbology: usage_current and function_hierarchic not correct

### ISSUE THREAD

**Issue by DflGruBoe** [QGEP/QGEP#611]
We have the problem that whenever there is a SAA-connection to a wastewater structure, the primary wastewater structure (e.g. M21) gets its values (function hierarchic, usage ...) from the minor rainwater or wastewater reach!  Does anyone have an advice?

![image](https://user-images.githubusercontent.com/67325872/97319551-4995fb80-186d-11eb-8bf2-3a39275143e0.png)

![image](https://user-images.githubusercontent.com/67325872/97319627-5a467180-186d-11eb-87ab-440b6980e269.png)

![image](https://user-images.githubusercontent.com/67325872/97319761-73e7b900-186d-11eb-828b-449b00bd70c0.png)

**Comment by urskaufmann** [comment]
I can not confirm. Never saw this in my data. 
If you do the network following or a lengthprofil you get the result you expect?

**Comment by DflGruBoe** [comment]
Yes - the network following works and the length profile looks good so far!

**Comment by m-kuhn** [comment]
The problem only occurs when all symbology is updated. When it is created manually and updated through triggers everything works well.
This is a bug, located in the symbology update function with the parameter _all = true

**Comment by DflGruBoe** [comment]
Very good - Solving this problem is important for us. When will the new datamodel be released?

**Comment by sjib** [comment]
It is released https://github.com/QGEP/datamodel/releases/tag/1.5.3
