### ISSUE TITLE
Translation of QGEP plugin

### ISSUE THREAD

**Issue by urskaufmann** [QGEP/QGEP#618]
I run QGEP on a German QGIS in a German project. But the plugin is in English. 
On transiflex is the plugin translated?
What's the idea for a translated plugin, is there a schedule?

**Comment by sjib** [comment]
@m-kuhn Where is the bottle neck? Transifex or just translation work to do?

**Comment by olivierdalang** [comment]
It seems there's an issue preventing the translations to load...
Just opened a PR with a fix. Did it use to work ? (not sure how this got broken ?!)

I'll also check how up to date translations are (seems like German is OK but French seems lagging behind).
