### ISSUE TITLE
Error on "Reuse last entered values" function

### ISSUE THREAD

**Issue by urskaufmann** [QGEP/QGEP#619]
Get an error, if I want to create more than one new structure part per session.  The PostGIS-error is, that the obj_id is to long, when QGIS creates the new (unique) id like this: newid = oldid_2.

See also #514. The constraints who helped there are defined for the structure_part-obj_id-field
Is this solved in newer QGIS-Versions (I use 3.10.7)?

**Comment by olivierdalang** [comment]
@urskaufmann Can you provide the exact steps to get this issue ? I'm unable to reproduce here with 3.10.14 (I can successfully add multiple structures in the same session with "reuse last entered values" enabled, both with regular add feature tool and with the Wizard). I even tried with manually defined obj_id, but they are correctly generated.

Also can you please check that the layer primary key is correctly set (this could explain why obj_id gets overwritten), and if not, specify which datamodel and qgis project version you are using ?
![image](https://user-images.githubusercontent.com/1894106/121170039-fb11fc00-c854-11eb-95d3-e6b9d8b6ea4d.png)

**Comment by urskaufmann** [comment]
I can reproduce without problem:
- turn on the "reuse last attribute value"
- set vw_qgep_wastewater_structure editable
- open the attribute window of one of the manholes and go to the structure part - tab
- create an new access_aid (I get a new record with obj_id = ch2127y8SP000002)
- create again a new access_aid (or another structure part). If I want to save the second structure_part, I get this error: Layer vw_Einstiegshilfe: PostGIS-Fehler beim Attributhinzufügen: FEHLER: Wert zu lang für Typ character varying(16).
- I can no more create any structure part in this session or I have to turn off the reuse last attribue value.

You will not get this error, if the OID-prefix has not 8 digits.

**Comment by olivierdalang** [comment]
Hmmm here I'm still not able to reproduce, I get a different error than you (on QGIS 3.18, when I opening the form, on QGIS 3.10, when I create the access aid) :
```
2021-06-10T14:49:16     WARNING    Query: DECLARE qgis_314 BINARY CURSOR WITH HOLD FOR SELECT "obj_id","kind"::text,"fk_dataowner"::text,"fk_provider"::text,"fk_wastewater_structure"::text,"identifier"::text,"last_modification"::text,"remark"::text,"renovation_demand"::text FROM "qgep_od"."vw_access_aid" WHERE "obj_id"=0 returned 7 [ERROR: operator does not exist: character varying = integer
             LINE 1: ...emand"::text FROM "qgep_od"."vw_access_aid" WHERE "obj_id"=0
              ^
             HINT: No operator matches the given name and argument type(s). You might need to add explicit type casts.
             ]
```

So it's even worse as it doesn't allow to create a feature at all. To me it looks like a bug in QGIS, but unsure what exactly is happening, and even more how it can work on your setup ?

@urskaufmann Can you please share your versions of datamodel / QGIS version / QGEP plugin / QGEP project / Postgres / postgis ? (best is to always add that information to any bug report so it's easier to reproduce)

**Comment by olivierdalang** [comment]
Hmm actually I'm able to reproduce on 1.5.4, the other error seems to come from unrelated changes in datamodel's master (as the QGIS project/plugin are not covered by unit tests, we'd never have found out about that before it being tested by users, so it would have been yet another broken release). Will open another issue for that.

**Comment by olivierdalang** [comment]
With the above issue fixed, it seems now OK, I guess as a side-effect of https://github.com/QGEP/datamodel/pull/173 (but I can't say I totally understand why that is...)
