### ISSUE TITLE
Wizard

### ISSUE THREAD

**Issue by oliver-ch** [qgep/QGEP#62]
I am doing a test run of the wizard and there are some errors.

**Comment by oliver-ch** [comment]
Tab Manhole: material

Konnte Änderungen am Layer vw_wizard_cover_manhole nicht festschreiben

Fehler: FEHLER: Ein Objekt nicht hinzugefügt.
  
  Datenlieferantenfehler:
      PostGIS-Fehler beim Attributhinzufügen: FEHLER:  Einfügen oder Aktualisieren in Tabelle „od_cover“ verletzt Fremdschlüssel-Constraint „fkey_vl_cover_material“
    DETAIL:  Schlüssel (material)=(4542) ist nicht in Tabelle „vl_cover_material“ vorhanden.
    CONTEXT:  SQL-Anweisung „INSERT INTO qgep.od_cover(
                    obj_id 
                  , brand
                  , cover_shape
                  , depth
                  , diameter
                  , fastening
                  , level
                  , material
                  , positional_accuracy
                  , situation_geometry
                  , sludge_bucket
                  , venting
                )
                VALUES(
                  sp_obj_id -- obj_id
                , NEW.brand
                , NEW.cover_shape
                , NEW.depth
                , NEW.diameter
                , NEW.fastening
                , NEW.level
                , NEW.material
                , NEW.positional_accuracy
                , NEW.situation_geometry
                , NEW.sludge_bucket
                , NEW.venting
                )“
    PL/pgSQL-Funktion qgep.vw_cover_insert() Zeile 26 bei SQL-Anweisung
    SQL-Anweisung „INSERT INTO qgep.vw_cover(
          brand
        , cover_shape
    --    , depth
        , diameter
        , fastening
        , level
        , material
        , positional_accuracy
        , situation_geometry
        , sludge_bucket
        , venting
        , identifier
        , remark
        , renovation_demand
        , last_modification
        , dataowner
        , provider
        , fk_wastewater_structure
      )
      VALUES
      (
          NEW.brand
        , NEW.cover_shape
    --    , NEW.depth
        , NEW.diameter
        , NEW.fastening
        , NEW.level
        , NEW.material
        , NEW.positional_accuracy
        , NEW.situation_geometry
        , NEW.sludge_bucket
        , NEW.venting
        , NEW.identifier
        , NEW.remark
        , NEW.renovation_demand
        , NEW.last_modification
        , NEW.dataowner
        , NEW.provider
        , mh_obj_id
      )“
    PL/pgSQL-Funktion qgep.vw_wizard_cover_manhole_insert() Zeile 95 bei SQL-Anweisung

**Comment by oliver-ch** [comment]
__2. Tab Manhole: depth__

It does not exist in the table vw_wizard_cover_manhole and therefore it cannot be saved.

**Comment by oliver-ch** [comment]
__3. Tab Cover: diameter__

It is not saved into the tables. In QGIS it is a int type with edit widget range however in the ui form it is a  QLineEdit. I don't konw if that is a problem.

**Comment by oliver-ch** [comment]
__4. Manhole, Tab Manhole: surface_inflow__

The ui form is incorrect. It should be a ComboBox instead of a SpinBox.

**Comment by m-kuhn** [comment]
What is the unit of the attribute od_mahole.depth? mm?

**Comment by m-kuhn** [comment]
The SQL script `datamodel/view/vw_wizard_cover_manhole.sql` needs to be rerun. Possibly uncomment the `DROP VIEW ...` line on top.

I used mm. as data unit for depth now. Please let me know if this is wrong.

**Comment by oliver-ch** [comment]
mm is the correct unit.
