### ISSUE TITLE
Simple fix to cut and merge Reaches on demo project

### ISSUE THREAD

**Issue by ponceta** [QGEP/QGEP#622]
A fix is still needed on the demo project :

As discussed with @tproduit, we still require to define **ws_obj_id** as UNIQUE in **vw_qgep_reach** form.

Works with transactional AND non-transactional groups activated.

![image](https://user-images.githubusercontent.com/8614223/105331122-61aeba00-5bd3-11eb-9654-50fb5d041206.png)

Should have been shared long ago, sorry for that.

Works on QGIS 3.10.8+ tested on win / linux

**Comment by ponceta** [comment]
To be fix with qgs project update 3.16, gentle ping @olivierdalang

**Comment by ponceta** [comment]
Should have been mentionned here : 

https://github.com/QGEP/QGEP/issues/622

**Comment by urskaufmann** [comment]
Yes, it works. If for the fields identifier and ws_identifier is Default = obj_id / ws_obj_id defined also in case of update, then its even better. But all other fields are copied - means also levels, fk to wastewater-nodes. So there is some manual work to do, that is not obvious. Think also about connections reach to reach (Blindanschluss). They have to be controlled.

**Comment by ponceta** [comment]
Yes thanks @urskaufmann, it is relevant to say that it's only a technical solution but topology and data coherence has to be checked meticulously by the user every time.

Foreign key to wastewater nodes shoud be set actually using the qgep connect tool 

https://github.com/QGEP/QGEP/issues/527 is still relevant and should be adressed to simplify the user side mechanics.

**Comment by ponceta** [comment]
@urskaufmann @olivierdalang was this also part of the project fixes you provided? If yes we can close this.
