### ISSUE TITLE
view qgep_swmm.vw_conduits might generates an error

### ISSUE THREAD

**Issue by tproduit** [QGEP/QGEP#625]
The line `st_simplifypreservetopology(st_curvetoline(re.progression_geometry), 0.5::double precision)::geometry(LineStringZ,2056) AS geom` might generate an error.

Need to be replaced by `st_force3d(st_simplifypreservetopology(st_curvetoline(re.progression_geometry), 0.5::double precision))::geometry(LineStringZ,2056) AS geom`.

Apparently, in some scenario, `st_simplifypreservetopology` changes the the number of dimensions of the geometry. Namely `st_ndims` returns 2 rather than 3.

**Comment by sjib** [comment]
@tproduit Is this fixed?

**Comment by tproduit** [comment]
> 
> 
> @tproduit Is this fixed?
No, I plan to do it in the same time as SWMM phase 2.

**Comment by sjib** [comment]
#564
