### ISSUE TITLE
Maintenance_Event_kind - Is this join useful?

### ISSUE THREAD

**Issue by ponceta** [QGEP/QGEP#626]
Demo project :

vw_qgep_maintenance

![image](https://user-images.githubusercontent.com/8614223/105851231-15a0b280-5fe3-11eb-82a6-d52fd197d327.png)

Otherwise, should be removed.

**Comment by sjib** [comment]
If you create a maintenance event the attribut kind is important

**Comment by ponceta** [comment]
What I mean is : are these joined fields relics of an old way to interact with maintenance event? Since they are not show on the form anymore :

![image](https://user-images.githubusercontent.com/8614223/105955127-16365900-6076-11eb-9898-a6ea76148d1d.png)

Same thoughts for the damage layer :

![image](https://user-images.githubusercontent.com/8614223/105955240-3fef8000-6076-11eb-9442-1281be71157f.png)

**Comment by ponceta** [comment]
I thought this was solved by represent_value but it seems that using represent_value could not solve all use cases.

Example for reach material, if you want to use both **value_fr** AND **abbr_fr** (e.g. symbology + form)
you have to create a join for one of the values.
