### ISSUE TITLE
Cannot digitize new wastewater structure geometry

### ISSUE THREAD

**Issue by m-kuhn** [QGEP/QGEP#628]
Digitizing a new wastewater structure geometry using the action in the feature form fails with a cryptic warning "Add Part" without more details.
Digitizing a new drainage channel works.

![image](https://user-images.githubusercontent.com/588407/106465903-e5518c00-649a-11eb-9d69-7ac905fd7488.png)

**Comment by m-kuhn** [comment]
The problem is related to the avoid overlap setting in the project file.

![image](https://user-images.githubusercontent.com/588407/106465952-f9958900-649a-11eb-84c0-dd6895b19a9f.png)

![image](https://user-images.githubusercontent.com/588407/106465963-fdc1a680-649a-11eb-8698-96335320b7c6.png)

**Comment by urskaufmann** [comment]
The QGEP-documentation is updated about this problem

**Comment by ponceta** [comment]
Project and documentation are updated. We can close this.
