### ISSUE TITLE
No network-following after refreshing topology

### ISSUE THREAD

**Issue by urskaufmann** [QGEP/QGEP#631]
I do a network following. Then I press the SQL button (e.g. because the network following has shown that the topology must be rebuilt) and next try a network following again, then I can't find any yellow crosses to start (sometimes I can't find a starting point only with upstream, but with downstream it does). I then have to, for example vw_qgep_Abwasserbauwerk switch editable and save again, then the network tracking works again. Starting and stopping the wizard is not enough.

**Comment by varrieta** [comment]
Same here. Sometimes, the upstream tool doesn't show a yellow cross anymore. 
Switching the views to editable doesn't make it works for me. I then have to close and reopen the project.

**Comment by m-kuhn** [comment]
What is the priority of this?

**Comment by varrieta** [comment]
Does anyone else has encountered the issue ? @ponceta ?

If not, I would say that it is a medium priority, because it doesn't happen all the time

**Comment by ponceta** [comment]
Any database change processed without a modification in QGIS will result on these kind of issues. 

Of course visually QGIS display canvas is fine but everything linked to snapping will fail.

In Pully we have included a manual refresh via a project reloading (file / open recent / ... )

**Comment by sjib** [comment]
@urskaufmann @ponceta Is this still a problem?

**Comment by ponceta** [comment]
![image](https://github.com/user-attachments/assets/566be273-832a-4088-adaf-7c6ab8a96dc7)

Look like it is not an issue anymore but this can lead the user to restart QGIS when it does not work as it should.
