### ISSUE TITLE
reach_point identifier not updating with new objects

### ISSUE THREAD

**Issue by PeterZamudio** [QGEP/QGEP#632]
The reach_point identifier is not updating with new objects. This causes the following error bei Interlis export:

*** ERROR *** CHECK(errid=11) Bezeichnung has to be defined
              LINE=2181,TOPIC=SIA405_Abwasser,CLASS=Haltungspunkt,TID=ch193u2fRP000012

It's now blocking our uploads to GeoShop so we would be grateful for a Quick-fix

Thank you

**Comment by PeterZamudio** [comment]
It's the same problem by:

*** ERROR *** CHECK(errid=11) Bezeichnung has to be defined
              LINE=28561,TOPIC=SIA405_Abwasser,CLASS=Einstiegshilfe,TID=ch20edheSP000389

*** ERROR *** CHECK(errid=11) Bezeichnung has to be defined
              LINE=36121,TOPIC=SIA405_Abwasser,CLASS=Haltungspunkt,TID=ch20edheRP000249

**Comment by sjib** [comment]
@PeterZamudio Did you generate the new objects with the wizard?
Which datamodel version do you use?

**Comment by sjib** [comment]
@PeterZamudio Can you check whether your behavior when digitizing is like described here: https://qgep.github.io/docs/user-guide/digitizing/digitizingchannels.html

If you do not enter an identifier (reach-identifier) in the General tab, QGEP will enter the obj_id also as identifier (you can change later). As default, the identifier of the reach is also the ws_identifier of the channel. The reachpoint-identifier are build from the reach-identifier+’F’ or +’T’ (from- and to-reachpoint).

**Comment by PeterZamudio** [comment]
Hello
The new objects are created with the wizard as discribed in  https://qgep.github.io/docs/user-guide/digitizing/digitizingchannels.html. The Reach-identifier is always entered as we have a set system number like 504123 always +1. The problem is by the Reach-Point which is created automaticly.

The Data Model is the newest 1.5.0 updated with PUM

**Comment by sjib** [comment]
@m-kuhn / @olivierdalang It looks like this rule from the doc is not working:  `The reachpoint-identifier are build from the reach-identifier+’F’ or +’T’ (from- and to-reachpoint).` 

Which trigger creates this and might not work?

**Comment by m-kuhn** [comment]
Interesting, I wasn't aware of such a trigger (but I agree it makes sense) but if it's in the doc it mus have existed at some point.

@olivierdalang can you have a look at vw_qgep_reach insert rules?

**Comment by m-kuhn** [comment]
Meanwhile it should be possible to use the field calculator to update existing reach point identifiers with `CONCAT("identifier", 'T')` and  `CONCAT("identifier", 'F')` respectively to fixup an already digitised dataset to an exportable state.

**Comment by olivierdalang** [comment]
The insert/update rule seem to have no specific logic, just uses what's given in the feature from the view (see extract below)-

As far as I can tell, this is only generated by QGIS through the edit form on the reach view. @PeterZamudio can you check that it is configured like this ?

![image](https://user-images.githubusercontent.com/1894106/107631089-c0ac9f80-6c64-11eb-9e93-c382854c36cd.png)

**Comment by PeterZamudio** [comment]
Hello Olivier and Matthias
I checked that from above
![grafik](https://user-images.githubusercontent.com/32352291/107640884-34ee3f80-6c73-11eb-9a6f-d5977382950a.png)
It seems the same.
![grafik](https://user-images.githubusercontent.com/32352291/107641258-b0e88780-6c73-11eb-90d9-b83747383478.png)
But the identifier is not being entered by new points and as I can see the reach_point from the import are not unique.

**Comment by PeterZamudio** [comment]
Maybe if we could do this "maximum("identifier")+1" I could renumber them and then they should do the rest on it's own.

**Comment by m-kuhn** [comment]
Can you activate the checkbox below: "Vorgabewert bei Aktualisierung anwenden"?
According to the warning below, that's required to make it work.
From my side adding that to the datamodel directly sounds good as well.

**Comment by PeterZamudio** [comment]
Thank you Matthias, I will give it a try

**Comment by PeterZamudio** [comment]
Summery of steps to solve the problem so far:
The problem is that by the SIA405 export there are errors Bezeichnung has to be defined.

Errors are shown:
*** ERROR *** CHECK(errid=11) Bezeichnung has to be defined
LINE=2181,TOPIC=SIA405_Abwasser,CLASS=Haltungspunkt,TID=ch193u2fRP000012

Haltungspunkt and others

The errors originate from the layers reach_point, vw_channel, vw_access and vw_wastwater_node

Steps I took to solve the problem:
In the layers reach_point, vw_channel, vw_access and vw_wastwater_node I used the Feldrechner to fill the attribute identifier
with a unique number (1100000+rownumber).

I then entered the "Vorgabewert" maximum("identifier")+1 plus I activated the "Vorgabewert bei Aktualisieren anwenden"

By Reach Channel Identifier I entered                     maximum( "ws_identifier" )+1
By Reach Reach_Points rp_from_identifier I entered maximum( "rp_from_identifier" )+1
By Reach Reach_Points rp_to_identifier I entered     maximum( "rp_to_identifier" )+1
By vw_access_aid Identifier I entered                       maximum( "identifier" )+1

I take it I have only solved the errors we had and there are more that we haven't used so far.

I hope this helps people with the same problem.

**Comment by urskaufmann** [comment]
> According to the warning below, that's required to make it work.

I do not understand, why there is this checkbox. If it onlys works with this checkbox, then the checkbox is not necessary. I'm sure, it worked in earlier QGIS Versions without this checkbox. 
I did add this default "Vorgabewert" (obj_id+'F') for the reach_point identifier in the project template. And I do not want the identifier to be changed automatically. So I did not check the checkbox.

**Comment by urskaufmann** [comment]
I can not confirm, that there are empty identifier-fields in reach_point table, when digitizing with the wizard.

I confirm, that there are empty identifiers with structure_parts as access_aide or benching and I'm not able to configure this field to set the identifier by default to the obj_id. 
Was there not a general trigger, that the identifier is set to the obj_id, if the identifier is not set by the user?

**Comment by olivierdalang** [comment]
As a quick fix, can you try with the following expression in the default value for identifier on the `vw_access_aid` layers (and the other structure parts layers) ? If anyone can come up with a less verbose expression that would be welcome :-)

```
with_variable(
  'parent_wws',
  get_feature('vw_qgep_wastewater_structure', 'obj_id', fk_wastewater_structure),
  concat(
      attributes(@parent_wws)['identifier'],
      '-',
      count( 1, filter:=fk_wastewater_structure=attributes(@parent_wws)['obj_id']) + 1
  )
)
```

If we want to go the trigger/rule way, to keep consistency, I'd be in favor to do so for all default values (for instance also for reach points). Also worth considering setting the columns to NOT NULL and UNIQUE if these are applicable.

**Comment by urskaufmann** [comment]
Does half of the work. It uses the identifier of the parent_wws (or I can change to the obj_id of the parent_wws). What will we do, if somebody changes the wws-identifier? 
My idea was: if there is no user-entry, we use the obj_id of the same table (structure_part) as identifier (structure part). Because most people are not interested in this attribute. Why is it not possible to enter 'obj_id' as default value for identifier?

The other thing is, that I can not enter more than one structure_part when I have the "reuse last attribute values" option on, because this option adds '_2' to the last obj_id #619 .

**Comment by PeterZamudio** [comment]
Just to clarify the settings in default(Vorgaben).
![image](https://user-images.githubusercontent.com/32352291/108380433-1d7cfc80-7207-11eb-8e0b-65a3cc118efe.png)
I have a unique number set and for new data the Identifier is set with default "maximum("identifier")+1"

1. Ticking the "Vorgabewert bei Aktualisierung anwenden" results that with every change to the data that the Identifier gets a new highest number + 1.      If it is set =ID or =ObID then it just sets it new with no change.

2. If the box is not marked then the new data gets highest number + 1 and stays that way with every data change.

Both settings are useful but very different. I am using number 2 as the number is set once must stay the same.
I am sure for Urs Kaufmann the setting 1 is the right one.

Hope this helps
Thank you for all the imputs.

**Comment by olivierdalang** [comment]
As far as I understood, the initial issue (reach point identifiers staying null) seems specific to Peter's setup, as neither Urs nor me were able to reproduce.
@PeterZamudio can you please :
- provide exact versions you are using (QGIS, QGEP plugin, datamodel (1.5.0) , Postgres/Postgis)
- see if this issue happens also with the demo data and default QGIS project
- if it doesn't happen with demo data/projet, provide a copy of your QGIS project and some data

For the other part of the issue (structure parts identifier staying null), I'll open a PR with following fixes :
- Add `ALTER VIEW qgep_od.vw_qgep_reach ALTER obj_id SET DEFAULT qgep_sys.generate_oid('qgep_od','access_aid');` to view generation  (same for all structure parts)
- Set default identifier to `obj_id` in the template QGIS projet, so it should work just like for wastewater structures and reachines, and prepopulate the identifier with the obj_id)

**Comment by olivierdalang** [comment]
Optionally, we could additionally enforce this in the insert/update trigger, so that even if things go wrong in the QGIS projet, identifiers get generated.

IMO we should only do that if it's really a requirement of the datamodel to have a non-empty value in identifier, as it brings some ambiguity between identifiers and primary keys. If so, we should also set identifiers to be non-nullable.

In the interlis, idenfitier is `Bezeichnung: MANDATORY TEXT*20;` which it seems doesn't validate non-null but empty strings. So it would make sense to populate that by default, and even set these columns as non-nullable if we want to match to the interlis definition as closely as possible.

@urskaufmann @sjib Any opinion on that ?

**Comment by olivierdalang** [comment]
Here are the PR to review/merge to fix this:
- 1/2 : default value in the view
  - [ ] Update to datamodel to set a default value for primary keys on views - https://github.com/QGEP/datamodel/pull/173
  - [ ] Update to QGIS projet to use `obj_id` as default for `identifier` - https://github.com/QGEP/QGEP/pull/636
 - 2/2 : enforce at trigger level
   - [ ] Update pirogue to allow for "inner defaults" - https://github.com/opengisch/pirogue/pull/10
   - [ ] Update create-views.py to configure these "inner defaults" - https://github.com/QGEP/datamodel/pull/174

**Comment by urskaufmann** [comment]
> In the interlis, idenfitier is `Bezeichnung: MANDATORY TEXT*20;` which it seems doesn't validate non-null but empty strings. So it would make sense to populate that by default, and even set these columns as non-nullable if we want to match to the interlis definition as closely as possible.
> 
> And while we're at it, do we want to apply that to all identifiers (not only structure parts) ?
> 

Thats the point. I do not want to handle all this mandatory fields manually. I do not use them. The ladder of manhole 1 has no name/identifier. And its obvious that nobody will give a name for the access_aid with kind "none" in manhole 2 :-).
So - duplicate the obj_id to the identifier and forget it, for all identifiers. My Opinion. Hope @sjib will agree...

Attention: if I get data that has Null as identifiers (or duplicate values), it should nevertheless be possible to import this data and then to calculat/correct this missing/wrong values.

**Comment by sjib** [comment]
I agree with @urskaufmann to just use obj_id as identifier if nothing else is provided. That is a simple solution.

**Comment by sjib** [comment]
@olivierdalang - what is the difference here? non-null but empty strings ..

> In the interlis, idenfitier is Bezeichnung: MANDATORY TEXT*20; which it seems doesn't validate non-null but empty strings. So it would make sense to populate that by default, and even set these columns as non-nullable if we want to match to the interlis definition as closely as possible.

In INTERLIS xtf you can have `<Bezeichnung></Bezeichnung>` or not have the tag at all in the dataset (both cases do not fullfill the MANDATORY requirement 
or have `<Bezeichnung>XXX</Bezeichnung>` - then the MANDATORY requirement is fullfilled. 
XXX then also has to be UNIQUE (together in combination with the `<fk_dataowner>` (if you combine two datasets with the same identifiers it is possible as long the are not maintained by the same dataowner.)

**Comment by PeterZamudio** [comment]
Please bear this in mind when thinking of what to insert into the Bezeichnung. Here in Entlebuch we have a ARA-Pipline that goes through 6 Gemeindes. The ARA-Pipeline is in one data set. The local pipelines, main and secondary are at the moment also in single data sets. Gregor Lütolf has warned me that at some stage in future we will have to put the 7 data sets together as one. If we fill the Bezeichnung with the T_IDs we might have a conflict and have to renumber all of them. If we fill the Bezeichnung with OBJID we should be OK as they should be unique to all data sets. As Olivier says with an other data owner the problem might be solved but I thing it would be better if they were unique from the start.

**Comment by sjib** [comment]
Usual Bezeichnung for Channel / Reach is from node - to node. What we discuss for using OBJ_ID = Bezeichnung is when you do not have a Bezeichnung system such as for Reach_points or Bauwerks_Teil (if it is not the main cover)

**Comment by olivierdalang** [comment]
Implementation for this is almost ready, just some minor packaging issues preventing from merging this right now.

We'll probably be able to merge, so you can test before next release.

**Comment by olivierdalang** [comment]
Ok this is ready to be tested (note that it requires an update to the datamodel, which itself requires upgrading python dependencies, as well as getting the updated QGIS project)
