### ISSUE TITLE
Can not digitize reaches with QGIS 3.16.3

### ISSUE THREAD

**Issue by urskaufmann** [QGEP/QGEP#635]
Get this error when closing the attribut form:
Layer vw_qgep_Haltung: PostGIS-Fehler beim Attributhinzufügen: FEHLER: NULL-Wert in Spalte »situation_geometry« verletzt Not-Null-Constraint DETAIL: Fehlgeschlagene Zeile enthält (00000000RP000010, null, 00000000RE000005F, null, null, null, null, null, 2021-02-16 21:25:28.193013, null, null, 00000000WN000000). CONTEXT: SQL-Anweisung »INSERT INTO qgep_od.reach_point ( obj_id , elevation_accuracy , identifier , level , outlet_shape , position_of_connection , remark , situation_geometry , last_modification , fk_dataowner , fk_provider , fk_wastewater_networkelement ) VALUES ( COALESCE( NEW.rp_from_obj_id, qgep_sys.generate_oid('qgep_od'::text, 'reach_point'::text) ) , NEW.rp_from_elevation_accuracy , NEW.rp_from_identifier , NEW.rp_from_level , NEW.rp_from_outlet_shape , NEW.rp_from_position_of_connection , NEW.rp_from_remark , ST_StartPoint(NEW.progression_geometry) -- situation_geometry , NEW.rp_from_last_modification , NEW.rp_from_fk_dataowner , NEW.rp_from_fk_provider , NEW.rp_from_fk_wastewater_networkelement ) RETURNING obj_id« PL/pgSQL-Funktion qgep_od.ft_vw_qgep_reach_insert() Zeile 10 bei SQL-Anweisung 

No error with QGIS 3.10.14 or when digitizing without qgep-wizard

**Comment by olivierdalang** [comment]
Ok I could reproduce, incoming fix here : https://github.com/QGEP/qgepplugin/pull/59

**Comment by olivierdalang** [comment]
The fix is now in master, will be available on next plugin release (not sure if/when scheduled)
