### ISSUE TITLE
No deltas in log for update to 1.5.4

### ISSUE THREAD

**Issue by DflGruBoe** [QGEP/QGEP#637]
Update to version 1.5.4 failed!

**Comment by sjib** [comment]
No files here: https://github.com/QGEP/datamodel/tree/master/delta - why? @m-kuhn

**Comment by m-kuhn** [comment]
No deltas have been produced, it only ships update to views and role permissions.
These are not managed in deltas.

https://github.com/QGEP/datamodel/compare/1.5.3...1.5.4

Is there an error message?

**Comment by m-kuhn** [comment]
When updating a datamodel to a new version without any deltas (e.g. 1.5.4) we don't see anything in the log of the database.

Regardless, upgrades are performed successfully.

This will be solved with a command to check the current pum version (https://github.com/opengisch/pum/issues/94) or a log with previously run commands.
