### ISSUE TITLE
Problem with Widget Type Value Relation

### ISSUE THREAD

**Issue by urskaufmann** [QGEP/QGEP#654]
To use a Value Relation for the fk_wastewater_networkelement in catchment_area would be a good thing. It is possible to enter a fk by typing the identifier (and not the obj_id) of a node (also in a multiedit session!). The option "use completer" is very helpfull, otherwise the list is much to long.  See the picture for the settings.

The problem is, that it's no more possible to delete a fk (set the NULL value), even the Allow NULL value option is on.
Is this a QGIS-Problem or knows somebody a way the delete the value with this configuration?
![Unbenannt](https://user-images.githubusercontent.com/1257403/116736524-47fde980-a9f0-11eb-868b-fbcd10bee792.PNG)

**Comment by ponceta** [comment]
I think the widget type here should be relation reference to be used with the identify on the map. 

This would actually help the user to draw the catchment area, then select directly the designated node on the map.

Example for rainwater networkelement :

![image](https://user-images.githubusercontent.com/8614223/129911457-528c789e-66d1-45ef-844a-72d891086d9a.png)

This would require 4 new relations between catchment area and the wastewater node layer.

(1x current rainwater 1x current wastewater 1x planned rainwater 1x planned wastewater)

But would be much more user friendly than searching for identifiers in a dropdown list.

![image](https://user-images.githubusercontent.com/8614223/129911793-7c0ffb09-056c-415b-9036-9657d6c0a1d3.png)

**Comment by sjib** [comment]
@urskaufmann Did you solve this with the new project file?
Is it still a `QGIS Upstream` issue?

**Comment by urskaufmann** [comment]
in the new project is the proposal from Arnaud, so this issue can be closed..
