### ISSUE TITLE
Database error when adding a new reach

### ISSUE THREAD

**Issue by sjib** [QGEP/QGEP#658]
I was installing QGIS 3.16 today on a new PC and then wanted to show the current demoproject. I faced two problems:

1. The demoproject did not translate to German when opening it with the qgep_de.qm file in the same folder and using a German QGIS installation.
2. I got the following error when trying to use the QGEP Wizard and creating a new reach:
`2021-05-28T11:07:23     CRITICAL    Layer vw_qgep_reach : PostGIS-Fehler beim Attributhinzufügen: ERROR: null value in column "situation_geometry" of relation "reach_point" violates not-null constraint
             DETAIL: Failing row contains (00000000RP034482, null, 00000000RE017231F, null, null, null, null, null, 2021-05-28 09:07:23.45324, null, null, 00000000WN011327).
             CONTEXT: SQL statement "INSERT INTO qgep_od.reach_point (
              obj_id
              , elevation_accuracy
              , identifier
              , level
              , outlet_shape
              , position_of_connection
              , remark
              , situation_geometry
              , last_modification
              , fk_dataowner
              , fk_provider
              , fk_wastewater_networkelement 
              ) VALUES ( 
              COALESCE( NEW.rp_from_obj_id, qgep_sys.generate_oid('qgep_od'::text, 'reach_point'::text) )
              , NEW.rp_from_elevation_accuracy
              , NEW.rp_from_id
`

Questions: 

- Are these two errors known?
- Are there already fixes available and could they be integrated in the current pluging and datamodel version?
- Or are there dependencies with other issues?
- I think we should have to make sure that we have a working demoproject and plugin with the actual LTR of QGIS.

**Comment by m-kuhn** [comment]
1. Check in your qgis settings if the language set to "override system locale" and "German", I think if "override system locale" is not activated it doesn't work (QGIS issue). Can you verify and report back. If you confirm we can open a QGIS upstream issue.
2. Can you add details about data model, @olivierdalang does this speak to you?

**Comment by sjib** [comment]
> 2. Can you add details about data model version, @olivierdalang does this speak to you?
I downloaded the datamodel today (demoproject dump) https://github.com/QGEP/datamodel/releases/download/1.5.4/qgep_1.5.4_structure_and_demo_data.backup

**Comment by sjib** [comment]
> 1. Check in your qgis settings if the language set to "override system locale" and "German", I think if "override system locale" is not activated it doesn't work (QGIS issue). Can you verify and report back. If you confirm we can open a QGIS upstream issue.

This hint solved the issue with translation. Thanks!
![system_locale_flag](https://user-images.githubusercontent.com/1265865/119985744-57f2f400-bfc3-11eb-8cc0-39cb494eca8a.jpg)

**Comment by m-kuhn** [comment]
Upstream issue opened https://github.com/qgis/QGIS/issues/43433

Renamed issue to focus on one thing

**Comment by urskaufmann** [comment]
The null-value reach is described in Issue #635. But the solution is not in the plugin!!!
Please update the plugin!

**Comment by olivierdalang** [comment]
https://github.com/QGEP/qgepplugin/pull/59 is merged
