### ISSUE TITLE
Allow to digitize geometries for special_structures

### ISSUE THREAD

**Issue by andreasneumann** [QGEP/QGEP#66]
Geometry (Spezialbauwerk oder Entwässerungsrinne) should be stored in od_wastewater_structure.detail_geometry_geometry

Idea is to have an action that allows to digitize geometry attached to manholes and special_structures.

**Comment by m-kuhn** [comment]
Like the drainage channel

**Comment by sjib** [comment]
UK and MK discuss solution

**Comment by m-kuhn** [comment]
Fixed in release 0.5.5

In the attribute form of layer vw_qgep_cover there are two menu entries

 * Digitize (free digitizing)
 * Digitize Drainage Channel (rectangular digitizing)
