### ISSUE TITLE
QGIS Project Update

### ISSUE THREAD

**Issue by ponceta** [QGEP/QGEP#660]
According to qgs project file transmitted from Urs to @m-kuhn 2th may 2021

**Comment by m-kuhn** [comment]
File attached here, forwarded on May 6 to @olivierdalang 
[qgep.zip](https://github.com/QGEP/QGEP/files/6590265/qgep.zip)

**Comment by urskaufmann** [comment]
Changes in projectfile:
-	In vw_qgep_wastewater-structure: the field wn_obj_id is now unique and not null (both enforced)
-	In vw_qgep_reach is the label definition changed (correct label if clear height and width are different)
-	Od_pipe_profil is not a Value List. I put this table in the Wastewater Structures Group. The attributes are now configured
-	vw_cover: fk_wastewater_structure: "Use a read only line edit" deselected
-	vw_wastewater: fk_wastewater_structure: "Use a read only line edit" deselected
-	overflow_char (Hydraulic): the attributes are now configured

-	hq_relation (Hydraulic): table added and configured
-	new project properties relation: node with leapingweir, node with prank weir, node with pump, node with throttle shut off u
-	Added this relations in the attribute form of wv_wastewater_node

-	new project properties relation: pump_charachteristic, hq relation
-	Added the hq relation in the attribute form of overflow_char
-	Used the pump characteristic relation in the vw_pump attribute form to add or edit the overflow_char.

-	hydr_geometry (Hydraulic): table added and configured
-	hydr_geom_relation (Hydraulic): table added and configured
-	new project properties relation: hydr_geometry, hydr_geom_relation
-	Added the hydr_geometry relation to the attribute form of wv_wastewater_node
-	hydraulic_char_data (Hydraulic): table added and configured
-	new project properties relation: hydr char data 2 node
-	Added the hydr char data 2 node relation to the attribute form of wv_wastewater_node
-	vw_qgep_maintenance: the preview expression changed (sort by date works now better)
-	Maintenance-tab in Form Layout of the mainlayers: the cardinality was no more correct in both mainlayers (it was no more possible to add new maintenance events
-	Overflow layers (pump and weirs): grouped the attributes in hydraulic and others. Hydraulic are the attributes that has to be filled for hydraulic calculation

**Comment by olivierdalang** [comment]
https://github.com/QGEP/QGEP/pull/661 merged

**Comment by ponceta** [comment]
@olivierdalang Will this be finalized? 

https://github.com/QGEP/QGEP/releases/tag/v9.0

**Comment by olivierdalang** [comment]
@ponceta You mean released as a regular release instead of prerelease ? Yes, we've just flagged it as a pre-release so it's clear for users they should only upgrade if they want to test (and so that it does not appear as the latest release).
