### ISSUE TITLE
Enable github discussions

### ISSUE THREAD

**Issue by ponceta** [QGEP/QGEP#669]
Github now offers a new discussion panel to filter topics, questions from issues.

This would help having a cleaner Issues repository and encourage discussions and collaborations on topics using Q/A structure etc.

An issue can be converted as a discussion

More about discussions :
https://docs.github.com/en/discussions

**Comment by ponceta** [comment]
Sample discussions : 

https://github.com/VilleDePully/EasyImport/discussions/21

**Comment by sjib** [comment]
@ponceta Looks interesting. Do you have a sample of an issue in QGEP we should convert into a discussion?

**Comment by ponceta** [comment]
As an issues author :

Discussion about datamodel and VSA values
https://github.com/QGEP/QGEP/issues/384

Discussion about Extensions and templating
https://github.com/QGEP/QGEP/issues/565

Discussion about construction points
https://github.com/QGEP/QGEP/issues/322

**Comment by sjib** [comment]
@ponceta Ok, I have enabled discussion and converted a first issues https://github.com/QGEP/QGEP/issues/384 into a discussion to get a look and feel.

**Comment by ponceta** [comment]
Fine for me, we can test it and validate it next technical meeting!
