### ISSUE TITLE
Datamodel tool does not recognise python dependencies

### ISSUE THREAD

**Issue by TriformMoritz** [QGEP/QGEP#675]
Datamodel shows missing python dependencies (pirogue, psycop2, pum) :
 ![image](https://user-images.githubusercontent.com/33837122/128373383-10807758-3241-4842-9c59-6cbe51279220.png)

And the following error message:

![image](https://user-images.githubusercontent.com/33837122/128373779-2829b6e7-3a17-42cf-9043-5fd23cb459f0.png)

yet if I use the OSGeo4W shell and list the packages, they are listed.

![image](https://user-images.githubusercontent.com/33837122/128373970-845d3dd8-6e1b-4966-8a04-3627ced577ad.png)

The python path also seems to be ok in Qgis and in the shell:
![image](https://user-images.githubusercontent.com/33837122/128374211-e0b341be-af86-47c8-8f9a-8b8efcb8531d.png)
![image](https://user-images.githubusercontent.com/33837122/128376810-031cf5af-cda0-41e4-993a-c3af8272c6e0.png)

Why is this message there?

**Comment by olivierdalang** [comment]
It seems `python` refers to python 2 instead of python 3 from your QGIS environment. I see some reference to python2 in PATH in your OSGeo4W shell. Maybe we should use `python3` instead of `python`, but I'm not sure it's always available.

What version of QGIS are you using, and how was it installed (OSGeo4W installer or standalone) ?

Can you type the following in the QGIS python console, and copy the output :
```
import subprocess
subprocess.run(['python', '--version'], capture_output=True)
```
Here i get `CompletedProcess(args=['python', '--version'], returncode=0, stdout=b'Python 3.9.5\r\n', stderr=b'')`

**Comment by TriformMoritz** [comment]
Installation was with OSGeo4W shell.
Message: CompletedProcess(args=['python', '--version'], returncode=0, stdout=b'', stderr=b'Python 2.7.14\r\n') 
So it seems I am using 2.7.14 inside Qgis. 
How can I change it?

**Comment by TriformMoritz** [comment]
So I changed the Python path insode the OSgeo4W shell:
![image](https://user-images.githubusercontent.com/33837122/128715198-a34b1a9b-e408-4cda-829c-17afe5916c27.png)

Installed pip (NOT IN THE 2.7 VERSION ) from:  https://bootstrap.pypa.io/pip/2.7/get-pip.py 

when seeing in the shell not many packages are installed:
![image](https://user-images.githubusercontent.com/33837122/128715535-30c2283a-8ce3-4fff-9630-e27c16d01c3d.png)

But in the datamodel tool it looks ok;
![image](https://user-images.githubusercontent.com/33837122/128716201-febc6261-2a1e-45fc-a9f9-ef0f3b5d055c.png)

Why?

**Comment by TriformMoritz** [comment]
I still get an error when launching the datamodel tool:

2021-08-09T15:46:36     WARNING    Traceback (most recent call last):
              File "C:/Users/Moritz/AppData/Roaming/QGIS/QGIS3\profiles\Triform TEKSI/python/plugins\qgepplugin\gui\qgepdatamodeldialog.py", line 97, in wrapper
              return func(*args, **kwargs)
              File "C:/Users/Moritz/AppData/Roaming/QGIS/QGIS3\profiles\Triform TEKSI/python/plugins\qgepplugin\gui\qgepdatamodeldialog.py", line 824, in upgrade_version
              timeout=300,
              File "C:/Users/Moritz/AppData/Roaming/QGIS/QGIS3\profiles\Triform TEKSI/python/plugins\qgepplugin\gui\qgepdatamodeldialog.py", line 297, in _run_cmd
              result.stdout.decode(sys.getdefaultencoding()), "QGEP"
             UnicodeDecodeError: 'utf-8' codec can't decode byte 0xea in position 76: invalid continuation byte

**Comment by TriformMoritz** [comment]
Version de Python : 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] 
Version de QGIS : 3.16.4-Hannover Hannover, 654e76b3cb 

Chemin Python :
C:/OSGEO4~1/apps/qgis-ltr/./python
C:/Users/Moritz/AppData/Roaming/QGIS/QGIS3\profiles\Triform TEKSI/python
C:/Users/Moritz/AppData/Roaming/QGIS/QGIS3\profiles\Triform TEKSI/python/plugins
C:/OSGEO4~1/apps/qgis-ltr/./python/plugins
C:\OSGEO4~1\apps\Python37
C:\OSGEO4~1\apps\Python37\Scripts
C:\OSGeo4W64\bin\python37.zip
C:\OSGEO4~1\apps\Python37\DLLs
C:\OSGEO4~1\apps\Python37\lib
C:\OSGeo4W64\bin
C:\Users\Moritz\AppData\Roaming\Python\Python37\site-packages
C:\OSGEO4~1\apps\Python37\lib\site-packages
C:\OSGEO4~1\apps\Python37\lib\site-packages\win32
C:\OSGEO4~1\apps\Python37\lib\site-packages\win32\lib
C:\OSGEO4~1\apps\Python37\lib\site-packages\Pythonwin
C:/Users/Moritz/AppData/Roaming/QGIS/QGIS3\profiles\Triform TEKSI/python
C:/Users/Moritz/AppData/Roaming/QGIS/QGIS3\profiles\Triform TEKSI/python/plugins\DataDrivenInputMask
C:\Users\Moritz\AppData\Roaming\QGIS\QGIS3\profiles\Triform TEKSI\python\plugins\mmqgis/forms
C:/Users/Moritz/AppData/Roaming/QGIS/QGIS3\profiles\Triform TEKSI/python/plugins\qgis_resource_sharing
C:\Users\Moritz\AppData\Roaming\QGIS\QGIS3\profiles\Triform TEKSI\python\plugins\qgis_resource_sharing
C:\Users\Moritz\AppData\Roaming\QGIS\QGIS3\profiles\Triform TEKSI\python\plugins\qgis_resource_sharing\ext_libs
C:/Users/Moritz/AppData/Roaming/QGIS/QGIS3\profiles\Triform TEKSI/python/plugins\SwapVectorDirection
C:/Users/Moritz/AppData/Local/Temp/9

**Comment by olivierdalang** [comment]
It will not work with python2 (the issue is that `python` is an alias to python2 on your environment, while we need python3). I think this would be fixed if you use the new OSGeo4W installer, which doesn't include python2 at all.

But anyways, I just pushed a new commit that calls `python3` so there's no ambiguity. Are you able to test from master ?

**Comment by TriformMoritz** [comment]
Master from QGEP Plugin? Do I need to add an repository?
So in order to get QGIS 3.16 with Python 3.7 -> Do I really need to reinstall QGIS (it would bother me a little, because it is working good right now. and used by everyone).

**Comment by olivierdalang** [comment]
I've released an experimental version of the plugin (`1.5.5-1`) so it's easier to test. It should appear in the manager shortly.

No need to reinstall QGIS, I made the changes on the plugin (just for clarification : your QGIS version is already using python3.x, it's just that the `python` alias from the command line points to python2.x when installed with the old OSGeo4W installer, and to python3.x when installed with the new OSGeo4W installer).

**Comment by olivierdalang** [comment]
@TriformMoritz Let me know if it works as expected, in which case I'll flag the release as non-experimental and we can close this issue

**Comment by TriformMoritz** [comment]
If I choose Master it seems the dependecies are working BUT it has now problems with my pg_service.config which it did not have yesterday.
2021-08-11T10:55:00     WARNING    Traceback (most recent call last):
              File "C:/Users/Moritz/AppData/Roaming/QGIS/QGIS3\profiles\Triform TEKSI/python/plugins\qgepplugin\gui\qgepdatamodeldialog.py", line 564, in add_pgconfig
              taken_names = self._read_pgservice().sections()
              File "C:/Users/Moritz/AppData/Roaming/QGIS/QGIS3\profiles\Triform TEKSI/python/plugins\qgepplugin\gui\qgepdatamodeldialog.py", line 342, in _read_pgservice
              config.read(PG_CONFIG_PATH)
              File "C:\OSGEO4~1\apps\Python37\lib\configparser.py", line 696, in read
              self._read(fp, filename)
              File "C:\OSGEO4~1\apps\Python37\lib\configparser.py", line 1079, in _read
              raise MissingSectionHeaderError(fpname, lineno, line)
             configparser.MissingSectionHeaderError: File contains no section headers.
             file: 'V:\\Informatique\\Configs\\PostgreSQL\\PGCONF\\pg_service.conf', line: 1
             '\ufeff# Diesen Block für jede neue Datenbank kopieren und anpassen\n'
             
s

**Comment by ponceta** [comment]
Error when loading qgs project

2021-08-12T11:48:22     WARNING    Error transferring https://github.com/QGEP/QGEP/releases/download/v9.0/qgep.zip - server replied: Not Found

**Comment by ponceta** [comment]
@TriformMoritz for your pg_service.conf file, make sure you saved it with Notepad++ in UNIX format

![image](https://user-images.githubusercontent.com/8614223/129336963-8a9af66c-b096-460a-82f2-348614cb0e34.png)

http://qgep.github.io/docs/fr/installation-guide/workstation.html#windows-pg-service

**Comment by TriformMoritz** [comment]
Thank you for your help! I restored an old file and it still did not work, Saving with Notepad worked! I will close this issue since it is working know. I will eventually open a new one if postgres user rights won't work.

**Comment by m-kuhn** [comment]
You probably had a UTF-8 BOM in your file.
See https://stackoverflow.com/a/32986612/2319028
