### ISSUE TITLE
Datamodel Tool fails to download qgep project

### ISSUE THREAD

**Issue by ponceta** [QGEP/QGEP#676]
**Describe the bug**
Initialization of QGIS project requires a project release

**To Reproduce**
Exact steps to reproduce the behavior:
1. Go to datamodel tool
2. Click on 1.5.5
3. Click on Load
4. See error in error logs

**Expected behavior**
Project is downloaded / started ?

**Screenshots / data**
If applicable, add screenshots or data to help explain your problem.

**Desktop (please complete the following information):**
 - QGEP plugin version 1.5.5-1
 - QGEP datamodel version 1.5.5
 - QGEP project file version v.9.0
 - QGIS Version QGIS 3.16.9
 - OS Windows

**Additional context**
Testing

**Comment by ponceta** [comment]
Assets need to be fixed in order for this to run:

https://github.com/QGEP/QGEP/releases/tag/v9.0

**Comment by 3nids** [comment]
this is done now: https://github.com/QGEP/QGEP/releases/tag/v9.0.3

**Comment by olivierdalang** [comment]
Should be fixed (release in QGIS plugin manager incoming)

**Comment by ponceta** [comment]
![image](https://user-images.githubusercontent.com/8614223/129744527-43d80b9c-7cdc-4e17-aa63-11ca57ca15ed.png)

Very nice, a freshly initialized datamodel with a fresh qgep.qgs project.

It will be much easier in the future to have a quickstart with this kind of approach.

We will miss translation with this but that's another issue.
