### ISSUE TITLE
Profile tool is appending next profile, restart necessary to make second profile

### ISSUE THREAD

**Issue by TriformMoritz** [QGEP/QGEP#693]
When using the profile tool two times (making one profile and than another), the profile is appended to the first one instead of making a complete new one. Closing the window does not resolve the problem.
When doing a network refresh or network follow (to reset the tool) , the profile tool stops working (no connection draw and no profile (white page). To make it work a QGIS restart is necessary.

**To Reproduce**
Exact steps to reproduce the behavior:
1. Click on the nodes to draw the profil
2. See the profil (should look ok).
3. Draw another profile (or close the profile window and do the same)
4. 
Exemple:
![image](https://user-images.githubusercontent.com/33837122/135086175-8d8f5067-c154-43d0-b76f-db7b3c63c3e2.png)

**Comment by TriformMoritz** [comment]
Do not have this error anymore .Resolved?

**Comment by sjib** [comment]
@TriformMoritz Please reopen if necessary.
