### ISSUE TITLE
Labeling from egg-formed reach

### ISSUE THREAD

**Issue by TriformMoritz** [QGEP/QGEP#704]
When assigning an egg-form o a reach, you introduce (example for an 900/600 egg):

- The maximum height. -> 900 in this example
- The ratio_height_width -> 900/600=1.5 in this example.

Seems to be all right in SWMM (egg with maximum height of 900)

Yet the labeling is 900/1350 in QGEP (should be 900/600). For me this is a division error.
Here are the print screens:

![image](https://user-images.githubusercontent.com/33837122/139074206-9b3464e1-5615-4760-8e3b-f8a56a2bc98f.png)

![image](https://user-images.githubusercontent.com/33837122/139074341-63c8008f-2db4-4670-95d6-6e9d3df39205.png)

![image](https://user-images.githubusercontent.com/33837122/139074508-1ff38af7-6cc0-4306-8c78-cd614159a28a.png)

**Comment by urskaufmann** [comment]
I think this must be corrected ( in vw_qgep_reach)

 CASE
            WHEN pp.height_width_ratio IS NOT NULL THEN round(re.clear_height::numeric * pp.height_width_ratio)::smallint::integer
            ELSE re.clear_height
        END AS width,

It should be / not *

And if we are there: should it not be _width (because it is not a attribut of the model, it is only a calculated value)
And in the project-file, the attribute width (_width)  should not be enterable...

**Comment by sjib** [comment]
Still open to do:

- [ ] should it not be _width (because it is not a attribut of the model, it is only a calculated value)
- [ ] And in the project-file, the attribute width (_width) should not be enterable...
