### ISSUE TITLE
python errors when opening attribute table

### ISSUE THREAD

**Issue by oliver-ch** [qgep/QGEP#71]
i get three python errors when i try to open the attribute tables (cover and manhole) in the demo project.

An error occured during execution of following code:
import qgepplugin.ui.forms

Traceback (most recent call last):
  File "", line 1, in 
  File "C:/OSGEO4~1/apps/qgis/./python\qgis\utils.py", line 460, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ImportError: No module named forms

An error occured during execution of following code:
if hasattr(qgepplugin.ui.forms,'DEBUGMODE') and qgepplugin.ui.forms.DEBUGMODE: reload(qgepplugin.ui.forms)

Traceback (most recent call last):
  File "", line 1, in 
NameError: name 'qgepplugin' is not defined

An error occured during execution of following code:
_qgis_featureform_15 = sip.wrapinstance( 48124448, qgis.gui.QgsAttributeForm )

Traceback (most recent call last):
  File "", line 1, in 
NameError: name 'qgepplugin' is not defined

**Comment by m-kuhn** [comment]
I have uploaded a new version (0.5.3) today that fixes these issues. Please update and try again.
