### ISSUE TITLE
Export only selection to SWMM

### ISSUE THREAD

**Issue by TriformMoritz** [QGEP/QGEP#720]
Issue:
Once the selection of the network (from a node, upstream or downstream) , including all appended tables and catchment is possible, see this issue: https://github.com/QGEP/QGEP/issues/603 , the export of only the selection to SWMM would be a great feature.
The modeler can than work only simulate the selected parts.
Proposal:
I would propose to add to the export SWMM mask  (creation of .inp file) a check mark (optional) "export only selection", like there is in many other algorithms in QGIS.

**Comment by tproduit** [comment]
@TriformMoritz  if some secondary network objects are selected in QGIS, would you need to have them exported?

**Comment by TriformMoritz** [comment]
**No**, not necessary, as we shouldn't be modeling secondary networks.
For that, the user should change secondary to primary in order to export.
The (not wanted) selection of secondary network objects should not bother the export of the primary selected network.

**Comment by ponceta** [comment]
This is now an option in new plugin :

![image](https://user-images.githubusercontent.com/8614223/224910942-48631c59-3acc-4b37-9a2a-a6699f01d877.png)

Please reopen if needed

**Comment by TriformMoritz** [comment]
Hello, Wanted to test this (did not get it to work)

My Workflow:
- Use the QGEP upstream fonction.
- Use "Select current path" (in the profile tab)-> 95  reaches selected
- Used Create Input -> Get this error:

 
Version de QGIS : 3.28.4-Firenze
Révision du code : fd0fb72ab3
Version de Qt : 5.15.3
Version de Python : 3.9.5
Version de GDAL : 3.6.2
Version de GEOS : 3.11.1-CAPI-1.17.1
Version de Proj : Rel. 9.1.1, December 1st, 2022
Version de PDAL : 2.4.3 (git-version: f8d673)
Algorithme commencé à: 2023-03-20T11:23:38
Démarrage de l'algorithme 'SWMM Create Input'…
Paramètres en entrée:
{ 'DATABASE' : 'pg_monthey154', 'INP_FILE' : 'C:/Users/Moritz/Documents/SWMM_Month1.6.0_Test4.inp', 'ONLY_SELECTED' : True, 'STATE' : 0, 'TEMPLATE_INP_FILE' : 'C:\\Users\\Moritz\\Documents\\NEW_INPUT.inp' }

Traceback (most recent call last):
File "C:\Users/Moritz/AppData/Roaming/QGIS/QGIS3\profiles\Triform/python/plugins\qgepplugin\processing_provider\swmm_create_input.py", line 180, in processAlgorithm
qs.write_input(hierarchy, selected_structures, selected_reaches)
UnboundLocalError: local variable 'selected_structures' referenced before assignment

Execution failed after 0.10 secondes

Chargement des couches de résultat
Algorithme 'SWMM Create Input' terminé

Without selection, the creation works without a problem.

**Comment by TriformMoritz** [comment]
Maybe it is because only reaches, not structures are selected.
My expected behaviour would be:
- All structures are also exported.
- All catchments are also exported.
Otherwise, we would have to upgrade the selection tool

**Comment by TriformMoritz** [comment]
Export works in **the english .qgs template** with the workflow described above (thank you Stefan for the input)

-     Use the QGEP upstream fonction.
-     Use "Select current path" (in the profile tab)-
-     Use Create Input 

The connected structures (ouvrages) are selected in the english version, but not in the french version (see this error (https://github.com/QGEP/qgepqwat2ili/issues/93#top). Once this issues is treated, the tool should work.
