### ISSUE TITLE
Interlis Export/Import: error when no password in pg_service.conf

### ISSUE THREAD

**Issue by urskaufmann** [QGEP/QGEP#725]
**Describe the bug**
We have no "user" and no "password" in the pg_service.conf -file. The identification for the database is taken from the windows-login.
If I start the INTERLIS-Export, there is an error  "...fe_sendauth: no password supplied"

If I manually add a user=yx and password=xy in the pg_service.conf, there is no error.

**To Reproduce**
Exact steps to reproduce the behavior:
described above

**Expected behavior**
no error and do not ask for password.

**Screenshots / data**
![Error INTERLISExport](https://user-images.githubusercontent.com/1257403/154064227-0325773d-4b41-421c-8dcd-413a66b5b4c7.png)

**Desktop (please complete the following information):**
 - QGEP plugin version 1.5.6-b7
 - QGEP datamodel version
 - QGEP project file version
 - QGIS Version 3.16.15
 - OS Win10

**Comment by sjib** [comment]
@urskaufmann Does https://github.com/opengisch/QgisModelBaker/pull/703 solve your issue?

**Comment by urskaufmann** [comment]
ModelBaker 703 solves not the problem with the missing password, but it solves the error when starting Import-Export (Error : Could not load qgepqwat2ili due to unmet dependencies. See logs for more details. 
qgepplugin:No module named 'QgisModelBaker.libili2db')

**Comment by urskaufmann** [comment]
password-problem also with qgep-plugin 1.5.6-b8.
the password is needed to create the pg2ili_abwasser schema
it would be no problem, if the schema would not be replaced everytime. May be it's faster to create the schema again than deleting old data in all tables, but with this we can prepare a database with the necessary schemas and the user can use qgep without postgres-password.
