### ISSUE TITLE
Interlis Export: invalid placed argument

### ISSUE THREAD

**Issue by urskaufmann** [QGEP/QGEP#726]
**Describe the bug**
When saving the xtf-File to a path with a space (Leerschlag), I get an error as in the screenshot below (could not export the ili2pg schema / invalid placed argument).
If I save to a path without space, it works...

**To Reproduce**
Choose a path with space when saving the xtf-file

**Expected behavior**
normal windows rules

**Screenshots / data**
![error_show_logs](https://user-images.githubusercontent.com/1257403/154068898-384cf34e-94b0-4d15-8250-51e2ddf809eb.png)

**Desktop (please complete the following information):**
 - QGEP plugin version 1.5.6-b7
 - QGEP datamodel version
 - QGEP project file version
 - QGIS Version 3.16.15
 - OS Win10

**Additional context**
-

**Comment by urskaufmann** [comment]
Show logs -Button goes with our virtual-pc-configuration not to a useful path. It could be helpful, if the path is in the messages...

**Comment by sjib** [comment]
Supporting file pathes with empty strings - add " around path variable (see https://github.com/QGEP/qgepqwat2ili/issues/59#issuecomment-1099108398):

parser_qgep.add_argument("path", help="path to the input/output .xtf file")
https://github.com/QGEP/qgepqwat2ili/blob/ca20959e7c87822fca4f09599739eeafad10b8db/qgepqwat2ili/__init__.py#L48

@olivierdalang Is this the right place to fix this globally?
