### ISSUE TITLE
QGEP-SWMM: Export secondary network for selection

### ISSUE THREAD

**Issue by tproduit** [QGEP/QGEP#729]
In complement to the issue #720, the user should choose if he wants to export only the primary network or also the secondary networks.
City of La Chaux-de-fond (@varrieta) could need this functionality when they want to calibrate a new network part.

**Comment by urskaufmann** [comment]
The user should be able to select the reaches he wants to export (similar to the Interlis-Export). Its then his problem, if he wants to export also parts of the secondary network, just a part of the primary network or what is interesting...

**Comment by tproduit** [comment]
With the export of secondary network, we encounter case that we didn't meet previously:

- Pipes with no _from node_
- Pipes with no _to node_ (blind connection)

These pipes will be exported in SWMM. The user will be warned with a message printed in the plugin.

![image](https://user-images.githubusercontent.com/8256037/200828674-9de5f0ba-d40b-4817-8ec6-cc2ed5e30027.png)

**Comment by sjib** [comment]
Blind connections are allowed (reach - reach connection) with SAA. There a message should only be done if it is with two PAA reaches (then reach - reach connection is not correct)

**Comment by ponceta** [comment]
@tproduit does SWMM support theses reach-reach connections? 

Is there any more required work here?

**Comment by tproduit** [comment]
No, SWMM doesn't support reach - reach connections. If the user exports secondary network with reach reach connections, he will need to create manually a "junction".
Eventually, we could rename this issue, if we do not want to close it. ie. "Generate automatically junctions for secondary blind connections".

**Comment by ponceta** [comment]
Do we have users who need this :

- [ ] Generate automatically junctions for secondary blind connections

If yes we should open a new issue mentionning this user -> fix has to be tested by the user.

If no please close this issue.

**Comment by sjib** [comment]
PAA defines what is hydraulicly relevant - that is the base concept here and that is supported. 

The other case with SAA needs a new issue and good arguments, why you want to start calculating SAA networks. I think the user should not rely on an algorithm to make his / her SAA networks fit SWMM but should change the base data accordingly and also add a node in SAA, if hydraulic simulation should work.
