### ISSUE TITLE
depth calculation

### ISSUE THREAD

**Issue by m-kuhn** [QGEP/QGEP#73]
When creating a new manhole or special structure:
- Fill depth with `cover.level - watewater_node.bottom_level` (if possible)

When attaching a reach to a `wastewater_node` that is connected to a `manhole` or `special_structure` 
- update the depth with `cover.level - reach_point.level` if `depth` is NULL or smaller than the current value.

**Comment by 3nids** [comment]
depth is a smallint....so is it in millimeter? why not meter?

**Comment by max-trolliet** [comment]
Does this come from the same format than the other manhole dimensions? The cover is usually given in mm as it is in the form for a new manhole.

But indeed, in practice, we use meter above sea level.

**Comment by sjib** [comment]
Depth ist not a level - it is the difference between cover.level minus reach_point.level if wastewater_node.bottom_level is empty, else it is cover.level minus wasterwater_node.bottom_level

As in construction mm are used this is just consequent to use it also for depth.Diameter is in mm, width, height are in mm, etc.

**Comment by 3nids** [comment]
@m-kuhn following recent removal of depth field, can this be closed?

**Comment by m-kuhn** [comment]
Superseded by #348
