### ISSUE TITLE
Datamodel tool and QGIS 3.22.5: error when installing python dependencies

### ISSUE THREAD

**Issue by urskaufmann** [QGEP/QGEP#734]
**Describe the bug**
I get this error when I want do install the python dependencies with QGIS 3.22.5. Same behaviour with 3.24.1, (no problem with 3.16.14):

_Could not install python dependencies. You can try to run the command manually from the OSGeo4W shell.
Command :
python3 -m pip install --user "pirogue==1.4.1" "psycopg2" "pyyaml" "pum==0.9.12"

Output :
Collecting pirogue==1.4.1
  Using cached pirogue-1.4.1.tar.gz (17 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'

Error :
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [14 lines of output]
      C:\PROGRA~1\QGIS3\apps\Python39\lib\site-packages\setuptools\dist.py:642: UserWarning: Usage of dash-separated 'description-file' will not be supported in future versions. Please use the underscore name 'description_file' instead
        warnings.warn(
      C:\PROGRA~1\QGIS3\apps\Python39\lib\distutils\dist.py:274: UserWarning: Unknown distribution option: 'entry_points'
        warnings.warn(msg)
      C:\PROGRA~1\QGIS3\apps\Python39\lib\distutils\dist.py:274: UserWarning: Unknown distribution option: 'install_requires'
        warnings.warn(msg)
      C:\PROGRA~1\QGIS3\apps\Python39\lib\distutils\dist.py:274: UserWarning: Unknown distribution option: 'python_requires'
        warnings.warn(msg)
      usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
         or: setup.py --help [cmd1 cmd2 ...]
         or: setup.py --help-commands
         or: setup.py cmd --help
      
      error: invalid command 'egg_info'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details._

**To Reproduce**
Use datamodel tool on QGIS 3.22.5 in the way you have to install the python dependencies

**Expected behavior**
-.

**Screenshots / data**
-.

**Desktop (please complete the following information):**
 - QGEP Plugin 1.5.6-b7
 - QGEP database independent
 - QGEP project file version independent
 - QGIS 3.22.5
 - OS Win 10

**Additional context**
-.

**Comment by urskaufmann** [comment]
QGIS 3.22.5 and 3.24.1 are installed in the same folder and with Python39 in the apps-folder.
QGIS 3.16.14 is installed in an other folder and with Python37 in the apps-folder

**Comment by sjib** [comment]
You can influence where to make installations if you do not want to use the default pathes – see https://qgep.github.io/docs/de/admin-guide/interlis-io/index.html#python-libraries

**Comment by olivierdalang** [comment]
From the error, it could be that your version of pip and/or setuptools are out of date (not sure why though ?!)

@urskaufmann Can you try to this code in your QGIS python console (one at a time, an please take a screenshot if you're getting errors):
```
os.system("pip install --upgrade pip && pause")
```
```
os.system("pip install --upgrade setuptools && pause")
```

**Comment by urskaufmann** [comment]
Thanks Olivier. It works with this 2 lines in the QGIS Python console. There are errors (sent direct to Olivier), but the datamodel tool works afterwards
