### ISSUE TITLE
'nan' values on reaches makes the layers export fail

### ISSUE THREAD

**Issue by ponceta** [QGEP/QGEP#737]
**Describe the bug**
On QGIS 3.22, I can't export into a shapefile or a geopackage my reaches because the contain 'nan' values in their altitude coordinates.

**To Reproduce**
Exact steps to reproduce the behavior:
1. Go to to the reach layer
2. Right Click on 'save as layer'
3. See error

**Expected behavior**
Export goes well

**Screenshots / data**
![image](https://user-images.githubusercontent.com/8614223/168012546-1cf26808-e290-4545-a087-20c2d2cb9b85.png)

**Desktop (please complete the following information):**
 - QGEP plugin version
 - QGEP datamodel version 1.5.3
 - QGEP project file version
 - QGIS Version 3.22
 - OS Win 10 x64

**Additional context**
This breaks the export to QFIELD with qfieldsync as well.

**Comment by urskaufmann** [comment]
Confirm for export to shp, but no error when exporting to gpkg. ?
Same behaviour also with 3.24.1

**Comment by ponceta** [comment]
It is causing trouble to FME and AutoCAD as well, I think there's something that has to be fixed on QGEP to avoid such unsupported Z values, Null was fine, I think we will have to track these 'nan' values down are replace otherwise we will face many unsatisfied users.

**Comment by sjib** [comment]
It is discussed on the OGR github: https://github.com/OSGeo/gdal/issues/3542

@andreasneumann May be you are more into such issues:
 - does it need a fix an QGEP side? 
 - Or is or will it be fixed on QGIS side? 
 - Or does the mentioned fix solve the problem and we just have to make sure to have the latest OGR2OGR?

**Comment by m-kuhn** [comment]
For reference https://github.com/qgis/QGIS/pull/47034

**Comment by urskaufmann** [comment]
another problem with nan-values in the vw_qgep_reach - geometry: with QGIS 3.22.8, these lines are visible, with QGIS 3.26.0 these lines are invisible (labels are displayed, but the line it self is not visible untill you click on the line with the tool to edit the vertexes) !

**Comment by sjib** [comment]
Re-Agreed on to be critical and be fixed until October 6th, 2022. @urskaufmann  is contact person for this issue - fixing by @olivierdalang

**Comment by domi4484** [comment]
QGIS pr opened: https://github.com/qgis/QGIS/pull/50507

**Comment by sjib** [comment]
Waiting for review https://github.com/qgis/QGIS/pull/50507

**Comment by domi4484** [comment]
Pull request + backport were merged. Would be good if someone could test it with the nightly builds.

**Comment by ponceta** [comment]
It seems that we have raised some other bug with the export (probably not related to nan values)

Red are reaches in postgres not exported to shapefile or geopackage :
![image](https://user-images.githubusercontent.com/8614223/203497247-11644f29-e488-41e2-a2f0-76535a864edf.png)

![image](https://user-images.githubusercontent.com/8614223/203497272-96878878-1941-462b-b5f8-29a5bc12de8a.png)

Since nan values are not an issue anymore since QGIS 3.28.1, this issue can be closed.

**Comment by ponceta** [comment]
Thank you @domi4484 for fixing this!

**Comment by sjib** [comment]
> Since nan values are not an issue anymore since QGIS 3.28.1, this issue can be closed.
I close - ok?
