### ISSUE TITLE
QGEP 1.5.5 and 1.5.6 datamodel releases

### ISSUE THREAD

**Issue by ponceta** [QGEP/QGEP#747]
**Describe the bug**
QGEP 1.5.5 and 1.5.6 datamodel releases are still not released (pre-release)

Having more than one release in that state shows unconfidence in release management.

**To Reproduce**
https://github.com/QGEP/datamodel/releases

**Expected behavior**
Versions are published and not in pre-release state

**Screenshots / data**
If applicable, add screenshots or data to help explain your problem.

**Desktop (please complete the following information):**
 - QGEP datamodel version 1.5.5 / 1.5.6

**Additional context**

**Comment by sjib** [comment]
Agreed on to be critical and be fixed until October 6th, 2022. @ponc is contact person for this issue - fixing by @olivierdalang

**Comment by olivierdalang** [comment]
Done

**Comment by ponceta** [comment]
Thank you @olivierdalang
