### ISSUE TITLE
Glitches with decimal numbers input in the co_level field in vw_qgep_wastewater_structure

### ISSUE THREAD

**Issue by urskaufmann** [QGEP/QGEP#749]
**Describe the bug**
I want to edit or enter a new cover_level (in the General Tab or Main Cover/Node tab). If there are already values in this field, I delete them with the "x-arrow-sign". If I enter the first number (e.g. 6 for 601.56), I get "6.000m.a.s.l" in the field. If I type my wanted level further, I get "60.000m.a.s.l", "601.000m.a.s.l", "601.5.000m.a.s.l", "601.56.000m.a.s.l". If I go to the next field, there stays "601.000m.a.s.l". Same behavior if I have no suffix.
It works if I type 601rightarrow-instead_of_point56. But thats not the way we type numbers, no discussion.

The same problem is with the reachpoint_levels in vw_qgep_reach (in Generel Tab and in Reach Points Tab).

It works as expected if I use the covers Tab or if I use the vw_qgep_cover to enter the cover level. Also no problem when entering e.g. wn_bottom_level in vw_qgep_wastewater_structure.

**To Reproduce**
Exact steps to reproduce the behavior:
described above

**Expected behavior**
we enter numbers with point...

**Screenshots / data**
-
**Desktop (please complete the following information):**
 - QGEP plugin version 1.56b-7
 - QGEP datamodel version 1.5.2 and 1.5.6
 - QGEP project file version different
 - QGIS Version 3.22, 3.16, 3.10
 - OS
I think its a problem of the datamodel version. I think at the beginning of QGEP, the behavior was normal

**Additional context**
-

**Comment by urskaufmann** [comment]
Seems to be the problem, if the field is more than once in the attribute form. If I delete the reachpoint-level-fields in the reach-point tab, I can edit the level-fields in the generell tab without problem. 
So the "same" problem as with multiedit: if the fields are more than once in a attribute-form, QGIS has a problem.
Would be very good, if this thing can be solved on QGIS side

**Comment by sjib** [comment]
@olivierdalang Can you open (or link to) an issue on QGIS side as discussed today in the technical meeting?

**Comment by olivierdalang** [comment]
This is the same as https://github.com/QGEP/QGEP/issues/750, right ?

**Comment by urskaufmann** [comment]
No, its not the same. This issue (749) is a problem, when a numeric field is more than once in a attribut-form (I checked this yesterday after the discussion).
750 is the behaviour of range-fields, that the entry is corrected without any hint to the max- or min-value. I expect in this case (750), that the field gets orange and that I can not press OK (as usual in QGIS).

**Comment by olivierdalang** [comment]
Ok, I opened an upstream issue here: https://github.com/qgis/QGIS/issues/50859

For this one I do not see an easy workaround (besides removing the rp_from_level from the other tab, but not sure that is satisfactory).

**Comment by urskaufmann** [comment]
Still the same with 3.28.2: if the numeric field is more than once in the form, there is the problem. If the field is just once, it works as expected

**Comment by sjib** [comment]
@urskaufmann Can you check with 3.28.4 or newer if it's solved now?

**Comment by urskaufmann** [comment]
Test with 3.28.5 and 3.30.1: the same (if there is a numeric field twice in the form, there is this behaviour)

**Comment by sjib** [comment]
> Test with 3.28.5 and 3.30.1: the same (if there is a numeric field twice in the form, there is this behaviour)

@domi4484 Can you open an issue for this remaining problem on QGIS please

**Comment by sjib** [comment]
@domi4484 or was this solved with https://github.com/qgis/QGIS/pull/52183 ?

**Comment by urskaufmann** [comment]
Test with 3.28.6: ok. Test with 3.30.3: not ok as domi4484 wrote. So work with 3.28.6 or 3.32
