### ISSUE TITLE
bad layer in last version

### ISSUE THREAD

**Issue by 3nids** [qgep/QGEP#75]
vw_network_segment is reported as a bad layer when I open the project

**Comment by andreasneumann** [comment]
Hi Denis,

vw_network_segment is a materialized view - can you try to refresh it?

Syntax:
REFRESH MATERIALIZED VIEW qgep.vw_network_segment;

**Comment by 3nids** [comment]
Hi Andreas,
Indeed it worked!
Thanks a lot!
