### ISSUE TITLE
vw_qgep_reach is not dropped when updating 

### ISSUE THREAD

**Issue by ponceta** [QGEP/QGEP#751]
**Describe the bug**
The view vw_qgep_reach is not dropped when updating.

This can lead to errors or inconsistensies.

https://github.com/QGEP/datamodel/blob/master/view/drop_views.sql

**To Reproduce**
Apply https://github.com/QGEP/datamodel/blob/master/view/drop_views.sql
on a database
qgep_od.vw_qgep_reach is still present

**Expected behavior**
Apply https://github.com/QGEP/datamodel/blob/master/view/drop_views.sql
all views are correctly removed.

**Screenshots / data**
https://github.com/QGEP/datamodel/blob/master/view/drop_views.sql

**Desktop (please complete the following information):**
 - QGEP datamodel version 1.5.5

**Additional context**

**Comment by sjib** [comment]
@ponceta Would this solve the issue:

Add a line 

DROP VIEW IF EXISTS qgep_od.vw_qgep_reach;
in https://github.com/QGEP/datamodel/blob/master/view/drop_views.sql

**Comment by ponceta** [comment]
FIX: 
https://github.com/QGEP/datamodel/pull/185
