### ISSUE TITLE
vw_qgep_reach not drawing the start and end line segments of a polygon. Problem caused by NAN

### ISSUE THREAD

**Issue by PeterZamudio** [QGEP/QGEP#752]
The problem started with QGIS 3.26.1 and is the same in 3.26.2.
We have a lot of QGEP pipelines that have no hight. If the start hight is NULL the Z is set to NAN. And all the pipelines with Z=NAN the first segment is no longer drawn. So, we now have lots of pipelines with the first and/or last segments missing in the graphic. The line is there, and I can edit it, but it is not displayed.

If I enter 0.000 as a hight the Z becomes 0.000 as well and the pipeline is properly drawn. But if the start hight is 0.000 and the end is 1000.123 the pipe has a length of 1000.???, which is wrong too.

Is there an easy solution? Or must we go back to 2.24.3 where it was working OK?

Screenshots:
see NAN-Problem.jpg

**Desktop
 - QGEP 1.5.5
 - QGEP 1.5.0
 - QGIS 3.26.2
 - Windows 10 & 11

![NAN-Problem](https://user-images.githubusercontent.com/32352291/190106985-175a4924-09dd-4353-b978-3b8cfba785a5.jpg)

**Comment by PeterZamudio** [comment]
The same data viewed in QGIS 3.24.2
![NAN-Problem_QGIS3 24 2](https://user-images.githubusercontent.com/32352291/190111502-74e1fc7d-2de4-4bea-b3fd-aa442da429d2.jpg)

**Comment by sjib** [comment]
@m-kuhn Can you check on this as you are involved on the QGIS side on fixing this. Thanks.

**Comment by PeterZamudio** [comment]
We have gone back to QGIS 3.24.3 and will stay there till the problem has been solved.

Thank you for looking into this problem.

**Comment by olivierdalang** [comment]
A first fix was done by Nyall: https://github.com/qgis/QGIS/commit/49051e5cf23bf7d8451c5cc68b4cdd4377c41016 and should land in 3.28 when it's out. If you have the possibility to test if it works as expected in a nightly build, that would be great.

**Comment by PeterZamudio** [comment]
Thank you too Olivier

I will try and test it as soon as 3.28 is out. I see 3.27.0-8.msi is the newest at the moment.

**Comment by PeterZamudio** [comment]
I did a test today with QGIS Version 3.27.0 nightly build. 
It seems to work fine now with no missing lines as before. See the graphic below. I think the problem has been soved.
![image](https://user-images.githubusercontent.com/32352291/196677318-4be55e0a-dc80-4a70-8ee9-17d9c9c69755.png)

**Comment by olivierdalang** [comment]
Ok so this can be closed ?

**Comment by PeterZamudio** [comment]
From my side yes. We will be waiting for the new QGIS version 3.28.1. Till then we have to stay with 3.24.3
Thank you for solving the problem.
