### ISSUE TITLE
The default values are not used when adding a reach via the wizard

### ISSUE THREAD

**Issue by rbovard** [QGEP/QGEP#757]
**Describe the bug**
The default values are not used when adding a reach via the wizard

**To Reproduce**
Widget definition:
![image](https://user-images.githubusercontent.com/4549666/193857307-e0003334-f9d5-4368-87d3-4e21e05fa877.png)

Form via QGEP plugin data entry tool (default value is not fine, it's the first one wich is selected):
![image](https://user-images.githubusercontent.com/4549666/193857860-634b7d1c-3f9f-413b-a561-0b5120fca0e6.png)

**Expected behavior**
Form via QGIS add feature tool (default value is fine):
![image](https://user-images.githubusercontent.com/4549666/193857531-5f176f3d-6bee-4356-8db9-0f555a6ee5fc.png)

**Desktop (please complete the following information):**
 - QGEP plugin version: 1.5.5
 - QGEP datamodel version: 1.5.6-1
 - QGEP project file version: 3.22.9
 - QGIS Version: 3.22.9
 - OS: Windows 10

**Comment by urskaufmann** [comment]
it's just a small note in the docu (Chapter 3.2.5):
_The standard-fields on the General tab (and only those fields) do reuse the last entered attribute value when you add new reaches with the wizard. The Reuse the last entered attribute values - option of QGIS has no influence._
This reuse for the standard-fields is hardcoded in the qgep-plugin. It seems that it also stronger than the default values...

**Comment by rbovard** [comment]
> This reuse for the standard-fields is hardcoded in the qgep-plugin. It seems that it also stronger than the default values...

Oh I see. Can someone else please confirm that? If it's that, I can add a note in the doc.

**Comment by m-kuhn** [comment]
Yes, they are remembered since https://github.com/QGEP/qgepplugin/pull/41, the list is hardcoded (see https://github.com/QGEP/QGEP/issues/163).

**Comment by sjib** [comment]
@rbovard Can you document this - then I will merge your updates.

**Comment by rbovard** [comment]
Done https://github.com/QGEP/docs/pull/194/commits/7052f1c79ec82d0c3e5014a59b81797b68508fe9

**Comment by sjib** [comment]
@rbovard Your last commit is not part of your other pull request on the documentation (https://github.com/QGEP/docs/pull/194)  - can you integrate it their so I can push at once? Or do you want to make a separte pull request for this?

**Comment by rbovard** [comment]
@sjib Are you sure? See https://github.com/QGEP/docs/pull/194/commits
