### ISSUE TITLE
progression_geometry of reaches with more than 2 vertices

### ISSUE THREAD

**Issue by cymed** [QGEP/QGEP#759]
**Describe the bug**
When creating a new reach, the rp_to_level and rp_from level are taken from the attributes and used for the progression_geometry. Intermediate vertices are not used and, as the majority of users usually works in 2D, they are set to 0 (QGIS default). This leads to wrong progression_geometries in 3D
**To Reproduce**
Exact steps to reproduce the behavior:
1. Create a new reach with set rp_to_level and rp_from_level

**Expected behavior**
As the slope of a reach is constant by definition, the Z value of the vertex should be interpolated.

**Desktop (please complete the following information):**
 - QGEP plugin version: 1.5.6-B7
 - QGEP datamodel version: 1.5.6
 - QGEP project file version: 14.04.2022
 - QGIS Version: 3.22.5
 - OS: Windows

**Additional context**
As the fixing of this bug is computationally very expensive, it should be done only if rp_to_level and/or rp_from level are changed (generally, it would be a good idea to separate the geometry triggers from the attribute triggers. At the moment the geometry is recalculated every time an attribute in a reach is changed)

**Comment by sjib** [comment]
So would this be something to adapt in QGIS or in TEKSI wastewater?

**Comment by ponceta** [comment]
I'm not sure to understand the "bug" or the way you want to work?

In Pully we snap every reach on GPS points (3D) or wastewater nodes (3D). Triggers are yet present to update any modification on the reach geometry (x,y,z) or the reach point altitude (attribute).

![image](https://user-images.githubusercontent.com/8614223/200599481-b1364bb0-4550-421a-95a4-ffda5e06b414.png)

The Z values could be interpolated or imported from local knowledge but we have actually few way to keep track on the source of the information (M value in a ZM geometry) 

NULL Z values should be set on QGIS as nan or NULL values and not 0, these vertices are unknown Z vertices and I agree with you it is a bit problematic too. This is terribly wrong when you use a 3D representation of your reaches going to 0 and then back to the mesured altitude.

**Comment by cymed** [comment]
The problem arises when the data is provided by third parties, the previous cadastre was managed in 2D or the reach was covered before recording the heights. In all these cases the z values are missing.

The main problem is that we somehow need to distinguish between measured and interpolated vertices (you might also have interpolated points if a curved reach was split at one point, as ST_Split returns a LineString). As I don't see a viable way to make this distinguishment automatically, the update must not triggered manually. This in turn means that a QGIS-side solution would work (as long as the function is run after updating the geometry over rp_to_level & rp_from_level)

**Comment by ponceta** [comment]
As information, we implemented the Z interpolation of vertices using the topology for altimetry purposes in QGIS in the last years as long as making QGIS stuff 3D ready. Actual triggers between 3D geometries and attributes are here to make sure that data is as coherent as much as it can be.

An approach could have been the full 3D version which would have removed completely the editable attributes of elevation but this is a bit early. 

If some postgres/postgis functions need to be fixed to be able to work with 3D data we have to fix these functions.

Working with curves is still not very well supported in matters of 3D (but partially supported)

https://docs.qgis.org/latest/en/docs/user_manual/working_with_vector/editing_geometry_attributes.html#enable-topological-editing

**Comment by cymed** [comment]
For database migrations, manual editing of vertices is not viable. As I needed the function for a migration I just made, I wrote one:

```
CREATE OR REPLACE FUNCTION qgep_sys.interpolate_vertices(
	re_obj_id character varying)
    RETURNS geometry
    LANGUAGE 'plpgsql'
    COST 100
    VOLATILE PARALLEL UNSAFE
AS $BODY$
DECLARE
    pg_geom geometry(CompoundCurveZ,2056);
	txt_geom varchar;
	from_level numeric(7,3);
	to_level numeric(7,3);
	distance_ratio float;
	z_value numeric(7,3);
	search_string varchar;
	pt_geom geometry(Point,2056);

BEGIN
from_level:= (SELECT rp.level FROM qgep_od.reach re
     LEFT JOIN qgep_od.reach_point rp ON rp.obj_id::text = re.fk_reach_point_from::text
			 WHERE re.obj_id = re_obj_id);
to_level:= (SELECT rp.level FROM qgep_od.reach re
     LEFT JOIN qgep_od.reach_point rp ON rp.obj_id::text = re.fk_reach_point_to::text
			 WHERE re.obj_id = re_obj_id);	
pg_geom:=(SELECT re.progression_geometry FROM qgep_od.reach re WHERE re.obj_id = re_obj_id)	;		 
txt_geom:=ST_AsText( (SELECT re.progression_geometry from  qgep_od.reach re WHERE re.obj_id=re_obj_id));
CREATE TEMP TABLE vertices (idx int,geom geometry(Point,2056));
INSERT INTO vertices
SELECT(ST_DumpPoints(ST_Force2D(pg_geom))).path[2],(ST_DumpPoints(ST_Force2D(pg_geom))).geom;
--get vertices 
FOR  counter in 1..ST_NPoints(pg_geom) loop
	pt_geom:=(SELECT geom from vertices WHERE idx=counter);
	distance_ratio:=ST_Length(
	 	ST_LineSubstring(
			ST_CurveToLine(
				ST_Force2D(pg_geom)
			),
			0,
			ST_LineLocatePoint(
				ST_CurveToLine(
					ST_Force2D(pg_geom)
				),
				pt_geom
			)
		)
 	)
	/ST_Length(ST_Force2D(pg_geom));
	z_value:=round(--new z-value
		(from_level*(1-distance_ratio)
		 +to_level*distance_ratio
		)::numeric
		,3); 
	search_string:=left(
		substring(
			ST_AsText(
				pt_geom
			)
			,7)
		,-1); 
txt_geom:=replace(txt_geom,search_string||' 0',search_string||' '||z_value);	
 end loop;
DROP TABLE vertices;
 RETURN ST_GeomFromText(txt_geom,2056);
END
$BODY$;

ALTER FUNCTION qgep_sys.interpolate_vertices(character varying)
    OWNER TO postgres;
```

I didn't push it though, as I couldn't figure out how to make the SRID dynamic. If someone want to finalise it, feel free.

**Comment by sjib** [comment]
SRID is set as variable:
`SRID=2056`
https://github.com/QGEP/datamodel/blob/e94fef6296354464e5855be98275596af0b0c3aa/scripts/db_setup.sh#L20

and then used e.g. like this:
`ALTER TABLE qgep_od.txt_symbol ADD COLUMN symbolpos_geometry geometry('POINT', :SRID);`
https://github.com/QGEP/datamodel/blob/e94fef6296354464e5855be98275596af0b0c3aa/03_qgep_db_dss.sql#L86

**Comment by sjib** [comment]
@cymed Closed - please re-open if an issue again.
