### ISSUE TITLE
slope_per_mill calculation

### ISSUE THREAD

**Issue by spch-GL** [qgep/QGEP#765]
I need explanations about the slope calculation formula which is:
```
CASE
            WHEN rp_from.level > 0::numeric AND rp_to.level > 0::numeric THEN round((rp_from.level - rp_to.level) / re.length_effective * 1000::numeric, 1)
            ELSE NULL::numeric
END

```
I do not understand the use of **re.length_effective** in this formula because it is not necessarily a 2D value

**Comment by sjib** [comment]
Yes it includes the 3D information from the reach points and calculates the 3D length:
Definition for reach.length_effective: "Tatsächliche schräge Länge (d.h. nicht in horizontale Ebene projiziert)  inklusive Kanalkrümmungen"
Translated with deepl: "Actual oblique length (i.e., not projected in horizontal plane) including channel curvatures."
