### ISSUE TITLE
Create 2 missing views

### ISSUE THREAD

**Issue by rbovard** [qgep/QGEP#768]
**Describe the bug**
Currently the views related to `infiltration_installation` and `wwtp_structure` are missing.

**Expected behavior**
The views `vw_infiltration_installation` and `vw_wwtp_structure` are created.

**Desktop (please complete the following information):**
 - QGEP datamodel version: 1.5.6-1

**Additional context**
I'll open a PR with these steps:
- Add the views in [create_views.py](https://github.com/QGEP/datamodel/blob/master/view/create_views.py)
- Create the [delta](https://github.com/QGEP/datamodel/tree/master/delta) file
- Add the views in [drop_views.sql](https://github.com/QGEP/datamodel/blob/master/view/drop_views.sql)

**Comment by urskaufmann** [comment]
Infiltration_installation are part of the vw_qgep_wastewater_structure layer (ii-fields). The standard symbology for this layer does not show the ii as it should be, this will be better in the next standard_project...
The wwtp_structures are missing, that's right. In my opinion it's good to have a seperate layer for this class and not to integrate in to vw_qgep_wastewater_structure

**Comment by rbovard** [comment]
It will not be integrated in `vw_qgep_wastewater_structure`, but in spectific views (`vw_infiltration_installation` and `vw_wwtp_structure`), see [here](https://github.com/QGEP/datamodel/blob/428870305122a5011cea71b0c06fa6694f9fe34c/view/create_views.py#L51-L56).
