### ISSUE TITLE
Identifier and obj_id fields in QGIS 3.26.3

### ISSUE THREAD

**Issue by urskaufmann** [QGEP/QGEP#774]
**Describe the bug**
I create a new reach or wastewater_structure with the QGEP-Wizard. In QGIS 3.26.3, there are not valid values in the obj_id and identifer-fields. In vw_qgep_reach I can not press OK. In vw_qgep_wastewater_structure there are functions instead of the values in the obj_id-fields. I can press OK and the obj_id's are afterwards correct.

If I do the same in QGIS 3.22.11 (same project-file, wizard, create new reach), the obj_ids and identifers are all filled in, if the attribute-window opens.

**To Reproduce**

**Expected behavior**
the same behaviour in 3.26.3 as in QGIS 3.22.11: obj_id is prefilled, identifier = obj_id and can be changed.

**Screenshots / data**
![newreach_3-22-11](https://user-images.githubusercontent.com/1257403/203842488-d958fcb2-5e4a-4a98-96df-42ab3145de52.png)
3.22.11: new reach

![newreach_3-26-3](https://user-images.githubusercontent.com/1257403/203842552-f8c2cca9-add8-4775-b7fa-c696de442675.png)
3.26.3: new reach

![new_wws_3-22-11](https://user-images.githubusercontent.com/1257403/203842624-a571da4b-fcff-401d-878e-962d896a1e30.png)
3.22.11: new wastewater_structure

![new_wws_3-26-3](https://user-images.githubusercontent.com/1257403/203842669-ef47c69e-a090-4dab-b154-1e7431177e9b.png)
3.26.3: new wastewater_structure

**Desktop (please complete the following information):**
 - QGEP plugin version 1.5.6-b8
 - QGEP datamodel version 1.5.5
 - QGEP project file version
 - QGIS Version 3.22.11  and 3.26.3
 - OS Win10

**Additional context**

**Comment by ponceta** [comment]
@urskaufmann it looks like QGIS is evolving on the Edition mode :

![image](https://user-images.githubusercontent.com/8614223/205875866-3668389c-8d6c-4e51-bada-d1e4cc7d2cc3.png)

Doc Testing :

https://docs.qgis.org/testing/en/docs/user_manual/introduction/qgis_configuration.html#data-sources-properties

- [ ] Check in project properties that transaction groups are still enabled
- [ ] Check that evaluate default values on provider side are enabled
- [ ] Check on QGIS 3.28.1

**Comment by urskaufmann** [comment]
thanks @ponceta , that was the right tipp. But it's not that easy and it seems, that QGIS has a problem with this data-source properties:
If I open a project the first time with QGIS 3.26.3, then the data-source properties are set to: automatic transaction groups and "evaluate default values on provider side" is checked. So I just change to "local edit buffer" (as shown in arnauds picture) - and it works not.
If I open the project then the data-source properties (who are set to  automatic transaction groups and "evaluate default values on provider side" is checked), I have first to uncheck the "evaluate default values on provider side", then click on "anwenden/apply", then check the "evaluate default values on provider side" again and change to "local edit buffer", then click anwenden and ok: magic - it works! 

Looks like QGIS set's the checkbox "evaluate default values on provider side" first not how the setting really is.
Can somebody check this in QGIS (3.28)? Thanks

**Comment by sjib** [comment]
I can reproduce the error and the work around on QGIS 3.26 on Windows


QGIS-Version | 3.26.3-Buenos Aires | QGIS-Codeversion | 65e4edfdada
-- | -- | -- | --

I suggest to make this a critcial error

**Comment by ponceta** [comment]
I can't reproduce on QGIS 3.28.2

![image](https://user-images.githubusercontent.com/8614223/211262357-ac9ecd4b-e51b-428d-8871-e9feb81fb9a0.png)

**Comment by urskaufmann** [comment]
With 3.26.3: the setting of option "evaluate default values on provider side" has to be repeated after every project start. Hope on version 3.28.2

**Comment by ponceta** [comment]
![image](https://user-images.githubusercontent.com/8614223/213176133-88e384ad-e68a-483b-affd-0f8f811ca103.png)

3.28.2 is fine with it and provide an option to keep the edit state of every layer.

**Comment by urskaufmann** [comment]
3.28.2 works fine, did not have to ajust something in the project properties...

**Comment by sjib** [comment]
I can confirm also that 3.28.2 works again as expected. So we should [document somewhere to not use 3.26.x](https://github.com/QGEP/QGEP/discussions/792)
