### ISSUE TITLE
Wrong orientation = 0 in label export

### ISSUE THREAD

**Issue by urskaufmann** [QGEP/QGEP#775]
**Describe the bug**
- There are reach-labels with orientation 0, but the reach has another orientation
- There is an error, when textinhalt = NULL

orientation = 0: if the label is long, then the anker-point of the label is at the end of the line -> there is no orientation. The orientation should be taken in the middle of the label and not at the anker-point. Same result with QGIS tool "Beschriftung extrahieren" -> Problem is on QGIS side
textinhalt=NULL: can be prevented by an adjusted label definition (coalesce). And/or: just ignore such labels while exporting (with or without warning)

**Expected result**
- All labels have the correct orientation
- do not create textinhalt with NULL

**Screenshots / data**
![QGEP](https://user-images.githubusercontent.com/1257403/201469336-61539f4a-0d76-40f0-bd82-3c4bb08d68aa.png)
in QGEP it looks like this

![ExportINTERLIS](https://user-images.githubusercontent.com/1257403/201469354-45e0b278-9755-4a0a-b1fe-99e8940619cb.png)
Export-Result looks like this: red labelpoints have orientation=0

**Desktop (please complete the following information):**
 - QGEP plugin version 1.5.6-b8
 - QGEP datamodel version
 - QGEP project file version
 - QGIS Version 3.26.3
 - OS Win 10

**Comment by urskaufmann** [comment]
As I wrote: the result (orientation=0 when label is long/line is short) is the same, when I use QGIS-Tool Beschriftung extrahieren or when I use the QGEP-Interlis-Export. I think the problem is in the QGIS-Tool.

**Comment by urskaufmann** [comment]
@m-kuhn @nirvn : the orientation = 0 -problem as described above when using the QGIS-tool "Beschriftung extrahieren" with short lines has to be solved in QGIS Upstream, then it will also be solved in QGEP-text-export.

**Comment by urskaufmann** [comment]
I realized now, that the QGIS standard behaviour for to long labels is to turn them horizontal (orientation = 0). That is shown, if you choose the option "alle Beschriftungen auf diesem Layer anzeigen ...". And the QGEP-Plugin works with this option.
So orientation=0 is not an error, but also not what I expected.
If I move a label manually, the orientation seems to be fixed.
Better solution: go to "Beschriftung" - "Platzierung" - "Beschriftungsüberlauf" and encrease the number (e.g. 7mm) -> more labels are displayed with line-orientation.
And/or use a condition, that short lines are not labeled

**Comment by sjib** [comment]
![20230119_layer_vw_qgep_reach_beschriftungsueberlauf](https://user-images.githubusercontent.com/1265865/213435204-ca883286-de69-4979-80d7-e2eff8251fb3.png)

@urskaufmann Is this the setting to adjust?
Can you adjust that in the new project file issue to be added as default settings?  https://github.com/QGEP/QGEP/issues/772
