### ISSUE TITLE
Slope calculation error

### ISSUE THREAD

**Issue by spch-GL** [QGEP/QGEP#776]
**Describe the bug**
The formula used in the slope calcuation is wrong

**To Reproduce**
The actual formula is : https://github.com/QGEP/datamodel/blob/dcfc70131ad4fa90b99e690b0b59a426fa715f22/view/vw_qgep_reach.py#L45 
It is using the `length_effective` which is the actual 3D length.

**Expected behavior**
The formula should use the **projected length** instead. Something like `ST_Length(progression_geometry)`

**Screenshots / data**
Whith the actual Slope_per_mill formula, rounded at 1 decimal, any slope steeper than 4.64% is wrong !

**Desktop (please complete the following information):**
 - QGEP datamodel version: 1.5.6-1

**Additional context**
https://github.com/QGEP/QGEP/discussions/766

**Comment by sjib** [comment]
So this is the suggestion for the new defintion of _slope_per_mill:
`CASE 
          WHEN rp_from.level > 0 AND rp_to.level > 0 THEN round((rp_from.level - rp_to.level)/ST_Length(progression_geometry)*1000,1) 
          ELSE NULL 
        END AS _slope_per_mill`

- [ ] Does this work if progression _geometry is 2D
- [ ] Does this work if progression_geometry is 3D
- [ ] Is _slope_per_mill used elsewhere and how could this change influence it?

Any objections to this solution?

I added this topic to the agenda of the next [technical meeting in December](https://github.com/teksi/Home/wiki/Meeting-2022-12-13-(Technical-Group)).
@spch-GL if you want to join please contact @ponceta for an invitation.

**Comment by spch-GL** [comment]
Thank you for this proposal, but I think that at least Denis Rouzaud can answer your questions about _slope_per_mill. And as I'm not really envolved in QGEP, I prefer not to participate

**Comment by ponceta** [comment]
Your contribution is welcome.

Using actual 3D length should never result in higher slopes since 3D length can only be longer than the 2D length.

Could then be the length_effective calculation wrong?

`WHEN rp_from.level > 0 AND rp_to.level > 0 THEN round((rp_from.level - rp_to.level)/re.length_effective*1000,1) `

@spch-GL Denis does not take part to the technical group, but @olivierdalang  can maybe bring the subject on your behalf?

**Comment by spch-GL** [comment]
Yes, 3D length can only be longer than 2D length. Thus, the slope resulting of its use is lower.

Yes, I'm sure @olivierdalang can do that

**Comment by ponceta** [comment]
https://github.com/QGEP/datamodel/search?q=_slope_per_mill

- [X] _slope_per_mill is actually used only in vw_qgep_reach
- [X]  work if progression _geometry is 2D
- [X] Does this work if progression_geometry is 3D

**Comment by olivierdalang** [comment]
Fixed by https://github.com/QGEP/datamodel/pull/195
