### ISSUE TITLE
export vw_qgep_reach with alias-fieldnames and displayed values

### ISSUE THREAD

**Issue by urskaufmann** [QGEP/QGEP#784]
**Describe the bug**
When exporting data of layer vw_qgep_reach in my german qgep-project (with alias-fieldnames) with both options (with alias-fieldnames and values as displayed) I get all attributes with Wertbeziehung = 0.

**To Reproduce**
Exact steps to reproduce the behavior:
1. Select vw_qgep_reach
2. Choose Export / Objekte speichern als.. in contextmenu of selected layer
3. choose both options Aliase für exportierte Namen verwenden and Alle gewählten Feldrohwerte durch Anzeigewerte ersetzen
4. Export as Shp oder gpkg
5. Check the values of attributes with Wertbeziehung in the Exportfile

**Expected behavior**
Should work with both options checked.

**Desktop (please complete the following information):**
 - QGEP plugin version
 - QGEP datamodel version
 - QGEP project file version
 - QGIS Version 3.26.3
 - OS Win10

**Comment by urskaufmann** [comment]
Same problem with QGIS 3.28.2.: @signedav
Attached two example export files: one with Aliasnames (and "0" instead of values for attributes with valuelists), the other without aliasnames (english field names and correct values of the valuelists).
[export_ohne_aliasnamen.csv](https://github.com/QGEP/QGEP/files/10550771/export_ohne_aliasnamen.csv)
[export_mit_aliasnamen.csv](https://github.com/QGEP/QGEP/files/10550772/export_mit_aliasnamen.csv)

**Comment by mbernasocchi** [comment]
@domi4484 that's for you

**Comment by urskaufmann** [comment]
Attached an project with example data (line-layer with alias-fieldnames, just 2 valuelist ) and a screenshot that shows the 2 options
(QGEP is not a quick installation ;-) )
[Test.zip](https://github.com/QGEP/QGEP/files/10555597/Test.zip)

I think, when using the aliasnames for export, then the export does not find the fields for writing the values, if there are relations with valuelists

**Comment by domi4484** [comment]
Thanks I was not seeing the option "Alle gewählten Feldwerte durch Anzeigewerte ersetzen" because it is visible only in some cases :)

The file `testdaten.gpkg` is missing in the zip file

**Comment by urskaufmann** [comment]
[Test.zip](https://github.com/QGEP/QGEP/files/10556845/Test.zip)
now with gpkg

**Comment by urskaufmann** [comment]
Not working with QGIS 3.28.5.

**Comment by urskaufmann** [comment]
Not working with QGIS 3.30.1

**Comment by sjib** [comment]
@domi4484 Any update on this?

**Comment by domi4484** [comment]
@sjib no, I didn't had the time to work on this

**Comment by nirvn** [comment]
FYI this can be closed, fixed by a commit pushed a few months ago: https://github.com/qgis/QGIS/commit/6af7d4d8c6d65fb58a75a4fd9b55c48299342fbc

**Comment by urskaufmann** [comment]
Tested with QGIS 3.34.3, it works. Thanks!!
