### ISSUE TITLE
CI Issue with docker image qgep

### ISSUE THREAD

**Issue by ponceta** [QGEP/QGEP#786]
**Describe the bug**
CI is broken due to docker image qgep

**To Reproduce**
1. Run CI action on a PR
2. fails before testing start

**Expected behavior**
CI is running smoothly

**Screenshots / data**
![image](https://user-images.githubusercontent.com/8614223/209318307-79bdb9e4-85b2-45df-b568-d522a78d544b.png)

**Comment by olivierdalang** [comment]
fixed in https://github.com/QGEP/datamodel/pull/201
