### ISSUE TITLE
Sequence number not ok after export and import in new database

### ISSUE THREAD

**Issue by urskaufmann** [QGEP/QGEP#788]
Bug or Feature request? For a user it's a bug...

**Describe the bug**
For some reasons I have exported my data with VSA-DSS INTERLIS and imported the data in a new database. The sequence-numbers are not part of the dss-export-import. If I use the same oid-prefix in the old and the new database, I get very fast an error when digitizing new records, because the obj_id already exists (because the e.g. the seq_catchment_area_oid . current value is 7 and not 301 as in the old database and the catchment_area with "prefix"CA000007 already exists).

**Expected behavior**
There should be a easy way to recalculate the current value for every table in a database. Usecases: import of data with same prefix as database-prefix

**Additional context**
"Workaround": use a new oid_prefix or check old values and edit the value in the new database

**Comment by sjib** [comment]
We could check the last 6 characters and then reset the sequence with:

`SELECT obj_id, left(right(obj_id,8), 2) as class_shortcut, right(obj_id,6) as postfix FROM qgep_od.manhole
ORDER BY postfix DESC`

![postfixes_table_manhole](https://user-images.githubusercontent.com/1265865/210805465-3540355d-567b-4301-9583-3040bad48d7f.png)

SELECT max(right(obj_id,6)) as maxpostfix FROM qgep_od.manhole

![max_postfix](https://user-images.githubusercontent.com/1265865/210807126-fdee0f0a-15af-401b-a7b9-94d786a751a9.png)

`ALTER SEQUENCE qgep_od.seq_mutation_oid RESTART WITH (maxpostfix);` (see https://www.postgresql.org/docs/current/sql-altersequence.html)

This only works if they are all numbers - this would need an additional check.

Additional background: https://www.postgresql.org/docs/current/sql-createsequence.html

@urskaufmann Can you try if this could be a valid way for a new function?

**Comment by urskaufmann** [comment]
Does not work - I think it's because maxpostfix is text and "Restart with" must be a number. If I use just the line "Alter sequence ... with 140;", it works.
How to convert this maxpostfix to integer? 

No Solution, if we change the postfix for more than 1M records #764  ?

**Comment by sjib** [comment]
> How to convert this maxpostfix to integer?

Einfach noch ::int hinter die Variable, allenfalls schon im SELECT statement

`ALTER SEQUENCE qgep_od.seq_mutation_oid RESTART WITH (maxpostfix::int);`

Mehr detaillierte Ideen hier:
https://stackoverflow.com/questions/69218854/how-to-cast-string-into-int-in-postgresql
oder wenn man noch Elemente löschen will wie allfällige Buchstaben:
https://learnsql.com/cookbook/how-to-convert-a-string-to-a-numeric-value-in-postgresql/

**Comment by sjib** [comment]
> No Solution, if we change the postfix for more than 1M records https://github.com/QGEP/QGEP/discussions/764 ?

Von der Grundidee her gleich, einfach komplizierter in der Umsetzung:
Suchen des aktuell "grössten" Postfix, dann eins höher einen neuen erzeugen.

**Comment by sjib** [comment]
@urskaufmann I found out that the RESTART WITH 1 has to be a constant and not a variable - see https://stackoverflow.com/questions/23402859/use-a-variable-or-parameter-to-specify-restart-value-for-alter-sequence

Here I found an alternative:
https://stackoverflow.com/questions/5342440/reset-auto-increment-counter-in-postgres
that uses a SELECT in the SELECT and then it works:

`SELECT SETVAL('qgep_od.seq_mutation_oid', (SELECT cast(max(right(obj_id,6))as int) FROM qgep_od.mutation));`

See also https://www.postgresql.org/docs/current/functions-sequence.html
I tested on Postgres12

**Comment by urskaufmann** [comment]
It works - if the qgep_od.table has records.

Is it possible to do this script for all sequences without hardcoding this tablenames?

**Comment by ponceta** [comment]
Technical Group propose to document the bug workaround as after import scripts procedure.

**Comment by urskaufmann** [comment]
The solution is a function and a sql-script:  
[adjust_max_sequence.zip](https://github.com/QGEP/QGEP/files/11204457/adjust_max_sequence.zip)

1. install the function in the database with "create_function_adjust_max_sequence.sql" in the zip-file.
2.  be sure you have the correct oid-prefix defined in table qgep_sys. oid_prefixes (just one prefix is true, prefix starts with 'ch')
3.  execute the 'adjust_max_sequence_all_qgep_od_tables.sql' in the database.

For each table, the largest number in the last six positions of the obj_id is searched for records with the actual prefix. This number  is set as current value in the qgep_od - sequences.
Works best with obj_id's that are created the qgep-way (prefix+class-shortcut+consecutive six-digit number) ;-)

Thanks @sjib for the help with the sql.
