### ISSUE TITLE
Channel: usage_current is not properly saved

### ISSUE THREAD

**Issue by andreasneumann** [qgep/QGEP#79]
I defined a usage_current, but it is saved as NULL

**Comment by andreasneumann** [comment]
on further investigation I see that the network element corresponding with the reach has a NULL value in fk_wastewater_structure and thus further joins for display in vw_reach fail

**Comment by m-kuhn** [comment]
I had fixed this issue in the datamodel scripts before. But it got lost on the way in the demo dataset.

It's about time that we have a clean way to create a demo dataset! I am losing too much time just because we have to maintain the demo dataset and the datamodel scripts separately.

**Comment by m-kuhn** [comment]
Should be solved in the latest dump.
Please check and reopen if appropriate.
