### ISSUE TITLE
CI is Broken for qgep .qgs translation from transifex

### ISSUE THREAD

**Issue by ponceta** [QGEP/QGEP#795]
**Describe the bug**
CI is Broken for qgep .qgs translation from transifex

**Additional context**
https://github.com/QGEP/QGEP/actions/runs/4013520026/jobs/6892955557

**Comment by ponceta** [comment]
ping @why-not-try-calmer

**Comment by why-not-try-calmer** [comment]
On it

**Comment by why-not-try-calmer** [comment]
Feel free to reopen should anything bad occur
