### ISSUE TITLE
qgep_import and qgep_swmm schema have no rights management

### ISSUE THREAD

**Issue by ponceta** [QGEP/QGEP#796]
**Describe the bug**
qgep_import schema has no rights management

![image](https://user-images.githubusercontent.com/8614223/214839401-a797a4ce-c047-4a98-b07e-e288314e5133.png)

See https://github.com/QGEP/datamodel/blob/master/12_1_roles.sql

This implies that the user has to set manually access to views to theses schemas or give full access to the database (which is a bad practice)

**Expected behavior**
qgep_import and qgep_swmm schemas have a correct right management system proposed with qgep initialization.

**Additional context**
Rights management should be enhanced generally for qgep.

**Comment by ponceta** [comment]
@varrieta @tproduit could you suggest some enhancement proposals or at least mention what rights you have given to your users?

**Comment by tproduit** [comment]
I don't have customized much the rights. I would say that:

* qgep_user must have **read and write** rights in _qgep_import_ and _qgep_swmm_ 
* qgep_viewer must have **read** rights in _qgep_import_ and _qgep_swmm_

**Comment by ponceta** [comment]
Fix merged.
