### ISSUE TITLE
Drop views before pum upgrade, create views after (CI included)

### ISSUE THREAD

**Issue by ponceta** [QGEP/QGEP#798]
**Describe the bug**
Drop views before pum upgrade, create views after pum upgrade (CI included)

**To Reproduce**
Views alterations will fail upgrade process
People might be tempted to apply only sql delta scripts which will lead to inconsistencies.

**Expected behavior**
Every upgrade of the datamodel is made by pum using the standard upgrade process common to all TEKSI modules.

**Additional context**
A modification of all precedent deltas concerning views is necessary (otherwise it will break compatibility with version 1.0.0)

**Comment by sjib** [comment]
I think we would have a least to run drop_symbology triggers first also with delete views?
https://github.com/QGEP/datamodel/blob/6aa60794729f24edcd9a7c6d7ad124a605dec4e9/06_symbology_functions.sql#L648

@ponceta What do you think?
