### ISSUE TITLE
last_modifications are not filled in

### ISSUE THREAD

**Issue by andreasneumann** [QGEP/QGEP#80]
It seems like in most tables the timestamp for last_modification is not set

**Comment by sjib** [comment]
Write rule or trigger for these fields (exists in each table). Demo see http://pointbeing.net/weblog/2008/03/mysql-versus-postgresql-adding-a-last-modified-column-to-a-table.html

ALTER TABLE mytable 
    ADD last_modification TIMESTAMP  DEFAULT CURRENT_TIMESTAMP;

 /* only once */
CREATE OR REPLACE FUNCTION update_last_modification_column()
        RETURNS TRIGGER AS '
  BEGIN
    NEW.last_modification = NOW();
    RETURN NEW;
  END;
' LANGUAGE 'plpgsql';
 
/*For each table */
CREATE TRIGGER update_lastmodified_modtime BEFORE UPDATE
  ON mytable FOR EACH ROW EXECUTE PROCEDURE
  update_lastmodified_column();

**Comment by sjib** [comment]
Added to create_sql - ready in next version

**Comment by andreasneumann** [comment]
Hi Stefan,
There is a simpler way to do it without the trigger. Just use "DEFAULT now()" in the table definition, e.g.
last_modification DEFAULT now()

This can already be part of the CREATE TABLE statement and doesn't require a "ALTER TABLE"

**Comment by andreasneumann** [comment]
Here is the correct syntax in the CREATE TABLE statement:

last_modification timestamp without time zone DEFAULT now(),

**Comment by sjib** [comment]
Ändert das den Wert auch wenn ich ein beliebiges Attribut in der Tabelle ändere, nicht nur wenn ich den Datensatz neu erzeuge?
ALTER table brauche ich, weil ich Sub und Superclass Tabellen habe und nur bei den Superclasstabellen das Last_modification anfüge - das ist für mich in der Erzeugung des SQL Statements einfacher

**Comment by sjib** [comment]
Check with todays model release and tell me whether ok.

**Comment by m-kuhn** [comment]
It doesn't work for me and I couldn't find any triggers related to this in the latest datamodel.

**Comment by sjib** [comment]
How would I need to adjust the code? @andreasneumann can you give me another solution to this?

**Comment by 3nids** [comment]
@sjib you have an example written by @m-kuhn 
see https://github.com/QGEP/datamodel/commit/103588ca323604e3d884e9f54bd1f6145c50a9be
The trigger function remains the same for all tables. You just need to create the trigger on each table.

**Comment by sjib** [comment]
I added this in the metadatabase. I have one open question: Do I need to add the code only to subtables or also to superclass tables. What about classes without subclasse?

**Comment by m-kuhn** [comment]
@sjib see link in the previous post

parent/standalone:
https://github.com/QGEP/datamodel/commit/103588ca323604e3d884e9f54bd1f6145c50a9be#diff-6aa404a4916b578c5870094bf3aef9c9R926

child:
https://github.com/QGEP/datamodel/commit/103588ca323604e3d884e9f54bd1f6145c50a9be#diff-6aa404a4916b578c5870094bf3aef9c9R1838

**Comment by sjib** [comment]
Updated in Metadatabase code - ready for next release
