### ISSUE TITLE
Combobox sizes too small

### ISSUE THREAD

**Issue by andreasneumann** [qgep/QGEP#81]
Some of the comboboxes are too small (both not enough wide and not enough tall).

Examples:

form "vw_wizard_reach_channel": comboboxes for "pipe_profile" and "owner". I guess there are several others. It is mainly the case with combobox widgets with a button to create new elements.

**Comment by m-kuhn** [comment]
Looks good here.
Please try on a machine with custom widgets installed and reopen if appropriate.
