### ISSUE TITLE
Datamodel tool - download of datamodel wrong path

### ISSUE THREAD

**Issue by sjib** [QGEP/QGEP#810]
**Describe the bug**
The datamodel does not find the datamodel  1.5.6 or 1.6.0 

**To Reproduce**
Exact steps to reproduce the behavior:
1. Go to 'QGEP/Datamodel tool'
2. Click on 'Select release'
3. Select pg_configuration
4. Action 'Initialize'
5. See error

**Expected behavior**
Datamodel tool should be able to initialize the selected datamodel version in the selected database

**Screenshots / data**
![20230317_datamodel_tool_datamodel_path_not_found](https://user-images.githubusercontent.com/1265865/225932238-62dfbc55-584d-45d2-9d0c-ac0a853b929f.jpg)

**Desktop (please complete the following information):**
 - QGEP plugin version 1.6.0
 - QGEP datamodel version - 1.5.6 or 1.6.0 to be installed
 - QGEP project file version - none
 - QGIS Version 3.28.4
 - OS Windows 11

**Additional context**

**Comment by sjib** [comment]
With plugin release 1.6.0-rc.2 it was working https://github.com/QGEP/QGEP/issues/805#issuecomment-1465910973

**Comment by sjib** [comment]
![20230317_datamodel_tool_datamodel_path_not_found2_160](https://user-images.githubusercontent.com/1265865/225939406-b91612cc-821f-4fba-94d5-3f99f0c87c6c.jpg)

The same with 1.6.0

**Comment by olivierdalang** [comment]
Fixed:

- removed the 1.5.6 link in https://github.com/QGEP/qgepplugin/pull/94
- fixed CI which did not upload the assets in https://github.com/QGEP/datamodel/pull/210
