### ISSUE TITLE
Upgrade to 1.6.0 impossible with multiple materials using same vsa_code

### ISSUE THREAD

**Issue by ponceta** [QGEP/QGEP#817]
**Describe the bug**
If you have custom materials referencing the same vsa_code, update will fail on delta 1.5.8 lines :

https://github.com/QGEP/datamodel/blob/84729b2952c469c1758e1f095021aee7c72e0b82/delta/delta_1.5.8_tbl_swmm_coefficient_friction.sql#L6C1-L8

![image](https://user-images.githubusercontent.com/8614223/235675193-ddd67f48-8054-4071-9fe4-5a657cc52172.png)

It would be nice to support this small customization (custom materials are a nice way of improving user experience without breaking the vsa compatibility)

**To Reproduce**
Exact steps to reproduce the behavior:
1. Create a custom material in reaches, reference an existing vsa_code
2. Apply delta 1.5.8

**Expected behavior**
Delta can be applied with custom values too.

**Comment by sjib** [comment]
@ponceta I think this is solved - can you close?
