### ISSUE TITLE
Clicking on a cover of a manhole does not open the manhole mask

### ISSUE THREAD

**Issue by andreasneumann** [qgep/QGEP#82]
Seems like if I click on an existing cover, the corresponding manhole mask is not embedded.

**Comment by m-kuhn** [comment]
Have you installed the custom widgets plugin?

**Comment by andreasneumann** [comment]
no - I did not know that this was a requirement. Where can I get this plugin?

**Comment by m-kuhn** [comment]
That is an installation option of QGIS.
On OSGeo4W I think it can be installed from the repository.
If you compile yourself you have to enable it in CMake
(WITH_CUSTOM_WIDGETS) and install QGIS to your system (without custom
prefix I assume).
There is also the option to specify the QT_PLUGIN_PATH if you have
installed to a custom location.

**Comment by m-kuhn** [comment]
Confirmed.
Custom Widgets need to be installed.
Expand the message above to get some input about how to do it if you compile yourself.
