### ISSUE TITLE
GitHub 2FA fails and you might loose all access to account and projects here.

### ISSUE THREAD

**Issue by ghost** [QGEP/QGEP#833]
Hello everyone

I hope you will forgive me for placing this here. But it is something that might effect how we are working here and I would like to warn you all. I recently activated 2FA in GitHub as is requested and required by the end of 2023. After a week or so of everything working fine my Microsoft Authentication App stopped working with GitHub. I was told to recover my account with the recovery codes. They sadly didn't work either. I wanted to contact GitHub on support but couldn't because you have to log in to be able to do that. The only access to help was a bot that told me GitHub could no longer give me access back to my old account due to security reasons??? I was told I must detach my email and create a new account. That all my repositories, Issues, Discussions... would be lost. So much for security!!! Who for!!!
Now I am here in my new new GitHub account still waiting for GitHub support to contact me. It has been a week now and I am still waiting. I googled a lot and found I am one of hundreds with the same problem and GitHub is blocked too with the backlog of people in panic. The best tip it seems it turn 2FA off and go to Txt message authentication. **Or activate Txt Message as an alternative access check.** I would hate to see all the connections here get lost because the system stops working and all the data gets lost.

I hope GitHub can reconnect my account but in internet it sounds like I will have lost it.

I know it's not QGEP but if 2FA blocks us out from access here and we lose accounts it will cause damage.

Good luck and I hope you don't get the same problem.

**Comment by sjib** [comment]
Thanks for the info. That is very annoing.

 ***@***.***> @Arnaud Poncet-Montanges (G) Do we have to think about some extra backup of our github work somewhere else?

**Comment by ZamudioPeter** [comment]
I just cannot believe it to be honest. I am still waiting for GitHub to contact me. I am now paying for 2 Pro accounts as with a free account there is no real support. My 1st account is locked up and the new account is empty.
For some this would be a really terrible situation to be in.

**Comment by ponceta** [comment]
Very strange. It is indeed a good thing to test the recovery of any 2FA methods when they are set but it's not only for GitHub but for all web applications. @ZamudioPeter A full password reset does not enables you to recover your account? You can also use Github mobile app to validate 2FA in parallel of your prefered authenticator.

@sjib we have organizations to avoid this scenario (even if a user lost his access, others can still manage administration of organizations including adding new members)

On TEKSI side it is an identified risk that online plateforms like GitHub and GitLab could, like any plateforms be unaccessible, but using git to deploy theses solutions locally garanties to a certain extent that the code is replicated locally to members and could be retrieved in that way.

**Comment by ponceta** [comment]
Now we have a ghost hauting this issue. Let's close it to avoid it escaping.
