### ISSUE TITLE
shape of manhole

### ISSUE THREAD

**Issue by 3nids** [qgep/QGEP#84]
At the SIGE, we have the shape of the manohle (rectangular, elliptic, circular, etc) and dimension 1 and 2.

I can't see any place to define the shape of the manhole.
Is it supposed to go in od_wastewater_structure.detail_geometry_geometry?

The problem, though, is that I don't know the orientation of the shape (rectangle or ellipse). Therefore, I won't be able to build a geometry.

What is the strategy?

**Comment by sjib** [comment]
VSA-DSS does not support orientation of manhole except when you add a detailed geometry, but this one is usually not expected for manholes. Many communities find this too detailed and do not have the money to collect and keep up to date this information. In the visualisation of Leitungskataster (LK) and the Werkinformation (WI) of sia405 there are only logos that do not need the orientation.

Dimension and Detailed Geometry (Attributation rules):
Geometry_detaillee: Géométrie détaillée particulièrement pour un OUVRAGE_SPECIAL. Pour l’attribut CHAMBRE_STANDARD utilisez Dimension1 et 2, de même pour une INSTALLATION_INFILTRATION normée. Les canalisations n’ont en général pas de géométrie
détaillée. (exception si le canal est un OUVRAGE_SPECIAL BEP_canal_accumulation,
BEP_canal_stockage, BEP_canal_retention). Il est inscrit dans INTERLIS OPTIONAL, car
l’attribut n’est pas obligatoire pour tous les ouvrages d’assainissement du réseau.

Detaillierte Geometrie insbesondere bei Spezialbauwerken. Für Normschächte i.d. R.
Dimension1 und 2 verwenden. Dito bei normierten Versickerungsanlagen. Kanäle haben
normalerweise keine Detailgeometrie. (Ausnahme falls Kanal als Spezialbauwerk modelliert wird:
Regenbecken_Regenrueckhaltekanal, Regenbecken_Fankgkanal, Regenbecken_Stauraumkanal). In INTERLIS OPTIONAL gesetzt, da nicht bei allen Abwasserbauwerken zwingend.

Dimension2 de la chambre (plus petite mesure intérieure). With round manhole leave dimension2 empty, with ovale add it, for rectangular shapes use detailled geometry.
Dimension2 des Schachtes (kleinstes Innenmass). Bei runden Schächten wird Dimension2 leer
gelassen, bei ovalen abgefüllt. Für eckige Schächte Detailgeometrie verwenden.

**Comment by 3nids** [comment]
Thanks a lot Stefan for this clear explanation.
