### ISSUE TITLE
Missing dependency sqlalchemy

### ISSUE THREAD

**Issue by paalped** [QGEP/QGEP#841]
**Describe the bug**
The python dependency sqlalchemy is missing when installing QGEP on a clean windows QGIS installation.

**To Reproduce**
1.) Install a new clean instance of QGIS
2:) Install QGEP
Error will yield: CRITICAL Error : Could not load qgepqwat2ili due to unmet dependencies. See logs for more details.
 qgepplugin.processing_provider:No module named 'sqlalchemy'

**Expected behavior**
You would expect the plugin to install its own dependencies in the QGEP plugin directory.

**Desktop (please complete the following information):**
 - QGEP plugin version 1.6.1               
 - QGIS Version 3.32.3
 - OS Windows

**Comment by sjib** [comment]
@paalped You have to install them manually if it does not work automatically: https://qgep.github.io/docs/en/admin-guide/interlis-io/index.html#python-libraries
