### ISSUE TITLE
Lost relations in copy of the project

### ISSUE THREAD

**Issue by urskaufmann** [QGEP/QGEP#844]
**Describe the bug**
I copy a qgep-project-file with several special configurations (labels, symbols) and change the service-name in notepad from pg_project1 to pg_project2.
When I open the project2.qgs, everything seems ok. Except the relations in the attribut form are now white lines.
Look at the pics  

**To Reproduce**
Exact steps to reproduce the behavior:
1. copy qgep-project file ->project2
2. change the service-name with texteditor (replace all)
3. open project2
4. control the attribute form with relations

**Expected behavior**
same behaviour in project 2 as in project 1

**Screenshots / data**
project 1:
![relations exist](https://github.com/QGEP/QGEP/assets/1257403/b09361ee-4950-4548-ad48-5ec3a101b323)

project 2 with new service-name:
![relations lost](https://github.com/QGEP/QGEP/assets/1257403/e21ac673-cb9b-4efe-a770-2e450f696e99)

**Desktop (please complete the following information):**
 - QGEP plugin version 1.6.1 
 - QGEP datamodel version 1.6.0
 - QGEP project file version

 - QGIS Version 3.28.15
 - OS Win 10

**Additional context**
- I think it's not a QGEP-problem, it's a QGIS-problem
- Why does it work when creating a project-file with datamodel-tool from the default qgs?

**Comment by ponceta** [comment]
@urskaufmann Can you reproduce it? If yes could you send me the original and the altered project? Is it possible that your pg_service name would be included in relation names and would be altered through the replace all?

**Comment by urskaufmann** [comment]
Sorry, I can not reproduce.? My QGIS Version is now 3.34.4. May be this is the reason?
