### ISSUE TITLE
1.6.2 Export SIA405 with labels

### ISSUE THREAD

**Issue by urskaufmann** [qgep/QGEP#849]
**Describe the bug**
When choosing Export sia405, without labels, it works
When choosing Export sia405 with labels, I get this error:

Ein Fehler trat bei der Ausführung von Python-Code auf: 
sqlalchemy.exc.IntegrityError: (psycopg2.errors.NotNullViolation) null value in column "textinhalt" of relation "sia405_textpos" violates not-null constraint DETAIL:  Failing row contains (51991, Werkplan, null, null). [SQL: INSERT INTO pg2ili_sia405abwasser.sia405_textpos (t_id, plantyp, textinhalt, bemerkung) VALUES (%(t_id)s, %(plantyp)s, %(textinhalt)s, %(bemerkung)s)] [parameters: ({'t_id': 48052, 'plantyp': 'Werkplan', 'textinhalt': 'CU 1000 ', 'bemerkung': None}, {'t_id': 48053, 'plantyp': 'Werkplan', 'textinhalt': 'PVC 125 ', 'bemerkung': None}, {'t_id': 48054, 'plantyp': 'Werkplan', 'textinhalt': 'PVC 150 ', 'bemerkung': None}, {'t_id': 48055, 'plantyp': 'Werkplan', 'textinhalt': 'PVC 125 ', 'bemerkung': None}, {'t_id': 48056, 'plantyp': 'Werkplan', 'textinhalt': 'PVC 150 ', 'bemerkung': None}, {'t_id': 48057, 'plantyp': 'Werkplan', 'textinhalt': 'PVC 200 ', 'bemerkung': None}, {'t_id': 48058, 'plantyp': 'Werkplan', 'textinhalt': 'PVC 300 ', 'bemerkung': None}, {'t_id': 48059, 'plantyp': 'Werkplan', 'textinhalt': 'PVC 200 ', 'bemerkung': None}  ... displaying 10 of 6184 total bound parameter sets ...  {'t_id': 54234, 'plantyp': 'Werkplan', 'textinhalt': 'CU 150 ', 'bemerkung': None}, {'t_id': 54235, 'plantyp': 'Werkplan', 'textinhalt': 'PVC 180 ', 'bemerkung': None})] (Background on this error at: http://sqlalche.me/e/13/gkpj) 
Traceback (most recent call last):
  File "C:\PROGRA~1\QGIS3\apps\Python39\lib\site-packages\sqlalchemy\engine\base.py", line 1256, in _execute_context
    self.dialect.do_executemany(
  File "C:\PROGRA~1\QGIS3\apps\Python39\lib\site-packages\sqlalchemy\dialects\postgresql\psycopg2.py", line 912, in do_executemany
    cursor.executemany(statement, parameters)
psycopg2.errors.NotNullViolation: null value in column "textinhalt" of relation "sia405_textpos" violates not-null constraint
DETAIL:  Failing row contains (51991, Werkplan, null, null).

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users/KAU/AppData/Roaming/QGIS/QGIS3\profiles\qgep161_prerealise/python/plugins\qgepplugin\qgepqwat2ili\qgepqwat2ili\gui\__init__.py", line 608, in action_do_export
    qgepsia405_export(selection=export_dialog.selected_ids, labels_file=labels_file_path, orientation=eorientation)
  File "C:\Users/KAU/AppData/Roaming/QGIS/QGIS3\profiles\qgep161_prerealise/python/plugins\qgepplugin\qgepqwat2ili\qgepqwat2ili\qgepsia405\export.py", line 1121, in qgep_export
    abwasser_session.flush()
  File "C:\PROGRA~1\QGIS3\apps\Python39\lib\site-packages\sqlalchemy\orm\session.py", line 2540, in flush
    self._flush(objects)
  File "C:\PROGRA~1\QGIS3\apps\Python39\lib\site-packages\sqlalchemy\orm\session.py", line 2682, in _flush
    transaction.rollback(_capture_exception=True)
  File "C:\PROGRA~1\QGIS3\apps\Python39\lib\site-packages\sqlalchemy\util\langhelpers.py", line 68, in __exit__
    compat.raise_(
  File "C:\PROGRA~1\QGIS3\apps\Python39\lib\site-packages\sqlalchemy\util\compat.py", line 182, in raise_
    raise exception
  File "C:\PROGRA~1\QGIS3\apps\Python39\lib\site-packages\sqlalchemy\orm\session.py", line 2642, in _flush
    flush_context.execute()
  File "C:\PROGRA~1\QGIS3\apps\Python39\lib\site-packages\sqlalchemy\orm\unitofwork.py", line 422, in execute
    rec.execute(self)
  File "C:\PROGRA~1\QGIS3\apps\Python39\lib\site-packages\sqlalchemy\orm\unitofwork.py", line 586, in execute
    persistence.save_obj(
  File "C:\PROGRA~1\QGIS3\apps\Python39\lib\site-packages\sqlalchemy\orm\persistence.py", line 239, in save_obj
    _emit_insert_statements(
  File "C:\PROGRA~1\QGIS3\apps\Python39\lib\site-packages\sqlalchemy\orm\persistence.py", line 1083, in _emit_insert_statements
    c = cached_connections[connection].execute(statement, multiparams)
  File "C:\PROGRA~1\QGIS3\apps\Python39\lib\site-packages\sqlalchemy\engine\base.py", line 1011, in execute
    return meth(self, multiparams, params)
  File "C:\PROGRA~1\QGIS3\apps\Python39\lib\site-packages\sqlalchemy\sql\elements.py", line 298, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "C:\PROGRA~1\QGIS3\apps\Python39\lib\site-packages\sqlalchemy\engine\base.py", line 1124, in _execute_clauseelement
    ret = self._execute_context(
  File "C:\PROGRA~1\QGIS3\apps\Python39\lib\site-packages\sqlalchemy\engine\base.py", line 1316, in _execute_context
    self._handle_dbapi_exception(
  File "C:\PROGRA~1\QGIS3\apps\Python39\lib\site-packages\sqlalchemy\engine\base.py", line 1510, in _handle_dbapi_exception
    util.raise_(
  File "C:\PROGRA~1\QGIS3\apps\Python39\lib\site-packages\sqlalchemy\util\compat.py", line 182, in raise_
    raise exception
  File "C:\PROGRA~1\QGIS3\apps\Python39\lib\site-packages\sqlalchemy\engine\base.py", line 1256, in _execute_context
    self.dialect.do_executemany(
  File "C:\PROGRA~1\QGIS3\apps\Python39\lib\site-packages\sqlalchemy\dialects\postgresql\psycopg2.py", line 912, in do_executemany
    cursor.executemany(statement, parameters)
sqlalchemy.exc.IntegrityError: (psycopg2.errors.NotNullViolation) null value in column "textinhalt" of relation "sia405_textpos" violates not-null constraint
DETAIL:  Failing row contains (51991, Werkplan, null, null).

[SQL: INSERT INTO pg2ili_sia405abwasser.sia405_textpos (t_id, plantyp, textinhalt, bemerkung) VALUES (%(t_id)s, %(plantyp)s, %(textinhalt)s, %(bemerkung)s)]
[parameters: ({'t_id': 48052, 'plantyp': 'Werkplan', 'textinhalt': 'CU 1000 ', 'bemerkung': None}, {'t_id': 48053, 'plantyp': 'Werkplan', 'textinhalt': 'PVC 125 ', 'bemerkung': None}, {'t_id': 48054, 'plantyp': 'Werkplan', 'textinhalt': 'PVC 150 ', 'bemerkung': None}, {'t_id': 48055, 'plantyp': 'Werkplan', 'textinhalt': 'PVC 125 ', 'bemerkung': None}, {'t_id': 48056, 'plantyp': 'Werkplan', 'textinhalt': 'PVC 150 ', 'bemerkung': None}, {'t_id': 48057, 'plantyp': 'Werkplan', 'textinhalt': 'PVC 200 ', 'bemerkung': None}, {'t_id': 48058, 'plantyp': 'Werkplan', 'textinhalt': 'PVC 300 ', 'bemerkung': None}, {'t_id': 48059, 'plantyp': 'Werkplan', 'textinhalt': 'PVC 200 ', 'bemerkung': None}  ... displaying 10 of 6184 total bound parameter sets ...  {'t_id': 54234, 'plantyp': 'Werkplan', 'textinhalt': 'CU 150 ', 'bemerkung': None}, {'t_id': 54235, 'plantyp': 'Werkplan', 'textinhalt': 'PVC 180 ', 'bemerkung': None})]
(Background on this error at: http://sqlalche.me/e/13/gkpj)

Python-Version: 3.9.18 (heads/master:5eba59e, Feb  1 2024, 20:02:10) [MSC v.1929 64 bit (AMD64)] 
QGIS-Version: 3.34.4-Prizren Prizren, decd43dc 

**Desktop (please complete the following information):**
 - QGEP plugin version 1.6.2
 - QGEP datamodel version 1.6.1
 - QGEP project file version -
 - QGIS Version 3.34.4
 - OS Win 10

**Additional context**
Imo QGEP should select just labels that have a text to export. I can not test before, if there are labels without text. But the export should know the constraint and not select empty labels.

**Comment by sjib** [comment]
Either we suppress labels without textinhalt - we would need to filter these labels where textinhalt isNull:
`            "textinhalt": row["properties"]["LabelText"],`
For me not clear where to filter?

Here a sample of the geojson: https://raw.githubusercontent.com/QGEP/qgepqwat2ili/cfa67c2742961e464c73462ab8e8267104af02d2/qgepqwat2ili/tests/data/labels.geojson

```
{
"type": "FeatureCollection",
"name": "labels",
"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:EPSG::2056" } },
"features": [
{ "type": "Feature", "properties": { "Layer": "vw_qgep_reach", "FeatureID": 108, "LabelText": "CS 250 75.06m 99.3‰", "LabelWidth": 31.98841777, "LabelHeight": 3.43677216, "LabelRotation": 326.19, "LabelUnplaced": false, "Family": "MS Shell Dlg 2", "Size": 8.25, "Italic": false, "Bold": false, "Underline": false, "FontStyle": null, "FontLetterSpacing": 0.0, "FontWordSpacing": 0.0, "MultiLineAlignment": "left", "MultiLineHeight": 1.0, "Color": "#660066", "FontOpacity": 100.0, "BufferDraw": true, "BufferSize": 2.8346, "BufferColor": "#ffffff", "BufferOpacity": 100.0, "qgep_obj_id": "ch13p7mzRE001221", "scale": "Leitungskataster", "path": "C:\\Users\\Olivier\\AppData\\Local\\Temp\\labels-Leitungskataster_694d7704359a42f1835e573c8b549263.geojson.annotated.geojson" }, "geometry": { "type": "Point", "coordinates": [ 2747274.089154582936317, 1262710.040365642635152 ] } },
{ "type": "Feature", "properties": { "Layer": "vw_qgep_wastewater_structure", "FeatureID": 6, "LabelText": "5420.0750", "LabelWidth": 11.36778483, "LabelHeight": 2.90803798, "LabelRotation": 0.0, "LabelUnplaced": false, "Family": "MS Shell Dlg 2", "Size": 6.75, "Italic": false, "Bold": false, "Underline": false, "FontStyle": null, "FontLetterSpacing": 0.0, "FontWordSpacing": 0.0, "MultiLineAlignment": "left", "MultiLineHeight": 1.0, "Color": "#660066", "FontOpacity": 100.0, "BufferDraw": false, "BufferSize": 0.0, "BufferColor": null, "BufferOpacity": 0.0, "qgep_obj_id": "ch13p7mzMA005019", "scale": "Leitungskataster", "path": "C:\\Users\\Olivier\\AppData\\Local\\Temp\\labels-Leitungskataster_694d7704359a42f1835e573c8b549263.geojson.annotated.geojson" }, "geometry": { "type": "Point", "coordinates": [ 2747317.289560908451676, 1262731.701755047775805 ] } },
```

Or we set a replacement value, if there is no content in textinhalt:
https://github.com/QGEP/qgepqwat2ili/blob/cfa67c2742961e464c73462ab8e8267104af02d2/qgepqwat2ili/qgep/export.py#L221
`            "textinhalt": row["properties"]["LabelText"],`

**Comment by urskaufmann** [comment]
I can not imagine, that labels witout text or with repalcement value make sense , specially because the formula how to create the text is not tranfered. Means I will never be sure how to create the text after I have e.g. changed an attribut. 
Suppress.

**Comment by sjib** [comment]
It looks like teksi wastewater has already implemented this skipping:
```

            print(f"label[properties]: {label['properties']}")

            if self.subset_ids and obj_id not in self.subset_ids:
                logger.warning(
                    f"Label for {layer_name} `{obj_id}` exists, but that object is not part of the export"
                )
                continue
```
```
            if not label["properties"]["LabelText"]:
                logger.warning(
                    f"Label of object '{obj_id}' from layer '{layer_name}' is empty and will not be exported"
                )
                continue
```

https://github.com/teksi/wastewater/blob/3acfba249866d299f8a22e249d9f1e475fe7b88d/plugin/teksi_wastewater/interlis/interlis_model_mapping/interlis_exporter_to_intermediate_schema.py#L2667 and following

@domi4484 Can I backport this to qgep using the same code adding it here after this statement?

https://github.com/QGEP/qgepqwat2ili/blob/cfa67c2742961e464c73462ab8e8267104af02d2/qgepqwat2ili/qgep/export.py#L1089

**Comment by domi4484** [comment]
@sjib yes I don't see why it should not work

**Comment by sjib** [comment]
- [ ] Needs confirmation, that patch solved the problem
