### ISSUE TITLE
SIA405 Export with wwtp_structure (ARA Bauwerk) fails

### ISSUE THREAD

**Issue by urskaufmann** [qgep/QGEP#850]
**Describe the bug**
I have a database with wwtp_structure as subclass of wastewater_structure.
When exporting to SIA405 (with / without label), I get this error:

Ein Fehler trat bei der Ausführung von Python-Code auf: 
sqlalchemy.exc.IntegrityError: (psycopg2.errors.ForeignKeyViolation) insert or update on table "abwassernetzelement" violates foreign key constraint "abwassernetzelement_abwasserbauwerkref_fkey" DETAIL:  Key (abwasserbauwerkref)=(169432) is not present in table "abwasserbauwerk". (Background on this error at: http://sqlalche.me/e/13/gkpj) 
Traceback (most recent call last):
  File "C:\PROGRA~1\QGIS3\apps\Python39\lib\site-packages\sqlalchemy\engine\base.py", line 771, in _commit_impl
    self.engine.dialect.do_commit(self.connection)
  File "C:\PROGRA~1\QGIS3\apps\Python39\lib\site-packages\sqlalchemy\engine\default.py", line 561, in do_commit
    dbapi_connection.commit()
psycopg2.errors.ForeignKeyViolation: insert or update on table "abwassernetzelement" violates foreign key constraint "abwassernetzelement_abwasserbauwerkref_fkey"
DETAIL:  Key (abwasserbauwerkref)=(169432) is not present in table "abwasserbauwerk".

The problem: with this message, you have no way to find the problem, because the mentioned key is a T_ID and the table where this key is written while the export is empty (there is no change because of the error).
1. Point: it can not be, that the user has no information about a error. I have 60'000 wastewater_structures - find the error!? I think this error is in the part that is programmed in QGEP (not the ili2pg-part). It should be possible to have a Obj_ID and not just a T_ID in the message.
2. Point: If I change the subclass of these records from wwtp_structure to special_structure, then the export works. I guess the same problem will be in TWW. WWTP_structure are seldom, I use them for Kleinkläranlagen and for Kompakt-SABA (Strassen-Abwasser-Behandlungs-Anlage). We should better support this ARA Bauwerk in QGEP/TWW. The vw_wwtp_structure exists. Is it correct, that these records are also in vw_qgep_wastewater_structure (with ws_type = NULL)??

**To Reproduce**
-

**Expected behavior**
Error messages help and do not use T-ID, but Obj_ID, or these baseclass-tables have values after a error
WWTP_structure is supported

**Screenshots / data**

**Desktop (please complete the following information):**
 - QGEP plugin version 1.6.0
 - QGEP datamodel version 1.6.0
 - QGEP project file version -
 - QGIS Version 3.34.4
 - OS Win 10

**Comment by urskaufmann** [comment]
current vw_wwtp_structure has a polygon_geometry. I think it should be a point_geometry as in vw_qgep_wastewater_structure, (point from the main node)

**Comment by sjib** [comment]
> 2. Point: If I change the subclass of these records from wwtp_structure to special_structure, then the export works. 

That is strange! The export matching is absolutely similar for special_structure and wwtp_structure:
https://github.com/QGEP/qgepqwat2ili/blob/cfa67c2742961e464c73462ab8e8267104af02d2/qgepqwat2ili/qgepdss/export.py#L1069
    logger.info("Exporting QGEP.special_structure -> ABWASSER.spezialbauwerk, ABWASSER.metaattribute")

and
    logger.info("Exporting QGEP.wwtp_structure -> ABWASSER.arabauwerk, ABWASSER.metaattribute")
https://github.com/QGEP/qgepqwat2ili/blob/cfa67c2742961e464c73462ab8e8267104af02d2/qgepqwat2ili/qgepdss/export.py#L1170

**Comment by urskaufmann** [comment]
In table baseclass, field t_type is the subclass. Means there should be "ARA Bauwerk". 
I think, when filling up this table and when searching again for the t_id with the t_ili_tid, it looks not for the same t_type... 
I cant imagine, what else happens

**Comment by urskaufmann** [comment]
by the way: to be able to export, I have changed t_type in vw_qgep_wastewater_structure for 4 records from NULL to special_structure. I have now +4 records in subtable special_structure. The 4 records in table wwtp_structure are still there. If I count together, I have 61945 records in table wastewater_structure, but 61494 records in the subclasses of wastewater_structure.
The user should not be able to see wwtp_records in vw_qgep_wastewater_structure and he should not be able to change the subclass-type for wwtp_structure or to wwtp_structure.

**Comment by sjib** [comment]
- [ ] Test mit nur einem ARA Bauwerk
- [ ] und einer Haltung zusätzlich

**Comment by sjib** [comment]
for view adaption see https://github.com/QGEP/QGEP/issues/851

**Comment by urskaufmann** [comment]
DSS Export with wwtp_structure without selection does work
