### ISSUE TITLE
QGEP 1.6.2, Import DSS in datamodel 1.6.1

### ISSUE THREAD

**Issue by urskaufmann** [qgep/QGEP#852]
**Describe the bug**
My database version 1.6.0 with more than 60k wastewater_structures. 
I export to INTERLIS with the bat-file (sql for exporting to Austausschema, then ili2pg)

I import this XTF with QGEP 1.62 in datamodell 1.6.1
After four or five tries, the validation runs without message.
After I get this window with all classes with records shown as valid (but nowbody will ever lock to all tables and all records if it's valid).
After pressing OK I have no more info what happens (is there something or is the cursor turning because QGIS is thired)?
And then the error window: lock below
I can not imagine the error. in the pg2ili_dss schema there are the records 
trottle_shut_off_unit:
40939	"manuell"	"Drosselschieber"	"auf Auslauf NW 500"	"ch24kkym0DR52863"				"von Roll Infratec Plattenschieber MONO PN10 DN500 "			"keine"		"verstellbar"		233986		
wastewater_node: 233986	"01010000200808000039B4C87623F34341508D972E32FE3141"			
wastewater_network_element: 233986		"Q640"	162393
baseclass: 40939	"absperr_drosselorgan"	"ch24kkym0DR52863"
233986	"abwasserknoten"	"ch24kkym0AK42775"

Ein Fehler trat bei der Ausführung von Python-Code auf: 

sqlalchemy.exc.IntegrityError: (psycopg2.errors.ForeignKeyViolation) insert or update on table "throttle_shut_off_unit" violates foreign key constraint "rel_throttle_shut_off_unit_wastewater_node" DETAIL:  Key (fk_wastewater_node)=(ch24kkym0AK42775) is not present in table "wastewater_node". [SQL: INSERT INTO qgep_od.throttle_shut_off_unit (obj_id, actuation, adjustability, control, cross_section, effective_cross_section, gross_costs, identifier, kind, manufacturer, remark, signal_transmission, subsidies, throttle_unit_opening_current, throttle_unit_opening_current_optimized, last_modification, fk_dataowner, fk_provider, fk_wastewater_node, fk_control_center, fk_overflow) VALUES (%(obj_id)s, %(actuation)s, %(adjustability)s, %(control)s, %(cross_section)s, %(effective_cross_section)s, %(gross_costs)s, %(identifier)s, %(kind)s, %(manufacturer)s, %(remark)s, %(signal_transmission)s, %(subsidies)s, %(throttle_unit_opening_current)s, %(throttle_unit_opening_current_optimized)s, %(last_modification)s, %(fk_dataowner)s, %(fk_provider)s, %(fk_wastewater_node)s, %(fk_control_center)s, %(fk_overflow)s)] [parameters: ({'obj_id': 'ch24kkym0DR52863', 'actuation': 3157, 'adjustability': 3160, 'control': 3165, 'cross_section': None, 'effective_cross_section': None, 'gross_costs': None, 'identifier': 'ch24kkym0DR52863', 'kind': 135, 'manufacturer': 'von Roll Infratec Plattenschieber MONO PN10 DN500 ', 'remark': 'auf Auslauf NW 500', 'signal_transmission': None, 'subsidies': None, 'throttle_unit_opening_current': None, 'throttle_unit_opening_current_optimized': None, 'last_modification': datetime.date(2024, 2, 28), 'fk_dataowner': None, 'fk_provider': None, 'fk_wastewater_node': 'ch24kkym0AK42775', 'fk_control_center': None, 'fk_overflow': None}, {'obj_id': 'ch24kkym0DR54762', 'actuation': 3157, 'adjustability': None, 'control': None, 'cross_section': None, 'effective_cross_section': None, 'gross_costs': None, 'identifier': 'ch24kkym0DR54762', 'kind': 2688, 'manufacturer': None, 'remark': None, 'signal_transmission': None, 'subsidies': None, 'throttle_unit_opening_current': None, 'throttle_unit_opening_current_optimized': None, 'last_modification': datetime.date(2024, 2, 28), 'fk_dataowner': None, 'fk_provider': None, 'fk_wastewater_node': 'ch24kkym0AK54747', 'fk_control_center': None, 'fk_overflow': None}, {'obj_id': 'ch24kkym0DR56007', 'actuation': 3153, 'adjustability': 3159, 'control': 3165, 'cross_section': None, 'effective_cross_section': None, 'gross_costs': None, 'identifier': 'ch24kkym0DR56007', 'kind': 133, 'manufacturer': 'Nill CE/V  10 l/s', 'remark': None, 'signal_transmission': 3170, 'subsidies': None, 'throttle_unit_opening_current': None, 'throttle_unit_opening_current_optimized': None, 'last_modification': datetime.date(2024, 2, 28), 'fk_dataowner': None, 'fk_provider': None, 'fk_wastewater_node': 'ch24kkym0AK56005', 'fk_control_center': None, 'fk_overflow': None}, {'obj_id': 'ch24kkym0DR57776', 'actuation': 3153, 'adjustability': 3159, 'control': 3165, 'cross_section': None, 'effective_cross_section': None, 'gross_costs': None, 'identifier': 'ch24kkym0DR57776', 'kind': 2688, 'manufacturer': None, 'remark': None, 'signal_transmission': None, 'subsidies': None, 'throttle_unit_opening_current': None, 'throttle_unit_opening_current_optimized': None, 'last_modification': datetime.date(2024, 2, 28), 'fk_dataowner': None, 'fk_provider': None, 'fk_wastewater_node': 'ch24kkym0AK57775', 'fk_control_center': None, 'fk_overflow': None}, {'obj_id': 'ch24kkym0DR57969', 'actuation': 3153, 'adjustability': 3159, 'control': 3165, 'cross_section': None, 'effective_cross_section': None, 'gross_costs': None, 'identifier': 'ch24kkym0DR57969', 'kind': 2688, 'manufacturer': None, 'remark': None, 'signal_transmission': None, 'subsidies': None, 'throttle_unit_opening_current': None, 'throttle_unit_opening_current_optimized': None, 'last_modification': datetime.date(2024, 2, 28), 'fk_dataowner': None, 'fk_provider': None, 'fk_wastewater_node': 'ch24kkym0AK57968', 'fk_control_center': None, 'fk_overflow': None}, {'obj_id': 'ch24kkym0DR58132', 'actuation': 3157, 'adjustability': None, 'control': 3165, 'cross_section': None, 'effective_cross_section': None, 'gross_costs': None, 'identifier': 'ch24kkym0DR58132', 'kind': 2688, 'manufacturer': 'Sistag Wey Typ 4.6', 'remark': None, 'signal_transmission': None, 'subsidies': None, 'throttle_unit_opening_current': None, 'throttle_unit_opening_current_optimized': None, 'last_modification': datetime.date(2024, 2, 28), 'fk_dataowner': None, 'fk_provider': None, 'fk_wastewater_node': 'ch24kkym0AK58131', 'fk_control_center': None, 'fk_overflow': None}, {'obj_id': 'ch24kkym0DR59464', 'actuation': 3153, 'adjustability': 3160, 'control': 3165, 'cross_section': None, 'effective_cross_section': None, 'gross_costs': None, 'identifier': 'ch24kkym0DR59464', 'kind': 2689, 'manufacturer': None, 'remark': None, 'signal_transmission': None, 'subsidies': None, 'throttle_unit_opening_current': None, 'throttle_unit_opening_current_optimized': None, 'last_modification': datetime.date(2024, 2, 28), 'fk_dataowner': None, 'fk_provider': None, 'fk_wastewater_node': 'ch24kkym0AK59404', 'fk_control_center': None, 'fk_overflow': None}, {'obj_id': 'ch24kkym0DR59836', 'actuation': 3157, 'adjustability': None, 'control': 3165, 'cross_section': None, 'effective_cross_section': None, 'gross_costs': None, 'identifier': 'ch24kkym0DR59836', 'kind': 2688, 'manufacturer': None, 'remark': 'Hochwasserschieber', 'signal_transmission': None, 'subsidies': None, 'throttle_unit_opening_current': None, 'throttle_unit_opening_current_optimized': None, 'last_modification': datetime.date(2024, 2, 28), 'fk_dataowner': None, 'fk_provider': None, 'fk_wastewater_node': 'ch24kkym0AK59835', 'fk_control_center': None, 'fk_overflow': None}  ... displaying 10 of 56 total bound parameter sets ...  {'obj_id': 'ch24kkym0DR87985', 'actuation': 3157, 'adjustability': 3160, 'control': 3165, 'cross_section': None, 'effective_cross_section': None, 'gross_costs': None, 'identifier': 'ch24kkym0DR87985', 'kind': 2688, 'manufacturer': None, 'remark': None, 'signal_transmission': None, 'subsidies': None, 'throttle_unit_opening_current': None, 'throttle_unit_opening_current_optimized': None, 'last_modification': datetime.date(2024, 2, 28), 'fk_dataowner': None, 'fk_provider': None, 'fk_wastewater_node': 'ch24kkym0AK83323', 'fk_control_center': None, 'fk_overflow': None}, {'obj_id': 'ch24kkym0DR89013', 'actuation': None, 'adjustability': None, 'control': None, 'cross_section': None, 'effective_cross_section': None, 'gross_costs': None, 'identifier': 'ch24kkym0DR89013', 'kind': 2746, 'manufacturer': 'nill Abflussregulator Typ EB', 'remark': 'EB einfache Blende, 40 l/s', 'signal_transmission': None, 'subsidies': None, 'throttle_unit_opening_current': None, 'throttle_unit_opening_current_optimized': None, 'last_modification': datetime.date(2024, 2, 28), 'fk_dataowner': None, 'fk_provider': None, 'fk_wastewater_node': 'ch24kkym0AK62489', 'fk_control_center': None, 'fk_overflow': None})] (Background on this error at: http://sqlalche.me/e/13/gkpj) 
Traceback (most recent call last):
  File "C:\PROGRA~1\QGIS3\apps\Python39\lib\site-packages\sqlalchemy\engine\base.py", line 1256, in _execute_context
    self.dialect.do_executemany(
  File "C:\PROGRA~1\QGIS3\apps\Python39\lib\site-packages\sqlalchemy\dialects\postgresql\psycopg2.py", line 912, in do_executemany
    cursor.executemany(statement, parameters)
psycopg2.errors.ForeignKeyViolation: insert or update on table "throttle_shut_off_unit" violates foreign key constraint "rel_throttle_shut_off_unit_wastewater_node"
DETAIL:  Key (fk_wastewater_node)=(ch24kkym0AK42775) is not present in table "wastewater_node".

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users/KAU/AppData/Roaming/QGIS/QGIS3\profiles\qgep161_prerealise/python/plugins\qgepplugin\qgepqwat2ili\qgepqwat2ili\gui\gui_import.py", line 216, in commit_session
    self.session.commit()
  File "C:\PROGRA~1\QGIS3\apps\Python39\lib\site-packages\sqlalchemy\orm\session.py", line 1046, in commit
    self.transaction.commit()
  File "C:\PROGRA~1\QGIS3\apps\Python39\lib\site-packages\sqlalchemy\orm\session.py", line 504, in commit
    self._prepare_impl()
  File "C:\PROGRA~1\QGIS3\apps\Python39\lib\site-packages\sqlalchemy\orm\session.py", line 483, in _prepare_impl
    self.session.flush()
  File "C:\PROGRA~1\QGIS3\apps\Python39\lib\site-packages\sqlalchemy\orm\session.py", line 2540, in flush
    self._flush(objects)
  File "C:\PROGRA~1\QGIS3\apps\Python39\lib\site-packages\sqlalchemy\orm\session.py", line 2682, in _flush
    transaction.rollback(_capture_exception=True)
  File "C:\PROGRA~1\QGIS3\apps\Python39\lib\site-packages\sqlalchemy\util\langhelpers.py", line 68, in __exit__
    compat.raise_(
  File "C:\PROGRA~1\QGIS3\apps\Python39\lib\site-packages\sqlalchemy\util\compat.py", line 182, in raise_
    raise exception
  File "C:\PROGRA~1\QGIS3\apps\Python39\lib\site-packages\sqlalchemy\orm\session.py", line 2642, in _flush
    flush_context.execute()
  File "C:\PROGRA~1\QGIS3\apps\Python39\lib\site-packages\sqlalchemy\orm\unitofwork.py", line 419, in execute
    n.execute_aggregate(self, set_)
  File "C:\PROGRA~1\QGIS3\apps\Python39\lib\site-packages\sqlalchemy\orm\unitofwork.py", line 697, in execute_aggregate
    persistence.save_obj(
  File "C:\PROGRA~1\QGIS3\apps\Python39\lib\site-packages\sqlalchemy\orm\persistence.py", line 239, in save_obj
    _emit_insert_statements(
  File "C:\PROGRA~1\QGIS3\apps\Python39\lib\site-packages\sqlalchemy\orm\persistence.py", line 1083, in _emit_insert_statements
    c = cached_connections[connection].execute(statement, multiparams)
  File "C:\PROGRA~1\QGIS3\apps\Python39\lib\site-packages\sqlalchemy\engine\base.py", line 1011, in execute
    return meth(self, multiparams, params)
  File "C:\PROGRA~1\QGIS3\apps\Python39\lib\site-packages\sqlalchemy\sql\elements.py", line 298, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "C:\PROGRA~1\QGIS3\apps\Python39\lib\site-packages\sqlalchemy\engine\base.py", line 1124, in _execute_clauseelement
    ret = self._execute_context(
  File "C:\PROGRA~1\QGIS3\apps\Python39\lib\site-packages\sqlalchemy\engine\base.py", line 1316, in _execute_context
    self._handle_dbapi_exception(
  File "C:\PROGRA~1\QGIS3\apps\Python39\lib\site-packages\sqlalchemy\engine\base.py", line 1510, in _handle_dbapi_exception
    util.raise_(
  File "C:\PROGRA~1\QGIS3\apps\Python39\lib\site-packages\sqlalchemy\util\compat.py", line 182, in raise_
    raise exception
  File "C:\PROGRA~1\QGIS3\apps\Python39\lib\site-packages\sqlalchemy\engine\base.py", line 1256, in _execute_context
    self.dialect.do_executemany(
  File "C:\PROGRA~1\QGIS3\apps\Python39\lib\site-packages\sqlalchemy\dialects\postgresql\psycopg2.py", line 912, in do_executemany
    cursor.executemany(statement, parameters)
sqlalchemy.exc.IntegrityError: (psycopg2.errors.ForeignKeyViolation) insert or update on table "throttle_shut_off_unit" violates foreign key constraint "rel_throttle_shut_off_unit_wastewater_node"
DETAIL:  Key (fk_wastewater_node)=(ch24kkym0AK42775) is not present in table "wastewater_node".

[SQL: INSERT INTO qgep_od.throttle_shut_off_unit (obj_id, actuation, adjustability, control, cross_section, effective_cross_section, gross_costs, identifier, kind, manufacturer, remark, signal_transmission, subsidies, throttle_unit_opening_current, throttle_unit_opening_current_optimized, last_modification, fk_dataowner, fk_provider, fk_wastewater_node, fk_control_center, fk_overflow) VALUES (%(obj_id)s, %(actuation)s, %(adjustability)s, %(control)s, %(cross_section)s, %(effective_cross_section)s, %(gross_costs)s, %(identifier)s, %(kind)s, %(manufacturer)s, %(remark)s, %(signal_transmission)s, %(subsidies)s, %(throttle_unit_opening_current)s, %(throttle_unit_opening_current_optimized)s, %(last_modification)s, %(fk_dataowner)s, %(fk_provider)s, %(fk_wastewater_node)s, %(fk_control_center)s, %(fk_overflow)s)]
[parameters: ({'obj_id': 'ch24kkym0DR52863', 'actuation': 3157, 'adjustability': 3160, 'control': 3165, 'cross_section': None, 'effective_cross_section': None, 'gross_costs': None, 'identifier': 'ch24kkym0DR52863', 'kind': 135, 'manufacturer': 'von Roll Infratec Plattenschieber MONO PN10 DN500 ', 'remark': 'auf Auslauf NW 500', 'signal_transmission': None, 'subsidies': None, 'throttle_unit_opening_current': None, 'throttle_unit_opening_current_optimized': None, 'last_modification': datetime.date(2024, 2, 28), 'fk_dataowner': None, 'fk_provider': None, 'fk_wastewater_node': 'ch24kkym0AK42775', 'fk_control_center': None, 'fk_overflow': None}, {'obj_id': 'ch24kkym0DR54762', 'actuation': 3157, 'adjustability': None, 'control': None, 'cross_section': None, 'effective_cross_section': None, 'gross_costs': None, 'identifier': 'ch24kkym0DR54762', 'kind': 2688, 'manufacturer': None, 'remark': None, 'signal_transmission': None, 'subsidies': None, 'throttle_unit_opening_current': None, 'throttle_unit_opening_current_optimized': None, 'last_modification': datetime.date(2024, 2, 28), 'fk_dataowner': None, 'fk_provider': None, 'fk_wastewater_node': 'ch24kkym0AK54747', 'fk_control_center': None, 'fk_overflow': None}, {'obj_id': 'ch24kkym0DR56007', 'actuation': 3153, 'adjustability': 3159, 'control': 3165, 'cross_section': None, 'effective_cross_section': None, 'gross_costs': None, 'identifier': 'ch24kkym0DR56007', 'kind': 133, 'manufacturer': 'Nill CE/V  10 l/s', 'remark': None, 'signal_transmission': 3170, 'subsidies': None, 'throttle_unit_opening_current': None, 'throttle_unit_opening_current_optimized': None, 'last_modification': datetime.date(2024, 2, 28), 'fk_dataowner': None, 'fk_provider': None, 'fk_wastewater_node': 'ch24kkym0AK56005', 'fk_control_center': None, 'fk_overflow': None}, {'obj_id': 'ch24kkym0DR57776', 'actuation': 3153, 'adjustability': 3159, 'control': 3165, 'cross_section': None, 'effective_cross_section': None, 'gross_costs': None, 'identifier': 'ch24kkym0DR57776', 'kind': 2688, 'manufacturer': None, 'remark': None, 'signal_transmission': None, 'subsidies': None, 'throttle_unit_opening_current': None, 'throttle_unit_opening_current_optimized': None, 'last_modification': datetime.date(2024, 2, 28), 'fk_dataowner': None, 'fk_provider': None, 'fk_wastewater_node': 'ch24kkym0AK57775', 'fk_control_center': None, 'fk_overflow': None}, {'obj_id': 'ch24kkym0DR57969', 'actuation': 3153, 'adjustability': 3159, 'control': 3165, 'cross_section': None, 'effective_cross_section': None, 'gross_costs': None, 'identifier': 'ch24kkym0DR57969', 'kind': 2688, 'manufacturer': None, 'remark': None, 'signal_transmission': None, 'subsidies': None, 'throttle_unit_opening_current': None, 'throttle_unit_opening_current_optimized': None, 'last_modification': datetime.date(2024, 2, 28), 'fk_dataowner': None, 'fk_provider': None, 'fk_wastewater_node': 'ch24kkym0AK57968', 'fk_control_center': None, 'fk_overflow': None}, {'obj_id': 'ch24kkym0DR58132', 'actuation': 3157, 'adjustability': None, 'control': 3165, 'cross_section': None, 'effective_cross_section': None, 'gross_costs': None, 'identifier': 'ch24kkym0DR58132', 'kind': 2688, 'manufacturer': 'Sistag Wey Typ 4.6', 'remark': None, 'signal_transmission': None, 'subsidies': None, 'throttle_unit_opening_current': None, 'throttle_unit_opening_current_optimized': None, 'last_modification': datetime.date(2024, 2, 28), 'fk_dataowner': None, 'fk_provider': None, 'fk_wastewater_node': 'ch24kkym0AK58131', 'fk_control_center': None, 'fk_overflow': None}, {'obj_id': 'ch24kkym0DR59464', 'actuation': 3153, 'adjustability': 3160, 'control': 3165, 'cross_section': None, 'effective_cross_section': None, 'gross_costs': None, 'identifier': 'ch24kkym0DR59464', 'kind': 2689, 'manufacturer': None, 'remark': None, 'signal_transmission': None, 'subsidies': None, 'throttle_unit_opening_current': None, 'throttle_unit_opening_current_optimized': None, 'last_modification': datetime.date(2024, 2, 28), 'fk_dataowner': None, 'fk_provider': None, 'fk_wastewater_node': 'ch24kkym0AK59404', 'fk_control_center': None, 'fk_overflow': None}, {'obj_id': 'ch24kkym0DR59836', 'actuation': 3157, 'adjustability': None, 'control': 3165, 'cross_section': None, 'effective_cross_section': None, 'gross_costs': None, 'identifier': 'ch24kkym0DR59836', 'kind': 2688, 'manufacturer': None, 'remark': 'Hochwasserschieber', 'signal_transmission': None, 'subsidies': None, 'throttle_unit_opening_current': None, 'throttle_unit_opening_current_optimized': None, 'last_modification': datetime.date(2024, 2, 28), 'fk_dataowner': None, 'fk_provider': None, 'fk_wastewater_node': 'ch24kkym0AK59835', 'fk_control_center': None, 'fk_overflow': None}  ... displaying 10 of 56 total bound parameter sets ...  {'obj_id': 'ch24kkym0DR87985', 'actuation': 3157, 'adjustability': 3160, 'control': 3165, 'cross_section': None, 'effective_cross_section': None, 'gross_costs': None, 'identifier': 'ch24kkym0DR87985', 'kind': 2688, 'manufacturer': None, 'remark': None, 'signal_transmission': None, 'subsidies': None, 'throttle_unit_opening_current': None, 'throttle_unit_opening_current_optimized': None, 'last_modification': datetime.date(2024, 2, 28), 'fk_dataowner': None, 'fk_provider': None, 'fk_wastewater_node': 'ch24kkym0AK83323', 'fk_control_center': None, 'fk_overflow': None}, {'obj_id': 'ch24kkym0DR89013', 'actuation': None, 'adjustability': None, 'control': None, 'cross_section': None, 'effective_cross_section': None, 'gross_costs': None, 'identifier': 'ch24kkym0DR89013', 'kind': 2746, 'manufacturer': 'nill Abflussregulator Typ EB', 'remark': 'EB einfache Blende, 40 l/s', 'signal_transmission': None, 'subsidies': None, 'throttle_unit_opening_current': None, 'throttle_unit_opening_current_optimized': None, 'last_modification': datetime.date(2024, 2, 28), 'fk_dataowner': None, 'fk_provider': None, 'fk_wastewater_node': 'ch24kkym0AK62489', 'fk_control_center': None, 'fk_overflow': None})]
(Background on this error at: http://sqlalche.me/e/13/gkpj)

Python-Version: 3.9.18 (heads/master:5eba59e, Feb  1 2024, 20:02:10) [MSC v.1929 64 bit (AMD64)] 
QGIS-Version: 3.34.4-Prizren Prizren, decd43dc 

Python-Pfad:
C:/PROGRA~1/QGIS3/apps/qgis-ltr/./python
C:/Users/KAU/AppData/Roaming/QGIS/QGIS3\profiles\qgep161_prerealise/python
C:/Users/KAU/AppData/Roaming/QGIS/QGIS3\profiles\qgep161_prerealise/python/plugins
C:/PROGRA~1/QGIS3/apps/qgis-ltr/./python/plugins
C:\PROGRA~1\QGIS3\apps\grass\grass83\etc\python
C:\Program Files\QGIS3\bin
C:\Program Files\QGIS3\bin\python39.zip
C:\PROGRA~1\QGIS3\apps\Python39\DLLs
C:\PROGRA~1\QGIS3\apps\Python39\lib
C:\PROGRA~1\QGIS3\apps\Python39
C:\PROGRA~1\QGIS3\apps\Python39\lib\site-packages
C:\PROGRA~1\QGIS3\apps\Python39\lib\site-packages\win32
C:\PROGRA~1\QGIS3\apps\Python39\lib\site-packages\win32\lib
C:\PROGRA~1\QGIS3\apps\Python39\lib\site-packages\Pythonwin
C:/Users/KAU/AppData/Roaming/QGIS/QGIS3\profiles\qgep161_prerealise/python
P:/Thun/Gemeinden/110-119 Thun/O1010 Thun, Nachführung Werkplan Abwasser/qgep
C:\Users/KAU/AppData/Roaming/QGIS/QGIS3\profiles\qgep161_prerealise/python/plugins\qgepplugin\qgepqwat2ili\qgepqwat2ili\gui\..\..
C:\Users/KAU/AppData/Roaming/QGIS/QGIS3\profiles\qgep161_prerealise/python/plugins\qgepplugin\qgepqwat2ili\qgepqwat2ili\gui\..\..
.

**Desktop (please complete the following information):**
 - QGEP plugin version 1.6.2
 - QGEP datamodel version 1.6.1
 - QGEP project file version -
 - QGIS Version 3.34.4
 - OS Win 10

**Additional context**

- [ ] After pressing OK I have no more info what happens (is there something or is the cursor turning because QGIS is thired)? 
- [ ] An other point: where are the log-files when importing and the import failes (not with next to the project, not next to the xtf-file)?

**Comment by urskaufmann** [comment]
Tried the same import a second time. On the window with all classes I deselected all trottle_shut_off units 

- [ ] (click 56 times! or how can I deselect a whole class) 
and run into an other error:

Ein Fehler trat bei der Ausführung von Python-Code auf: 

KeyError: 
Traceback (most recent call last):
  File "C:\Users/KAU/AppData/Roaming/QGIS/QGIS3\profiles\qgep161_prerealise/python/plugins\qgepplugin\qgepqwat2ili\qgepqwat2ili\gui\gui_import.py", line 216, in commit_session
    self.session.commit()
  File "C:\PROGRA~1\QGIS3\apps\Python39\lib\site-packages\sqlalchemy\orm\session.py", line 1046, in commit
    self.transaction.commit()
  File "C:\PROGRA~1\QGIS3\apps\Python39\lib\site-packages\sqlalchemy\orm\session.py", line 504, in commit
    self._prepare_impl()
  File "C:\PROGRA~1\QGIS3\apps\Python39\lib\site-packages\sqlalchemy\orm\session.py", line 483, in _prepare_impl
    self.session.flush()
  File "C:\PROGRA~1\QGIS3\apps\Python39\lib\site-packages\sqlalchemy\orm\session.py", line 2540, in flush
    self._flush(objects)
  File "C:\PROGRA~1\QGIS3\apps\Python39\lib\site-packages\sqlalchemy\orm\session.py", line 2682, in _flush
    transaction.rollback(_capture_exception=True)
  File "C:\PROGRA~1\QGIS3\apps\Python39\lib\site-packages\sqlalchemy\util\langhelpers.py", line 68, in __exit__
    compat.raise_(
  File "C:\PROGRA~1\QGIS3\apps\Python39\lib\site-packages\sqlalchemy\util\compat.py", line 182, in raise_
    raise exception
  File "C:\PROGRA~1\QGIS3\apps\Python39\lib\site-packages\sqlalchemy\orm\session.py", line 2642, in _flush
    flush_context.execute()
  File "C:\PROGRA~1\QGIS3\apps\Python39\lib\site-packages\sqlalchemy\orm\unitofwork.py", line 419, in execute
    n.execute_aggregate(self, set_)
  File "C:\PROGRA~1\QGIS3\apps\Python39\lib\site-packages\sqlalchemy\orm\unitofwork.py", line 521, in execute_aggregate
    self.execute(uow)
  File "C:\PROGRA~1\QGIS3\apps\Python39\lib\site-packages\sqlalchemy\orm\unitofwork.py", line 573, in execute
    states = [s for s in states if uow.states[s][0] == self.isdelete]
  File "C:\PROGRA~1\QGIS3\apps\Python39\lib\site-packages\sqlalchemy\orm\unitofwork.py", line 573, in 
    states = [s for s in states if uow.states[s][0] == self.isdelete]
KeyError: 


Python-Version: 3.9.18 (heads/master:5eba59e, Feb  1 2024, 20:02:10) [MSC v.1929 64 bit (AMD64)] 
QGIS-Version: 3.34.4-Prizren Prizren, decd43dc 

Python-Pfad:
C:/PROGRA~1/QGIS3/apps/qgis-ltr/./python
C:/Users/KAU/AppData/Roaming/QGIS/QGIS3\profiles\qgep161_prerealise/python
C:/Users/KAU/AppData/Roaming/QGIS/QGIS3\profiles\qgep161_prerealise/python/plugins
C:/PROGRA~1/QGIS3/apps/qgis-ltr/./python/plugins
C:\PROGRA~1\QGIS3\apps\grass\grass83\etc\python
C:\Program Files\QGIS3\bin
C:\Program Files\QGIS3\bin\python39.zip
C:\PROGRA~1\QGIS3\apps\Python39\DLLs
C:\PROGRA~1\QGIS3\apps\Python39\lib
C:\PROGRA~1\QGIS3\apps\Python39
C:\PROGRA~1\QGIS3\apps\Python39\lib\site-packages
C:\PROGRA~1\QGIS3\apps\Python39\lib\site-packages\win32
C:\PROGRA~1\QGIS3\apps\Python39\lib\site-packages\win32\lib
C:\PROGRA~1\QGIS3\apps\Python39\lib\site-packages\Pythonwin
C:/Users/KAU/AppData/Roaming/QGIS/QGIS3\profiles\qgep161_prerealise/python
P:/Thun/Gemeinden/110-119 Thun/O1010 Thun, Nachführung Werkplan Abwasser/qgep
C:\Users/KAU/AppData/Roaming/QGIS/QGIS3\profiles\qgep161_prerealise/python/plugins\qgepplugin\qgepqwat2ili\qgepqwat2ili\gui\..\..
C:\Users/KAU/AppData/Roaming/QGIS/QGIS3\profiles\qgep161_prerealise/python/plugins\qgepplugin\qgepqwat2ili\qgepqwat2ili\gui\..\..
.

**Comment by sjib** [comment]
I think the only way is to also add DEFERRABLE INITIALLY DEFERRED to the datamodel as in TEKSI Wastewater see e.g. https://github.com/teksi/wastewater/pull/178/files

**Comment by sjib** [comment]
>  (click 56 times! or how can I deselect a whole class)

- [ ] In TEKSI Wastewater this is solved - check on backporting also to qgep - it has been tried to add option selection / deselection per class
https://github.com/QGEP/qgepqwat2ili/blob/ef399256541b380d5f61863f9b5607a6506d09fc/qgepqwat2ili/gui/gui_import.py#L118

**Comment by sjib** [comment]
--- Add additional DEREFERABLE constraints in delta file

-- option 1
```
ALTER TABLE qgep_od.overflow DROP CONSTRAINT rel_overflow_overflow_to;
ALTER TABLE qgep_od.overflow ADD CONSTRAINT rel_overflow_overflow_to FOREIGN KEY (fk_overflow_to) 
REFERENCES qgep_od.wastewater_node(obj_id) ON UPDATE CASCADE ON DELETE set null DEFERRABLE INITIALLY DEFERRED;
```

-- option 2 since postgresql 9.4 -- see https://emmer.dev/blog/deferrable-constraints-in-postgresql/ , possible for foreign keys relations
`ALTER TABLE qgep_od.overflow ALTER CONSTRAINT rel_overflow_overflow_to DEFERRABLE INITIALLY DEFERRED;`

-- option 2 Testing with data in fk seems to work e.g.
`ALTER TABLE qgep_od.wastewater_networkelement ALTER CONSTRAINT rel_wastewater_networkelement_wastewater_structure DEFERRABLE INITIALLY DEFERRED;`
