### ISSUE TITLE
QGEP 1.62 Export DSS with selection

### ISSUE THREAD

**Issue by urskaufmann** [qgep/QGEP#856]
**Describe the bug**
Without selection: it works

With selection: I get this error (all reaches are Kreisprofil!):

Ein Fehler trat bei der Ausführung von Python-Code auf: 
sqlalchemy.exc.IntegrityError: (psycopg2.errors.ForeignKeyViolation) insert or update on table "rohrprofil_geometrie" violates foreign key constraint "rohrprofil_geometrie_rohrprofilref_fkey" DETAIL:  Key (rohrprofilref)=(264) is not present in table "rohrprofil". (Background on this error at: http://sqlalche.me/e/13/gkpj) 
Traceback (most recent call last):
  File "C:\PROGRA~1\QGIS3\apps\Python39\lib\site-packages\sqlalchemy\engine\base.py", line 771, in _commit_impl
    self.engine.dialect.do_commit(self.connection)
  File "C:\PROGRA~1\QGIS3\apps\Python39\lib\site-packages\sqlalchemy\engine\default.py", line 561, in do_commit
    dbapi_connection.commit()
psycopg2.errors.ForeignKeyViolation: insert or update on table "rohrprofil_geometrie" violates foreign key constraint "rohrprofil_geometrie_rohrprofilref_fkey"
DETAIL:  Key (rohrprofilref)=(264) is not present in table "rohrprofil".

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users/KAU/AppData/Roaming/QGIS/QGIS3\profiles\qgep161_prerealise/python/plugins\qgepplugin\qgepqwat2ili\qgepqwat2ili\gui\__init__.py", line 613, in action_do_export
    qgepdss_export(selection=export_dialog.selected_ids, labels_file=labels_file_path, orientation=eorientation)
  File "C:\Users/KAU/AppData/Roaming/QGIS/QGIS3\profiles\qgep161_prerealise/python/plugins\qgepplugin\qgepqwat2ili\qgepqwat2ili\qgepdss\export.py", line 3609, in qgep_export
    abwasser_session.commit()
  File "C:\PROGRA~1\QGIS3\apps\Python39\lib\site-packages\sqlalchemy\orm\session.py", line 1046, in commit
    self.transaction.commit()
  File "C:\PROGRA~1\QGIS3\apps\Python39\lib\site-packages\sqlalchemy\orm\session.py", line 508, in commit
    t[1].commit()
  File "C:\PROGRA~1\QGIS3\apps\Python39\lib\site-packages\sqlalchemy\engine\base.py", line 1762, in commit
    self._do_commit()
  File "C:\PROGRA~1\QGIS3\apps\Python39\lib\site-packages\sqlalchemy\engine\base.py", line 1793, in _do_commit
    self.connection._commit_impl()
  File "C:\PROGRA~1\QGIS3\apps\Python39\lib\site-packages\sqlalchemy\engine\base.py", line 773, in _commit_impl
    self._handle_dbapi_exception(e, None, None, None, None)
  File "C:\PROGRA~1\QGIS3\apps\Python39\lib\site-packages\sqlalchemy\engine\base.py", line 1510, in _handle_dbapi_exception
    util.raise_(
  File "C:\PROGRA~1\QGIS3\apps\Python39\lib\site-packages\sqlalchemy\util\compat.py", line 182, in raise_
    raise exception
  File "C:\PROGRA~1\QGIS3\apps\Python39\lib\site-packages\sqlalchemy\engine\base.py", line 771, in _commit_impl
    self.engine.dialect.do_commit(self.connection)
  File "C:\PROGRA~1\QGIS3\apps\Python39\lib\site-packages\sqlalchemy\engine\default.py", line 561, in do_commit
    dbapi_connection.commit()
sqlalchemy.exc.IntegrityError: (psycopg2.errors.ForeignKeyViolation) insert or update on table "rohrprofil_geometrie" violates foreign key constraint "rohrprofil_geometrie_rohrprofilref_fkey"
DETAIL:  Key (rohrprofilref)=(264) is not present in table "rohrprofil".

(Background on this error at: http://sqlalche.me/e/13/gkpj)

Python-Version: 3.9.18 (heads/master:5eba59e, Feb  1 2024, 20:02:10) [MSC v.1929 64 bit (AMD64)] 
QGIS-Version: 3.34.4-Prizren Prizren, decd43dc

**Desktop (please complete the following information):**
 - QGEP plugin version 1.62
 - QGEP datamodel version 1.61
 - QGEP project file version - 
 - QGIS Version 3.34.4
 - OS Win10

**Comment by sjib** [comment]
```
    logger.info("Exporting QGEP.profile_geometry -> ABWASSER.rohrprofil_geometrie, ABWASSER.metaattribute")
    query = qgep_session.query(QGEP.profile_geometry)
```

https://github.com/QGEP/qgepqwat2ili/blob/ef399256541b380d5f61863f9b5607a6506d09fc/qgepqwat2ili/qgepdss/export.py#L2083

Here we need to add a filter criteria so that the class rohrprofil_geometrie is also selected

Similar to e.g. Haltungspunkt
```
    logger.info("Exporting QGEP.reach_point -> ABWASSER.haltungspunkt, ABWASSER.metaattribute")
    query = qgep_session.query(QGEP.reach_point)
    if filtered:
        query = query.join(
            QGEP.reach,
            or_(
                QGEP.reach_point.obj_id == QGEP.reach.fk_reach_point_from,
                QGEP.reach_point.obj_id == QGEP.reach.fk_reach_point_to,
            ),
        ).filter(QGEP.wastewater_networkelement.obj_id.in_(subset_ids))
    for row in query:
```

Equivalent in TEKSI Wastewater:

```
    def _export_reach_point(self):
        query = self.tww_session.query(self.model_classes_tww_od.reach_point)
        if self.filtered:
            query = query.join(
                self.model_classes_tww_od.reach,
                or_(
                    self.model_classes_tww_od.reach_point.obj_id
                    == self.model_classes_tww_od.reach.fk_reach_point_from,
                    self.model_classes_tww_od.reach_point.obj_id
                    == self.model_classes_tww_od.reach.fk_reach_point_to,
                ),
            ).filter(
                self.model_classes_tww_od.wastewater_networkelement.obj_id.in_(self.subset_ids)
            )
```

**Comment by sjib** [comment]
General concept for filtering needed also for TEKSI wastewater: https://github.com/teksi/wastewater/issues/154

**Comment by sjib** [comment]
TEKSI wastewater has set filter already - could be backported?

```
    def _export_pipe_profile(self):
        query = self.tww_session.query(self.model_classes_tww_od.pipe_profile)
        if self.filtered:
            query = query.join(self.model_classes_tww_od.reach).filter(
                self.model_classes_tww_od.wastewater_networkelement.obj_id.in_(self.subset_ids)
            )
```

**Comment by sjib** [comment]
This would lead to this, if I adapted correctly:

```
    logger.info("Exporting QGEP.profile_geometry -> ABWASSER.rohrprofil_geometrie, ABWASSER.metaattribute")
    query = qgep_session.query(QGEP.profile_geometry)
    if filtered:
        query = query.join(
            QGEP.reach,
        ).filter(QGEP.wastewater_networkelement.obj_id.in_(subset_ids))
    for row in query:
```

@urskaufmann What do you think?

**Comment by sjib** [comment]
|  Class | SIA405 Abwasser 2015 | SIA405 Abwasser 2020| DSS 2015 | DSS 2020 | KEK 2015 | KEK 2020  |
|---|---|---|---|---|---|---|
| channel | filtered  | filtered  | filtered  | filtered  |   |   |
| manhole   | filtered  | filtered  | filtered  | filtered  |   |   |
| discharge_point   | filtered  | filtered  | filtered  | filtered  |   |   |
| special_structure   | filtered  | filtered  | filtered  | filtered  |   |   |
| infiltration_installation  | filtered  | filtered  | filtered  | filtered  |   |   |
| wwtp_structure | filtered  | filtered  | filtered  | filtered  |   |   |
| planning_zone  |   |   |   |   |   |   |
| infiltration_zone  |   |   |   |   |   |   |
| drainage_system   |   |   |   |   |   |   |
| water_body_protection_sector  |   |   |   |   |   |   |
| ground_water_protection_perimeter   |   |   |   |   |   |   |
| groundwater_protection_zone   |   |   |   |   |   |   |
| pipe_profile  | add filter  | filtered    | add filter  | filtered    |   |   |
| wwtp_energy_use   |   |   |   |   |   |   |
| waste_water_treatment   |   |   |   |   |   |   |
| sludge_treatment |   |   |   |   |   |   |
| control_center   | missing | [filtered.nojoin](https://github.com/cymed/TEKSI-wastewater/blob/0c868c69f211cd1fc3f728e2c7c411656f3bbae2/plugin/teksi_wastewater/interlis/interlis_model_mapping/interlis_exporter_to_intermediate_schema.py#L1068)  | missing | filtered.nojoin |   |   |
| ford |   | -  |   | -  | -  | -  |
| chute |   | -  |   | -  | -  | -  |
| lock |   |   | -  |   | -  | -  |
| passage |   | -  |   |-   | -  |-   |
| dam |   | -  |   |-   | -  |-   |
| rock_ramp |   | -  |   |-   | -  |-   |
| fish_pass |   | -  |   |-   | -  |-   |
| bathing_area |   | -  |   |-   | -  |-   |
| hydr_geometry |   | filtered.nojoin   |   | filtered.nojoin  | -  |-   |

to do add other classes

**Comment by urskaufmann** [comment]
My idea for the selection:
1. Start is always the actual selection of reaches. And this selection will generally not expanded during the export. 
One exception: if there is one reach of a channel selected and others are not, then it makes sense to expand the selection, that all reaches of the channel are selected.
2. Select all nodes, that are connected to the reach (from_reachpoint.fk_wastewater_networkelement, to_reachpoint.fk_wastewater_networkelement).
3. Add all nodes, that are selected in vw_qgep_wastewater_structure (respectively the main_node of the wastewater_structure)
4. Like this we have a first list of all wastewater_networkelements (reaches and nodes)
5. Select all wastewater_structure records, that are connected to the selected networkelements
6. To get also not-main-nodes in special_structures, it will be necessary to select all networkelements starting with the list wastewater-structures Nr 5 and to add them to list networkelements Nr 4. -> List 6
7. Starting from List 5, the structure_parts can be selected
8.  Starting from List 5, the re_wws_maintenance events -> maintenance_events can be selected
9.  Starting from List 6, the catchment_areas can be selected
10. Starting from List 6, the single_objects can be selected
11. Starting from List 6, the overflows, trottle_shut_off_units, hydr_geometries etc. can be selected
12. etc. etc.
Pipe_profile: starting from List 6. Or why not take always all records?
Organisation: Why not take always all records?

Like this, there must be special controls in case of
- a reach is connected directly to another reach, that is not selected (not in List 6): the fk to this reach must be skipped
- overflow (pump), that has an overflow_to-node, which is not selected (not in List 6): the overflow_to-node must be skipped

**Comment by sjib** [comment]
Here the current filter for Haltungspunkt:
`   logger.info("Exporting QGEP.reach_point -> ABWASSER.haltungspunkt, ABWASSER.metaattribute")
    query = qgep_session.query(QGEP.reach_point)
    if filtered:
        query = query.join(
            QGEP.reach,
            or_(
                QGEP.reach_point.obj_id == QGEP.reach.fk_reach_point_from,
                QGEP.reach_point.obj_id == QGEP.reach.fk_reach_point_to,
            ),
        ).filter(QGEP.wastewater_networkelement.obj_id.in_(subset_ids))`

As discussed with @urskaufmann we do not want the reach selected if we have a reach - reach connection.

So therefore I think we have to eliminate the` QGEP.reach_point.obj_id == QGEP.reach.fk_reach_point_to,` part.

```
    logger.info("Exporting QGEP.reach_point -> ABWASSER.haltungspunkt, ABWASSER.metaattribute")
    query = qgep_session.query(QGEP.reach_point)
    if filtered:
        query = query.join(
            QGEP.reach,
            or_(
                QGEP.reach_point.obj_id == QGEP.reach.fk_reach_point_from,
           #     QGEP.reach_point.obj_id == QGEP.reach.fk_reach_point_to,
            ),
        ).filter(QGEP.wastewater_networkelement.obj_id.in_(subset_ids))
```

@urskaufmann Next pull for testing https://github.com/QGEP/qgepqwat2ili/pull/144/commits/c73046331e62e35bc6ed8d5e22412905783cfaf2

**Comment by urskaufmann** [comment]
I added this # an every export.py . I can not test with dss export, because there will be other errors. I tested with sia405-export selection an a case with two reach that have both a reach to reach connections. ( If I select also the third reach, so there are nodes and not reaches at the end of the selection, there is no error).

Error:

Ein Fehler trat bei der Ausführung von Python-Code auf: 

sqlalchemy.exc.IntegrityError: (psycopg2.errors.ForeignKeyViolation) insert or update on table "haltungspunkt" violates foreign key constraint "haltungspunkt_abwassernetzelementref_fkey" DETAIL:  Key (abwassernetzelementref)=(24) is not present in table "abwassernetzelement". (Background on this error at: http://sqlalche.me/e/13/gkpj) 
Traceback (most recent call last):
  File "C:\PROGRA~1\QGIS3\apps\Python39\lib\site-packages\sqlalchemy\engine\base.py", line 771, in _commit_impl
    self.engine.dialect.do_commit(self.connection)
  File "C:\PROGRA~1\QGIS3\apps\Python39\lib\site-packages\sqlalchemy\engine\default.py", line 561, in do_commit
    dbapi_connection.commit()
psycopg2.errors.ForeignKeyViolation: insert or update on table "haltungspunkt" violates foreign key constraint "haltungspunkt_abwassernetzelementref_fkey"
DETAIL:  Key (abwassernetzelementref)=(24) is not present in table "abwassernetzelement".


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users/KAU/AppData/Roaming/QGIS/QGIS3\profiles\qgep161_prerealise/python/plugins\qgepplugin\qgepqwat2ili\qgepqwat2ili\gui\__init__.py", line 608, in action_do_export
    qgepsia405_export(selection=export_dialog.selected_ids, labels_file=labels_file_path, orientation=eorientation)
  File "C:\Users/KAU/AppData/Roaming/QGIS/QGIS3\profiles\qgep161_prerealise/python/plugins\qgepplugin\qgepqwat2ili\qgepqwat2ili\qgepsia405\export.py", line 1123, in qgep_export
    abwasser_session.commit()
  File "C:\PROGRA~1\QGIS3\apps\Python39\lib\site-packages\sqlalchemy\orm\session.py", line 1046, in commit
    self.transaction.commit()
  File "C:\PROGRA~1\QGIS3\apps\Python39\lib\site-packages\sqlalchemy\orm\session.py", line 508, in commit
    t[1].commit()
  File "C:\PROGRA~1\QGIS3\apps\Python39\lib\site-packages\sqlalchemy\engine\base.py", line 1762, in commit
    self._do_commit()
  File "C:\PROGRA~1\QGIS3\apps\Python39\lib\site-packages\sqlalchemy\engine\base.py", line 1793, in _do_commit
    self.connection._commit_impl()
  File "C:\PROGRA~1\QGIS3\apps\Python39\lib\site-packages\sqlalchemy\engine\base.py", line 773, in _commit_impl
    self._handle_dbapi_exception(e, None, None, None, None)
  File "C:\PROGRA~1\QGIS3\apps\Python39\lib\site-packages\sqlalchemy\engine\base.py", line 1510, in _handle_dbapi_exception
    util.raise_(
  File "C:\PROGRA~1\QGIS3\apps\Python39\lib\site-packages\sqlalchemy\util\compat.py", line 182, in raise_
    raise exception
  File "C:\PROGRA~1\QGIS3\apps\Python39\lib\site-packages\sqlalchemy\engine\base.py", line 771, in _commit_impl
    self.engine.dialect.do_commit(self.connection)
  File "C:\PROGRA~1\QGIS3\apps\Python39\lib\site-packages\sqlalchemy\engine\default.py", line 561, in do_commit
    dbapi_connection.commit()
sqlalchemy.exc.IntegrityError: (psycopg2.errors.ForeignKeyViolation) insert or update on table "haltungspunkt" violates foreign key constraint "haltungspunkt_abwassernetzelementref_fkey"
DETAIL:  Key (abwassernetzelementref)=(24) is not present in table "abwassernetzelement".

(Background on this error at: http://sqlalche.me/e/13/gkpj)


Python-Version: 3.9.18 (heads/master:5eba59e, Feb  1 2024, 20:02:10) [MSC v.1929 64 bit (AMD64)] 
QGIS-Version: 3.34.4-Prizren Prizren, decd43dc

**Comment by urskaufmann** [comment]
![image](https://github.com/QGEP/QGEP/assets/1257403/34af14ef-4cc1-40b2-9d0b-66cbffe11d58)
Select just 1 and 2: error, because of the Blindnaschluss between 1 and 3.
Select 1,2 and 3: no Blindanschluss at the end of the selection, no error
