### ISSUE TITLE
MAKE INTERLIS EXPORT GREAT AGAIN

### ISSUE THREAD

**Issue by ponceta** [qgep/QGEP#862]
**Describe the bug**
To ease the migration to TEKSI wastewater, we need a simple way to export QGEP data using INTERLIS and a proposed standard configuration.

**To Make Great Again**
Steps:

- [x] Make it work on postgres 14/15 (16 won't work without a datamodel evolution because of `system_user` reserved keyword)
- [x] Make it work using modelbaker library
- [x] Make t_baskets work 

**Expected behavior**
INTERLIS Export is easy and works fine on a standard configuration

**Screenshots / data**
![image](https://github.com/user-attachments/assets/e78c0be7-76b8-4020-9ad0-2b347dea2b13)

**Desktop (please complete the following information):**
 - QGEP plugin version
 - QGEP datamodel version
 - QGEP project file version
 - QGIS Version
 - OS

**Additional context**

**Comment by sjib** [comment]
@ponceta In what class is system_user? We can easily rename that e.g. to sys_user or systemuser or user system - please let me know.

**Comment by ponceta** [comment]
> @ponceta In what class is system_user? We can easily rename that e.g. to sys_user or systemuser or user system - please let me know.

`qgep_od.mutation`

**Comment by sjib** [comment]
@ponceta 
Here the patches for datamodel https://github.com/teksi/wastewater/pull/387
and 
qgepqwat2ili https://github.com/QGEP/qgepqwat2ili/pull/155

**Comment by sjib** [comment]
Should be solved with release 1.6.6
