### ISSUE TITLE
DSS Export : organisation error when exporting 

### ISSUE THREAD

**Issue by ponceta** [qgep/QGEP#866]
**Describe the bug**
![image](https://github.com/user-attachments/assets/5604cc4c-f6a5-4590-8661-850684d48681)
This is due to your data not conform with the organisations class prerequisites for 2015 DSS Export

**HOW TO FIX**
TODO

**Expected behavior**
Users are well informed on how to make the DSS 2015 export working to migrate from QGEP to TWW

**Screenshots / data**
If applicable, add screenshots or data to help explain your problem.

**Desktop (please complete the following information):**
 - QGEP plugin version 1.6.3
 - QGEP datamodel version 1.6.2
 - QGEP project file version
 - QGIS Version
 - OS

**Additional context**

**Comment by sjib** [comment]
Documentation: https://qgep.github.io/docs/admin-guide/interlis-io/index.html#export
