### ISSUE TITLE
INTERLIS import of curve elements does not work properly

### ISSUE THREAD

**Issue by ponceta** [qgep/QGEP#868]
**Describe the bug**
INTERLIS import of curve elements does not work properly

![image](https://github.com/user-attachments/assets/b9cda4a7-54b7-41aa-8e9e-7b00ed574e31)

**To Reproduce**
Exact steps to reproduce the behavior:
1. Import Transfert Dataset 2015
2. Zoom on 2645539.62, 1149813.97
3. See error

**Expected behavior**
Curved elements are imported as well

**Screenshots / data**
If applicable, add screenshots or data to help explain your problem.

**Desktop (please complete the following information):**
 - QGEP plugin version
 - QGEP datamodel version
 - QGEP project file version
 - QGIS Version
 - OS

**Additional context**

**Comment by sjib** [comment]
@sjib seems to work with TWW - check why this is different.
Maybe ili2db newer version solved this

**Comment by ponceta** [comment]
After a quick check, it fails also on TWW import ...

This is critical because a user importing data will face some data loss without any warning!

**Comment by sjib** [comment]
We do not have any ARCS in the the test-dataset-DSS.xtf (and also in the transferdatensatz_2015_d_LV95_T-20210727.xtf and transferdatensatz_2020_1_d_LV95_T-20231213.xtf) anymore - it is just a straight line.

```

			<DSS_2020_1_LV95.Siedlungsentwaesserung.Haltung TID="ch080qwzHA000146">
				<Letzte_Aenderung>20191014</Letzte_Aenderung>
				<DatenherrRef REF="ch080qwzPR000018"/>
				<DatenlieferantRef REF="ch080qwzPR000017"/>

				<Bezeichnung>1.070-1.062</Bezeichnung>
				<AbwasserbauwerkRef REF="ch080qwzKA000146"/>
				<Innenschutz>unbekannt</Innenschutz>
				<LaengeEffektiv>947.22</LaengeEffektiv>
				<Lagebestimmung>genau</Lagebestimmung>
				<Lichte_Hoehe>1000</Lichte_Hoehe>
				<Material>Beton_Spezialbeton</Material>
				<Verlauf>
					<POLYLINE>
						<COORD>
							<C1>2645200.000</C1>
							<C2>1149950.000</C2>
						</COORD>
						<COORD>
							<C1>2646103.000</C1>
							<C2>1149720.000</C2>
						</COORD>
					</POLYLINE>
				</Verlauf>
				<RohrprofilRef REF="ch080qwzRP000002"/>
				<nachHaltungspunktRef REF="ch080qwzHP00146E"/>
				<vonHaltungspunktRef REF="ch080qwzHP00146A"/>
			</DSS_2020_1_LV95.Siedlungsentwaesserung.Haltung>
```

So we have to make an extra dataset where this is changed (again) to test if ARCS are supported or not.

**Comment by sjib** [comment]
@ponceta How can I edit the "Verlauf" of a reach easily?

**Comment by sjib** [comment]
This was the old LV03 Verlauf

```
        <DSS_2004_01.SIEDLUNGSENTWAESSERUNG.Haltung.Verlauf>
          <POLYLINE>
            <P C1="645200.000000" C2="149950.000000" C3="0.000000" />
            <P C1="645200.000000" C2="149950.000000" C3="0.000000" />
            <P C1="645200.000000" C2="149950.000000" C3="0.000000" />
            <A C1="645727.575000" C2="149890.354000" R="1511.266116" />
            <P C1="646103.000000" C2="149720.000000" C3="0.000000" />
            <P C1="646103.000000" C2="149720.000000" C3="0.000000" />
            <P C1="646103.000000" C2="149720.000000" C3="0.000000" />
          </POLYLINE>
        </DSS_2004_01.SIEDLUNGSENTWAESSERUNG.Haltung.Verlauf>
```

**Comment by sjib** [comment]
INTERLIS 2.3. Referenzhandbuch https://www.interlis.ch/download/interlis2/ili2-refman_2003-05-13_e.pdf

3.3.12.11 Coding of POLYLINE
Attribute values of the type POLYLINE are coded as follows:

```
PolylineValue = TAG ( POLYLINE )
[ LineAttr ]
SegmentSequence
ETAG ( POLYLINE ).
```
`StartSegment = CoordValue.`

`LineSegment = CoordValue.`

```
ArcSegment = TAG ( ARC )
TAG ( C1 ) NumericConst ETAG ( C1 )
TAG ( C2 ) NumericConst ETAG ( C2 )
[ TAG ( C3 ) NumericConst ETAG ( C3 ) ]
TAG ( A1 ) NumericConst ETAG ( A1 )
TAG ( A2 ) NumericConst ETAG ( A2 )
[ TAG ( R ) NumericConst ETAG ( R ) ]
ETAG ( ARC ).
```

`LineFormSegment = StructureValue.`

```
SegmentSequence = StartSegment { LineSegment
| ArcSegment
| LineFormSegment}.
```

**Comment by sjib** [comment]
This is the correct adaption for INTERLIS 2.3

first a point where we start with COORD
then an ARC with C1/C2 the endpoint and A1/A2 an intermediary point on the ARC

```
				<Verlauf>
					<POLYLINE>
						<COORD>
							<C1>2645200.000</C1>
							<C2>1149950.000</C2>
						</COORD>
						<!-- <A C1="645727.575000" C2="149890.354000" R="1511.266116" /> -->
						<ARC>
							<C1>2646103.000</C1>
							<C2>1149720.000</C2>
							<A1>2645727.575000</A1>
							<A2>1149890.354000</A2>
						</ARC>

					</POLYLINE>
				</Verlauf>
```

**Comment by sjib** [comment]
![grafik](https://github.com/user-attachments/assets/82bd8fed-2002-4b19-b49d-2389b20b5898)

Looks now as expected:

`"ch080qwzHA000146"	"COMPOUNDCURVE Z (CIRCULARSTRING Z (2645200 1149950 0,2645727.575 1149890.354 0,2646103 1149720 0))"`

**Comment by sjib** [comment]
Re-exporting Transferdatensatz VSA-DSS gives same ARC

![grafik](https://github.com/user-attachments/assets/7d5eb892-2f1d-46f1-931a-f86763d5c608)

**Comment by sjib** [comment]
Input has too many "Nachkommastellen" *.57000" instead of only "*.575" - I will adapt this in this new version of  Transferdatensatz

**Comment by sjib** [comment]
@ponceta Shall I integrate this adaption into our 

- tww [test-dataset-DSS.xtf](https://github.com/teksi/wastewater/blob/main/plugin/teksi_wastewater/tests/data/test-dataset-DSS.xtf)?
- gep [qgepqwat2ili/data/test_data](https://github.com/QGEP/qgepqwat2ili/tree/master/qgepqwat2ili/data/test_data)

**Comment by ponceta** [comment]
@sjib yes, it should be great to see at least one curve element in the test data. 

I think this will raise many questions and issues linked to the curve support on QGIS side but it is not to address this topic if we assume we support curved elements.

    Until yet in Pully I had back down from curved to straights elements 
    due to the lack of support of theses geometries from the CAD world 
    in the GIS world but it is maybe now the right time to check 
    how much has evolved from then and assume their support.
