### ISSUE TITLE
INTERLIS export is not a valid XTF file and therefore can't be imported 

### ISSUE THREAD

**Issue by ponceta** [qgep/QGEP#876]
**Describe the bug**
INTERLIS export is not a valid XTF file and therefore can't be imported 

**To Reproduce**
Exact steps to reproduce the behavior:
1. INTERLIS export some data (example demo data)
2. Start a fresh database with the datamodel tool
3. INTERLIS import

**Expected behavior**
Even is the data are not perfect, an import is possible to QGEP with some warnings.

**Screenshots / data**
If applicable, add screenshots or data to help explain your problem.

**Desktop (please complete the following information):**
 - QGEP plugin version
 - QGEP datamodel version
 - QGEP project file version
 - QGIS Version
 - OS

**Additional context**

**Comment by sjib** [comment]
to do: give some hints which INTERLIS errors have to be solved to import:

- refrence errors will give errors later
- ...

**Comment by sjib** [comment]
https://github.com/QGEP/QGEP/issues/889
