### ISSUE TITLE
Datamodel tool logic is badly ordered

### ISSUE THREAD

**Issue by ponceta** [qgep/QGEP#877]
**Describe the bug**
Actual Datamodel tool logic is badly ordered :

![image](https://github.com/user-attachments/assets/0f19895f-1731-46f2-8054-3a84f8541cf6)

When starting or an initialization through the datamodel tool, the plugin will try to state what to expect from the update on the first alphabetical pg_service available (here pg_port has nothing to do with TEKSI modules), this will lead to useless errors and warning because you did not choose the right connexion to check if the module (here qgep) has to be initialized, updated or if there is nothing to do because you are already up to date

As a reminder for next TMMT implementation :

1. Choose the connexion first
2. Then choose the module (not available yet)
3. Then choose the release you want to deploy

**To Reproduce**
Exact steps to reproduce the behavior:
1. Go to the datamodel tool
2. select release
3. See some errors or warning if your selected connexion is not a qgep or a blank database.

**Expected behavior**
Have a logical order way to ease the user initialization or updates.

**Screenshots / data**
If applicable, add screenshots or data to help explain your problem.

**Desktop (please complete the following information):**
 - QGEP plugin version
 - QGEP datamodel version
 - QGEP project file version
 - QGIS Version
 - OS

**Additional context**

**Comment by urskaufmann** [comment]
Test with qgep plugin 1.6.5:
If the python requirements are not ok, then the new order is not ok.
I start with 1 (service), then have first to choose 3 (release), before 2 is checked and the install-button is enabled. Confusing...

**Comment by ponceta** [comment]
@3nids Something to note here for TMMT, if modules have different prerequisites, they should be visible from TMMT somewhere. I see here that it was maybe anticipated that we had to select a release before installing dependencies.

@urskaufmann Thank you for the feedback!

![Datamodel_Tool](https://github.com/user-attachments/assets/975bf001-d3b3-4271-9a76-f6d50c2f802e)

**Comment by ponceta** [comment]
1.6.6 will be :

![image](https://github.com/user-attachments/assets/32252067-6a98-4dc0-960a-641b9dae6786)

**Comment by sjib** [comment]
@urskaufmann please test and if ok close

**Comment by urskaufmann** [comment]
Perfect, thanks, also upgrade 1.6.2 to 1.6.3 works
