### ISSUE TITLE
unique index on od_wasterwater_structure.identifier

### ISSUE THREAD

**Issue by 3nids** [QGEP/QGEP#88]
There is a unique index on  od_wasterwater_structure.identifier without having a unique constraint on the field.

Anyway, I would ask to remove this index since we have sometimes duplicated identifier. This can arise from historical reasons (merge of 2 services) and if you have elements from different providers.

OK?

**Comment by 3nids** [comment]
also applies to wasterwater_networkelement

**Comment by 3nids** [comment]
Stefan:
> In VSA-DSS-Mini the combination identifier (Bezeichnung) and Datenherr has to be unique. Therefore if we want to be able to export data in this model structure on the level of waste water sewer associations (Verbandsgep) we will have to be careful on lifting this unique content. Can we define the same rule as in the INTERLIS model of VSA-DSS-Mini for this:

> For all nodes (Abwasserbauwerk/Knoten and Leitung (Abwasserbauwerk / Haltung)
UNIQUE 
    Bezeichnung, Metaattribute->Datenherr;  !! Neben UNIQUE OBJ_ID zusätzlich auch Kombination Bezeichnung, Datenherr, damit mit VSA-DSS-Mini kompatibel (Wegleitung GEP-Daten 2013)
END Knoten;

**Comment by 3nids** [comment]
Yes, you can define an index to be unique over several columns.
In such case, that would be:

CREATE UNIQUE INDEX in_od_wastewater_structure_identifier
   ON qgep.od_wastewater_structure (identifier ASC NULLS LAST, fk_owner ASC NULLS LAST);

**Comment by sjib** [comment]
Ok, I added this to the code an it will be changed with the next release of the model

**Comment by 3nids** [comment]
Thanks!
Waiting on the new input to close this.

**Comment by sjib** [comment]
Latest model release is now completly debugged and running thru. You will get it by email.
