### ISSUE TITLE
why not using inheritance in the data model?

### ISSUE THREAD

**Issue by 3nids** [qgep/QGEP#89]
I am about to commit a change in the main SQL file [0]  to add some inheritance [1] for the value list.
Since all value list have the same structure, they can inherit a base table. This will allow me to list elements of the base table to get a global dictionary for value lists.

Do you have any reason why not implementing this?
Can I perform the changes directly in [0] ?

Now, this makes me wondering why we haven't use this throughout od tables. As far as I understand, this would have save us from using view, wouldn't it? Also, it integrates in the model the structure as seen by VSA-DSS.

I read there are some problems with indexes and constraints [1,2], is this why we don't use inheritance ?

[0] https://github.com/qgep/QGEP/blob/master/datamodel/04_qgep_db_dss.sql
[1] http://www.postgresql.org/docs/9.1/static/ddl-inherit.html
[2] http://ledgersmbdev.blogspot.ch/2012/08/postgresql-or-modelling-part-3-table.html

**Comment by sjib** [comment]
What specific interhitance would you like to add. Can you make an example?

**Comment by 3nids** [comment]
Well, for instance chanel and manhole would inherit waste water structure, as it is described in the VSA-DSS model.
Therefore, when listing waster water structure we would have both at once.

No need for views, rules and insert triggers.

**Comment by 3nids** [comment]
For info, I added inheritance for the value lists.

Here is the base table:
https://github.com/qgep/QGEP/blob/master/datamodel/03_qgep_db_dss.sql#L7

And here is an example of a value list declaration:
https://github.com/qgep/QGEP/blob/master/datamodel/03_qgep_db_dss.sql#L2528

**Comment by sjib** [comment]
If you can do this in SQL that would be great, that would be closer to the way INTERLIS 2 works instead to the way how it was modelled with INTERLIS 1 where you could not inherit things. With Access this was not possible.

 

Can you give me the model for superclass – subclasss inheritance?

**Comment by m-kuhn** [comment]
As far as I remember @andreasneumann considered this 2 years ago and brought up some reasons why support from PG side for inheritance is not good enough.

It may be good to hear from him the reasons for his hesitation and check if this has been fixed in PG meanwhile.

**Comment by andreasneumann** [comment]
Hi,

We can discuss this tomorrow. One hesitation I had is the lack of support of table inheritance in other databases. We lock us more into PostgreSQL if we use this feature and it becomes more difficult to support alternative databases, such as SpatiaLite.

However, the more severe problem is that there are even issues with table inheritance with in PostgreSQL. It seems that table inheritance is a rather obscure feature of PostgreSQL and not widely in use. As an example, you cannot use foreign keys anymore if you use table inheritance - which is a severe limitation. See http://stackoverflow.com/questions/24360312/foreign-keys-table-inheritance-in-postgresql 

Table inheritance seems to be mostly used to partition very large tables (e.g. across multiple tablespaces), not so much for inheritance.

But I am open for tests and more research on the issue.

**Comment by 3nids** [comment]
From a short overview with Matthias, it appears it's not yet a good idea to jump into this.
It might be improved in next versions of PG.
