### ISSUE TITLE
Labeling of Manholes and Special Constructions

### ISSUE THREAD

**Issue by andreasneumann** [QGEP/QGEP#9]
Individual reaches should be labeled (E1, E2, E3, etc.) - should be labeled along the reach close to the manhole.

Order: first the bigger reaches and then the smaller ones or clock-wise.
Only the important channels (Sammelkanal, etc.)

Sample should be attached (graphic)

**Comment by m-kuhn** [comment]
At the moment the labels are saved on wastewater structure level but joined to and represented on covers.

Would it make sense to only save the wastewater structure and `I`/`O` information on the wastewater structure table and attach the cover information on cover level (i.e. so we have only one appropriate `C` entry per cover)?

    C1 = 493.5
    C2 = 490.2
    4320.6432
    I1 = 401.2
    O1 = 400.3
    O2 = 400.2

vs.

    C = 493.5
    4320.6432
    I1 = 401.2
    O1 = 400.3
    O2 = 400.2

and

    C = 490.2
    4320.6432
    I1 = 401.2
    O1 = 400.3
    O2 = 400.2

**Comment by andreasneumann** [comment]
I think for special structures that have more than one cover we only want one label. These labels are quite big already, so we don't want two or more labels per special structure.

Actually, for special structures we don't want a label on the cover, but outside of the geometry of the special structure. I discsussed this with Nyall - and for the long run there could be an automated label placement for this. Until this works properly, I suggest to have manual label positions for special structures.

Two ore more covers on manholes are very rare. I don't think we have one in Uster.

**Comment by m-kuhn** [comment]
I don't think we want to have a switch on manhole vs. special structure.
We probably want to have a switch on if a custom position is defined (on wastewater structure level).

Proposal (taking into account the assumptions outlined in the above comment):

 * Placed labels on every cover by default
   * including every other cover of the same wastewater structure
 * Unless there is a manual position specified for the wastewater structure
 * Covers should not be numbered

**Comment by andreasneumann** [comment]
But a distinction between manhole and special_structure would make sense - because there are different labeling options for polygons versus points. It wouldn't make sense to label covers of a special_structure, as the label would usually overlap with the polygon geometry and would look ugly. The labels of special structure need to be placed outside of the polygon of the detail geometry of the special structure - not next to the cover.

**Comment by m-kuhn** [comment]
Then we will want two different label fields,
one on od_manhole and one on od_special_structure (not sure about the other wastewater structures).

**Comment by sjib** [comment]
C1 = 493.5
C2 = 490.2
4320.6432
I1 = 401.2
O1 = 400.3
O2 = 400.2
should be implemented.
open issues: language dependencies

**Comment by m-kuhn** [comment]
Depends on #156

**Comment by sjib** [comment]
Take into consideration main cover?

**Comment by urskaufmann** [comment]
The problem with labelling the wastewater structures:
Users should be able to configure the label-text (without programming).
The sequence 
cover / identifier / in / out 
is not for everyone the sequence, he is used. In my opinion, it should be
identifier/ cover / in / out          or 
identifier / Manhole-dimension/cover / in / out                    or 
Identifier / shortcut for function / cover / in / out.
The Shortcut-letters are in German D / E / A  (not C / I / O).
Normally, I just want the I/O-levels of the PAA-channels to be written.

I think, there should be a UI to define this things: the sequence of the different lines, the shortcut-letters and which channels I/O level are mentioned.

The next thing is to solve the unnecessary multi-labelling of wastewater structures with more than one cover ore wastewater node (look #356 )

And then is the labelling of the channels with I1, I2 etc if there is more than one I or O. And in principle the same, if there are more than one covers.

**Comment by urskaufmann** [comment]
This is the issue we where talking about this afternoon at codesprint 4: Labeling the I1, I2 along the reach next to the manhole.
The challenge: the reach or reachpoint does not know, which number in the manhole-label it is (I1, I2 or...). Possible solution: create a new field (qgep)_field, where the text I1, I2 or O1 is fixed.  The manhole-label takes all information from this field and the level-field and the label along the reach next to the manhole corresponds always with the manhole-label

Sample:
![LabelingE1E2](https://user-images.githubusercontent.com/1257403/111817962-ede11300-88de-11eb-91bc-e19aa08b9862.PNG)

**Comment by sjib** [comment]
@urskaufmann Is this still an issue?

**Comment by urskaufmann** [comment]
Yes, it is. The thing in the first post is not implemented: "Individual reaches should be labeled (E1, E2, E3, etc.) - should be labeled along the reach close to the manhole."
For me it's no more a top priority (it's necessary if you have a printed map, if you work at the screen you can get the info, which level belongs to which reach - and everybody works more and more at the screen...)
