### ISSUE TITLE
Arbon-migration: double coordinates in reach geometry

### ISSUE THREAD

**Issue by andreasneumann** [qgep/QGEP#90]
Most (if not all) reach geometries in the Arbon project contain the same coordinates twice at the start and end of the line. This should be corrected. The error already occurs in the Interlis transfer file.

Either the initial itf can be correctly exported, or we can run ST_RemoveRepeatedPoints() over the geometries directly in Postgis.

**Comment by m-kuhn** [comment]
Updated in the intermediate database as interlis import is broken anyway currently and the master intermediate file is in my possession.
Interlis import will still have to be fixed so this is just to fix the the demo db

**Comment by andreasneumann** [comment]
Thanks - not sure if we should leave this open or not? Perhaps we should add the ST_RemoveRepeatedPoints() to the migration script? - It would not harm anyway. Most likely it is an issue of the Interlis-export from Dabase/Gepview. I expect the data from Urs K. to have the same issue.

**Comment by m-kuhn** [comment]
Done, it won't hurt anyway.
I hope I got it right... I don't feel like testing this by letting my cpu spin for 2 hours just to get a broken dataset introduced by a still buggy interlis importer
