### ISSUE TITLE
inheritance for value lists

### ISSUE THREAD

**Issue by 3nids** [QGEP/QGEP#91]
Value lists tables now inherit from a generic value list table [qgep.is_value_list_base](https://github.com/qgep/QGEP/blob/master/datamodel/03_qgep_db_dss.sql#L7)

[example](https://github.com/qgep/QGEP/blob/master/datamodel/03_qgep_db_dss.sql#L2528) of use.

@sjib can you add this to the master model? 
No problem if you want to rename the
master table.

**Comment by sjib** [comment]
Ok, I added this to the code an it will be changed with the next release of the model

**Comment by 3nids** [comment]
Thanks!
Waiting on the new input to close this.

**Comment by 3nids** [comment]
@sjib when is the next model release?

**Comment by sjib** [comment]
I will try next week after adding the other issues

**Comment by m-kuhn** [comment]
Will be released until end of week.

**Comment by 3nids** [comment]
@sjib I would prefer to keep the issues open until it's committed in the repo. Otherwise, there is no mean of control.
