### ISSUE TITLE
identifiers of reaches

### ISSUE THREAD

**Issue by 3nids** [QGEP/QGEP#92]
In practice, how do you name the identifier of the reaches?
At SIGE, it seems we use 1_2_3_4 with:
1: from channel
2: from manhole
3: to channel
4: to manhole

This leads to a problem of limited size of identifier in wasterwater_network_element (20).

Is it not the way to go?
Otherwise, @sjib can you increase the size of the field?

thanks!

**Comment by 3nids** [comment]
It seems I am mixing channel and reaches.
I have the problem for od_waster_water_structure (od_channel)

**Comment by sjib** [comment]
In the Wegleitung Document I sent you (3rd page) you  find some recommendations how to do identifiers for channels:

 

Die Bezeichnung der Leitungen wird in der Regel in der täglichen Arbeit selten

verwendet und auch nicht auf Plänen dargestellt. Trotzdem muss sie die oben

aufgeführten zwingenden Grundsätze einhalten. Wenn möglich soll sie vom

Erfassungssystem automatisiert vergeben werden und nicht vom Erfasser jedes Mal

eingegeben werden müssen (Fehleranfälligkeit). 

 

Mögliche Bezeichnungssysteme / Possible system:

* von-bis Schacht Bezeichnung: 127-128 (from – to identifier 127-128)

* von Schacht Bezeichnung: 127 (from identifier: 127)

* ganz unabhängige Bezeichnung: 4267. Independant identifier 4267

 

Diese setzt die Empfehlung, dass die Bezeichnung keine Attribute (und Beziehungen) abbilden soll, konsequent um.

**Comment by 3nids** [comment]
The thing is that our manhole (covers) are named 3004-20 (channel-manhole). Hence if I use from-to identifier, I have sometimes 21 characters identifiers....
So, would it be possible to increase to 25?

For the automation, I'll see with Matthias.
This should be feasible in the view triggers he created.

**Comment by andreasneumann** [comment]
In Uster we use the following system:

Primary waste-water network (public network): Integer number 1 to n

Secondary waste-water network (private network): streetnr_housenr_counter of the parcel closest to the connection into the primary waste-water network:
e.g.: 130_2_5, where 130 is the street nr identifier, 2 is the main or first house nr of the parcel, and 5 is the reach nr 5 on this parcel.

**Comment by andreasneumann** [comment]
I would not mind increasing the number of possible characters.

**Comment by 3nids** [comment]
can we?

**Comment by andreasneumann** [comment]
In my opinion - yes. Even if it goes beyond the model. But until we have the "OK" from Stefan you may want to do a custom post-processing script. I guess you have some local modifications anyway?

**Comment by urskaufmann** [comment]
i do not use this identifiers. For me it is an automatic filled field.
what do you do with this identifier, if you realise, that the reach goes not from/to the manhole you guess? when you build e new manhole in the reach? with the rules discribed above, you have to rebuild the identifier. With triggers or manually? But identifers should not change.
I do not use this identifers...

**Comment by sjib** [comment]
I will bring it up as Gelbdruck for VSA-DSS and discuss it this month in the VSA group

**Comment by sjib** [comment]
The VSA workgroup agreed to change the identifier from TEXT*20 to TEXT*41. I will add that to the model definition also.

**Comment by 3nids** [comment]
the length is still 20 in the code
https://github.com/QGEP/datamodel/blob/master/03_qgep_db_dss.sql#L993

as said, it's easier if we close issue when they are really solved ;)

by the way, in postgres, the length of varchar does not preserve any space in the DB which is not true for char(x). So, better allow a bit more flexibility....

**Comment by 3nids** [comment]
there are 38 occurences of `identifier  varchar(20) ;`
would be nice to replace them all

**Comment by sjib** [comment]
Thanks for the hint, corrected in the new version of today.

**Comment by sjib** [comment]
by the way, in postgres, the length of varchar does not preserve any space in the DB which is not true for char(x). So, better allow a bit more flexibility....
I do not get the hint: would it be better to change from varchar(41) to char(41)?

**Comment by 3nids** [comment]
No, char is a fixed-length column and will always take the maximum amount.
varchar is variable and only take the space that is effectively used by each row (not the maximum with, as it is in msql if I'm right).
just saying saving space is not a valid reason to restrict the size of text fields.

**Comment by 3nids** [comment]
thanks for the fix
