### ISSUE TITLE
symbology function: triggers are missing

### ISSUE THREAD

**Issue by 3nids** [qgep/QGEP#93]
When looking at manhole, I see that _function_hierarchic is not filled.
I see there are functions declared in https://github.com/qgep/QGEP/blob/master/datamodel/06_symbology_functions.sql 

shall I run them manually?
shouldn't there be some triggers?

**Comment by andreasneumann** [comment]
The triggers are still missing - it is on my todo list.

Andreas

**Comment by 3nids** [comment]
ok, thanks for the reply.
can you tell me how to run this manually?

**Comment by andreasneumann** [comment]
see https://github.com/qgep/QGEP/blob/master/migration/90_update_symbology_attribs.sql
maybe your data is a bit different, but something similar should do the trick. This updates usage_current and function_hierarchic of the manholes based on incoming/outgoing reaches/channels.

**Comment by 3nids** [comment]
thanks!
