### ISSUE TITLE
  How to document

### ISSUE THREAD

**Issue by sjib** [QGEP/QGEP#98]
Please put your findings here: https://github.com/qgep/QGEP/wiki/How-to-document

**Comment by m-kuhn** [comment]
I will look at this the week after next in Denmark where a lot of people experienced in documentation and translation are around.

**Comment by m-kuhn** [comment]
I have been told that for the best compatibility the restructured text (rst) + sphinx system can be recommended.

Pro:
 * Can be translated
 * Can be managed on github (with concurrent editing and conflict solving)
 * Images can also be translated with transifex
 * We have people to contact who are experienced
 * Can automatically generate a table of content
 * Can be exported to PDF
 * Can be exported to HTML

Contra:
 * Another syntax language to learn (similar to markdown)

Apparently a very nice example is how mapserver does it.
Whenever a new version is committed it is automatically built on the travis-ci platform and made available on a github.io page. That means, no infrastructure to maintain from our side, automatic update to the latest version.

Github repository:
https://github.com/mapserver/docs

Automatically generated result:
 * HTML: http://mapserver.org/documentation.html
 * PDF: http://mapserver.org/MapServer.pdf

**Comment by andreasneumann** [comment]
Here is an online editor for rst:

http://rst.ninjs.org/

**Comment by m-kuhn** [comment]
Info on rst tags:

https://github.com/qgis/QGIS-Documentation/tree/master/source/docs/documentation_guidelines

**Comment by m-kuhn** [comment]
Documentation system is in place.
Information can be found here:
https://github.com/QGEP/docs
